select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(RREINT_RECUPERATORE) = '', ' ', RTRIM(RREINT_RECUPERATORE)) AS VARCHAR(5)) AS rreint_recuperatore,
  TRY_CAST(RREINT_NUM_RAPPORTINO AS NUMBER(7,0)) AS rreint_num_rapportino,
  TRY_CAST(IFF(RTRIM(RREINT_PROVENIENZA) = '', ' ', RTRIM(RREINT_PROVENIENZA)) AS VARCHAR(2)) AS rreint_provenienza,
  TRY_CAST(RREINT_PRATICA AS NUMBER(12,0)) AS rreint_pratica,
  TRY_CAST(RREINT_DATA_ASSEGNAZIONE AS NUMBER(8,0)) AS rreint_data_assegnazione,
  TRY_CAST(RREINT_ASS_RATE AS NUMBER(9,0)) AS rreint_ass_rate,
  TRY_CAST(RREINT_ASS_MORA AS NUMBER(9,0)) AS rreint_ass_mora,
  TRY_CAST(RREINT_ASS_ALTRI AS NUMBER(9,0)) AS rreint_ass_altri,
  TRY_CAST(RREINT_ASS_SPESE AS NUMBER(9,0)) AS rreint_ass_spese,
  TRY_CAST(IFF(RTRIM(RREINT_AZIONE) = '', ' ', RTRIM(RREINT_AZIONE)) AS VARCHAR(3)) AS rreint_azione,
  TRY_CAST(IFF(RTRIM(RREINT_ESITO) = '', ' ', RTRIM(RREINT_ESITO)) AS VARCHAR(3)) AS rreint_esito,
  TRY_CAST(RREINT_DATA_RIENTRO AS NUMBER(8,0)) AS rreint_data_rientro,
  TRY_CAST(RREINT_LOTTO_RECUPERO AS NUMBER(7,0)) AS rreint_lotto_recupero,
  TRY_CAST(IFF(RTRIM(RREINT_BYPASS) = '', ' ', RTRIM(RREINT_BYPASS)) AS VARCHAR(1)) AS rreint_bypass,
  TRY_CAST(RREINT_SPESE_DA_ADDEB AS NUMBER(9,0)) AS rreint_spese_da_addeb,
  TRY_CAST(RREINT_INC_RATE AS NUMBER(9,0)) AS rreint_inc_rate,
  TRY_CAST(RREINT_INC_MORA AS NUMBER(9,0)) AS rreint_inc_mora,
  TRY_CAST(RREINT_INC_ALTRI AS NUMBER(9,0)) AS rreint_inc_altri,
  TRY_CAST(RREINT_INC_SPESE AS NUMBER(9,0)) AS rreint_inc_spese,
  TRY_CAST(IFF(RTRIM(RREINT_NUM_RAPP_ESTERNO) = '', ' ', RTRIM(RREINT_NUM_RAPP_ESTERNO)) AS VARCHAR(12)) AS rreint_num_rapp_esterno,
  TRY_CAST(RREINT_LOTTO_RIENTRO AS NUMBER(7,0)) AS rreint_lotto_rientro,
  TRY_CAST(RREINT_ASS_NUM_RATE AS NUMBER(3,0)) AS rreint_ass_num_rate,
  TRY_CAST(RREINT_ASS_MORA_CALC AS NUMBER(9,0)) AS rreint_ass_mora_calc,
  TRY_CAST(RREINT_DATA_VERSAMENTO AS NUMBER(8,0)) AS rreint_data_versamento,
  TRY_CAST(RREINT_PROV_CALC AS NUMBER(9,0)) AS rreint_prov_calc,
  TRY_CAST(RREINT_PROV_MOD AS NUMBER(9,0)) AS rreint_prov_mod,
  TRY_CAST(IFF(RTRIM(RREINT_PROVVIGIONI) = '', ' ', RTRIM(RREINT_PROVVIGIONI)) AS VARCHAR(1)) AS rreint_provvigioni,
  TRY_CAST(RREINT_ASS_AGG_RATE AS NUMBER(13,0)) AS rreint_ass_agg_rate,
  TRY_CAST(RREINT_ASS_AGG_MORA AS NUMBER(13,0)) AS rreint_ass_agg_mora,
  TRY_CAST(RREINT_ASS_AGG_ALTRI AS NUMBER(13,0)) AS rreint_ass_agg_altri,
  TRY_CAST(RREINT_ASS_AGG_SPESE AS NUMBER(13,0)) AS rreint_ass_agg_spese,
  TRY_CAST(RREINT_ASS_AGG_MORA_CALC AS NUMBER(13,0)) AS rreint_ass_agg_mora_calc,
  TRY_CAST(RREINT_CAPITALE_PROVVIG AS NUMBER(13,0)) AS rreint_capitale_provvig,
  TRY_CAST(RREINT_CLIENTE AS NUMBER(9,0)) AS rreint_cliente,
  TRY_CAST(IFF(RTRIM(RREINT_FAS_OPE) = '', ' ', RTRIM(RREINT_FAS_OPE)) AS VARCHAR(2)) AS rreint_fas_ope,
  TRY_CAST(RREINT_ASS_TOTALE AS NUMBER(13,0)) AS rreint_ass_totale,
  TRY_CAST(RREINT_SALDO_TOTALE AS NUMBER(13,0)) AS rreint_saldo_totale,
  TRY_CAST(RREINT_SALDO_RATE AS NUMBER(13,0)) AS rreint_saldo_rate,
  TRY_CAST(RREINT_SALDO_MORA AS NUMBER(13,0)) AS rreint_saldo_mora,
  TRY_CAST(RREINT_SALDO_ALTRO AS NUMBER(13,0)) AS rreint_saldo_altro,
  TRY_CAST(RREINT_RATA_MEDIA AS NUMBER(13,0)) AS rreint_rata_media,
  TRY_CAST(RREINT_INC_VER_RATE AS NUMBER(13,0)) AS rreint_inc_ver_rate,
  TRY_CAST(RREINT_INC_VER_MORA AS NUMBER(13,0)) AS rreint_inc_ver_mora,
  TRY_CAST(RREINT_INC_VER_ALTRI AS NUMBER(13,0)) AS rreint_inc_ver_altri,
  TRY_CAST(RREINT_INC_VER_SPESE AS NUMBER(13,0)) AS rreint_inc_ver_spese,
  TRY_CAST(RREINT_FL_MOSSA AS NUMBER(1,0)) AS rreint_fl_mossa,
  TRY_CAST(IFF(RTRIM(RREINT_FL_RISOLTA) = '', ' ', RTRIM(RREINT_FL_RISOLTA)) AS VARCHAR(1)) AS rreint_fl_risolta,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','re2incrret') }}
