select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(AIECPARD_SEZIONE) = '', ' ', RTRIM(AIECPARD_SEZIONE)) AS VARCHAR(1)) AS aiecpard_sezione,
  TRY_CAST(AIECPARD_PRATICA AS NUMBER(12,0)) AS aiecpard_pratica,
  TRY_CAST(AIECPARD_PROGRESSIVO AS NUMBER(9,0)) AS aiecpard_progressivo,
  TRY_CAST(AIECPARD_RIGA AS NUMBER(5,0)) AS aiecpard_riga,
  TRY_CAST(AIECPARD_CAUSALE AS NUMBER(3,0)) AS aiecpard_causale,
  TRY_CAST(IFF(RTRIM(AIECPARD_TIPO_DOCUMENTO) = '', ' ', RTRIM(AIECPARD_TIPO_DOCUMENTO)) AS VARCHAR(2)) AS aiecpard_tipo_documento,
  TRY_CAST(AIECPARD_NUM_DOCUMENTO AS NUMBER(12,0)) AS aiecpard_num_documento,
  TRY_CAST(AIECPARD_DATA_DOCUMENTO AS NUMBER(8,0)) AS aiecpard_data_documento,
  TRY_CAST(AIECPARD_IMP_PARTITA AS NUMBER(13,0)) AS aiecpard_imp_partita,
  TRY_CAST(AIECPARD_DATA_SCAD_VAL AS NUMBER(8,0)) AS aiecpard_data_scad_val,
  TRY_CAST(AIECPARD_DATA_COMP AS NUMBER(8,0)) AS aiecpard_data_comp,
  TRY_CAST(AIECPARD_EVENTO AS NUMBER(11,0)) AS aiecpard_evento,
  TRY_CAST(IFF(RTRIM(AIECPARD_TIPO_MOV) = '', ' ', RTRIM(AIECPARD_TIPO_MOV)) AS VARCHAR(1)) AS aiecpard_tipo_mov,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','aiecfpard') }}
