WITH base AS (

    SELECT
        O.OXIZDAT_IDE AS CD_IDE,
        O.OXIZDAT_PRG_SIMUL AS PRG_SIMULAZIONE,
        {{ custom_to_timestamp_ntz('O.OXIZDAT_DATA_AGG', 'O.OXIZDAT_ORA_AGG') }} AS TS_INIZIO_VALIDITA,
        {{ custom_to_timestamp_ntz('O.OXIZDAT_DATA_IDENTIF_COMPL', 'O.OXIZDAT_ORA_IDENTIF_COMPL') }} AS TS_FINE_VALIDITA, -- WARN: data model mappa sia TS_INIZIO_VALIDITA sia TS_FINE_VALIDITA sulle stesse 4 colonne sorgente senza distinguerle; assunto TS_INIZIO_VALIDITA=DATA/ORA_AGG (aggiornamento), TS_FINE_VALIDITA ricalcolata comunque nel SELECT finale
        CASE WHEN O.OXIZDAT_UTENTE_CANC IS NOT NULL THEN 'S' ELSE 'N' END AS FL_CANCELLATO,
        O.OXIZDAT_PROCEDURA AS TP_PROCEDURA,
        O.OXIZDAT_PRATICA AS CD_PRATICA,
        O.OXIZDAT_COD_ANA AS CD_CONTROPARTE,
        O.OXIZDAT_RAPPORTO AS CD_RAPPORTO,
        O.OXIZDAT_PRG_RAPPORTO AS PRG_RAPPORTO,
        O.OXIZDAT_MODALITA_IDE AS CD_MODALITA_IDE,
        O.OXIZDAT_TIPO_IDE_REM AS TP_IDE_REMOTO,
        O.OXIZDAT_COMP_TIPO_IDE_REM AS TP_IDE_REMOTO_COMP,
        O.OXIZDAT_FCON_TIPO_IDE_PERS AS DS_TIPO_IDE_PERS,
        O.OXIZDAT_FCON_AUTOCERT_PSOG AS FL_AUTOCERT_PSOG,
        O.OXIZDAT_IDENTIF_COMPLETATA AS FL_IDENTIF_COMPLETATA,
        {{ custom_to_date('O.OXIZDAT_DATA_IDENTIF_COMPL') }} AS DT_IDENTIF_COMPLETATA,
        O.OXIZDAT_ORA_IDENTIF_COMPL AS NM_ORA_IDENTIF_COMPLETATA,
        O.OXIZDAT_GIA_CLIENTE AS FL_GIA_CLIENTE,
        O.OXIZDAT_GIA_CLIENTE_TDOC AS CD_GIA_CLIENTE_TDOC,
        O.OXIZDAT_GIA_CLIENTE_NDOC AS NM_GIA_CLIENTE_NDOC,
        O.OXIZDAT_APPL_PROV AS CD_APPL_PROV,
        O.OXIZDAT_APPL_DETT AS CD_APPL_DETT,
        O.OXIZDAT_EMAIL AS DS_EMAIL,
        O.OXIZDAT_CELL AS DS_CELLULARE
    FROM {{ ref('oxizfdat') }} O

)

, dedup AS (

    SELECT
        CD_IDE, PRG_SIMULAZIONE, TS_INIZIO_VALIDITA, TS_FINE_VALIDITA, FL_CANCELLATO,
        TP_PROCEDURA, CD_PRATICA, CD_CONTROPARTE, CD_RAPPORTO, PRG_RAPPORTO, CD_MODALITA_IDE,
        TP_IDE_REMOTO, TP_IDE_REMOTO_COMP, DS_TIPO_IDE_PERS, FL_AUTOCERT_PSOG,
        FL_IDENTIF_COMPLETATA, DT_IDENTIF_COMPLETATA, NM_ORA_IDENTIF_COMPLETATA,
        FL_GIA_CLIENTE, CD_GIA_CLIENTE_TDOC, NM_GIA_CLIENTE_NDOC, CD_APPL_PROV, CD_APPL_DETT,
        DS_EMAIL, DS_CELLULARE,
        {{ hash_cols([
            'CD_IDE', 'PRG_SIMULAZIONE', 'FL_CANCELLATO', 'TP_PROCEDURA', 'CD_PRATICA',
            'CD_CONTROPARTE', 'CD_RAPPORTO', 'PRG_RAPPORTO', 'CD_MODALITA_IDE', 'TP_IDE_REMOTO',
            'TP_IDE_REMOTO_COMP', 'DS_TIPO_IDE_PERS', 'FL_AUTOCERT_PSOG', 'FL_IDENTIF_COMPLETATA',
            'DT_IDENTIF_COMPLETATA', 'NM_ORA_IDENTIF_COMPLETATA', 'FL_GIA_CLIENTE',
            'CD_GIA_CLIENTE_TDOC', 'NM_GIA_CLIENTE_NDOC', 'CD_APPL_PROV', 'CD_APPL_DETT',
            'DS_EMAIL', 'DS_CELLULARE'
        ]) }} AS HASHED_COLS
    FROM base
    {{ is_incremental_S1('CD_IDE') }}

)

SELECT
    H.CD_IDE,
    H.PRG_SIMULAZIONE,
    H.TS_INIZIO_VALIDITA,
    {{ ts_fine_validita('H.CD_IDE', 'H.TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA,
    H.FL_CANCELLATO,
    H.TP_PROCEDURA,
    H.CD_PRATICA,
    H.CD_CONTROPARTE,
    H.CD_RAPPORTO,
    H.PRG_RAPPORTO,
    H.CD_MODALITA_IDE,
    H.TP_IDE_REMOTO,
    H.TP_IDE_REMOTO_COMP,
    H.DS_TIPO_IDE_PERS,
    H.FL_AUTOCERT_PSOG,
    H.FL_IDENTIF_COMPLETATA,
    H.DT_IDENTIF_COMPLETATA,
    H.NM_ORA_IDENTIF_COMPLETATA,
    H.FL_GIA_CLIENTE,
    H.CD_GIA_CLIENTE_TDOC,
    H.NM_GIA_CLIENTE_NDOC,
    H.CD_APPL_PROV,
    H.CD_APPL_DETT,
    H.DS_EMAIL,
    H.DS_CELLULARE
FROM dedup H
-- WARN: nessun LASTMODIFIEDDATA nel data model per questa entita', da chiarire col team
