version: 2

sources:
  - name: source_l0
    schema: L0
    tables:
      - name: configurazione_banca_dati
        data_tests:
          - try_cast
          - primary_key:
              arguments:
                pk_columns: [codice_banca_dati_pk]
