select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(CASRSER_CARTA AS NUMBER(12,0)) AS casrser_carta,
  TRY_CAST(IFF(RTRIM(CASRSER_SERVIZIO) = '', ' ', RTRIM(CASRSER_SERVIZIO)) AS VARCHAR(5)) AS casrser_servizio,
  TRY_CAST(IFF(RTRIM(CASRSER_PACCHETTO) = '', ' ', RTRIM(CASRSER_PACCHETTO)) AS VARCHAR(5)) AS casrser_pacchetto,
  TRY_CAST(IFF(RTRIM(CASRSER_STATO) = '', ' ', RTRIM(CASRSER_STATO)) AS VARCHAR(2)) AS casrser_stato,
  TRY_CAST(CASRSER_DATA_ADE_SERV AS NUMBER(8,0)) AS casrser_data_ade_serv,
  TRY_CAST(CASRSER_DATA_ATT_SERV AS NUMBER(8,0)) AS casrser_data_att_serv,
  TRY_CAST(CASRSER_DATA_CHI_SERV AS NUMBER(8,0)) AS casrser_data_chi_serv,
  TRY_CAST(IFF(RTRIM(CASRSER_SERV_OBB_FAC) = '', ' ', RTRIM(CASRSER_SERV_OBB_FAC)) AS VARCHAR(1)) AS casrser_serv_obb_fac,
  TRY_CAST(IFF(RTRIM(CASRSER_PACC_OBB_FAC) = '', ' ', RTRIM(CASRSER_PACC_OBB_FAC)) AS VARCHAR(1)) AS casrser_pacc_obb_fac,
  TRY_CAST(IFF(RTRIM(CASRSER_UTENTE_INS) = '', ' ', RTRIM(CASRSER_UTENTE_INS)) AS VARCHAR(10)) AS casrser_utente_ins,
  TRY_CAST(CASRSER_DATA_INS AS NUMBER(8,0)) AS casrser_data_ins,
  TRY_CAST(CASRSER_ORA_INS AS NUMBER(8,0)) AS casrser_ora_ins,
  TRY_CAST(CASRSER_IMP_ADDEBITI AS NUMBER(13,0)) AS casrser_imp_addebiti,
  TRY_CAST(CASRSER_ANNO_EC_RECESSO AS NUMBER(4,0)) AS casrser_anno_ec_recesso,
  TRY_CAST(CASRSER_MESE_EC_RECESSO AS NUMBER(2,0)) AS casrser_mese_ec_recesso,
  TRY_CAST(CASRSER_IMP_TOT_PASSIVA AS NUMBER(13,0)) AS casrser_imp_tot_passiva,
  TRY_CAST(IFF(RTRIM(CASRSER_PROV_CARICAMENTO) = '', ' ', RTRIM(CASRSER_PROV_CARICAMENTO)) AS VARCHAR(1)) AS casrser_prov_caricamento,
  TRY_CAST(CASRSER_IMP_MARKUP AS NUMBER(13,0)) AS casrser_imp_markup,
  TRY_CAST(CASRSER_IMPOSTE AS NUMBER(13,0)) AS casrser_imposte,
  TRY_CAST(CASRSER_PROVVIGIONI AS NUMBER(13,0)) AS casrser_provvigioni,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','casrfser') }}
