select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  COALESCE(TRY_CAST(data_modifica AS TIMESTAMP_NTZ), TRY_CAST(data_creazione AS TIMESTAMP_NTZ)) AS ts_coalesce_modif_creaz, --TRYCAST prima della COALESCE altrimenti non funziona correttamente
  TRY_CAST(idProdottoVersione AS NUMBER(11,0)) AS idprodottoversione,
  TRY_CAST(idProdotto AS NUMBER(11,0)) AS idprodotto,
  TRY_CAST(codiceVersione AS VARCHAR(45)) AS codiceversione,
  TRY_CAST(dsVersione AS VARCHAR(100)) AS dsversione,
  TRY_CAST(abilitato AS NUMBER(1,0)) AS abilitato,
  TRY_CAST(eliminato AS NUMBER(1,0)) AS eliminato,
  TRY_CAST(codiceVersioneCompagnia AS VARCHAR(45)) AS codiceversionecompagnia,
  TRY_CAST(idRamo AS NUMBER(11,0)) AS idramo,
  TRY_CAST(modPagamento AS VARCHAR(30)) AS modpagamento,
  TRY_CAST(frequenzeAmmesse AS VARCHAR(30)) AS frequenzeammesse,
  TRY_CAST(isvap AS NUMBER(1,0)) AS isvap,
  TRY_CAST(idClasse AS NUMBER(11,0)) AS idclasse,
  TRY_CAST(dsVersioneLunga AS VARCHAR(255)) AS dsversionelunga,
  TRY_CAST(dataCreazione AS TIMESTAMP_NTZ) AS datacreazione,
  TRY_CAST(idNodoCreazione AS NUMBER(11,0)) AS idnodocreazione,
  TRY_CAST(idUserCreazione AS NUMBER(11,0)) AS idusercreazione,
  TRY_CAST(dataUltimaModifica AS TIMESTAMP_NTZ) AS dataultimamodifica,
  TRY_CAST(idNodoModifica AS NUMBER(11,0)) AS idnodomodifica,
  TRY_CAST(idUserModifica AS NUMBER(11,0)) AS idusermodifica,
  TRY_CAST(tipiBene AS VARCHAR(30)) AS tipibene,
  TRY_CAST(script_commerciale AS VARCHAR(255)) AS script_commerciale,
  TRY_CAST(scheda_prodotto AS VARCHAR(255)) AS scheda_prodotto,
  TRY_CAST(invio_doc_precontrattuale AS NUMBER(1,0)) AS invio_doc_precontrattuale,
  TRY_CAST(imported AS NUMBER(1,0)) AS imported,
  TRY_CAST(is_standalone AS NUMBER(1,0)) AS is_standalone,
  TRY_CAST(data_creazione AS TIMESTAMP_NTZ) AS data_creazione,
  TRY_CAST(data_modifica AS TIMESTAMP_NTZ) AS data_modifica
from {{ source('source_l0','tblprodottiversioni') }}
