select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  COALESCE(TRY_CAST(data_modifica AS TIMESTAMP_NTZ), TRY_CAST(data_creazione AS TIMESTAMP_NTZ)) AS ts_coalesce_modif_creaz, --TRYCAST prima della COALESCE altrimenti non funziona correttamente
  TRY_CAST(idUsers AS NUMBER(11,0)) AS idusers,
  TRY_CAST(username AS VARCHAR(20)) AS username,
  TRY_CAST(cognome AS VARCHAR(150)) AS cognome,
  TRY_CAST(nome AS VARCHAR(150)) AS nome,
  TRY_CAST(email AS VARCHAR(250)) AS email,
  TRY_CAST(tipoUser AS NUMBER(6,0)) AS tipouser,
  TRY_CAST(bloccato AS NUMBER(6,0)) AS bloccato,
  TRY_CAST(idRamo AS NUMBER(6,0)) AS idramo,
  TRY_CAST(user_sesso AS VARCHAR(1)) AS user_sesso,
  TRY_CAST(user_CF_IVA AS VARCHAR(30)) AS user_cf_iva,
  TRY_CAST(user_data_nascita AS DATE) AS user_data_nascita,
  TRY_CAST(user_citta_nascita AS VARCHAR(150)) AS user_citta_nascita,
  TRY_CAST(user_provincia_nascita AS VARCHAR(4)) AS user_provincia_nascita,
  TRY_CAST(user_telefono AS VARCHAR(30)) AS user_telefono,
  TRY_CAST(user_fax AS VARCHAR(30)) AS user_fax,
  TRY_CAST(user_cellulare AS VARCHAR(30)) AS user_cellulare,
  TRY_CAST(user_note AS VARCHAR) AS user_note,
  TRY_CAST(codice_zona AS VARCHAR(3)) AS codice_zona,
  TRY_CAST(codice_profilo_racf AS VARCHAR(10)) AS codice_profilo_racf,
  TRY_CAST(user_force_chg_pwd AS NUMBER(6,0)) AS user_force_chg_pwd,
  TRY_CAST(user_dataUltimoAccesso AS TIMESTAMP_NTZ) AS user_dataultimoaccesso,
  TRY_CAST(codice_uog AS VARCHAR(45)) AS codice_uog,
  TRY_CAST(data_creazione AS TIMESTAMP_NTZ) AS data_creazione,
  TRY_CAST(data_modifica AS TIMESTAMP_NTZ) AS data_modifica
from {{ source('source_l0','tblusers') }}
