select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  COALESCE(TRY_CAST(data_modifica AS TIMESTAMP_NTZ), TRY_CAST(data_creazione AS TIMESTAMP_NTZ)) AS ts_coalesce_modif_creaz, --TRYCAST prima della COALESCE altrimenti non funziona correttamente
  TRY_CAST(idQuestionarioContraente AS NUMBER(11,0)) AS idquestionariocontraente,
  TRY_CAST(idAnagraficaProspect AS NUMBER(11,0)) AS idanagraficaprospect,
  TRY_CAST(idUserCreazione AS NUMBER(11,0)) AS idusercreazione,
  TRY_CAST(idNodoCreazione AS NUMBER(11,0)) AS idnodocreazione,
  TRY_CAST(idUserModifica AS NUMBER(11,0)) AS idusermodifica,
  TRY_CAST(idNodoModifica AS NUMBER(11,0)) AS idnodomodifica,
  TRY_CAST(idStatoQuestionarioContraente AS NUMBER(11,0)) AS idstatoquestionariocontraente,
  TRY_CAST(codice_cliente AS VARCHAR(45)) AS codice_cliente,
  TRY_CAST(cognome AS VARCHAR(150)) AS cognome,
  TRY_CAST(nome AS VARCHAR(150)) AS nome,
  TRY_CAST(codice_fiscale AS VARCHAR(30)) AS codice_fiscale,
  TRY_CAST(data_nascita AS DATE) AS data_nascita,
  TRY_CAST(sesso AS VARCHAR(1)) AS sesso,
  TRY_CAST(provincia_nascita AS VARCHAR(4)) AS provincia_nascita,
  TRY_CAST(citta_nascita AS VARCHAR(150)) AS citta_nascita,
  TRY_CAST(indirizzo_residenza AS VARCHAR(250)) AS indirizzo_residenza,
  TRY_CAST(citta_residenza AS VARCHAR(150)) AS citta_residenza,
  TRY_CAST(provincia_residenza AS VARCHAR(4)) AS provincia_residenza,
  TRY_CAST(cap_residenza AS VARCHAR(10)) AS cap_residenza,
  TRY_CAST(email AS VARCHAR(250)) AS email,
  TRY_CAST(cognome_nome_operatore AS VARCHAR(250)) AS cognome_nome_operatore,
  TRY_CAST(idQuestionario AS NUMBER(11,0)) AS idquestionario,
  TRY_CAST(risposte AS VARCHAR) AS risposte,
  TRY_CAST(esito AS VARCHAR) AS esito,
  TRY_CAST(tipo_invio_stampa AS NUMBER(3,0)) AS tipo_invio_stampa,
  TRY_CAST(modifica_operatore AS NUMBER(1,0)) AS modifica_operatore,
  TRY_CAST(operatore_verificato AS NUMBER(1,0)) AS operatore_verificato,
  TRY_CAST(ndg_convenzionato AS VARCHAR(45)) AS ndg_convenzionato,
  TRY_CAST(ragione_sociale_convenzionato AS VARCHAR(150)) AS ragione_sociale_convenzionato,
  TRY_CAST(codice_agos_utente AS VARCHAR(45)) AS codice_agos_utente,
  TRY_CAST(nome_utente AS VARCHAR(150)) AS nome_utente,
  TRY_CAST(cognome_utente AS VARCHAR(150)) AS cognome_utente,
  TRY_CAST(codice_controparte_associato_utente AS VARCHAR(45)) AS codice_controparte_associato_utente,
  TRY_CAST(data_export_doc AS TIMESTAMP_NTZ) AS data_export_doc,
  TRY_CAST(data_creazione AS TIMESTAMP_NTZ) AS data_creazione,
  TRY_CAST(data_modifica AS TIMESTAMP_NTZ) AS data_modifica
from {{ source('source_l0','tblquestionaricontraenti') }}
