select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  COALESCE(TRY_CAST(data_modifica AS TIMESTAMP_NTZ), TRY_CAST(data_creazione AS TIMESTAMP_NTZ)) AS ts_coalesce_modif_creaz, --TRYCAST prima della COALESCE altrimenti non funziona correttamente
  TRY_CAST(idQuestionario AS NUMBER(11,0)) AS idquestionario,
  TRY_CAST(idAnagraficaProspect AS NUMBER(11,0)) AS idanagraficaprospect,
  TRY_CAST(idUserCreazione AS NUMBER(11,0)) AS idusercreazione,
  TRY_CAST(idNodoCreazione AS NUMBER(11,0)) AS idnodocreazione,
  TRY_CAST(opzione_prodotto AS NUMBER(3,0)) AS opzione_prodotto,
  TRY_CAST(esito AS VARCHAR) AS esito,
  TRY_CAST(motivo_esito AS VARCHAR) AS motivo_esito,
  TRY_CAST(risposta_1 AS VARCHAR) AS risposta_1,
  TRY_CAST(risposta_2 AS VARCHAR) AS risposta_2,
  TRY_CAST(risposta_3 AS VARCHAR) AS risposta_3,
  TRY_CAST(risposta_4 AS VARCHAR) AS risposta_4,
  TRY_CAST(risposta_5 AS VARCHAR) AS risposta_5,
  TRY_CAST(risposta_6 AS VARCHAR) AS risposta_6,
  TRY_CAST(risposta_7 AS VARCHAR) AS risposta_7,
  TRY_CAST(risposta_8 AS VARCHAR) AS risposta_8,
  TRY_CAST(risposta_9 AS VARCHAR) AS risposta_9,
  TRY_CAST(risposta_10 AS VARCHAR) AS risposta_10,
  TRY_CAST(is_cross_selling AS NUMBER(1,0)) AS is_cross_selling,
  TRY_CAST(xsell_tipo_prodotto AS VARCHAR(45)) AS xsell_tipo_prodotto,
  TRY_CAST(xsell_codice_societa AS VARCHAR(45)) AS xsell_codice_societa,
  TRY_CAST(xsell_codice_pratica AS VARCHAR(45)) AS xsell_codice_pratica,
  TRY_CAST(xsell_codice_carta AS VARCHAR(45)) AS xsell_codice_carta,
  TRY_CAST(xsell_codice_stato_pratica_lista_pratiche AS VARCHAR(45)) AS xsell_codice_stato_pratica_lista_pratiche,
  TRY_CAST(xsell_codice_stato_pratica AS VARCHAR(45)) AS xsell_codice_stato_pratica,
  TRY_CAST(xsell_data_caricamento_pratica AS VARCHAR(45)) AS xsell_data_caricamento_pratica,
  TRY_CAST(xsell_data_stampa_contratto AS VARCHAR(45)) AS xsell_data_stampa_contratto,
  TRY_CAST(xsell_data_approvazione_pratica AS VARCHAR(45)) AS xsell_data_approvazione_pratica,
  TRY_CAST(xsell_data_decorrenza AS VARCHAR(45)) AS xsell_data_decorrenza,
  TRY_CAST(xsell_data_liquidazione AS VARCHAR(45)) AS xsell_data_liquidazione,
  TRY_CAST(xsell_codice_settore AS VARCHAR(45)) AS xsell_codice_settore,
  TRY_CAST(xsell_tipo_settore AS VARCHAR(45)) AS xsell_tipo_settore,
  TRY_CAST(xsell_importo_finanziato AS VARCHAR(45)) AS xsell_importo_finanziato,
  TRY_CAST(xsell_importo_rata AS VARCHAR(45)) AS xsell_importo_rata,
  TRY_CAST(xsell_numero_mesi_dilazione AS VARCHAR(45)) AS xsell_numero_mesi_dilazione,
  TRY_CAST(xsell_numero_rate AS VARCHAR(45)) AS xsell_numero_rate,
  TRY_CAST(xsell_codice_assicurazione AS VARCHAR(45)) AS xsell_codice_assicurazione,
  TRY_CAST(xsell_importo_fido_attuale AS VARCHAR(45)) AS xsell_importo_fido_attuale,
  TRY_CAST(xsell_codice_pim AS VARCHAR(45)) AS xsell_codice_pim,
  TRY_CAST(data_creazione AS DATE) AS data_creazione,
  TRY_CAST(data_modifica AS DATE) AS data_modifica
from {{ source('source_l0','tblquestionario') }}
