select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  COALESCE(TRY_CAST(data_modifica AS TIMESTAMP_NTZ), TRY_CAST(data_creazione AS TIMESTAMP_NTZ)) AS ts_coalesce_modif_creaz, --TRYCAST prima della COALESCE altrimenti non funziona correttamente
  TRY_CAST(idTitolo AS NUMBER(11,0)) AS idtitolo,
  TRY_CAST(idProdottoVersione AS NUMBER(11,0)) AS idprodottoversione,
  TRY_CAST(idCertificato AS VARCHAR(250)) AS idcertificato,
  TRY_CAST(cod_agenzia AS VARCHAR(45)) AS cod_agenzia,
  TRY_CAST(ramo AS VARCHAR(45)) AS ramo,
  TRY_CAST(numeroCertificato AS VARCHAR(250)) AS numerocertificato,
  TRY_CAST(sub_agenzia AS VARCHAR(45)) AS sub_agenzia,
  TRY_CAST(dataEffetto AS DATE) AS dataeffetto,
  TRY_CAST(dataScadenza AS DATE) AS datascadenza,
  TRY_CAST(contr_nome_ragsoc AS VARCHAR(250)) AS contr_nome_ragsoc,
  TRY_CAST(codProdotto AS VARCHAR(250)) AS codprodotto,
  TRY_CAST(descrizione_titolo AS VARCHAR(250)) AS descrizione_titolo,
  TRY_CAST(dataValuta AS DATE) AS datavaluta,
  TRY_CAST(dataPagamento AS DATE) AS datapagamento,
  TRY_CAST(premioNetto AS NUMBER(38,10)) AS premionetto,
  TRY_CAST(premioAddizionale AS NUMBER(38,10)) AS premioaddizionale,
  TRY_CAST(premioImponibile AS NUMBER(38,10)) AS premioimponibile,
  TRY_CAST(premioTasse AS NUMBER(38,10)) AS premiotasse,
  TRY_CAST(premioLordo AS NUMBER(38,10)) AS premiolordo,
  TRY_CAST(premio_commissioni AS NUMBER(38,10)) AS premio_commissioni,
  TRY_CAST(tipoPagamento AS VARCHAR(25)) AS tipopagamento,
  TRY_CAST(statoTitolo AS NUMBER(11,0)) AS statotitolo,
  TRY_CAST(tipoOperazione AS NUMBER(11,0)) AS tipooperazione,
  TRY_CAST(data_creazione AS DATE) AS data_creazione,
  TRY_CAST(data_modifica AS DATE) AS data_modifica
from {{ source('source_l0','tbltitoli') }}
