select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  COALESCE(TRY_CAST(data_modifica AS TIMESTAMP_NTZ), TRY_CAST(data_creazione AS TIMESTAMP_NTZ)) AS ts_coalesce_modif_creaz, --TRYCAST prima della COALESCE altrimenti non funziona correttamente
  TRY_CAST(idNodo AS NUMBER(11,0)) AS idnodo,
  TRY_CAST(dsNodo AS VARCHAR(250)) AS dsnodo,
  TRY_CAST(codNodo AS VARCHAR(20)) AS codnodo,
  TRY_CAST(idNodoPadre AS NUMBER(11,0)) AS idnodopadre,
  TRY_CAST(idTipoNodo AS NUMBER(6,0)) AS idtiponodo,
  TRY_CAST(compagnia AS NUMBER(6,0)) AS compagnia,
  TRY_CAST(tipoNodoBanca AS VARCHAR(10)) AS tiponodobanca,
  TRY_CAST(areaNodo AS VARCHAR(10)) AS areanodo,
  TRY_CAST(ABI AS VARCHAR(10)) AS abi,
  TRY_CAST(CAB AS VARCHAR(5)) AS cab,
  TRY_CAST(INDIRIZZO AS VARCHAR(250)) AS indirizzo,
  TRY_CAST(COMUNE AS VARCHAR(150)) AS comune,
  TRY_CAST(PROV AS VARCHAR(4)) AS prov,
  TRY_CAST(CAP AS VARCHAR(10)) AS cap,
  TRY_CAST(file_cert AS VARCHAR(255)) AS file_cert,
  TRY_CAST(alias_cert AS VARCHAR(45)) AS alias_cert,
  TRY_CAST(pwd_cert AS VARCHAR(45)) AS pwd_cert,
  TRY_CAST(numeratoreFlusso AS NUMBER(11,0)) AS numeratoreflusso,
  TRY_CAST(telefono AS VARCHAR(60)) AS telefono,
  TRY_CAST(fax AS VARCHAR(60)) AS fax,
  TRY_CAST(nome_resp AS VARCHAR(150)) AS nome_resp,
  TRY_CAST(cognome_resp AS VARCHAR(150)) AS cognome_resp,
  TRY_CAST(email_resp AS VARCHAR(255)) AS email_resp,
  TRY_CAST(nodo_CF_IVA AS VARCHAR(30)) AS nodo_cf_iva,
  TRY_CAST(codServiceEsterno AS VARCHAR(20)) AS codserviceesterno,
  TRY_CAST(dsServiceEsterno AS VARCHAR(100)) AS dsserviceesterno,
  TRY_CAST(data_creazione AS TIMESTAMP_NTZ) AS data_creazione,
  TRY_CAST(data_modifica AS TIMESTAMP_NTZ) AS data_modifica
from {{ source('source_l0','tblnodi') }}
