select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  COALESCE(TRY_CAST(data_modifica AS TIMESTAMP_NTZ), TRY_CAST(data_creazione AS TIMESTAMP_NTZ)) AS ts_coalesce_modif_creaz, --TRYCAST prima della COALESCE altrimenti non funziona correttamente
  TRY_CAST(idTitolo AS NUMBER(11,0)) AS idtitolo,
  TRY_CAST(idPreventivo AS NUMBER(11,0)) AS idpreventivo,
  TRY_CAST(dataCreazione AS TIMESTAMP_NTZ) AS datacreazione,
  TRY_CAST(idUserCreazione AS NUMBER(11,0)) AS idusercreazione,
  TRY_CAST(idNodoCreazione AS NUMBER(11,0)) AS idnodocreazione,
  TRY_CAST(dataUltimaModifica AS TIMESTAMP_NTZ) AS dataultimamodifica,
  TRY_CAST(idUserModifica AS NUMBER(11,0)) AS idusermodifica,
  TRY_CAST(idNodoModifica AS NUMBER(11,0)) AS idnodomodifica,
  TRY_CAST(idTipoOperazione AS VARCHAR(4)) AS idtipooperazione,
  TRY_CAST(dataEmissioneTitolo AS DATE) AS dataemissionetitolo,
  TRY_CAST(dataScadenzaTitolo AS DATE) AS datascadenzatitolo,
  TRY_CAST(statoTitolo AS NUMBER(6,0)) AS statotitolo,
  TRY_CAST(tipoPagamento AS NUMBER(6,0)) AS tipopagamento,
  TRY_CAST(dataPagamento AS DATE) AS datapagamento,
  TRY_CAST(premioLordo AS NUMBER(38,10)) AS premiolordo,
  TRY_CAST(tasse AS NUMBER(38,10)) AS tasse,
  TRY_CAST(provvigioni AS NUMBER(38,10)) AS provvigioni,
  TRY_CAST(eliminato AS NUMBER(6,0)) AS eliminato,
  TRY_CAST(tasso_provvigioni AS NUMBER(11,0)) AS tasso_provvigioni,
  TRY_CAST(tasso_commissioni AS NUMBER(11,0)) AS tasso_commissioni,
  TRY_CAST(commissioni AS NUMBER(38,10)) AS commissioni,
  TRY_CAST(dataEffettoCopertura AS DATE) AS dataeffettocopertura,
  TRY_CAST(dataScadenzaCopertura AS DATE) AS datascadenzacopertura,
  TRY_CAST(dataExportBroker AS TIMESTAMP_NTZ) AS dataexportbroker,
  TRY_CAST(dataExportACE AS TIMESTAMP_NTZ) AS dataexportace,
  TRY_CAST(imported AS NUMBER(1,0)) AS imported,
  TRY_CAST(data_creazione AS TIMESTAMP_NTZ) AS data_creazione,
  TRY_CAST(data_modifica AS TIMESTAMP_NTZ) AS data_modifica
from {{ source('source_l0','acedrv_tbltitoli') }}
