select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(DPS_PROCEDURA) = '', ' ', RTRIM(DPS_PROCEDURA)) AS VARCHAR(2)) AS dps_procedura,
  TRY_CAST(DPS_PRATICA AS NUMBER(12,0)) AS dps_pratica,
  TRY_CAST(DPS_DATA_SCAD_TIT AS NUMBER(8,0)) AS dps_data_scad_tit,
  TRY_CAST(IFF(RTRIM(DPS_OPERAZIONE) = '', ' ', RTRIM(DPS_OPERAZIONE)) AS VARCHAR(3)) AS dps_operazione,
  TRY_CAST(DPS_EFFETTO_OCS AS NUMBER(12,0)) AS dps_effetto_ocs,
  TRY_CAST(DPS_MARCATURA AS NUMBER(10,0)) AS dps_marcatura,
  TRY_CAST(DPS_LOG_DATA AS NUMBER(8,0)) AS dps_log_data,
  TRY_CAST(DPS_LOG_ORA AS NUMBER(8,0)) AS dps_log_ora,
  TRY_CAST(DPS_IDE_DOWNLOAD_T AS NUMBER(13,0)) AS dps_ide_download_t,
  TRY_CAST(DPS_IDE_DOWNLOAD_D AS NUMBER(13,0)) AS dps_ide_download_d,
  TRY_CAST(DPS_IDE_UPLOAD_T AS NUMBER(13,0)) AS dps_ide_upload_t,
  TRY_CAST(DPS_IDE_UPLOAD_D AS NUMBER(13,0)) AS dps_ide_upload_d,
  TRY_CAST(IFF(RTRIM(DPS_ESITO_OCS) = '', ' ', RTRIM(DPS_ESITO_OCS)) AS VARCHAR(2)) AS dps_esito_ocs,
  TRY_CAST(DPS_CD_ESITO_OPE AS NUMBER(2,0)) AS dps_cd_esito_ope,
  TRY_CAST(DPS_CD_STATO_TIT AS NUMBER(2,0)) AS dps_cd_stato_tit,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','efexfedps') }}
