select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(NULLIF(RTRIM(AIPARDL_SEZIONE), '') AS VARCHAR(1)) AS aipardl_sezione,
  TRY_CAST(AIPARDL_PRATICA AS NUMBER(12,0)) AS aipardl_pratica,
  TRY_CAST(AIPARDL_PROGRESSIVO AS NUMBER(9,0)) AS aipardl_progressivo,
  TRY_CAST(AIPARDL_RIGA AS NUMBER(5,0)) AS aipardl_riga,
  TRY_CAST(AIPARDL_CAUSALE AS NUMBER(3,0)) AS aipardl_causale,
  TRY_CAST(NULLIF(RTRIM(AIPARDL_TIPO_DOCUMENTO), '') AS VARCHAR(2)) AS aipardl_tipo_documento,
  TRY_CAST(AIPARDL_NUM_DOCUMENTO AS NUMBER(12,0)) AS aipardl_num_documento,
  TRY_CAST(AIPARDL_DATA_DOCUMENTO AS NUMBER(8,0)) AS aipardl_data_documento,
  TRY_CAST(AIPARDL_IMP_PARTITA AS NUMBER(13,0)) AS aipardl_imp_partita,
  TRY_CAST(AIPARDL_DATA_SCAD_VAL AS NUMBER(8,0)) AS aipardl_data_scad_val,
  TRY_CAST(AIPARDL_DATA_COMP AS NUMBER(8,0)) AS aipardl_data_comp,
  TRY_CAST(AIPARDL_EVENTO AS NUMBER(11,0)) AS aipardl_evento,
  TRY_CAST(NULLIF(RTRIM(AIPARDL_TIPO_MOV), '') AS VARCHAR(1)) AS aipardl_tipo_mov,
  TRY_CAST(AIPARDL_PROG_VAR AS NUMBER(9,0)) AS aipardl_prog_var,
  TRY_CAST(AIPARDL_DATA_VARIAZIONE AS NUMBER(8,0)) AS aipardl_data_variazione,
  TRY_CAST(AIPARDL_ORA_VARIAZIONE AS NUMBER(8,0)) AS aipardl_ora_variazione,
  TRY_CAST(NULLIF(RTRIM(AIPARDL_OPERATORE_VARIAZ), '') AS VARCHAR(10)) AS aipardl_operatore_variaz,
  TRY_CAST(NULLIF(RTRIM(AIPARDL_TIPO_OPERAZIONE), '') AS VARCHAR(1)) AS aipardl_tipo_operazione,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','aiecfpardl') }}
