select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(TP_BUDGET AS VARCHAR(10)) AS tp_budget,
  TRY_CAST(DT_INIZIO_VALIDITA AS TIMESTAMP) AS dt_inizio_validita,
  TRY_CAST(DT_FINE_VALIDITA AS TIMESTAMP) AS dt_fine_validita,
  TRY_CAST(NM_ANNO AS NUMBER(4)) AS nm_anno,
  TRY_CAST(NM_MESE AS NUMBER(2)) AS nm_mese,
  TRY_CAST(TP_PROCEDURA AS VARCHAR(10)) AS tp_procedura,
  TRY_CAST(CD_GER_TERRITORIALE_1 AS VARCHAR(50)) AS cd_ger_territoriale_1,
  TRY_CAST(CD_GER_TERRITORIALE_2 AS VARCHAR(50)) AS cd_ger_territoriale_2,
  TRY_CAST(CD_GER_TERRITORIALE_3 AS VARCHAR(50)) AS cd_ger_territoriale_3,
  TRY_CAST(CD_GER_TERRITORIALE_4 AS VARCHAR(50)) AS cd_ger_territoriale_4,
  TRY_CAST(CD_NODO_FOGLIA AS VARCHAR(50)) AS cd_nodo_foglia,
  TRY_CAST(CD_MERCATO_1 AS VARCHAR(50)) AS cd_mercato_1,
  TRY_CAST(CD_MERCATO_2 AS VARCHAR(50)) AS cd_mercato_2,
  TRY_CAST(CD_MERCATO_3 AS VARCHAR(50)) AS cd_mercato_3,
  TRY_CAST(CD_MERCATO_4 AS VARCHAR(50)) AS cd_mercato_4,
  TRY_CAST(EU_BDG_FINANZ AS NUMBER(38,2)) AS eu_bdg_finanz,
  TRY_CAST(NM_BDG_IRR AS NUMBER(38,6)) AS nm_bdg_irr,
  TRY_CAST(NM_BDG_DURATA AS NUMBER(38,6)) AS nm_bdg_durata,
  TRY_CAST(EU_FTP AS NUMBER(38,2)) AS eu_ftp,
  TRY_CAST(NM_TAN AS NUMBER(38,6)) AS nm_tan,
  TRY_CAST(NM_BDG_PRAT_DECORSE AS NUMBER(38,6)) AS nm_bdg_prat_decorse,
  TRY_CAST(EU_BDG_NPV AS NUMBER(38,2)) AS eu_bdg_npv,
  TRY_CAST(EU_BDG_NPV_ASSIC AS NUMBER(38,2)) AS eu_bdg_npv_assic
from {{ source('source_l0','budget_prod_filiale') }}
