select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(energ AS VARCHAR(2)) AS energ,
  TRY_CAST(idEng AS VARCHAR(40)) AS ideng,
  TRY_CAST(cdAppliEng AS VARCHAR(12)) AS cdapplieng,
  TRY_CAST(NMSYSGES AS VARCHAR(20)) AS nmsysges,
  TRY_CAST(cdCtreRes AS VARCHAR(7)) AS cdctreres,
  TRY_CAST(cdCt AS VARCHAR(40)) AS cdct,
  TRY_CAST(cdEDC AS VARCHAR(40)) AS cdedc,
  TRY_CAST(cdBilHB AS VARCHAR(1)) AS cdbilhb,
  TRY_CAST(cdArPmt AS VARCHAR(1)) AS cdarpmt,
  TRY_CAST(cdAppCmpt AS VARCHAR(40)) AS cdappcmpt,
  TRY_CAST(cdIndAct AS VARCHAR(1)) AS cdindact,
  TRY_CAST(cdTypRest AS VARCHAR(2)) AS cdtyprest,
  TRY_CAST(cdModTit AS VARCHAR(1)) AS cdmodtit,
  TRY_CAST(cdFCT AS VARCHAR(3)) AS cdfct,
  TRY_CAST(cdClasIFRS9 AS VARCHAR(3)) AS cdclasifrs9,
  TRY_CAST(cdClasLoc AS VARCHAR(3)) AS cdclasloc,
  TRY_CAST(cdBuck AS VARCHAR(2)) AS cdbuck,
  TRY_CAST(cdRefScen AS VARCHAR(10)) AS cdrefscen,
  TRY_CAST(txPD AS VARCHAR(15)) AS txpd,
  TRY_CAST(cdBuckPrec AS VARCHAR(2)) AS cdbuckprec,
  TRY_CAST(mtProvECLOrig AS VARCHAR(19)) AS mtproveclorig,
  TRY_CAST(cdDev AS VARCHAR(3)) AS cddev,
  TRY_CAST(mtProvPrecOrig AS VARCHAR(19)) AS mtprovprecorig,
  TRY_CAST(cdDevProvPre AS VARCHAR(3)) AS cddevprovpre,
  TRY_CAST(mtVarProvOrig AS VARCHAR(19)) AS mtvarprovorig,
  TRY_CAST(cdSensVarOrig AS VARCHAR(1)) AS cdsensvarorig,
  TRY_CAST(mtProvECLEuro AS VARCHAR(19)) AS mtprovecleuro,
  TRY_CAST(mtProvPrecEuro AS VARCHAR(19)) AS mtprovpreceuro,
  TRY_CAST(mtVarProvEuro AS VARCHAR(19)) AS mtvarproveuro,
  TRY_CAST(cdSensVarEuro AS VARCHAR(1)) AS cdsensvareuro,
  TRY_CAST(filler AS VARCHAR(50)) AS filler
from {{ source('source_l0','flux_cre_provision') }}
where energ = '01'
