select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRIM(SUBSTR(DS_COLONNA, 1, 8))   AS CLOSING_DATE,                    -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTR(DS_COLONNA, 9, 5))   AS RISK_TAKER_ENTITY,               -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTR(DS_COLONNA, 14, 12)) AS SOURCE_APPLICATION,
  TRIM(SUBSTR(DS_COLONNA, 26, 1))  AS TRANSMISSION_FREQUENCY,
  TRIM(SUBSTR(DS_COLONNA, 27, 12)) AS DATE_TIME_PROCESSING,            -- fix: era TRY_CAST AS TIMESTAMP_NTZ
  TRIM(SUBSTR(DS_COLONNA, 39, 2))  AS RECORD_TYPE,
  TRIM(SUBSTR(DS_COLONNA, 41, 20)) AS LOCAL_ID_COUNTER,
  TRIM(SUBSTR(DS_COLONNA, 61, 10)) AS CENTRAL_ID_COUNTER,              -- fix: era TRY_CAST AS NUMERIC(10,0)
  TRIM(SUBSTR(DS_COLONNA, 71, 30)) AS OVERALL_FACILITY_REF,
  TRIM(SUBSTR(DS_COLONNA, 101, 30)) AS FACILITY_DETAIL_LINE_REF,
  TRIM(SUBSTR(DS_COLONNA, 131, 40)) AS MITIGANT_ID,
  TRIM(SUBSTR(DS_COLONNA, 171, 12)) AS NATO,
  TRIM(SUBSTR(DS_COLONNA, 183, 20)) AS LOCAL_ID_GUARANTOR,
  TRIM(SUBSTR(DS_COLONNA, 203, 10)) AS CENTRAL_ID_GUARANTOR,           -- fix: era TRY_CAST AS NUMERIC(10,0)
  TRIM(SUBSTR(DS_COLONNA, 213, 1))  AS PLACE_DEPOSIT_REAL_ESTATE,      -- fix: era TRY_CAST AS NUMERIC(1,0)
  TRIM(SUBSTR(DS_COLONNA, 214, 1))  AS SCOPE_MITIGANT,
  TRIM(SUBSTR(DS_COLONNA, 215, 7))  AS LEGAL_NATURE_MIGRANT,
  TRIM(SUBSTR(DS_COLONNA, 222, 1))  AS INIT_AMOUNT_SGN,
  TRIM(SUBSTR(DS_COLONNA, 223, 16)) AS INIT_AMOUNT_INT,                -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTR(DS_COLONNA, 239, 2))  AS INIT_AMOUNT_DEC,                -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTR(DS_COLONNA, 241, 3))  AS CURR_MITIGANT,
  TRIM(SUBSTR(DS_COLONNA, 244, 8))  AS DATE_COMING_INTO_EFFECT,        -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTR(DS_COLONNA, 252, 8))  AS DATE_EXPIRING,                  -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTR(DS_COLONNA, 260, 1))  AS ELIGIBILITY_MITIGANT,
  TRIM(SUBSTR(DS_COLONNA, 261, 2))  AS COUNTRY_GOV_LAW,
  TRIM(SUBSTR(DS_COLONNA, 263, 5))  AS FREQ_REVALUATION_MITIGANT,      -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTR(DS_COLONNA, 268, 1))  AS MARGIN_CALL_TRIGG_THRES_SGN,
  TRIM(SUBSTR(DS_COLONNA, 269, 16)) AS MARGIN_CALL_TRIGG_THRES_INT,    -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTR(DS_COLONNA, 285, 2))  AS MARGIN_CALL_TRIGG_THRES_DEC,    -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTR(DS_COLONNA, 287, 3))  AS CURR_MARGIN_CALL_TRIGG_THRES,
  TRIM(SUBSTR(DS_COLONNA, 290, 1))  AS BASEL_2_STOCK_INDEX_ID,
  TRIM(SUBSTR(DS_COLONNA, 291, 8))  AS MATURITY_SECURITIES,            -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTR(DS_COLONNA, 299, 2))  AS NATIONALITY_SECURITIES,
  TRIM(SUBSTR(DS_COLONNA, 301, 1))  AS SETTLEMENTE_PERIOD_20DAYS,
  TRIM(SUBSTR(DS_COLONNA, 302, 1))  AS SETTLEMENTE_PERIOD_X2,
  TRIM(SUBSTR(DS_COLONNA, 303, 1))  AS MIN_AMOUNT_MARGIN_CALL_TRANS_SGN,
  TRIM(SUBSTR(DS_COLONNA, 304, 16)) AS MIN_AMOUNT_MARGIN_CALL_TRANS_INT, -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTR(DS_COLONNA, 320, 2))  AS MIN_AMOUNT_MARGIN_CALL_TRANS_DEC, -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTR(DS_COLONNA, 322, 3))  AS CUR_MIN_AMOUNT_MARGIN_CALL_TRANS,
  TRIM(SUBSTR(DS_COLONNA, 325, 6))  AS BANKING_PRODUCT_TYPE,
  TRIM(SUBSTR(DS_COLONNA, 331, 16)) AS REVISED_AMOUNT_INT,             -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTR(DS_COLONNA, 347, 1))  AS DISPUTE_IND_MARGIN_EXCHANGED,
  TRIM(SUBSTR(DS_COLONNA, 348, 12)) AS PCCO_VALUE_PRINCIPAL_1,
  TRIM(SUBSTR(DS_COLONNA, 360, 1))  AS VALUE_PRINCIPAL_1_SGN,
  TRIM(SUBSTR(DS_COLONNA, 361, 16)) AS VALUE_PRINCIPAL_1_INT,          -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTR(DS_COLONNA, 377, 2))  AS VALUE_PRINCIPAL_1_DEC           -- fix: era TRY_CAST AS NUMERIC(2,0)
from {{ source('source_l0','report_m1') }}
