select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRIM(SUBSTRING(DS_COLONNA, 1, 20))   AS LOCAL_ID_COUNTERPARTY,
  TRIM(SUBSTRING(DS_COLONNA, 21, 10))  AS CENTRAL_ID_COUNTERPARTY,             -- fix: era TRY_CAST AS NUMERIC(10,0)
  TRIM(SUBSTRING(DS_COLONNA, 31, 40))  AS PRODUCT_IDENTIFIER,
  TRIM(SUBSTRING(DS_COLONNA, 71, 6))   AS RISK_TYPE,
  TRIM(SUBSTRING(DS_COLONNA, 77, 12))  AS COMMITMENT_TRANSACTION_NATURE,
  TRIM(SUBSTRING(DS_COLONNA, 89, 8))   AS DATE_START_COMMITMENT,               -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTRING(DS_COLONNA, 97, 8))   AS DATE_END_COMMITMENT,                 -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTRING(DS_COLONNA, 105, 16)) AS AMOUNT_MTM_INT,                      -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 121, 16)) AS AMOUNT_AMORTISED_COST_INT,           -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 137, 16)) AS AMOUNT_NOT_DUE_COUPONS_INT,          -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 153, 16)) AS NOMINAL_AMOUNT_INT,                  -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 169, 3))  AS SENIORITY_TRANCHE_VEHICLE,
  TRIM(SUBSTRING(DS_COLONNA, 172, 5))  AS TRANCHE_RATING,
  TRIM(SUBSTRING(DS_COLONNA, 177, 2))  AS SOURCE_TRANCHE_RATING,               -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 179, 1))  AS STS_SECURITIZATION_IND,
  TRIM(SUBSTRING(DS_COLONNA, 180, 6))  AS BANKING_PRODUCT_TYPE,
  TRIM(SUBSTRING(DS_COLONNA, 186, 3))  AS INDICATOR_PRODUCT_SCHEDULE,
  TRIM(SUBSTRING(DS_COLONNA, 189, 40)) AS UNIQUE_CONTRACT_REF,
  TRIM(SUBSTRING(DS_COLONNA, 229, 40)) AS UNIQUE_CONTRACT_ELEMENT_REF,
  TRIM(SUBSTRING(DS_COLONNA, 269, 16)) AS CONTRACT_INITIAL_AMOUNT_INT,         -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 285, 1))  AS INIT_EFFECTIVE_INTEREST_RATE_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 286, 4))  AS INIT_EFFECTIVE_INTEREST_RATE_INT,    -- fix: era TRY_CAST AS NUMERIC(4,0)
  TRIM(SUBSTRING(DS_COLONNA, 290, 5))  AS INIT_EFFECTIVE_INTEREST_RATE_DEC,    -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTRING(DS_COLONNA, 295, 1))  AS TYPE_INTEREST_RATE,
  TRIM(SUBSTRING(DS_COLONNA, 296, 12)) AS REFERENCE_INDEX,
  TRIM(SUBSTRING(DS_COLONNA, 308, 1))  AS FREQ_INTEREST_PAYMENTS,
  TRIM(SUBSTRING(DS_COLONNA, 309, 8))  AS FIRST_REPAYMENT_DATE,                -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTRING(DS_COLONNA, 317, 10)) AS QTY_FIN_SEC,                         -- fix: era TRY_CAST AS NUMERIC(10,0)
  TRIM(SUBSTRING(DS_COLONNA, 327, 1))  AS TYPE_IDENTIF_MARKETABLE_SECUR,       -- fix: era TRY_CAST AS NUMERIC(1,0)
  TRIM(SUBSTRING(DS_COLONNA, 328, 16)) AS INIT_UNIT_PURCHASE_PRICE_INT,        -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 344, 2))  AS INIT_UNIT_PURCHASE_PRICE_DEC,        -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 346, 1))  AS ASSET_MOBILISATION_INDICATOR,        -- fix: era TRY_CAST AS NUMERIC(1,0)
  TRIM(SUBSTRING(DS_COLONNA, 347, 8))  AS ISSUANCE_DATE_SECURITY,              -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTRING(DS_COLONNA, 355, 8))  AS MATURITY_DATE_SECURITY,              -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTRING(DS_COLONNA, 363, 12)) AS PCCO_VALUE_PRINCIPAL_1,
  TRIM(SUBSTRING(DS_COLONNA, 375, 16)) AS VALUE_PRINCIPAL_1_INT,               -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 391, 12)) AS PCCO_RELATED_DEBTS_RECEIVABLES,
  TRIM(SUBSTRING(DS_COLONNA, 403, 16)) AS AMNT_REL_DEBTS_RECEIVABLES_INT,      -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 419, 1))  AS BUSINESS_OBJ_CLOSING_DATE,
  TRIM(SUBSTRING(DS_COLONNA, 420, 1))  AS AMOUNT_ACQ_COST_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 421, 16)) AS AMOUNT_ACQ_COST_INT,                 -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 437, 2))  AS AMOUNT_ACQ_COST_DEC,                 -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 439, 1))  AS QUOTED_ASSET_INDICATOR,
  TRIM(SUBSTRING(DS_COLONNA, 440, 2))  AS CRDT_QLT_STEP_SEC_TRANCHE_ORIGIN,   -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 442, 1))  AS P1_21_47_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 443, 4))  AS P1_21_47_INT,                        -- fix: era TRY_CAST AS NUMERIC(4,0)
  TRIM(SUBSTRING(DS_COLONNA, 447, 5))  AS P1_21_47_DEC,                        -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTRING(DS_COLONNA, 452, 7))  AS P1_21_48,
  TRIM(SUBSTRING(DS_COLONNA, 459, 1))  AS P1_21_49_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 460, 16)) AS P1_21_49_INT,                        -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 476, 2))  AS P1_21_49_DEC,                        -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 478, 3))  AS P1_21_50,
  TRIM(SUBSTRING(DS_COLONNA, 481, 1))  AS P1_21_51_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 482, 16)) AS P1_21_51_INT,                        -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 498, 2))  AS P1_21_51_DEC,                        -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 500, 3))  AS P1_21_52,
  TRIM(SUBSTRING(DS_COLONNA, 503, 1))  AS P1_21_53_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 504, 16)) AS P1_21_53_INT,                        -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTRING(DS_COLONNA, 520, 2))  AS P1_21_53_DEC,                        -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 522, 3))  AS P1_21_54,
  TRIM(SUBSTRING(DS_COLONNA, 525, 1))  AS IN_HIGH_QUALITY_LIQUID_ASSET,
  TRIM(SUBSTRING(DS_COLONNA, 526, 12)) AS TX_COMMITMENT_TRANSACTION_NAT,
  TRIM(SUBSTRING(DS_COLONNA, 538, 2))  AS ENGINE_TREATMENT,                    -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTRING(DS_COLONNA, 540, 1))  AS SRT_SECURITIZED_RECEIVABLES_IND,
  TRIM(SUBSTRING(DS_COLONNA, 541, 1))  AS ATTACHMENT_POINT_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 542, 4))  AS ATTACHMENT_POINT_INT,                -- fix: era TRY_CAST AS NUMERIC(4,0)
  TRIM(SUBSTRING(DS_COLONNA, 546, 5))  AS ATTACHMENT_POINT_DEC,                -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTRING(DS_COLONNA, 551, 1))  AS DETACHMENT_POINT_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 552, 4))  AS DETACHMENT_POINT_INT,                -- fix: era TRY_CAST AS NUMERIC(4,0)
  TRIM(SUBSTRING(DS_COLONNA, 556, 5))  AS DETACHMENT_POINT_DEC,                -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTRING(DS_COLONNA, 561, 1))  AS BASEL_2_WEIGH_COMMIT_IAA_RBA_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 562, 4))  AS BASEL_2_WEIGH_COMMIT_IAA_RBA_INT,   -- fix: era TRY_CAST AS NUMERIC(4,0)
  TRIM(SUBSTRING(DS_COLONNA, 566, 5))  AS BASEL_2_WEIGH_COMMIT_IAA_RBA_DEC,   -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTRING(DS_COLONNA, 571, 7))  AS SECURITIZATION_METHOD,
  TRIM(SUBSTRING(DS_COLONNA, 578, 2))  AS SME_SECURITIZATION_REASON,
  TRIM(SUBSTRING(DS_COLONNA, 580, 1))  AS CREDIT_STATUS,                       -- fix: era TRY_CAST AS NUMERIC(1,0)
  TRIM(SUBSTRING(DS_COLONNA, 581, 1))  AS IN_EQUITY_SECURITY,
  TRIM(SUBSTRING(DS_COLONNA, 582, 1))  AS FREQ_REVISION_INT_RATE_UNIT_TIME,
  TRIM(SUBSTRING(DS_COLONNA, 583, 3))  AS FREQ_REVISION_INT_RATE_NUMBER,       -- fix: era TRY_CAST AS NUMERIC(3,0)
  TRIM(SUBSTRING(DS_COLONNA, 586, 1))  AS ADDITIVE_PROFIT_MARGIN_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 587, 4))  AS ADDITIVE_PROFIT_MARGIN_INT,          -- fix: era TRY_CAST AS NUMERIC(4,0)
  TRIM(SUBSTRING(DS_COLONNA, 591, 5))  AS ADDITIVE_PROFIT_MARGIN_DEC,          -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTRING(DS_COLONNA, 596, 7))  AS INTEREST_CALCULATION_BASIS,
  TRIM(SUBSTRING(DS_COLONNA, 603, 1))  AS MULTIPLICATIVE_PROFIT_MARGIN_SGN,
  TRIM(SUBSTRING(DS_COLONNA, 604, 4))  AS MULTIPLICATIVE_PROFIT_MARGIN_INT,    -- fix: era TRY_CAST AS NUMERIC(4,0)
  TRIM(SUBSTRING(DS_COLONNA, 608, 5))  AS MULTIPLICATIVE_PROFIT_MARGIN_DEC     -- fix: era TRY_CAST AS NUMERIC(5,0)
from {{ source('source_l0','report_p1') }}