select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRIM(SUBSTR(DS_COLONNA, 1, 8))    AS CLOSING_DATE,                        -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTR(DS_COLONNA, 9, 5))    AS RISK_TAKER_ENTITY,                   -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTR(DS_COLONNA, 14, 12))  AS SOURCE_APPLICATION,
  TRIM(SUBSTR(DS_COLONNA, 26, 1))   AS TRANSMISSION_FREQUENCY,
  TRIM(SUBSTR(DS_COLONNA, 27, 12))  AS DATE_TIME_PROCESSING,                -- fix: era TRY_CAST AS TIMESTAMP_NTZ
  TRIM(SUBSTR(DS_COLONNA, 39, 2))   AS RECORD_TYPE,
  TRIM(SUBSTR(DS_COLONNA, 41, 1))   AS NATURE_FLOW,                         -- fix: lunghezza 4→1 (SAS $1)
  TRIM(SUBSTR(DS_COLONNA, 42, 2))   AS ZONE_RESERVED_CA,                    -- fix: offset e lunghezza aggiornati (SAS $2)
  TRIM(SUBSTR(DS_COLONNA, 44, 7))   AS FREE_ZONE_01,                        -- fix: offset e lunghezza aggiornati (SAS/INFILE $7)
  TRIM(SUBSTR(DS_COLONNA, 51, 20))  AS LOCAL_ID_COUNTERPARTY,
  TRIM(SUBSTR(DS_COLONNA, 71, 10))  AS CENTRAL_ID_COUNTERPARTY,             -- fix: era TRY_CAST AS NUMERIC(10,0)
  TRIM(SUBSTR(DS_COLONNA, 81, 30))  AS OVERALL_FACILITY_REFERENCE,
  TRIM(SUBSTR(DS_COLONNA, 111, 30)) AS FACILITY_DETAIL_LINE_REFERENCE,
  TRIM(SUBSTR(DS_COLONNA, 141, 40)) AS MITIGANT_IDENTIFIER,
  TRIM(SUBSTR(DS_COLONNA, 181, 40)) AS PRODUCT_IDENTIFIER,                  -- fix: lunghezza 10→40 (SAS $40)
  TRIM(SUBSTR(DS_COLONNA, 221, 40)) AS REFERENCE_COUNTERPARTY_PROVISION,    -- fix: offset e lunghezza aggiornati (SAS $40)
  TRIM(SUBSTR(DS_COLONNA, 261, 20)) AS FREE_ZONE_02,                        -- fix: offset e lunghezza aggiornati (SAS $20)
  TRIM(SUBSTR(DS_COLONNA, 281, 1))  AS NATURE_IMPAIRMENT,
  TRIM(SUBSTR(DS_COLONNA, 282, 1))  AS SCOPE_ALLOC_PROVISION_HAIRCUT,
  TRIM(SUBSTR(DS_COLONNA, 283, 12)) AS ZONE_RESERVED_GRMD,                  -- fix: lunghezza 16→12 (SAS $12)
  TRIM(SUBSTR(DS_COLONNA, 295, 20)) AS FREE_ZONE_03,                        -- fix: offset e lunghezza aggiornati (INFILE $20)
  TRIM(SUBSTR(DS_COLONNA, 315, 1))  AS AMOUNT_PROVISION_HAIRCUT_SGN,
  TRIM(SUBSTR(DS_COLONNA, 316, 16)) AS AMOUNT_PROVISION_HAIRCUT_INT,        -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTR(DS_COLONNA, 332, 2))  AS AMOUNT_PROVISION_HAIRCUT_DEC,        -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTR(DS_COLONNA, 334, 1))  AS AMOUNT_PROVISION_PREV_QUART_SGN,
  TRIM(SUBSTR(DS_COLONNA, 335, 16)) AS AMOUNT_PROVISION_PREV_QUART_INT,     -- fix: era TRY_CAST AS NUMERIC(16,0)
  TRIM(SUBSTR(DS_COLONNA, 351, 2))  AS AMOUNT_PROVISION_PREV_QUART_DEC,     -- fix: era TRY_CAST AS NUMERIC(2,0)
  TRIM(SUBSTR(DS_COLONNA, 353, 3))  AS CURR_AMOUNT_PROVISION_PREV_QUART,
  TRIM(SUBSTR(DS_COLONNA, 356, 12)) AS PCCO_PROVISION_HAIRCUT,
  TRIM(SUBSTR(DS_COLONNA, 368, 6))  AS BANKING_PRODUCT_TYPE
from {{ source('source_l0','report_p9') }}