select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRIM(SUBSTR(DS_COLONNA, 1, 8))   AS CLOSING_DATE,               -- fix: era TRY_CAST AS DATE
  TRIM(SUBSTR(DS_COLONNA, 9, 5))   AS RISK_TAKER_ENTITY,          -- fix: era TRY_CAST AS NUMERIC(5,0)
  TRIM(SUBSTR(DS_COLONNA, 14, 12)) AS SOURCE_APPLICATION,
  TRIM(SUBSTR(DS_COLONNA, 26, 1))  AS TRANSMISSION_FREQUENCY,
  TRIM(SUBSTR(DS_COLONNA, 27, 12)) AS DATE_TIME_PROCESSING,       -- fix: era TRY_CAST AS TIMESTAMP_NTZ
  TRIM(SUBSTR(DS_COLONNA, 39, 2))  AS RECORD_TYPE,
  TRIM(SUBSTR(DS_COLONNA, 41, 20)) AS LOCAL_ID_COUNTERPARTY,
  TRIM(SUBSTR(DS_COLONNA, 61, 10)) AS CENTRAL_ID_COUNTERPARTY,    -- fix: era TRY_CAST AS NUMERIC(10,0)
  TRIM(SUBSTR(DS_COLONNA, 71, 40)) AS COUNTERPARTY_NAME,
  TRIM(SUBSTR(DS_COLONNA, 111, 70)) AS ADDRESS,
  TRIM(SUBSTR(DS_COLONNA, 181, 30)) AS CITY,
  TRIM(SUBSTR(DS_COLONNA, 211, 15)) AS POSTCODE,                  -- fix: era TRY_CAST AS NUMERIC(15,0)
  TRIM(SUBSTR(DS_COLONNA, 226, 3))  AS BASEL_EXT_COUNTERPARTY_PRTF, -- fix: era TRY_CAST AS NUMERIC(3,0)
  TRIM(SUBSTR(DS_COLONNA, 229, 1))  AS LEVERAGED_FUNDS_INDICATOR,
  TRIM(SUBSTR(DS_COLONNA, 230, 6))  AS ECONOMIC_AGENT

from {{ source('source_l0','report_c1') }}
