-- Storicizzazione: S4 (actual, incremental/insert_overwrite)

SELECT
    PR.TP_PROCEDURA AS TP_PROCEDURA,
    PR.CD_PRATICA AS CD_PRATICA,
    PR.CD_TIPO_PRODOTTO AS CD_TIPO_PRODOTTO,
    PR.CD_EMETTITORE AS CD_EMETTITORE,
    PR.CD_PRODOTTO AS CD_PRODOTTO,
    PR.DS_PRODOTTO_POG AS DS_PRODOTTO_POG,
    CQ.TP_CONTRATTO AS TP_CONTRATTO_CQ,
    PR.CD_TABELLA_FINANZIARIA AS CD_TABELLA_FINANZIARIA,
    PR.DS_TABELLA_FINANZIARIA AS DS_TABELLA_FINANZIARIA,
    TF.CD_ATTRIBUTO_TT AS CD_ATTRIBUTO_TT,
    PR.CD_DESTINAZIONE_BENE AS CD_DESTINAZIONE_BENE,
    PR.DS_DESTINAZIONE_BENE AS DS_DESTINAZIONE_BENE,
    CO.EU_PREZZO_BENE AS EU_PREZZO_BENE,
    PR.CD_MACRO_PRODOTTO_1 AS CD_MACRO_PRODOTTO_1,
    PR.CD_MACRO_PRODOTTO_2 AS CD_MACRO_PRODOTTO_2,
    PR.CD_MACRO_PRODOTTO_3 AS CD_MACRO_PRODOTTO_3,
    PR.CD_MACRO_PRODOTTO_4 AS CD_MACRO_PRODOTTO_4,
    PR.CD_MERCATO_1 AS CD_MERCATO_1,
    PR.CD_MERCATO_2 AS CD_MERCATO_2,
    PR.CD_MERCATO_3 AS CD_MERCATO_3,
    PR.CD_MERCATO_4 AS CD_MERCATO_4,
    PR.CD_FILIALE_PRAT AS CD_FILIALE_PRAT,
    PR.CD_FILIALE_INT AS CD_FILIALE_INT,
    PR.CD_RESPONSABILE AS CD_RESPONSABILE,
    PR.CD_CANALE_ACQUISIZIONE AS CD_CANALE_ACQUISIZIONE,
    PR.DS_CANALE_ACQUISIZIONE AS DS_CANALE_ACQUISIZIONE,
    PR.CD_TIPO_PROCESSO AS CD_TIPO_PROCESSO,
    PR.DS_TIPO_PROCESSO AS DS_TIPO_PROCESSO,
    PR.FL_WEB_CANALE_ACQ AS FL_WEB_CANALE_ACQ,
    PR.CD_INTERMEDIARIO AS CD_INTERMEDIARIO,
    PR.TP_INTERMEDIARIO AS TP_INTERMEDIARIO,
    PR.CD_RETE_VENDITA AS CD_RETE_VENDITA,
    PR.CD_AGENTE AS CD_AGENTE,
    PR.CD_SUB_AGENTE AS CD_SUB_AGENTE,
    PR.CD_CONVENZIONATO AS CD_CONVENZIONATO,
    PR.CD_PUNTO_VENDITA AS CD_PUNTO_VENDITA,
    PR.CD_VENDITORE AS CD_VENDITORE,
    NULL AS CD_GER_TERRITORIALE_1, -- AGT.CD_RETE AS CD_GER_TERRITORIALE_1
    NULL AS CD_GER_TERRITORIALE_2, -- AGT.CD_AREA AS CD_GER_TERRITORIALE_2
    NULL AS CD_GER_TERRITORIALE_3, -- AGT.CD_DISTRETTO AS CD_GER_TERRITORIALE_3
    NULL AS CD_GER_TERRITORIALE_4, -- AGT.CD_FILIALE AS CD_GER_TERRITORIALE_4
    PR.CD_NODO_FOGLIA AS CD_NODO_FOGLIA,
    CQ.CD_GER_TIPO_CLIENTE_1 AS CD_GER_TIPO_CLIENTE_1,
    CQ.CD_GER_TIPO_CLIENTE_2 AS CD_GER_TIPO_CLIENTE_2,
    CQ.CD_GER_TIPO_CLIENTE_3 AS CD_GER_TIPO_CLIENTE_3,
    CQ.CD_GER_TIPO_CLIENTE_4 AS CD_GER_TIPO_CLIENTE_4,
    PR.CD_CLIENTE AS CD_CLIENTE,
    PR.CD_COOBLIGATO AS CD_COOBLIGATO,
    PR.CD_STATO AS CD_STATO,
    PR.CD_ATTRIBUTO AS CD_ATTRIBUTO,
    CA.CD_BLOCCO AS CD_BLOCCO,
    PR.DT_CARICAMENTO AS DT_CARICAMENTO,
    PR.DT_ESAMINATA AS DT_ESAMINATA,
    PR.DT_ESITO AS DT_ESITO,
    PR.DT_APPROVAZIONE AS DT_APPROVAZIONE,
    PR.DT_RESPINTA AS DT_RESPINTA,
    PR.DT_RITIRATA AS DT_RITIRATA,
    PR.DT_LIQUIDAZIONE AS DT_LIQUIDAZIONE,
    PR.DT_DECORRENZA AS DT_DECORRENZA,
    PR.DT_STORNATA AS DT_STORNATA,
    PR.DT_CHIUSURA_REGOLARE AS DT_CHIUSURA_REGOLARE,
    PR.DT_ESTINZIONE_ANTICIPATA AS DT_CH_ESTINZIONE_ANTICIPATA,
    PR.DT_PASSAGGIO_PERDITA AS DT_CH_PASSAGGIO_PERDITA,
    PR.DT_CESSIONE AS DT_CH_CESSIONE,
    PR.DT_CHIUSURA_EFFETTIVA AS DT_CHIUSURA_EFFETTIVA,
    PR.DT_MESSA_IN_MORA AS DT_MESSA_IN_MORA,
    PR.DT_DBT AS DT_DBT,
    PR.EU_FINANZIATO AS EU_FINANZIAMENTO,
    PR.EU_FIDO AS EU_FIDO,
    PR.EU_RATA AS EU_RATA,
    CO.EU_ANTICIPO AS EU_ANTICIPO,
    CASE PR.TP_PROCEDURA 
    WHEN 'CO' THEN CO.NM_DURATA_FINANZ 
    WHEN 'CQ' THEN CQ.NM_DURATA_FINANZ 
    END AS NM_DURATA_FINANZ,
    PR.DT_PRIMA_SCADENZA_IST AS DT_PRIMA_SCADENZA_IST,
    PR.DT_ULTIMA_SCADENZA_IST AS DT_ULTIMA_SCADENZA_IST,
    PR.DT_PRIMA_SCADENZA AS DT_PRIMA_SCADENZA,
    PR.DT_ULTIMA_SCADENZA AS DT_ULTIMA_SCADENZA,
    CO.CD_FREQ_RATA AS CD_FREQ_RATA,
    CO.FL_MAXI_RATA_OPZIONATA AS FL_MAXI_RATA_OPZIONATA,
    CO.DT_MAXI_RATA AS DT_MAXI_RATA,
    CO.EU_MAXI_RATA AS EU_MAXI_RATA,
    CO.NM_TASSO_COSTRUZIONE AS NM_TASSO_COSTRUZIONE,
    CASE PR.TP_PROCEDURA 
    WHEN 'CO' THEN CO.NM_TAEG1 
    WHEN 'CA' THEN CA.NM_TAEG 
    WHEN 'CQ' THEN CQ.NM_TAEG 
    END AS NM_TAEG1,
    CO.NM_TAEG2 AS NM_TAEG2,
    CASE PR.TP_PROCEDURA 
    WHEN 'CO' THEN CO.NM_TAN1 
    WHEN 'CA' THEN CA.NM_TAN 
    WHEN 'CQ' THEN CQ.NM_TAN 
    END AS NM_TAN1,
    CO.NM_TAN2 AS NM_TAN2,
    CASE PR.TP_PROCEDURA 
    WHEN 'CO' THEN CO.NM_TEG1 
    WHEN 'CQ' THEN CQ.NM_TEG 
    END AS NM_TEG1,
    CO.NM_TEG2 AS NM_TEG2,
    CASE PR.TP_PROCEDURA 
    WHEN 'CO' THEN CO.NM_TASSO_MORA 
    WHEN 'CA' THEN CA.NM_TASSO_MORA 
    WHEN 'CQ' THEN CQ.NM_TASSO_MORA 
    END AS NM_TASSO_MORA,
    CO.NM_TASSO_CLIENTE AS NM_TASSO_CLIENTE,
    CASE PR.TP_PROCEDURA 
    WHEN 'CO' THEN CO.NM_IRR_NOMINALE 
    WHEN 'CQ' THEN CQ.NM_IRR_NOMINALE 
    END AS NM_IRR_NOMINALE,
    CASE PR.TP_PROCEDURA 
    WHEN 'CO' THEN CO.NM_IRR_EFFETTIVO 
    WHEN 'CQ' THEN CQ.NM_IRR_EFFETTIVO 
    END AS NM_IRR_EFFETTIVO,
    PR.FL_GIA_CLIENTE_MARKETING AS FL_GIA_CLIENTE_MARKETING,
    PR.CD_GIA_CLIENTE_MARKETING AS CD_GIA_CLIENTE_MARKETING,
    PR.FL_GIA_CLIENTE_CREDITI AS FL_GIA_CLIENTE_CREDITI,
    PR.CD_GIA_CLIENTE_CREDITI AS CD_GIA_CLIENTE_CREDITI,
    PR.FL_FIRMA_DOPPIA AS FL_FIRMA_DOPPIA,
    PR.FL_CARTOLARIZZATA AS FL_CARTOLARIZZATA,
    CO.FL_BENE_DETRAZ_FISCALE AS FL_BENE_DETRAZ_FISCALE,
    PR.FL_PRODOTTO_ASSICURATIVO AS FL_PRODOTTO_ASSICURATIVO
FROM {{ ref('pratica') }} AS PR
LEFT JOIN {{ ref('consumo') }} AS CO 
ON CO.CD_PRATICA = PR.CD_PRATICA 
AND PR.TP_PROCEDURA = 'CO'
LEFT JOIN {{ ref('carta') }} AS CA 
ON CA.CD_PRATICA = PR.CD_PRATICA 
AND PR.TP_PROCEDURA = 'CA'
LEFT JOIN {{ ref('cqs') }} AS CQ 
ON CQ.CD_PRATICA = PR.CD_PRATICA 
AND PR.TP_PROCEDURA = 'CQ'
LEFT JOIN {{ ref('tabelle_finanziarie') }} AS TF 
ON TF.TP_PROCEDURA = PR.TP_PROCEDURA 
AND TF.CD_TABELLA_FINANZIARIA = PR.CD_TABELLA_FINANZIARIA
-- TODO LEFT JOIN { re('ana_gerarchia_territoriale') }} AS AGT ON AGT.CD_NODO_FOGLIA = PR.CD_NODO_FOGLIA
WHERE PR.CD_PRODOTTO NOT IN ('32','02','09','16')
AND PR.CD_EMETTITORE NOT IN ('300','301','600')

UNION ALL
SELECT
    'FS' AS TP_PROCEDURA,
    CL.CD_PRATICA AS CD_PRATICA,
    NULL AS CD_TIPO_PRODOTTO,
    NULL AS CD_EMETTITORE,
    NULL AS CD_PRODOTTO,
    NULL AS DS_PRODOTTO_POG,
    NULL AS TP_CONTRATTO_CQ,
    NULL AS CD_TABELLA_FINANZIARIA,
    NULL AS DS_TABELLA_FINANZIARIA,
    NULL AS CD_ATTRIBUTO_TT,
    NULL AS CD_DESTINAZIONE_BENE,
    NULL AS DS_DESTINAZIONE_BENE,
    NULL AS EU_PREZZO_BENE,
    NULL AS CD_MACRO_PRODOTTO_1,
    NULL AS CD_MACRO_PRODOTTO_2,
    NULL AS CD_MACRO_PRODOTTO_3,
    NULL AS CD_MACRO_PRODOTTO_4,
    NULL AS CD_MERCATO_1,
    NULL AS CD_MERCATO_2,
    NULL AS CD_MERCATO_3,
    NULL AS CD_MERCATO_4,
    NULL AS CD_FILIALE_PRAT,
    NULL AS CD_FILIALE_INT,
    NULL AS CD_RESPONSABILE,
    NULL AS CD_CANALE_ACQUISIZIONE,
    NULL AS DS_CANALE_ACQUISIZIONE,
    NULL AS CD_TIPO_PROCESSO,
    NULL AS DS_TIPO_PROCESSO,
    NULL AS FL_WEB_CANALE_ACQ,
    NULL AS CD_INTERMEDIARIO,
    NULL AS TP_INTERMEDIARIO,
    NULL AS CD_RETE_VENDITA,
    NULL AS CD_AGENTE,
    NULL AS CD_SUB_AGENTE,
    NULL AS CD_CONVENZIONATO,
    NULL AS CD_PUNTO_VENDITA,
    NULL AS CD_VENDITORE,
    NULL AS CD_GER_TERRITORIALE_1,
    NULL AS CD_GER_TERRITORIALE_2,
    NULL AS CD_GER_TERRITORIALE_3,
    NULL AS CD_GER_TERRITORIALE_4,
    NULL AS CD_NODO_FOGLIA,
    NULL AS CD_GER_TIPO_CLIENTE_1,
    NULL AS CD_GER_TIPO_CLIENTE_2,
    NULL AS CD_GER_TIPO_CLIENTE_3,
    NULL AS CD_GER_TIPO_CLIENTE_4,
    NULL AS CD_CLIENTE,
    NULL AS CD_COOBLIGATO,
    NULL AS CD_STATO,
    NULL AS CD_ATTRIBUTO,
    NULL AS CD_BLOCCO,
    NULL AS DT_CARICAMENTO,
    NULL AS DT_ESAMINATA,
    NULL AS DT_ESITO,
    NULL AS DT_APPROVAZIONE,
    NULL AS DT_RESPINTA,
    NULL AS DT_RITIRATA,
    NULL AS DT_LIQUIDAZIONE,
    CL.DT_INIZIO_LIN_CREDIT AS DT_DECORRENZA,
    NULL AS DT_STORNATA,
    NULL AS DT_CHIUSURA_REGOLARE,
    NULL AS DT_CH_ESTINZIONE_ANTICIPATA,
    NULL AS DT_CH_PASSAGGIO_PERDITA,
    NULL AS DT_CH_CESSIONE,
    NULL AS DT_CHIUSURA_EFFETTIVA,
    NULL AS DT_MESSA_IN_MORA,
    NULL AS DT_DBT,
    NULL AS EU_FINANZIAMENTO,
    NULL AS EU_FIDO,
    NULL AS EU_RATA,
    NULL AS EU_ANTICIPO,
    NULL AS NM_DURATA_FINANZ,
    NULL AS DT_PRIMA_SCADENZA_IST,
    NULL AS DT_ULTIMA_SCADENZA_IST,
    NULL AS DT_PRIMA_SCADENZA,
    NULL AS DT_ULTIMA_SCADENZA,
    NULL AS CD_FREQ_RATA,
    NULL AS FL_MAXI_RATA_OPZIONATA,
    NULL AS DT_MAXI_RATA,
    NULL AS EU_MAXI_RATA,
    NULL AS NM_TASSO_COSTRUZIONE,
    NULL AS NM_TAEG1,
    NULL AS NM_TAEG2,
    NULL AS NM_TAN1,
    NULL AS NM_TAN2,
    NULL AS NM_TEG1,
    NULL AS NM_TEG2,
    NULL AS NM_TASSO_MORA,
    NULL AS NM_TASSO_CLIENTE,
    NULL AS NM_IRR_NOMINALE,
    NULL AS NM_IRR_EFFETTIVO,
    NULL AS FL_GIA_CLIENTE_MARKETING,
    NULL AS CD_GIA_CLIENTE_MARKETING,
    NULL AS FL_GIA_CLIENTE_CREDITI,
    NULL AS CD_GIA_CLIENTE_CREDITI,
    NULL AS FL_FIRMA_DOPPIA,
    NULL AS FL_CARTOLARIZZATA,
    NULL AS FL_BENE_DETRAZ_FISCALE,
    NULL AS FL_PRODOTTO_ASSICURATIVO
FROM {{ ref('creditline') }} AS CL
WHERE CL.TP_LINEA_DI_CREDITO = 'CREDIT_LINE'