-- DataMart L3: DM_DIM_PRODUZ_UTILIZZI_CARTE
-- Processo: MONITORAGGIO_PRODUZIONE  |  schema target: L3_MONITORING_PRODUZIONE
-- Storicizzazione: S4 (actual, incremental/insert_overwrite)
-- Procedure (UNION ALL): P1
-- CD_GER_TERRITORIALE_1..4 da ANA_GERARCHIA_TERRITORIALE (LEFT JOIN su CD_NODO_FOGLIA).
-- WARN parser: campi duplicati ignorati: ['NM_DURATA_FINANZ']

SELECT
    CU.TP_PROCEDURA AS TP_PROCEDURA,
    CU.CD_PRATICA AS CD_PRATICA,
    CU.CD_PROTOCOLLO AS CD_PROTOCOLLO,
    CU.CD_RIGA AS CD_RIGA,
    CU.CD_EMETTITORE AS CD_EMETTITORE,
    CU.CD_MACRO_PRODOTTO_1 AS CD_MACRO_PRODOTTO_1,
    CU.CD_MACRO_PRODOTTO_2 AS CD_MACRO_PRODOTTO_2,
    CU.CD_MACRO_PRODOTTO_3 AS CD_MACRO_PRODOTTO_3,
    CU.CD_MACRO_PRODOTTO_4 AS CD_MACRO_PRODOTTO_4,
    CU.CD_MERCATO_1 AS CD_MERCATO_1,
    CU.CD_MERCATO_2 AS CD_MERCATO_2,
    CU.CD_MERCATO_3 AS CD_MERCATO_3,
    CU.CD_MERCATO_4 AS CD_MERCATO_4,
    CAST(NULL AS VARCHAR(10)) AS CD_GER_TERRITORIALE_1,   -- TODO AGT.CD_RETE
    CAST(NULL AS VARCHAR(3))  AS CD_GER_TERRITORIALE_2,   -- TODO AGT.CD_AREA
    CAST(NULL AS VARCHAR(3))  AS CD_GER_TERRITORIALE_3,   -- TODO AGT.CD_DISTRETTO
    CAST(NULL AS VARCHAR(3))  AS CD_GER_TERRITORIALE_4,   -- TODO AGT.CD_FILIALE
    CU.CD_NODO_FOGLIA AS CD_NODO_FOGLIA,
    CU.EU_FINANZIATO AS EU_FINANZIAMENTO,
    CU.NM_DURATA_FINANZ AS NM_DURATA_FINANZ,
    CU.NM_IRR AS NM_IRR,
    CU.TP_UTILIZZO AS TP_UTILIZZO,
    CU.TP_MOVIMENTO AS TP_MOVIMENTO,
    CU.FL_STORNATO AS FL_STORNATO,
    CU.FL_STORNO AS FL_STORNO,
    CU.CD_PROMOZIONE AS CD_PROMOZIONE,
    CU.NM_MESI_DILAZIONE AS NM_MESI_DILAZIONE,
    CU.PC_COMMISSIONE AS PC_COMMISSIONE,
    CU.NM_TAEG AS NM_TAEG,
    CU.FL_CONTRIBUTI_PROMO AS FL_CONTRIBUTI_PROMO,
    CU.NM_TAN_PROMO AS NM_TAN_PROMO,
    CU.NM_TEG_PROMO AS NM_TEG_PROMO,
    CU.NM_TAEG_PROMO AS NM_TAEG_PROMO,
    CU.FL_TAEG_FISSO AS FL_TAEG_FISSO,
    CU.NM_TAEG_FISSO_MIN AS NM_TAEG_FISSO_MIN,
    CU.NM_TAEG_FISSO_MAX AS NM_TAEG_FISSO_MAX,
    CU.PC_SCONTO AS PC_SCONTO,
    CU.NM_RATE AS NM_RATE,
    CU.PC_TASSO_RATA AS PC_TASSO_RATA
FROM {{ ref('carte_utilizzi') }} AS CU
-- TODO LEFT JOIN { re('ana_gerarchia_territoriale') }} AS AGT ON AGT.CD_NODO_FOGLIA = CU.CD_NODO_FOGLIA  -- FIX: RT del data model citava PRATICA, join riportato sulla MAIN CARTE_UTILIZZI; -- FIX: 'AS B AND' -> 'ON'
WHERE CU.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')