-- DataMart L3: DM_MOV_PRODUZIONE
-- Processo: MONITORAGGIO_PRODUZIONE  |  schema target: L3_MONITORING_PRODUZIONE
-- Storicizzazione: S4 (actual, incremental/insert_overwrite)
-- Fact da UNPIVOT delle date di PRATICA. 6 procedure in UNION ALL.
-- EMFN/misure: Consumo usa EMFN (EU_FINANZIATO - EU_COMMISSIONI_IST - EU_TOT_CONTRIB_DA_INTER + COALESCE(EU_PROVVIGIONI,0));
--   CQS usa EU_FINANZIATO; Carte non specifica le misure NUM/DEN (NULL). Lo storno inverte il segno su DT_STORNATA.
-- Numerose incongruenze/typo del data model annotate con -- FIX / -- WARN.

WITH prat_unpivot AS (
    SELECT
        TP_PROCEDURA,      -- VARCHAR(2)   : SELECT/WHERE/JOIN (CO, CA, CQ)
        CD_PRATICA,        -- NUMBER(16,0) : SELECT/JOIN (CO, CA, CQ)
        EU_FINANZIATO,     -- NUMBER(13,2) : misure CO e CQ
        CD_PRODOTTO,       -- VARCHAR(2)   : filtro WHERE ramo CO
        CD_EMETTITORE,     -- NUMBER(3,0)  : filtro WHERE ramo CA
        DT_MOVIMENTO,      -- generata dall'UNPIVOT
        TP_MOVIMENTO       -- generata dall'UNPIVOT
    FROM {{ ref('pratica') }}
    UNPIVOT (DT_MOVIMENTO FOR TP_MOVIMENTO IN (DT_CARICAMENTO, DT_ESITO, DT_RESPINTA, DT_RITIRATA, DT_DECORRENZA, DT_STORNATA))
    WHERE DT_MOVIMENTO IS NOT NULL
    -- WARN: il data model usa set di date UNPIVOT incoerenti tra i campi; usato il set completo (6 date)
),

--TODO
-- eu_pv AS (
--     SELECT CD_PROCEDURA, CD_PRATICA, SUM(EU_TOTALE) AS EU_PROVVIGIONI
--     FROM { re('provvigioni_e_rappel') }} WHERE TP_PROVVIGIONE = 'PV'
--     GROUP BY CD_PROCEDURA, CD_PRATICA
-- )

-- ========== Procedura: Passaggi di stato Consumo ==========

sa_agg AS (
    SELECT
        SA.CD_PRATICA,
        SA.TP_PROCEDURA,
        SUM(SA.EU_PREMIO_LORDO) AS EU_PREMIO_LORDO
    FROM {{ ref('servizi_assicurativi') }} SA
    GROUP BY
        SA.CD_PRATICA,
        SA.TP_PROCEDURA
)

SELECT
    PR.TP_PROCEDURA AS TP_PROCEDURA,
    PR.CD_PRATICA AS CD_PRATICA,
    0 AS CD_EMETTITORE_UTILIZZO,
    0 AS CD_PROTOCOLLO_UTILIZZO,
    0 AS CD_RIGA_UTILIZZO,
    PR.DT_MOVIMENTO AS DT_MOVIMENTO,
    PR.TP_MOVIMENTO AS TP_MOVIMENTO,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN 'S' ELSE 'N' END AS FL_STORNO,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_CARICAMENTO' THEN 1 ELSE 0 END AS NM_PRATICA_CARICATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_ESITO' THEN 1 ELSE 0 END AS NM_PRATICA_ESITATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_RESPINTA' THEN 1 ELSE 0 END AS NM_PRATICA_RESPINTA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_RITIRATA' THEN 1 ELSE 0 END AS NM_PRATICA_RITIRATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_DECORRENZA' THEN 1 WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN -1 ELSE 0 END AS NM_PRATICA_DECORSA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN PR.EU_FINANZIATO * -1 ELSE PR.EU_FINANZIATO END AS EU_FINANZIATO,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * -1 ELSE (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) END AS EMFN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_IRR_EFFETTIVO * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_IRR_EFFETTIVO * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_IRR_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_IRR_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_DURATA_FINANZ_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */)) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */)) END AS NM_DURATA_FINANZ_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TAEG1 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TAEG1 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAEG1_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAEG1_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TAN1 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TAN1 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAN1_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAN1_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TEG1 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TEG1 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TEG1_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TEG1_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TAEG2 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TAEG2 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAEG2_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAEG2_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TAN2 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TAN2 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAN2_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TAN2_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TEG2 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TEG2 * (PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TEG2_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO - C.EU_COMMISSIONI_IST - C.EU_TOT_CONTRIB_DA_INTER /* + TODO COALESCE(P.EU_PROVVIGIONI, 0) */) * C.NM_DURATA_FINANZ) END AS NM_TEG2_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.EU_FRESH_CASH) * -1 ELSE (C.EU_FRESH_CASH) END AS EU_FRESH_CASH,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.EU_EROGATO) * -1 ELSE (C.EU_EROGATO) END AS EU_EROGATO,
    SA.EU_PREMIO_LORDO AS EU_PREMIO_ASSICURAZIONE_LORDO,
    --TODO CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (P.EU_PROVVIGIONI) * -1 ELSE (P.EU_PROVVIGIONI) END AS EU_PROVVIGIONE,
    CAST(NULL AS NUMBER(13,2)) AS EU_PROVVIGIONE,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.EU_SPESE_TOT_IST) * -1 ELSE (C.EU_SPESE_TOT_IST) END AS EU_SPESE_TOT_IST,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.EU_TOT_CONTRIB_DA_INTER) * -1 ELSE (C.EU_TOT_CONTRIB_DA_INTER) END AS EU_TOT_CONTRIB_DA_INTER,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.EU_SPESE_RICORRENTI_TOT) * -1 ELSE (C.EU_SPESE_RICORRENTI_TOT) END AS EU_SPESE_RICORRENTI_TOT
FROM prat_unpivot PR
LEFT JOIN {{ ref('consumo') }} C ON C.TP_PROCEDURA = PR.TP_PROCEDURA AND C.CD_PRATICA = PR.CD_PRATICA
--TODO LEFT JOIN eu_pv P ON P.CD_PROCEDURA = PR.CD_PROCEDURA AND P.CD_PRATICA = PR.CD_PRATICA
--TODO LEFT JOIN eu_ra R ON R.CD_PROCEDURA = PR.CD_PROCEDURA AND R.CD_PRATICA = PR.CD_PRATICA
LEFT JOIN sa_agg SA
    ON SA.CD_PRATICA = PR.CD_PRATICA
    AND SA.TP_PROCEDURA = PR.TP_PROCEDURA
WHERE PR.DT_MOVIMENTO IS NOT NULL
    AND PR.TP_PROCEDURA = 'CO'
    AND (PR.CD_PRODOTTO NOT IN ('02', '09', '16', '32') OR PR.CD_PRODOTTO IS NULL)

UNION ALL

-- ========== Procedura: Passaggi di stato Carte ==========
SELECT
    PR.TP_PROCEDURA AS TP_PROCEDURA,
    PR.CD_PRATICA AS CD_PRATICA,
    0 AS CD_EMETTITORE_UTILIZZO,
    0 AS CD_PROTOCOLLO_UTILIZZO,
    0 AS CD_RIGA_UTILIZZO,
    PR.DT_MOVIMENTO AS DT_MOVIMENTO,
    PR.TP_MOVIMENTO AS TP_MOVIMENTO,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN 'S' ELSE 'N' END AS FL_STORNO,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_CARICAMENTO' THEN 1 ELSE 0 END AS NM_PRATICA_CARICATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_ESITO' THEN 1 ELSE 0 END AS NM_PRATICA_ESITATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_RESPINTA' THEN 1 ELSE 0 END AS NM_PRATICA_RESPINTA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_RITIRATA' THEN 1 ELSE 0 END AS NM_PRATICA_RITIRATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_DECORRENZA' THEN 1 WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN -1 ELSE 0 END AS NM_PRATICA_DECORSA,
    NULL AS EU_FINANZIATO,
    NULL AS EMFN,
    NULL AS NM_IRR_NUM,
    NULL AS NM_IRR_DEN,
    NULL AS NM_DURATA_FINANZ_NUM,
    NULL AS NM_DURATA_FINANZ_DEN,
    NULL AS NM_TAEG1_NUM,
    NULL AS NM_TAEG1_DEN,
    NULL AS NM_TAN1_NUM,
    NULL AS NM_TAN1_DEN,
    NULL AS NM_TEG1_NUM,
    NULL AS NM_TEG1_DEN,
    NULL AS NM_TAEG2_NUM,
    NULL AS NM_TAEG2_DEN,
    NULL AS NM_TAN2_NUM,
    NULL AS NM_TAN2_DEN,
    NULL AS NM_TEG2_NUM,
    NULL AS NM_TEG2_DEN,
    NULL AS EU_FRESH_CASH,
    NULL AS EU_EROGATO,
    NULL AS EU_PREMIO_ASSICURAZIONE_LORDO,
    --TODO CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (P.EU_PROVVIGIONI) * -1 ELSE (P.EU_PROVVIGIONI) END AS EU_PROVVIGIONE,
    CAST(NULL AS NUMBER(13,2)) AS EU_PROVVIGIONE,
    NULL AS EU_SPESE_TOT_IST,
    NULL AS EU_TOT_CONTRIB_DA_INTER,
    NULL AS EU_SPESE_RICORRENTI_TOT
FROM prat_unpivot PR
--TODO LEFT JOIN eu_pv P ON P.CD_PROCEDURA = PR.CD_PROCEDURA AND P.CD_PRATICA = PR.CD_PRATICA
--TODO LEFT JOIN eu_ra R ON R.CD_PROCEDURA = PR.CD_PROCEDURA AND R.CD_PRATICA = PR.CD_PRATICA
WHERE DT_MOVIMENTO IS NOT NULL
    AND PR.TP_PROCEDURA = 'CA' 
    AND (PR.CD_EMETTITORE NOT IN (600, 300, 301) OR PR.CD_EMETTITORE IS NULL)    -- WARN: misure NUM/DEN non specificate per Carte nel data model -> NULL

UNION ALL

-- ========== Procedura: Passaggi di stato CQS ==========
SELECT
    PR.TP_PROCEDURA AS TP_PROCEDURA,
    PR.CD_PRATICA AS CD_PRATICA,
    0 AS CD_EMETTITORE_UTILIZZO,
    0 AS CD_PROTOCOLLO_UTILIZZO,
    0 AS CD_RIGA_UTILIZZO,
    PR.DT_MOVIMENTO AS DT_MOVIMENTO,
    PR.TP_MOVIMENTO AS TP_MOVIMENTO,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN 'S' ELSE 'N' END AS FL_STORNO,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_CARICAMENTO' THEN 1 ELSE 0 END AS NM_PRATICA_CARICATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_ESITO' THEN 1 ELSE 0 END AS NM_PRATICA_ESITATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_RESPINTA' THEN 1 ELSE 0 END AS NM_PRATICA_RESPINTA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_RITIRATA' THEN 1 ELSE 0 END AS NM_PRATICA_RITIRATA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_DECORRENZA' THEN 1 WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN -1 ELSE 0 END AS NM_PRATICA_DECORSA,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN PR.EU_FINANZIATO * -1 ELSE PR.EU_FINANZIATO END AS EU_FINANZIATO,
    NULL AS EMFN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_IRR_EFFETTIVO * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_IRR_EFFETTIVO * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_IRR_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_IRR_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_DURATA_FINANZ_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO)) * -1 ELSE ((PR.EU_FINANZIATO)) END AS NM_DURATA_FINANZ_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TAEG * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TAEG * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_TAEG1_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_TAEG1_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TAN * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TAN * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_TAN1_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_TAN1_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.NM_TEG * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE (C.NM_TEG * (PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_TEG1_NUM,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) * -1 ELSE ((PR.EU_FINANZIATO) * C.NM_DURATA_FINANZ) END AS NM_TEG1_DEN,
    NULL AS NM_TAEG2_NUM,
    NULL AS NM_TAEG2_DEN,
    NULL AS NM_TAN2_NUM,
    NULL AS NM_TAN2_DEN,
    NULL AS NM_TEG2_NUM,
    NULL AS NM_TEG2_DEN,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.EU_FRESH_CASH) * -1 ELSE (C.EU_FRESH_CASH) END AS EU_FRESH_CASH,
    CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (C.EU_EROGATO) * -1 ELSE (C.EU_EROGATO) END AS EU_EROGATO,
    NULL AS EU_PREMIO_ASSICURAZIONE_LORDO,
    --TODO CASE WHEN PR.TP_MOVIMENTO = 'DT_STORNATA' THEN (P.EU_PROVVIGIONI) * -1 ELSE (P.EU_PROVVIGIONI) END AS EU_PROVVIGIONE,
    CAST(NULL AS NUMBER(13,2)) AS EU_PROVVIGIONE,
    NULL AS EU_SPESE_TOT_IST,
    NULL AS EU_TOT_CONTRIB_DA_INTER,
    NULL AS EU_SPESE_RICORRENTI_TOT
FROM prat_unpivot PR
LEFT JOIN {{ ref('cqs') }} C ON C.TP_PROCEDURA = PR.TP_PROCEDURA AND C.CD_PRATICA = PR.CD_PRATICA
--TODO LEFT JOIN eu_pv P ON P.CD_PROCEDURA = PR.CD_PROCEDURA AND P.CD_PRATICA = PR.CD_PRATICA
--TODO LEFT JOIN eu_ra R ON R.CD_PROCEDURA = PR.CD_PROCEDURA AND R.CD_PRATICA = PR.CD_PRATICA
WHERE DT_MOVIMENTO IS NOT NULL
    AND PR.TP_PROCEDURA = 'CQ'

UNION ALL

-- ========== Procedura: Pratiche FINSTOCK ==========
SELECT
    'FS' AS TP_PROCEDURA,
    CL.CD_PRATICA AS CD_PRATICA,
    0 AS CD_EMETTITORE_UTILIZZO,
    0 AS CD_PROTOCOLLO_UTILIZZO,
    0 AS CD_RIGA_UTILIZZO,
    CL.DT_INIZIO_LIN_CREDIT  AS DT_MOVIMENTO,
    'DT_DECORRENZA' AS TP_MOVIMENTO,
    'N' AS FL_STORNO,
    0 AS NM_PRATICA_CARICATA,
    0 AS NM_PRATICA_ESITATA,
    0 AS NM_PRATICA_RESPINTA,
    0 AS NM_PRATICA_RITIRATA,
    1 AS NM_PRATICA_DECORSA,
    NULL AS EU_FINANZIATO,
    NULL AS EMFN,
    NULL AS NM_IRR_NUM,
    NULL AS NM_IRR_DEN,
    NULL AS NM_DURATA_FINANZ_NUM,
    NULL AS NM_DURATA_FINANZ_DEN,
    NULL AS NM_TAEG1_NUM,
    NULL AS NM_TAEG1_DEN,
    NULL AS NM_TAN1_NUM,
    NULL AS NM_TAN1_DEN,
    NULL AS NM_TEG1_NUM,
    NULL AS NM_TEG1_DEN,
    NULL AS NM_TAEG2_NUM,
    NULL AS NM_TAEG2_DEN,
    NULL AS NM_TAN2_NUM,
    NULL AS NM_TAN2_DEN,
    NULL AS NM_TEG2_NUM,
    NULL AS NM_TEG2_DEN,
    NULL AS EU_FRESH_CASH,
    NULL AS EU_EROGATO,
    NULL AS EU_PREMIO_ASSICURAZIONE_LORDO,
    CAST(NULL AS NUMBER(13,2)) AS EU_PROVVIGIONE,
    NULL AS EU_SPESE_TOT_IST,
    NULL AS EU_TOT_CONTRIB_DA_INTER,
    NULL AS EU_SPESE_RICORRENTI_TOT
FROM {{ ref('creditline') }} AS CL
WHERE TP_LINEA_DI_CREDITO = 'CREDIT_LINE'
--FROM {{ env_var('DBT_DATABASE') }}.L2_SWORD.creditline AS CL

UNION ALL

-- ========== Procedura: Utilizzi Carte ==========
SELECT
    a.TP_PROCEDURA AS TP_PROCEDURA,
    a.CD_PRATICA AS CD_PRATICA,
    a.CD_EMETTITORE AS CD_EMETTITORE_UTILIZZO,
    a.CD_PROTOCOLLO AS CD_PROTOCOLLO_UTILIZZO,
    a.CD_RIGA AS CD_RIGA_UTILIZZO,
    a.DT_DECORRENZA AS DT_MOVIMENTO,
    'DT_UTILIZZO' AS TP_MOVIMENTO,
    -- WARN: RT modello indicava 0; usato il flag FL_STORNO
    a.FL_STORNO AS FL_STORNO,
    0 AS NM_PRATICA_CARICATA,
    0 AS NM_PRATICA_ESITATA,
    0 AS NM_PRATICA_RESPINTA,
    0 AS NM_PRATICA_RITIRATA,
    0 AS NM_PRATICA_DECORSA,
     CASE WHEN a.FL_STORNO = 'S' THEN -1 * a.EU_FINANZIATO ELSE a.EU_FINANZIATO END AS EU_FINANZIATO,
    NULL AS EMFN,
    CASE WHEN a.FL_STORNO = 'S' THEN -1 * (COALESCE(a.NM_IRR, b.NM_TAN) * a.EU_FINANZIATO * COALESCE(a.NM_DURATA_FINANZ, c.NM_VALORE_PARAMETRO)) ELSE (COALESCE(a.NM_IRR, b.NM_TAN) * a.EU_FINANZIATO * COALESCE(a.NM_DURATA_FINANZ, c.NM_VALORE_PARAMETRO)) END AS NM_IRR_NUM,
    CASE WHEN a.FL_STORNO = 'S' THEN -1 * (a.EU_FINANZIATO * COALESCE(a.NM_DURATA_FINANZ, c.NM_VALORE_PARAMETRO)) ELSE (a.EU_FINANZIATO * COALESCE(a.NM_DURATA_FINANZ, c.NM_VALORE_PARAMETRO)) END AS NM_IRR_DEN,
    CASE WHEN a.FL_STORNO = 'S' THEN -1 * (a.EU_FINANZIATO * COALESCE(a.NM_DURATA_FINANZ, c.NM_VALORE_PARAMETRO)) ELSE (a.EU_FINANZIATO * COALESCE(a.NM_DURATA_FINANZ, c.NM_VALORE_PARAMETRO)) END AS NM_DURATA_FINANZ_NUM,
    CASE WHEN a.FL_STORNO = 'S' THEN -1 * (a.EU_FINANZIATO) ELSE (a.EU_FINANZIATO) END AS NM_DURATA_FINANZ_DEN,
    NULL AS NM_TAEG1_NUM,
    NULL AS NM_TAEG1_DEN,
    NULL AS NM_TAN1_NUM,
    NULL AS NM_TAN1_DEN,
    NULL AS NM_TEG1_NUM,
    NULL AS NM_TEG1_DEN,
    NULL AS NM_TAEG2_NUM,
    NULL AS NM_TAEG2_DEN,
    NULL AS NM_TAN2_NUM,
    NULL AS NM_TAN2_DEN,
    NULL AS NM_TEG2_NUM,
    NULL AS NM_TEG2_DEN,
    NULL AS EU_FRESH_CASH,
    NULL AS EU_EROGATO,
    NULL AS EU_PREMIO_ASSICURAZIONE_LORDO,
    CAST(NULL AS NUMBER(13,2)) AS EU_PROVVIGIONE,
    NULL AS EU_SPESE_TOT_IST,
    NULL AS EU_TOT_CONTRIB_DA_INTER,
    NULL AS EU_SPESE_RICORRENTI_TOT
FROM {{ ref('carte_utilizzi') }} a
LEFT JOIN {{ ref('carta') }} b ON a.TP_PROCEDURA = b.TP_PROCEDURA AND a.CD_PRATICA = b.CD_PRATICA
LEFT JOIN {{ source('L3_MONITORING_PRODUZIONE','dm_config_running_o') }} c
    ON c.DT_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND c.CD_CHIAVE_PARAMETRO = 'DFU'
WHERE (A.CD_EMETTITORE NOT IN (300, 301, 700) OR A.CD_EMETTITORE IS NULL)
	AND A.FL_STORNATO_INTRADAY = 'N'
    AND A.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')

UNION ALL

-- ========== Procedura: Utilizzi FINSTOCK ==========
SELECT
    'FS' AS TP_PROCEDURA,
    LO.CD_PRATICA AS CD_PRATICA,
    -- WARN: non specificato nel modello (PK)
    0 AS CD_EMETTITORE_UTILIZZO,
    LO.CD_CERTIFICATO AS CD_PROTOCOLLO_UTILIZZO,
    -- WARN: non specificato nel modello (PK)
    0 AS CD_RIGA_UTILIZZO,
    LO.DT_INIZIO_CALC_INTSSI AS DT_MOVIMENTO,
    'DT_LOAN' AS TP_MOVIMENTO,
    'N' AS FL_STORNO,
    0 AS NM_PRATICA_CARICATA,
    0 AS NM_PRATICA_ESITATA,
    0 AS NM_PRATICA_RESPINTA,
    0 AS NM_PRATICA_RITIRATA,
    0 AS NM_PRATICA_DECORSA,
    NULL AS EU_FINANZIATO,
    NULL AS EMFN,
    NULL AS NM_IRR_NUM,
    NULL AS NM_IRR_DEN,
    NULL AS NM_DURATA_FINANZ_NUM,
    NULL AS NM_DURATA_FINANZ_DEN,
    NULL AS NM_TAEG1_NUM,
    NULL AS NM_TAEG1_DEN,
    NULL AS NM_TAN1_NUM,
    NULL AS NM_TAN1_DEN,
    NULL AS NM_TEG1_NUM,
    NULL AS NM_TEG1_DEN,
    NULL AS NM_TAEG2_NUM,
    NULL AS NM_TAEG2_DEN,
    NULL AS NM_TAN2_NUM,
    NULL AS NM_TAN2_DEN,
    NULL AS NM_TEG2_NUM,
    NULL AS NM_TEG2_DEN,
    NULL AS EU_FRESH_CASH,
    NULL AS EU_EROGATO,
    NULL AS EU_PREMIO_ASSICURAZIONE_LORDO,
    CAST(NULL AS NUMBER(13,2)) AS EU_PROVVIGIONE,
    NULL AS EU_SPESE_TOT_IST,
    NULL AS EU_TOT_CONTRIB_DA_INTER,
    NULL AS EU_SPESE_RICORRENTI_TOT
FROM {{ ref('loan') }} LO
WHERE CD_STATO_CERTIF = 'LIVE'
-- FROM {{ env_var('DBT_DATABASE') }}.L2_SWORD.loan AS LO
