select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(LOGEF_NUM_EFFETTO AS NUMBER(12,0)) AS logef_num_effetto,
  TRY_CAST(IFF(RTRIM(LOGEF_PROVENIENZA) = '', ' ', RTRIM(LOGEF_PROVENIENZA)) AS VARCHAR(2)) AS logef_provenienza,
  TRY_CAST(LOGEF_PRATICA AS NUMBER(12,0)) AS logef_pratica,
  TRY_CAST(IFF(RTRIM(LOGEF_PGM) = '', ' ', RTRIM(LOGEF_PGM)) AS VARCHAR(10)) AS logef_pgm,
  TRY_CAST(IFF(RTRIM(LOGEF_UTENTE) = '', ' ', RTRIM(LOGEF_UTENTE)) AS VARCHAR(10)) AS logef_utente,
  TRY_CAST(LOGEF_DATA AS NUMBER(8,0)) AS logef_data,
  TRY_CAST(LOGEF_ORA AS NUMBER(8,0)) AS logef_ora,
  TRY_CAST(IFF(RTRIM(LOGEF_STATO) = '', ' ', RTRIM(LOGEF_STATO)) AS VARCHAR(1)) AS logef_stato,
  TRY_CAST(LOGEF_GESTORE AS NUMBER(9,0)) AS logef_gestore,
  TRY_CAST(IFF(RTRIM(LOGEF_DISLOCAZIONE) = '', ' ', RTRIM(LOGEF_DISLOCAZIONE)) AS VARCHAR(1)) AS logef_dislocazione,
  TRY_CAST(LOGEF_DATA_PRE AS NUMBER(8,0)) AS logef_data_pre,
  TRY_CAST(LOGEF_DATA_INC AS NUMBER(8,0)) AS logef_data_inc,
  TRY_CAST(LOGEF_DATA_RIT AS NUMBER(8,0)) AS logef_data_rit,
  TRY_CAST(LOGEF_DATA_RIE AS NUMBER(8,0)) AS logef_data_rie,
  TRY_CAST(IFF(RTRIM(LOGEF_REC_FILE) = '', ' ', RTRIM(LOGEF_REC_FILE)) AS VARCHAR(500)) AS logef_rec_file,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','ga2logef') }}
