SELECT
    CA.AC_CODICE AS CD_CONTROPARTE,
    CA.AC_TIPO_ANAGRAFICA AS TP_CONTROPARTE,
    CA.AC_FORMA_GIURIDICA AS CD_FORMA_GIURIDICA,
    CA.AC_CODICE_FISCALE AS CD_FISCALE,
    CA.AC_CODICE_FISC_CALC AS FL_CF_CALCOLATO,
    CA.AC_CODICE_FISC_FORZ AS FL_CF_FORZATO,
    CA.AC_UTENTE_FORZATURA AS CD_UTENTE_FORZATURA_CF,
    CA.AC_PARTITA_IVA AS CD_PARTITA_IVA,
    CA.AC_NOME AS DS_NOME,
    CA.AC_SECONDO_NOME AS DS_SECONDO_NOME,
    CA.AC_COGNOME AS DS_COGNOME,
    CA.AC_COGNOME_MADRE AS DS_COGNOME_MADRE,
    CA.AC_RIFERIMENTO AS CD_RIFERIMENTO_ALTRA_ANAGRAFICA,
    CA.AC_MATRICOLA AS CD_MATRICOLA,
    CA.AC_RAG_SOCIALE_1 AS DS_RAGIONE_SOCIALE,
    CA.AC_RAG_SOCIALE_2 AS DS_RAGIONE_SOCIALE_2,
    CA.AC_CITTADINANZA AS CD_CITTADINANZA,
    CI1.CRECI_DESCRIZIONE AS DS_CITTADINANZA,
    CA.AC_NASCITA_LUOGO AS DS_CITTA_NASCITA,
    CA.AC_NASCITA_NAZIONE AS CD_NAZIONE_NASCITA,
    NA1.ANATNA_DESCRIZIONE AS DS_NAZIONE_NASCITA,
    CA.AC_NASCITA_PROV AS CD_PROVINCIA_NASCITA,
    PR1.ANATPR_DESCRIZIONE AS DS_PROVINCIA_NASCITA,
    CA.AC_NASCITA_LUOGO AS DS_COMUNE_NASCITA,
    CA.AC_NASCITA_CAB_LOC AS CD_CAB_COMUNE_NASCITA,
    {{ custom_to_date('CA.AC_NASCITA_DATA') }} AS DT_NASCITA,
    CA.AC_SESSO AS CD_SESSO,
    {{ custom_to_date('CA.AC_DATA_CESSAZIONE') }} AS DT_DECESSO,
    CA.AC_ABI AS CD_ABI,
    CA.AC_COD_IDEN AS CD_IDENTIFICATIVO,
    CA.AC_CODICE_NDG AS CD_NDG,
    CA.AC_CODICE_NDG2 AS CD_NDG2,
    CA.AC_CODICE_NDG3 AS CD_NDG3,
    CA.AC_CODICE_NDG_CRF AS CD_NDG_CRF,
    CA.AC_INPS_MATRICOLA AS CD_INPS_MATRICOLA,
    CA.AC_INAIL_PAT AS CD_INAIL_PAT,
    CA.AC_IPA AS CD_IPA,
    CA.AC_FILIALE AS CD_FILIALE,
    CA.AC_FILIALE_STORICA AS CD_FILIALE_STORICA,
    CA.AC_ESENZIONE_IVA AS CD_ESENZIONE_IVA,
    CA.AC_TIPO_ATTIVITA AS CD_SETTORE_ATTIVITA,
    AT1.ANATAT_DESCRIZIONE AS DS_ATECO,
    CA.AC_ATECO AS CD_ATECO,
    CA.AC_RAMOGRUPPO AS CD_RAE,
    RA1.ANATRA_DESCRIZIONE AS DS_RAE,
    CA.AC_SOTTOGRUPPO AS CD_SAE,
    SA1.ANATSA_DESCRIZIONE AS DS_SAE,
    CA.AC_TAE AS CD_TAE,
    CA.AC_NUM_CAMCOMMERCIO AS CD_CCIAA,
    CA.AC_TIPO_CAMCOMMERCIO AS TP_CCIAA,
    CA.AC_PROV_CAMCOMMERCIO AS CD_PROVINCIA_CCIAA,
    PR2.ANATPR_DESCRIZIONE AS DS_PROVINCIA_CCIAA,
    {{ custom_to_date('CA.AC_DATA_CAMCOMMERCIO') }} AS DT_REGISTRAZIONE_CCIAA,
    CA.AC_CTR_CAMCOMMERCIO AS FL_CONTROLLO_CCIAA,
    CA.AC_FALLIBILE AS FL_FALLIBILE,
    {{ custom_to_date('CA.AC_DATA_FALLIMENTO') }} AS DT_FALLIMENTO,
    CA.AC_PROC_CONCORSUALI AS TP_PROC_CONCORSUALI,
    CA.AC_PROC_LEGALI AS TP_PROC_LEGALI,
    CA.AC_IDE_NUM_DOCUMENTO AS CD_DOCUMENTO,
    CA.AC_IDE_TIPO_DOCUMENTO AS TP_DOCUMENTO,
    CA.AC_IDE_UFFICIO_RILASCIO AS TP_EMITTENTE,
    {{ custom_to_date('CA.AC_IDE_DATA_RILASCIO') }} AS DT_RILASCIO_DOC,
    {{ custom_to_date('CA.AC_IDE_DATA_SCADENZA') }} AS DT_FINE_VALIDITA_DOC,
    CA.AC_IDE_LUOGO_RILASCIO AS DS_COMUNE_RILASCIO_DOC,
    CA.AC_IDE_PROV_RILASCIO AS CD_PROVINCIA_RILASCIO_DOC,
    PR3.ANATPR_DESCRIZIONE AS DS_PROVINCIA_RILASCIO_DOC,
    CA.AC_IDE_NAZIONE_RILASCIO AS CD_NAZIONE_RILASCIO_DOC,
    NA2.ANATNA_DESCRIZIONE AS DS_NAZIONE_RILASCIO_DOC,
    CA.AC_IDE_NUM2_DOCUMENTO AS CD_DOCUMENTO_2,
    CA.AC_TSA_NUM AS NM_TESSERA_SANITARIA,
    {{ custom_to_date('CA.AC_TSA_DATA_SCADENZA') }}
        AS DT_SCADENZA_TESSERA_SANITARIA,
    CA.AC_IDE_NOTE AS DS_NOTE_DOCUMENTO,
    CA.AC_IDE_UNIV_FORZ AS FL_UNIVOCITA_DOCUMENTO,
    CA.AC_IDE_SOSP_FORZ AS FL_SOSPETTO_FORZATO_DOCUMENTO,
    CA.AC_PRESSO AS DS_PRESSO,
    CA.AC_FRAZIONE AS DS_FRAZIONE,
    CA.AC_INDIRIZZO_1 AS DS_INDIRIZZO_1,
    {{ custom_to_date('CA.AC_INDIR_ATT') }} AS DT_INDIRIZZO_RESIDENZA_DAL,
    CA.AC_INDIRIZZO_2 AS DS_INDIRIZZO_2,
    CA.AC_IND_NORM AS FL_INDIRIZZO_NORMALIZZATO,
    CA.AC_IND_FORZ AS FL_INDIRIZZO_FORZATO,
    CA.AC_CAP AS CD_CAP,
    PR4.ANATPR_REGIONE AS CD_REGIONE_RESIDENZA,
    RE1.ANATRE_DESCRIZIONE AS DS_REGIONE_RESIDENZA,
    CA.AC_PAESE_ESTERO AS CD_NAZIONE_RESIDENZA,
    NA3.ANATNA_DESCRIZIONE AS DS_NAZIONE_RESIDENZA,
    CA.AC_LOCALITA AS DS_COMUNE_RESIDENZA,
    CA.AC_PROVINCIA AS CD_PROVINCIA_RESIDENZA,
    PR4.ANATPR_DESCRIZIONE AS DS_PROVINCIA_RESIDENZA,
    CA.AC_COD_CAB_COMUNE AS CD_CAB_RESIDENZA,
    CA.AC_TIPO_SEDE AS CD_TIPO_SEDE,
    CA.AC_SEDE_INDIRIZZO_1 AS DS_SEDE_INDIRIZZO_1,
    CA.AC_SEDE_INDIRIZZO_2 AS DS_SEDE_INDIRIZZO_2,
    CA.AC_SEDE_IND_NORM AS FL_SEDE_INDIRIZZO_NORMALIZZATO,
    CA.AC_SEDE_IND_FORZ AS FL_SEDE_INDIRIZZO_FORZATO,
    CA.AC_SEDE_PRESSO AS DS_SEDE_PRESSO,
    CA.AC_SEDE_FRAZIONE AS DS_SEDE_FRAZIONE,
    RE2.ANATRE_DESCRIZIONE AS DS_SEDE_REGIONE,
    CA.AC_SEDE_PROVINCIA AS CD_SEDE_PROVINCIA,
    PR5.ANATPR_DESCRIZIONE AS DS_SEDE_PROVINCIA,
    CA.AC_SEDE_CAP AS CD_SEDE_CAP,
    CA.AC_SEDE_LOCALITA AS DS_SEDE_COMUNE,
    CA.AC_SEDE_CAB_LOC AS CD_SEDE_CAB_COMUNE,
    CA.AC_SEDE_NAZIONE AS CD_SEDE_NAZIONE,
    NA4.ANATNA_DESCRIZIONE AS DS_SEDE_NAZIONE,
    CA.AC_PSG_TIPO AS TP_PERMESSO_SOGGIORNO,
    {{ custom_to_date('CA.AC_PSG_SOGGIORNO_DAL') }}
        AS DT_INIZIO_PERMESSO_SOGGIORNO,
    {{ custom_to_date('CA.AC_PSG_DATA_SCADENZA') }}
        AS DT_SCADENZA_PERMESSO_SOGGIORNO,
    CA.AC_PSG_SCAD_FORZ AS FL_SCADENZA_FORZATA_PERMESSO,
    CA.AC_PSG_VAL_FORZ AS FL_VALIDITA_FORZATA_PERMESSO,
    CA.AC_TELEFONO_CEL AS NM_CELLULARE,
    CA.AC_TELEFONO AS NM_TELEFONO,
    CA.AC_TELEFONO_2 AS NM_TELEFONO_UFFICIO,
    CA.AC_TELEFONO_SEDE AS NM_TELEFONO_SEDE,
    CA.AC_FAX AS DS_FAX,
    CA.AC_EMAIL AS DS_EMAIL,
    CA.AC_EMAIL_PEC AS DS_EMAIL_PEC,
    CA.AC_POSIZIONE AS CD_OCCUPAZIONE,
    CA.AC_OCC_OCCUPAZIONE AS CD_OCCUPAZIONE_2,
    {{ custom_to_date('CA.AC_DATA_POSIZIONE') }} AS DT_OCCUPAZIONE,
    PO1.ANATPO_DESCRIZIONE AS DS_OCCUPAZIONE,
    CA.AC_OCC_TIPO_ATTIVITA AS CD_TIPO_ATTIVITA_OCCUPAZIONE,
    CA.AC_OCC_SETTORE AS CD_SETTORE_OCCUPAZIONE,
    {{ custom_to_date('CA.AC_DL_OCCUPAZIONE_DAL') }}
        AS DT_INIZIO_OCCUPAZIONE_CLI,
    {{ custom_to_date('CA.AC_DL_OCCUPAZIONE_AL') }} AS DT_FINE_OCCUPAZIONE_CLI,
    CA.AC_ST_FLAG_ALBO_ARTIG AS FL_ISCRITTO_ALBO_ARTIGIANI,
    CA.AC_ST_NUM_DIPENDENTI AS NM_DIPENDENTI,
    CA.AC_CAPITALE_SOCIALE AS NM_CAPITALE_SOCIALE,
    CA.AC_PARTEC_ENTE_PUB AS FL_PARTECIPATA_ENTE_PUBBLICO,
    CA.AC_DL_DENOMINAZIONE AS DS_DATORE_LAVORO,
    CA.AC_DL_CODICE_FISCALE AS CD_FISCALE_DATORE_LAVORO,
    CA.AC_DL_PARTITA_IVA AS CD_PARTITA_IVA_DATORE_LAVORO,
    CA.AC_DL_FORMA_GIURIDICA AS CD_FORMA_GIURIDICA_DATORE_LAVORO,
    CA.AC_DL_COD_IDEN AS CD_IDEN_DATORE_LAVORO,
    CA.AC_DL_INDIRIZZO AS DS_INDIRIZZO_DATORE_LAVORO,
    CA.AC_DL_PRESSO AS DS_PRESSO_DATORE_LAVORO,
    CA.AC_DL_LOCALITA AS DS_COMUNE_DATORE_LAVORO,
    CA.AC_DL_CAP AS CD_CAP_INDIRIZZO_DATORE_LAVORO,
    CA.AC_DL_FRAZIONE AS DS_FRAZIONE_DATORE_LAVORO,
    CA.AC_DL_PROVINCIA AS CD_PROVINCIA_DATORE_LAVORO,
    PR6.ANATPR_DESCRIZIONE AS DS_PROVINCIA_DATORE_LAVORO,
    CA.AC_DL_TELEFONO AS NM_TELEFONO_DATORE_LAVORO,
    CA.AC_DL_IND_NORM AS FL_INDIRIZZO_NORMALIZZATO_DATORE_LAVORO,
    CA.AC_DL_IND_FORZ AS FL_INDIRIZZO_FORZATO_DATORE_LAVORO,
    CA.AC_DL_FAX AS DS_FAX_DATORE_LAVORO,
    CA.AC_TIPO_CONTROPARTE_19 AS FL_DIPENDENTE,
    CA.AC_TIPO_CONTROPARTE_01 AS FL_CLIENTE,
    CA.AC_TIPO_CONTROPARTE_02 AS FL_AGENTE,
    CA.AC_TIPO_CONTROPARTE_03 AS FL_TIPO_ALTRO,
    CA.AC_TIPO_CONTROPARTE_04 AS FL_GARANTE,
    CA.AC_TIPO_CONTROPARTE_06 AS FL_FORNITORE,
    CA.AC_TIPO_CONTROPARTE_11 AS FL_COOBLIGATO,
    CA.AC_TIPO_CONTROPARTE_12 AS FL_CONVENZIONATO,
    CA.AC_TIPO_CONTROPARTE_13 AS FL_DITTA,
    CA.AC_TIPO_CONTROPARTE_14 AS FL_FIRMATARIO,
    CA.AC_TIPO_CONTROPARTE_16 AS FL_DELEGATO,
    CA.AC_TIPO_CONTROPARTE_17 AS FL_FONDO_PENSIONE,
    CA.AC_TIPO_CONTROPARTE_18 AS FL_FINANZIARIA,
    CA.AC_TIPO_CONTROPARTE_21 AS FL_DATORE_LAVORO,
    CA.AC_INTERM_ABILITATO AS TP_INTERMEDIARIO_ABILITATO,
    CA.AC_ANA_DI_GRUPPO AS FL_ANA_DI_GRUPPO,
    CA.AC_CLIENTE_BANCA AS FL_CLIENTE_BANCA,
    CA.AC_RILEV_QUALITA AS TP_CONSENSO_SRQ,
    CA.AC_OFF_COMM_INTERNE AS TP_CONSENSO_OCI,
    CA.AC_OFF_COMM_INT_AUT AS TP_CONSENSO_OIA,
    CA.AC_OFF_COMM_ESTERNE AS TP_CONSENSO_OCE,
    CA.AC_OFF_COMM_EST_AUT AS TP_CONSENSO_OEA,
    CA.AC_SERVIZI_ALTRI AS TP_CONSENSO_OSA,
    CA.AC_DATI_SENSIBILI AS TP_CONSENSO_DSU,
    CA.AC_CONS_INFO_SIC AS TP_CONSENSO_SIC,
    CA.AC_ISTRUTT_PRATICHE AS TP_CONSENSO_IPR,
    {{ custom_to_date('CA.AC_DT_PRIVACY_ISTRUTT') }} AS DT_CONSENSO_IPR,
    {{ custom_to_date('CA.AC_DT_RILEV_QUALITA') }} AS DT_CONSENSO_SRQ,
    {{ custom_to_date('CA.AC_DT_PRIVACY_OFFERTE') }} AS DT_CONSENSO_OCI,
    {{ custom_to_date('CA.AC_DT_OFF_COMM_INT_AUT') }} AS DT_CONSENSO_OIA,
    {{ custom_to_date('CA.AC_DT_OFF_COMM_ESTERNE') }} AS DT_CONSENSO_OCE,
    {{ custom_to_date('CA.AC_DT_OFF_COMM_EST_AUT') }} AS DT_CONSENSO_OEA,
    {{ custom_to_date('CA.AC_DT_SERVIZI_ALTRI') }} AS DT_CONSENSO_OSA,
    {{ custom_to_date('CA.AC_DT_PRIVACY_SENSIBILI') }} AS DT_CONSENSO_DSU,
    {{ custom_to_date('CA.AC_DATA_CONS_INFO_SIC') }} AS DT_CONSENSO_CIS,
    CA.AC_NOTE_CONS_INFO_SIC AS DS_NOTE_SIC,
    CA.AC_PRIVACY_RICH_CANC AS TP_CANCELLAZIONE_DATI_PRIVACY,
    {{ custom_to_decimal('CA.AC_RED_REDDITO', 13, 2) }} AS EU_REDDITO_ANNUO,
    CA.AC_RED_NUM_MENSILITA AS NM_MENSILITA_REDDITO,
    {{ custom_to_decimal('CA.AC_RED_ALTRI_REDDITI', 13, 2) }}
        AS EU_ALTRI_REDDITI,
    CA.AC_RED_TIPO AS TP_REDDITO,
    {{ custom_to_decimal('CA.AC_RED_REDDITO_FAM', 13, 2) }}
        AS EU_REDDITO_FAMILIARE,
    {{ custom_to_decimal('CA.AC_RED_REDDITO_FAM_C', 13, 2) }}
        AS EU_REDDITO_FAMILIARE_CONIUGE,
    CA.AC_IN_CODICE_CR AS CD_CENTRALE_RISCHI,
    CA.AC_IN_CODICE_SIA AS CD_SIA,
    CA.AC_LEG_CODICE AS CD_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_NOME AS DS_NOME_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_INDIRIZZO AS DS_INDIRIZZO_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_PRESSO AS DS_PRESSO_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_CAP AS CD_CAP_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_FRAZIONE AS DS_FRAZIONE_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_LOCALITA AS DS_COMUNE_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_PROVINCIA AS CD_PROVINCIA_LEGALE_RAPPRESENTANTE,
    PR7.ANATPR_DESCRIZIONE AS DS_PROVINCIA_LEGALE_RAPPRESENTANTE,
    {{ custom_to_date('CA.AC_LEG_DATA_NASCITA') }}
        AS DT_NASCITA_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_LUOGO_NASCITA AS DS_LOUGO_NASCITA_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_PROV_NASCITA AS CD_PROVINCIA_NASCITA_LEGALE_RAPPRESENTANTE,
    PR8.ANATPR_DESCRIZIONE AS DS_PROVINCIA_NASCITA_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_NAZ_NASCITA AS CD_NAZIONE_NASCITA_LEGALE_RAPPRESENTANTE,
    NA5.ANATNA_DESCRIZIONE AS DS_NAZIONE_NASCITA_LEGALE_RAPPRESENTANTE,
    CA.AC_LEG_CITTADINANZA AS CD_CITTADINANZA_LEGALE_RAPPRESENTANTE,
    CI2.CRECI_DESCRIZIONE AS DS_CITTADINANZA_LEGALE_RAPPRESENTANTE,
    CA.AC_CAUSALE_ANNULLO AS CD_CAUSALE_ANNULLO,
    {{ custom_to_date('CA.AC_DATA_ANNULLO') }} AS DT_ANNULLO,
    {{ custom_to_date('CA.AC_DATA_INSERIMENTO') }} AS DT_INSERIMENTO,
    CA.AC_UTENTE_INSERIMENTO AS CD_UTENTE_INSERIMENTO,
    {{ custom_to_date('CA.AC_DATA_VARIAZIONE') }} AS DT_VARIAZIONE,
    CA.AC_UTENTE_VARIAZIONE AS CD_UTENTE_VARIAZIONE,
    {{ custom_to_date('CA.AC_DATA_TRASMISSIONE') }} AS DT_TRASMISSIONE,
    CA.AC_RICER_1 AS DS_STRINGA_RICERCA,
    CA.AC_USER_1 AS CD_USER_1,
    CA.AC_USER_2 AS CD_USER_2,
    CA.AC_USER_3 AS CD_USER_3,
    CA.AC_NORMALIZZATO_RAG AS FL_NORM_DENOMINAZIONE,
    CA.AC_NORMALIZZATO_LOC AS FL_NORM_LOCALITA,
    CA.AC_NORMALIZZATO_IND AS FL_NORM_INDIRIZZO,
    CA.AC_NOTA_01 AS DS_NOTA_01,
    CA.AC_NOTA_02 AS DS_NOTA_02,
    CA.AC_FIL_CASELLA_POSTALE AS CD_FILIALE_CASELLA_POSTALE,
    CA.AC_NUM_CASELLA_POSTALE AS NM_CASELLA_POSTALE
FROM {{ ref('ccanagr') }} AS CA
LEFT JOIN {{ ref('cccretci') }} AS CI1
    ON
        CA.AC_CITTADINANZA = CI1.CRECI_CITTADINANZA
        AND CI1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND CI1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatna') }} AS NA1
    ON
        CA.AC_NASCITA_NAZIONE = NA1.ANATNA_NAZIONE
        AND NA1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND NA1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR1
    ON
        CA.AC_NASCITA_PROV = PR1.ANATPR_PROVINCIA
        AND PR1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatat') }} AS AT1
    ON
        CA.AC_ATECO = AT1.ANATAT_ATECO
        AND AT1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND AT1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatra') }} AS RA1
    ON
        CA.AC_RAMOGRUPPO = RA1.ANATRA_RAE
        AND RA1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND RA1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatsa') }} AS SA1
    ON
        CA.AC_SOTTOGRUPPO = SA1.ANATSA_SAE
        AND SA1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND SA1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR2
    ON
        CA.AC_PROV_CAMCOMMERCIO = PR2.ANATPR_PROVINCIA
        AND PR2.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR2.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR3
    ON
        CA.AC_IDE_PROV_RILASCIO = PR3.ANATPR_PROVINCIA
        AND PR3.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR3.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatna') }} AS NA2
    ON
        CA.AC_IDE_NAZIONE_RILASCIO = NA2.ANATNA_NAZIONE
        AND NA2.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND NA2.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR4
    ON
        CA.AC_PROVINCIA = PR4.ANATPR_PROVINCIA
        AND PR4.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR4.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatre') }} AS RE1
    ON
        PR4.ANATPR_REGIONE = RE1.ANATRE_REGIONE
        AND RE1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND RE1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatna') }} AS NA3
    ON
        CA.AC_PAESE_ESTERO = NA3.ANATNA_NAZIONE
        AND NA3.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND NA3.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR5
    ON
        CA.AC_SEDE_PROVINCIA = PR5.ANATPR_PROVINCIA
        AND PR5.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR5.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatre') }} AS RE2
    ON
        PR5.ANATPR_REGIONE = RE2.ANATRE_REGIONE
        AND RE2.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND RE2.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatna') }} AS NA4
    ON
        CA.AC_SEDE_NAZIONE = NA4.ANATNA_NAZIONE
        AND NA4.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND NA4.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpo') }} AS PO1
    ON
        CA.AC_POSIZIONE = PO1.ANATPO_POSIZ_CONTROP
        AND PO1.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PO1.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR6
    ON
        CA.AC_DL_PROVINCIA = PR6.ANATPR_PROVINCIA
        AND PR6.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR6.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR7
    ON
        CA.AC_LEG_PROVINCIA = PR7.ANATPR_PROVINCIA
        AND PR7.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR7.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatpr') }} AS PR8
    ON
        CA.AC_LEG_PROV_NASCITA = PR8.ANATPR_PROVINCIA
        AND PR8.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND PR8.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanatna') }} AS NA5
    ON
        CA.AC_LEG_NAZ_NASCITA = NA5.ANATNA_NAZIONE
        AND NA5.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND NA5.FL_DELETED = 'N'
LEFT JOIN {{ ref('cccretci') }} AS CI2
    ON
        CA.AC_LEG_CITTADINANZA = CI2.CRECI_CITTADINANZA
        AND CI2.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND CI2.FL_DELETED = 'N'
