WITH LEGAME_RAW AS (
    SELECT
        P.CD_CONTROPARTE,
        P.TP_CONTROPARTE,
        F.CD_CONTROPARTE AS CD_CONTROPARTE_DI,
        F.CD_PARTITA_IVA AS CD_PARTITA_IVA_DI,
        F.TS_INIZIO_VALIDITA,
        P.LASTMODIFIEDDATA,
        LAG(F.CD_CONTROPARTE) OVER (
            PARTITION BY P.CD_CONTROPARTE, F.CD_FISCALE
            ORDER BY F.TS_INIZIO_VALIDITA
        ) AS PREV_CD_CONTROPARTE_DI,
        LAG(F.CD_PARTITA_IVA) OVER (
            PARTITION BY P.CD_CONTROPARTE, F.CD_FISCALE
            ORDER BY F.TS_INIZIO_VALIDITA
        ) AS PREV_PARTITA_IVA_DI
    FROM {{ ref('variazioni_anagrafiche') }} AS P
    INNER JOIN {{ ref('variazioni_anagrafiche') }} AS F
        ON
            P.CD_FISCALE = F.CD_FISCALE
            AND F.TP_CONTROPARTE = 'F'
    WHERE
        P.TP_CONTROPARTE = 'P'
        AND (P.CD_PARTITA_IVA IS NULL OR P.CD_PARTITA_IVA = '')
        AND F.CD_PARTITA_IVA IS NOT NULL
        AND F.CD_PARTITA_IVA != ''
),

LEGAME_DISTINCT AS (
    SELECT
        CD_CONTROPARTE,
        TP_CONTROPARTE,
        CD_CONTROPARTE_DI,
        CD_PARTITA_IVA_DI,
        MIN(TS_INIZIO_VALIDITA) AS TS_INSERIMENTO,
        MAX(LASTMODIFIEDDATA) AS LASTMODIFIEDDATA
    FROM LEGAME_RAW
    WHERE
        PREV_CD_CONTROPARTE_DI IS NULL
        OR CD_CONTROPARTE_DI != PREV_CD_CONTROPARTE_DI
        OR CD_PARTITA_IVA_DI != PREV_PARTITA_IVA_DI
    GROUP BY
        CD_CONTROPARTE, TP_CONTROPARTE, CD_CONTROPARTE_DI, CD_PARTITA_IVA_DI
)

SELECT
    CD_CONTROPARTE,
    TP_CONTROPARTE,
    TS_INSERIMENTO,
    CD_CONTROPARTE_DI,
    CD_PARTITA_IVA_DI,
    LASTMODIFIEDDATA
FROM LEGAME_DISTINCT
{% if is_incremental() %}
    WHERE
        LASTMODIFIEDDATA
        > (
            SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ)
            FROM {{ this }}
        )
{% endif %}
