SELECT
    GR.NGRANT_CODICE AS CD_CONTROPARTE,
    GR.NGRANT_TIPO_SEGNALAZIONE AS TP_SEGNALAZIONE,
    GR.NGRANT_TES_PROGR AS PR_SEGNALAZIONE,
    {{ custom_to_date('GR.NGRANT_DATA_INIZIO') }} AS DT_INIZIO,
    {{ custom_to_date('GR.NGRANT_DATA_FINE') }} AS DT_FINE,
    {{ custom_to_timestamp_ntz('GR.NGRANT_DATA_INS', 'GR.NGRANT_ORA_INS') }}
        AS TS_INSERIMENTO,
    TS.NGRTTS_DESCRIZIONE AS DS_SEGNALAZIONE,
    TS.NGRTTS_RISCHIO AS CD_RISCHIO,
    TS.NGRTTS_CLASSE AS CD_CLASSE,
    TS.NGRTTS_GRUPPO AS CD_GRUPPO,
    {{ custom_to_date('GR.NGRANT_DATA_INS') }} AS DT_INSERIMENTO_RECORD,
    {{ custom_to_time('GR.NGRANT_ORA_INS') }} AS NM_ORA_INSERIMENTO_RECORD,
    GR.NGRANT_UTENTE_INS AS CD_UTENTE_INSERIMENTO_RECORD,
    {{ custom_to_date('GR.NGRANT_DATA_CHI') }} AS DT_CHIUSURA_RECORD,
    {{ custom_to_time('GR.NGRANT_ORA_CHI') }} AS NM_ORA_CHIUSURA_RECORD,
    GR.NGRANT_UTENTE_CHI AS CD_UTENTE_CHIUSURA_RECORD,
    GR.NGRANT_TIPO_NOM AS TP_NOMINATIVO,
    GR.NGRANT_TIPO_NOM_FAS AS TP_NOMINATIVO_FAS,
    GR.NGRANT_RAG_SOCIALE_1 AS DS_RAGIONE_SOCIALE,
    GR.NGRANT_ORIGINE_CONT AS CD_ORIGINE_CONTATTO,
    GR.NGRANT_MOTIVO_CONT AS CD_MOTIVO_CONTATTO,
    GR.LASTMODIFIEDDATA
FROM {{ ref('yqngrant') }} AS GR
LEFT JOIN {{ ref('yqngrtts') }} AS TS
    ON
        GR.NGRANT_TIPO_SEGNALAZIONE = TS.NGRTTS_TIPO_SEGNALAZIONE
        AND TS.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        AND TS.FL_DELETED = 'N'
WHERE
    GR.FL_DELETED = 'N'
    {% if is_incremental() %}
        AND GR.LASTMODIFIEDDATA
        > (
            SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ)
            FROM {{ this }}
        )
    {% endif %}
