select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(CD_SOCIETA AS VARCHAR(4)) AS cd_societa,
  TRY_CAST(CD_ESERCIZIO_CONT AS VARCHAR(4)) AS cd_esercizio_cont,
  TRY_CAST(CD_DOCUMENTO AS VARCHAR(10)) AS cd_documento,
  TRY_CAST(CD_POSIZIONE_DOC AS VARCHAR(3)) AS cd_posizione_doc,
  TRY_CAST(CD_TP_DOCUMENTO AS VARCHAR(2)) AS cd_tp_documento,
  TRY_TO_DATE(TRIM(DT_CONTABILE), 'DDMMYYY') AS dt_contabile,
  TRY_TO_DATE(TRIM(DT_DOC_RIFERIMENTO), 'DDMMYYY') AS dt_doc_riferimento,
  TRY_CAST(CD_DOC_RIFERIMENTO AS VARCHAR(16)) AS cd_doc_riferimento,
  TRY_CAST(CD_SETTORE_CONT AS VARCHAR(4)) AS cd_settore_cont,
  TRY_TO_DATE(TRIM(DT_ACQUISIZIONE), 'DDMMYYY') AS dt_acquisizione,
  TRY_CAST(CD_UTENTE_REG AS VARCHAR(12)) AS cd_utente_reg,
  TRY_CAST(CD_SESSIONE_BATCH AS VARCHAR(12)) AS cd_sessione_batch,
  TRY_CAST(CD_TIPO_CONTO AS VARCHAR(1)) AS cd_tipo_conto,
  TRY_CAST(CD_KEY_CONTAB AS VARCHAR(2)) AS cd_key_contab,
  TRY_CAST(CD_CONTO_CONTAB AS VARCHAR(10)) AS cd_conto_contab,
  TRY_CAST(CD_CC_CLI AS VARCHAR(10)) AS cd_cc_cli,
  TRY_CAST(CD_CAUSALE_CONTAB AS VARCHAR(20)) AS cd_causale_contab,
  TRY_CAST(CD_SEGNO_CONTAB AS VARCHAR(1)) AS cd_segno_contab,
  TRY_CAST(REPLACE(REPLACE(EU_REGISTRAZIONE, '.', ''), ',', '.') AS NUMBER(15,2)) AS eu_registrazione,
  TRY_CAST(DS_TESTATA_DOC AS VARCHAR(25)) AS ds_testata_doc,
  TRY_CAST(DS_POSIZIONE AS VARCHAR(50)) AS ds_posizione,
  TRY_CAST(CD_IVA AS VARCHAR(2)) AS cd_iva,
  TRY_CAST(REPLACE(REPLACE(EU_BASE_IMPONIBILE, '.', ''), ',', '.') AS NUMBER(15,2)) AS eu_base_imponibile,
  TRY_CAST(CD_DOCUMENTO_PRG AS NUMBER(10,0)) AS cd_documento_prg,
  TRY_TO_DATE(TRIM(DT_PAREGGIO), 'DDMMYYY') AS dt_pareggio,
  TRY_CAST(TP_RITENUTA_ACC AS VARCHAR(2)) AS tp_ritenuta_acc,
  TRY_CAST(CD_RITENUTA_ACC AS VARCHAR(2)) AS cd_ritenuta_acc,
  TRY_CAST(REPLACE(REPLACE(EU_IMPONIBILE_RA, '.', ''), ',', '.') AS NUMBER(15,2)) AS eu_imponibile_ra,
  TRY_CAST(REPLACE(REPLACE(EU_RITENUTA_ACC, '.', ''), ',', '.') AS NUMBER(15,2)) AS eu_ritenuta_acc,
  TRY_CAST(CD_CONDIZIONE_PAG AS VARCHAR(4)) AS cd_condizione_pag,
  TRY_TO_DATE(TRIM(DT_BASE), 'DDMMYYY') AS dt_base,
  TRY_CAST(NM_GIORNI AS NUMBER(3,0)) AS nm_giorni,
  TRY_CAST(CD_MODALITA_PAG AS VARCHAR(1)) AS cd_modalita_pag,
  TRY_CAST(CD_BLOCCO_PAG AS VARCHAR(1)) AS cd_blocco_pag,
  TRY_CAST(CD_ATTRIBUZIONE AS VARCHAR(18)) AS cd_attribuzione,
  TRY_TO_DATE(TRIM(DT_VALUTA), 'DDMMYYY') AS dt_valuta,
  TRY_CAST(CD_KEY_RIF_1 AS VARCHAR(12)) AS cd_key_rif_1,
  TRY_CAST(CD_KEY_RIF_2 AS VARCHAR(12)) AS cd_key_rif_2,
  TRY_CAST(CD_PERIODO_CONTAB AS VARCHAR(2)) AS cd_periodo_contab,
  TRY_CAST(NM_ELEMENTO_WBS AS NUMBER(8,0)) AS nm_elemento_wbs,
  TRY_CAST(DS_CENTRO_COSTO AS VARCHAR(10)) AS ds_centro_costo
from {{ source('source_l0','mov_contab_gnrle') }}
