SELECT
    S.PSVT_PROGRESSIVO AS PR_POSTVENDITA,
    S.PSVT_PROCEDURA AS TP_PROCEDURA,
    S.PSVT_PRATICA AS CD_PRATICA,
    S.PSVT_AZIONE AS CD_AZIONE,
    T.CCPTAZ_DESCRIZIONE AS DS_AZIONE,
    S.PSVT_STATO AS CD_STATO_RICHIESTA,
    {{ custom_to_date('S.PSVT_DATA_STATO') }} AS DT_STATO_RICHIESTA,
    S.PSVT_BLOCCO AS CD_ATTRIBUTO_RICHIESTA,
    S.PSVT_TIPO_CARIC AS TP_CARICAMENTO_RICHIESTA,
    S.PSVT_CANALE_ACQ AS CD_CANALE_ACQ_RICHIESTA,
    S.PSVT_TIPO_CONTATTO AS TP_CONTATTO_RICHIESTA,
    S.PSVT_ORIGINE_RICHIESTA AS CD_ORIGINE_RICHIESTA,
    S.PSVT_FILIALE AS CD_FILIALE_RICHIESTA,
    S.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
FROM {{ ref('ccpsvt') }} S
LEFT JOIN {{ ref('ccpsvtaz') }} T
    ON T.CCPTAZ_PROCEDURA = S.PSVT_PROCEDURA
    AND T.CCPTAZ_AZIONE = S.PSVT_AZIONE
    AND T.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND T.FL_DELETED = 'N'
WHERE S.FL_DELETED = 'N'