WITH cactfpan_1 AS (
    SELECT
        CACTPAN_CONTRATTO,
        MAX(CACTPAN_DATA_SPEDIZIONE) AS DT_INVIO_CARTA
    FROM {{ ref('cactfpan') }}
    WHERE FL_DELETED = 'N'
    GROUP BY CACTPAN_CONTRATTO
),
crvouf_1 AS (
    SELECT
        CRVOC_CARTA,
        CRVOC_IMPORTO,
        ROW_NUMBER() OVER (
            PARTITION BY CRVOC_CARTA
            ORDER BY CRVOC_DATA_ACQUISTO
        ) AS KEY_PROG
    FROM {{ ref('crvouf') }}
    WHERE FL_DELETED = 'N'
)
SELECT
    A.CRCAR_KEY_N AS CD_PRATICA,
    'CA' AS TP_PROCEDURA,
    B.CEMPR_CATEGORIA AS CD_CATEGORIA_CARTA,
    A.CRCAR_EME AS CD_EMETTITORE,
    C.CEMEM_E_COMMERCE AS TP_CATEGORIA_CARTE,
    A.CRCAR_PRODOTTO AS CD_PRODOTTO,
    B.CEMPR_DESCRIZIONE AS DS_PRODOTTO_CARTA,
    A.CRCAR_STATO AS CD_STATO,
    D.CRTSTA_DESCRIZIONE AS DS_STATO,
    A.CRCAR_CLIENTE AS CD_CLIENTE,
    C.CEMEM_DESCRIZIONE AS DS_CARTA,
    A.CRCAR_BLOCCO AS CD_BLOCCO,
    E.CRB_DESCRIZIONE AS DS_BLOCCO,
    B.CEMPR_CIRCUITO AS CD_CIRCUITO,
    A.CRCAR_MOD_CALC_RATA AS TP_RIMBORSO,
    CASE
        WHEN A.CRCAR_MOD_CALC_RATA = 'T' THEN 'Ripagamento Totale'
        WHEN A.CRCAR_MOD_CALC_RATA = 'P' THEN 'A prontuario'
        WHEN A.CRCAR_MOD_CALC_RATA = 'A' THEN '% sul fido'
        WHEN A.CRCAR_MOD_CALC_RATA = 'R' THEN '% sul saldo'
        WHEN A.CRCAR_MOD_CALC_RATA = 'S' THEN 'Griglia saldi rata'
        WHEN A.CRCAR_MOD_CALC_RATA = 'F' THEN 'Griglia fido rata'
    END AS DS_TIPO_RIMBORSO,
    B.CEMPR_PAG_GIORNI_SALDO AS NM_DUE_DAYS_INPIU,
    {{ custom_to_decimal('A.CRCAR_CREDIT_LIMIT') }} AS EU_FIDO,
    {{ custom_to_decimal('H.CRVOC_IMPORTO') }} AS EU_PRIMO_UTILIZZO,
    A.CRCAR_TAB_INDICIZZATO AS CD_TASSO_INDICIZZATO,
    {{ custom_to_decimal('CASE
        WHEN GREATEST(A.CRCAR_INT_DAL_1, A.CRCAR_INT_DAL_2, A.CRCAR_INT_DAL_3) = A.CRCAR_INT_DAL_1
            THEN A.CRCAR_INT_TASSO_1
        WHEN GREATEST(A.CRCAR_INT_DAL_1, A.CRCAR_INT_DAL_2, A.CRCAR_INT_DAL_3) = A.CRCAR_INT_DAL_2
            THEN A.CRCAR_INT_TASSO_2
        ELSE A.CRCAR_INT_TASSO_3
    END') }} AS NM_TAN,
    {{ custom_to_decimal('F.CRTEG_TEG') }} AS NM_TAEG,
    {{ custom_to_decimal('B.CEMPR_MORA_TASSO') }} AS NM_TASSO_MORA,
    {{ ole_to_date('A.CRCAR_ST_DATA_5') }} AS DT_ATTIVAZIONE_CARTA,
    {{ ole_to_date('A.CRCAR_ST_DATA_8') }} AS DT_UTILIZZATA,
    {{ ole_to_date('A.CRCAR_ST_DATA_6') }} AS DT_BLOCCATA,
    {{ ole_to_date('A.CRCAR_ST_DATA_7') }} AS DT_ESAUIRITA,
    {{ ole_to_date('A.CRCAR_DATA_VALIDITA') }} AS DT_INIZIO_VALIDITA_CARTA,
    {{ ole_to_date('A.CRCAR_DATA_PRIMO_UTILIZZO') }} AS DT_PRIMO_UTILIZZO,
    {{ custom_to_date('G.DT_INVIO_CARTA') }} AS DT_INVIO_CARTA,
    {{ custom_to_date('A.CRCAR_DATA_PRIMO_EC') }} AS DT_PRIMO_EC,
    {{ custom_to_date('B.CEMPR_RITARDO_SPED_CARTA') }} AS DT_RESO_SPEDIZIONE,
    {{ ole_to_date('A.CRCAR_DATA_RICHIESTA') }} AS DT_RICHIESTA,
    {{ ole_to_date('A.CRCAR_DATA_RINNOVO') }} AS DT_RINNOVO,
    {{ custom_to_date('A.CRCAR_DATA_PRODUZIONE') }} AS DT_EMBOSSATURA,
    {{ ole_to_date('A.CRCAR_DATA_SCADENZA') }} AS DT_SCADENZA,
    {{ custom_to_date('A.CRCAR_DATA_VAL_ORIG') }} AS DT_DATA_VAL_ORIG,
    B.CEMPR_CODICE_BIN AS CD_BIN,
    CASE
        WHEN {{ custom_is_not_null('B.CEMPR_INVIO_EC_MAIL') }}
          OR {{ custom_is_not_null('B.CEMPR_INVIO_EC_INTERNET') }}
        THEN 'Y'
        ELSE 'N'
    END AS FL_ESTRATTO_CONTO_ONLINE,
    A.CRCAR_MOD_INVIO_EC AS CD_MODALITA_INVIO,
    C.CEMEM_INVIO_SMS_ACQ AS FL_INVIO_SMS,
    CASE
        WHEN NOT EXISTS (
            SELECT 1
            FROM {{ ref('crcarblo') }} CB
            WHERE CB.CAB_PRATICA = A.CRCAR_KEY_N
              AND CB.CAB_PROVENIENZA = 'CA'
              AND (CB.CAB_COD_BLOCCO_OCS <> 'FF' OR {{ custom_is_null('CB.CAB_COD_BLOCCO_OCS') }})
              AND TRIM(CB.CAB_STATO) = ''
              AND CB.FL_DELETED = 'N'
        )
        THEN 'S'
        ELSE 'N'
    END AS FL_AUMENTO_FIDO,
    B.CEMPR_PREPAGATE AS FL_PREPAGATA,
    A.CRCAR_PRODUZIONE AS CD_PRODUZIONE,
    A.CRCAR_SPEDIZIONE AS CD_SPEDIZIONE,
    {{ custom_to_decimal('A.CRCAR_PAG_MIN_IMPORTO') }} AS EU_PAG_MIN_IMPORTO,
    A.CRCAR_PAG_MIN_PERC AS PC_PAG_MIN,
    A.CRCAR_CONVENZIONATO AS CD_CONVENZIONATO,
    A.CRCAR_GARANTE1 AS CD_GARANTE1,
    A.CRCAR_GARANTE2 AS CD_GARANTE2,
    A.CRCAR_GARANTE3 AS CD_GARANTE3,
    {{ ole_to_date('A.CRCAR_DATA_RILASCIO') }} AS DT_DATA_RILASCIO,
    {{ ole_to_date('A.CRCAR_DATA_STAMPA_BP') }} AS DT_DATA_STAMPA_BP,
    A.CRCAR_RICHIESTA_FATTURA AS FL_RICHIESTA_FATTURA,
    A.CRCAR_LOTTO_PRODUZIONE AS CD_LOTTO_PRODUZIONE,
    A.CRCAR_LOTTO_SPEDIZIONE AS CD_LOTTO_SPEDIZIONE,
    A.CRCAR_CALCOLO_SCORING AS FL_CALCOLO_SCORING,
    A.CRCAR_ESITO_APPROVAZIONE AS TP_ESITO_APPROVAZIONE,
    A.CRCAR_OVERRIDE AS DS_OVERRIDE,
    A.CRCAR_AUTORIZZ_OVERRIDE AS CD_AUTORIZZ_OVERRIDE,
    A.CRCAR_DESTINATARIO_SPEDIZIONE AS TP_DESTINATARIO_SPEDIZIONE,
    A.CRCAR_DESTINATARIO_PIN AS TP_DESTINATARIO_PIN,
    {{ ole_to_date('A.CRCAR_BLOCCO_DATA_DA') }} AS DT_BLOCCO_DATA_DA,
    A.CRCAR_A_RECUPERO AS FL_A_RECUPERO,
    A.CRCAR_FLAG_CARNET AS TP_FLAG_CARNET,
    A.CRCAR_AZIENDALE AS FL_AZIENDALE,
    A.CRCAR_FLAG_COM_ENTRATA AS FL_FLAG_COM_ENTRATA,
    A.CRCAR_ST_STATO_1 AS TP_ST_STATO_1,
    A.CRCAR_ST_STATO_2 AS TP_ST_STATO_2,
    A.CRCAR_ST_STATO_3 AS TP_ST_STATO_3,
    A.CRCAR_ST_STATO_4 AS TP_ST_STATO_4,
    {{ ole_to_date('A.CRCAR_ST_DATA_5') }} AS DT_ST_DATA_5,
    A.CRCAR_ST_OPERATORE_5 AS CD_ST_OPERATORE_5,
    {{ ole_to_date('A.CRCAR_ST_DATA_6') }} AS DT_ST_DATA_6,
    A.CRCAR_ST_OPERATORE_6 AS CD_ST_OPERATORE_6,
    {{ ole_to_date('A.CRCAR_ST_DATA_7') }} AS DT_ST_DATA_7,
    A.CRCAR_ST_OPERATORE_7 AS CD_ST_OPERATORE_7,
    {{ ole_to_date('A.CRCAR_ST_DATA_8') }} AS DT_ST_DATA_8,
    A.CRCAR_ST_OPERATORE_8 AS CD_ST_OPERATORE_8,
    A.CRCAR_BL_CODICE_BLOCCO_1 AS CD_BL_CODICE_BLOCCO_1,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_1') }} AS DT_BL_DATA_DA_1,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_1') }} AS DT_BL_DATA_AL_1,
    A.CRCAR_BL_CODICE_BLOCCO_2 AS CD_BL_CODICE_BLOCCO_2,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_2') }} AS DT_BL_DATA_DA_2,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_2') }} AS DT_BL_DATA_AL_2,
    A.CRCAR_BL_CODICE_BLOCCO_3 AS CD_BL_CODICE_BLOCCO_3,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_3') }} AS DT_BL_DATA_DA_3,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_3') }} AS DT_BL_DATA_AL_3,
    A.CRCAR_BL_CODICE_BLOCCO_4 AS CD_BL_CODICE_BLOCCO_4,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_4') }} AS DT_BL_DATA_DA_4,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_4') }} AS DT_BL_DATA_AL_4,
    A.CRCAR_BL_CODICE_BLOCCO_5 AS CD_BL_CODICE_BLOCCO_5,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_5') }} AS DT_BL_DATA_DA_5,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_5') }} AS DT_BL_DATA_AL_5,
    A.CRCAR_BL_CODICE_BLOCCO_6 AS CD_BL_CODICE_BLOCCO_6,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_6') }} AS DT_BL_DATA_DA_6,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_6') }} AS DT_BL_DATA_AL_6,
    A.CRCAR_BL_CODICE_BLOCCO_7 AS CD_BL_CODICE_BLOCCO_7,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_7') }} AS DT_BL_DATA_DA_7,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_7') }} AS DT_BL_DATA_AL_7,
    A.CRCAR_BL_CODICE_BLOCCO_8 AS CD_BL_CODICE_BLOCCO_8,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_8') }} AS DT_BL_DATA_DA_8,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_8') }} AS DT_BL_DATA_AL_8,
    A.CRCAR_BL_CODICE_BLOCCO_9 AS CD_BL_CODICE_BLOCCO_9,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_9') }} AS DT_BL_DATA_DA_9,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_9') }} AS DT_BL_DATA_AL_9,
    A.CRCAR_BL_CODICE_BLOCCO_10 AS CD_BL_CODICE_BLOCCO_10,
    {{ ole_to_date('A.CRCAR_BL_DATA_DA_10') }} AS DT_BL_DATA_DA_10,
    {{ ole_to_date('A.CRCAR_BL_DATA_AL_10') }} AS DT_BL_DATA_AL_10,
    A.CRCAR_TIPO_CARICAMENTO AS TP_TIPO_CARICAMENTO,
    A.CRCAR_TIPO_DEST_EC AS TP_TIPO_DEST_EC,
    {{ custom_to_decimal('A.CRCAR_COM_INVIO_EC_RI') }} AS EU_COM_INVIO_EC_RI,
    {{ custom_to_decimal('A.CRCAR_COM_INVIO_EC_BP') }} AS EU_COM_INVIO_EC_BP,
    A.CRCAR_MOD_EMISS_CARTA AS TP_MOD_EMISS_CARTA,
    A.CRCAR_PAG_CODICE_RID AS CD_PAG_CODICE_RID,
    A.CRCAR_PAG_INTEST_CONTO AS CD_PAG_INTEST_CONTO,
    A.CRCAR_PAG_BANCA_INTERNA AS CD_PAG_BANCA_INTERNA,
    A.CRCAR_ANA_AMMIN AS CD_ANA_AMMIN,
    A.CRCAR_TIPO_INT_CONTO_CC AS TP_TIPO_INT_CONTO_CC,
    A.CRCAR_LIV_DELIBERA AS TP_LIV_DELIBERA,
    A.CRCAR_LIV_RESPINTA AS TP_LIV_RESPINTA,
    {{ custom_to_decimal('A.CRCAR_COM_ADESIONE') }} AS EU_COM_ADESIONE,
    {{ ole_to_date('A.CRCAR_DATA_RID') }} AS DT_DATA_RID,
    A.CRCAR_FIRMATARIO AS CD_FIRMATARIO,
    A.CRCAR_INTESTAZIONE_CARTA AS DS_INTESTAZIONE_CARTA,
    A.CRCAR_INTESTAZIONE_ESTEN AS DS_INTESTAZIONE_ESTEN,
    A.CRCAR_INTESTAZIONE_MAN AS FL_INTESTAZIONE_MAN,
    A.CRCAR_AGG_CONTROPARTE_1 AS CD_AGG_CONTROPARTE_1,
    A.CRCAR_AGG_INTESTAZIONE_1 AS DS_AGG_INTESTAZIONE_1,
    A.CRCAR_AGG_PRODUZIONE_1 AS TP_AGG_PRODUZIONE_1,
    A.CRCAR_AGG_SPEDIZIONE_1 AS TP_AGG_SPEDIZIONE_1,
    A.CRCAR_AGG_LOTTO_PRODUZIONE_1 AS CD_AGG_LOTTO_PRODUZIONE_1,
    A.CRCAR_AGG_LOTTO_SPEDIZIONE_1 AS CD_AGG_LOTTO_SPEDIZIONE_1,
    A.CRCAR_AGG_PROD_1 AS TP_AGG_PROD_1,
    A.CRCAR_AGG_CONTROPARTE_2 AS CD_AGG_CONTROPARTE_2,
    A.CRCAR_AGG_INTESTAZIONE_2 AS DS_AGG_INTESTAZIONE_2,
    A.CRCAR_AGG_PRODUZIONE_2 AS TP_AGG_PRODUZIONE_2,
    A.CRCAR_AGG_SPEDIZIONE_2 AS TP_AGG_SPEDIZIONE_2,
    A.CRCAR_AGG_LOTTO_PRODUZIONE_2 AS CD_AGG_LOTTO_PRODUZIONE_2,
    A.CRCAR_AGG_LOTTO_SPEDIZIONE_2 AS CD_AGG_LOTTO_SPEDIZIONE_2,
    A.CRCAR_AGG_PROD_2 AS TP_AGG_PROD_2,
    A.CRCAR_AGG_CONTROPARTE_3 AS CD_AGG_CONTROPARTE_3,
    A.CRCAR_AGG_INTESTAZIONE_3 AS DS_AGG_INTESTAZIONE_3,
    A.CRCAR_AGG_PRODUZIONE_3 AS TP_AGG_PRODUZIONE_3,
    A.CRCAR_AGG_SPEDIZIONE_3 AS TP_AGG_SPEDIZIONE_3,
    A.CRCAR_AGG_LOTTO_PRODUZIONE_3 AS CD_AGG_LOTTO_PRODUZIONE_3,
    A.CRCAR_AGG_LOTTO_SPEDIZIONE_3 AS CD_AGG_LOTTO_SPEDIZIONE_3,
    A.CRCAR_AGG_PROD_3 AS TP_AGG_PROD_3,
    A.CRCAR_STANDARD AS FL_STANDARD,
    A.CRCAR_STAMPA_PIN AS FL_STAMPA_PIN,
    {{ ole_to_date('A.CRCAR_INT_DAL_1') }} AS DT_INT_DAL_1,
    {{ ole_to_date('A.CRCAR_INT_DAL_2') }} AS DT_INT_DAL_2,
    {{ ole_to_date('A.CRCAR_INT_DAL_3') }} AS DT_INT_DAL_3,
    {{ custom_to_decimal('A.CRCAR_COM_RINNOVO') }} AS EU_COM_RINNOVO,
    {{ custom_to_decimal('A.CRCAR_COM_INVIO_EC') }} AS EU_COM_INVIO_EC,
    {{ custom_to_decimal('A.CRCAR_COM_OVERLIMIT') }} AS EU_COM_OVERLIMIT,
    A.CRCAR_GARANZIA_175 AS TP_GARANZIA_175,
    A.CRCAR_GARANZIA_176 AS TP_GARANZIA_176,
    A.CRCAR_GARANZIA_177 AS TP_GARANZIA_177,
    A.CRCAR_GARANZIA_178 AS TP_GARANZIA_178,
    A.CRCAR_GARANZIA_179 AS TP_GARANZIA_179,
    A.CRCAR_FLAG_PIN AS FL_FLAG_PIN,
    A.CRCAR_AP AS DS_AP,
    A.CRCAR_CVC1 AS DS_CVC1,
    A.CRCAR_CVC2 AS DS_CVC2,
    A.CRCAR_TENTATIVI_PIN AS NM_TENTATIVI_PIN,
    {{ ole_to_date('A.CRCAR_DATA_ATM') }} AS DT_DATA_ATM,
    A.CRCAR_NUM_ATM_GG AS NM_NUM_ATM_GG,
    A.CRCAR_NUM_ATM_MM AS NM_NUM_ATM_MM,
    {{ custom_to_decimal('A.CRCAR_IMP_ATM_GG') }} AS EU_IMP_ATM_GG,
    {{ custom_to_decimal('A.CRCAR_IMP_ATM_MM') }} AS EU_IMP_ATM_MM,
    A.CRCAR_PAN_ORGANIZ AS CD_PAN_ORGANIZ,
    A.CRCAR_PROD_MULTIFUNZ_F AS FL_PROD_MULTIFUNZ_F,
    A.CRCAR_PROD_MULTIFUNZ_R AS FL_PROD_MULTIFUNZ_R,
    A.CRCAR_PROD_MULTIFUNZ_S AS FL_PROD_MULTIFUNZ_S,
    A.CRCAR_PROD_MULTIFUNZ_T AS FL_PROD_MULTIFUNZ_T,
    A.CRCAR_RICHIESTA_PIN AS FL_RICHIESTA_PIN,
    A.CRCAR_FURTO_PAN AS CD_FURTO_PAN,
    {{ custom_to_date('A.CRCAR_FURTO_DATA') }} AS DT_FURTO_DATA,
    A.CRCAR_FURTO_ORA AS TS_FURTO_ORA,
    A.CRCAR_AZIENDA_PAN AS CD_AZIENDA_PAN,
    A.CRCAR_TIPO_CTR AS TP_TIPO_CTR,
    A.CRCAR_FURTO_STATO AS TP_FURTO_STATO,
    A.CRCAR_FURTO_BLOCCO AS TP_FURTO_BLOCCO,
    A.CRCAR_PVV AS DS_PVV,
    A.CRCAR_IND_PVV AS DS_IND_PVV,
    A.CRCAR_FURTO_PAN_2 AS CD_FURTO_PAN_2,
    A.CRCAR_FURTO_OPERATORE AS CD_FURTO_OPERATORE,
    A.CRCAR_TAB_CALC_RATA AS CD_TAB_CALC_RATA,
    {{ custom_to_date('A.CRCAR_DATA_ASSICURAZIONE') }} AS DT_DATA_ASSICURAZIONE,
    A.CRCAR_PROMO_CODE AS CD_PROMO_CODE,
    {{ custom_to_date('A.CRCAR_DT_CHIUSURA_ASS') }} AS DT_CHIUSURA_ASS,
    A.CRCAR_INVIO_POSITIVO AS TP_INVIO_POSITIVO,
    A.CRCAR_FLAG_ATTESA_ATT AS FL_FLAG_ATTESA_ATT,
    {{ custom_to_date('A.CRCAR_DATA_SCAD_TESSER') }} AS DT_DATA_SCAD_TESSER,
    A.CRCAR_MESI_VALIDITA AS NM_MESI_VALIDITA,
    A.CRCAR_DURATA_PIANO_TEO AS NM_DURATA_PIANO_TEO,
    A.CRCAR_ASSICURAZIONE_ATTIVA AS FL_ASSICURAZIONE_ATTIVA,
    A.CRCAR_UTENTE_MODIFICA AS CD_UTENTE_MODIFICA,
    {{ custom_to_date('A.CRCAR_DATA_MODIFICA') }} AS DT_DATA_MODIFICA,
    A.CRCAR_ORA_MODIFICA AS TS_ORA_MODIFICA,
    A.CRCAR_TIPO_RILAVORAZIONI AS TP_TIPO_RILAVORAZIONI,
    A.CRCAR_PROG_RILAVORAZIONI AS NM_PROG_RILAVORAZIONI,
    A.CRCAR_PROG_RICICLI AS NM_PROG_RICICLI,
    A.CRCAR_NDG_PROMOTORE AS CD_NDG_PROMOTORE,
    {{ custom_to_date('A.CRCAR_DATA_AGG_1') }} AS DT_DATA_AGG_1,
    A.CRCAR_DATO_AGG_1 AS DS_DATO_AGG_1,
    A.CRCAR_DATO_AGG_2 AS DS_DATO_AGG_2,
    A.CRCAR_DATO_AGG_3 AS DS_DATO_AGG_3,
    A.CRCAR_DATO_AGG_4 AS DS_DATO_AGG_4,
    A.CRCAR_COD_INIZIATIVA AS CD_COD_INIZIATIVA,
    A.CRCAR_RIF_INTERNO_CNV AS CD_RIF_INTERNO_CNV,
    A.CRCAR_PROD_MULTIFUNZ AS FL_PROD_MULTIFUNZ,
    A.CRCAR_INVIO_POSITIVO_PRIV AS FL_INVIO_POSITIVO_PRIV,
    A.CRCAR_BAR_CODE AS CD_BAR_CODE,
    A.CRCAR_TABELLA_FIN AS CD_TABELLA_FIN,
    A.CRCAR_EC_FREQUENZA AS TP_EC_FREQUENZA,
    A.CRCAR_PAG_GG_VALUTA AS NM_PAG_GG_VALUTA,
    {{ custom_to_decimal('A.CRCAR_COM_ENTRATA') }} AS EU_COM_ENTRATA,
    A.CRCAR_PROTOCOLLO AS CD_PROTOCOLLO,
    A.CRCAR_MODULO_CONVENZIONATO AS FL_MODULO_CONVENZIONATO,
    {{ custom_to_decimal('A.CRCAR_SPESE_INCASSO') }} AS EU_SPESE_INCASSO,
    A.CRCAR_TIPO_PROD AS TP_TIPO_PROD,
    A.CRCAR_ASSIC_RATA AS FL_ASSIC_RATA,
    A.CRCAR_ASSIC_ANNUALE AS FL_ASSIC_ANNUALE,
    A.CRCAR_FIRMA_SU_RID AS FL_FIRMA_SU_RID,
    A.CRCAR_VALUTA_I_E AS TP_VALUTA_I_E,
    A.CRCAR_STATO_POLIZZA AS TP_STATO_POLIZZA,
    A.CRCAR_RIF_PV_EXT AS CD_RIF_PV_EXT,
    A.CRCAR_PROG_CARTA_SU_CC AS NM_PROG_CARTA_SU_CC,
    A.CRCAR_PURN AS CD_PURN,
    A.CRCAR_EMAIL AS CD_EMAIL,
    A.CRCAR_NDG_CONTATTO AS CD_NDG_CONTATTO,
    A.CRCAR_PRAT_CONSUMO_ORIGINE AS CD_PRAT_CONSUMO_ORIGINE,
    A.CRCAR_MICROCIRCUITO AS FL_MICROCIRCUITO,
    A.CRCAR_AGEVOL AS CD_AGEVOL,
    A.CRCAR_GG_CICLO_EC AS NM_GG_CICLO_EC,
    {{ custom_to_date('A.CRCAR_INI_INT_GRAT') }} AS DT_INI_INT_GRAT,
    {{ custom_to_date('A.CRCAR_FIN_INT_GRAT') }} AS DT_FIN_INT_GRAT,
    {{ custom_to_decimal('A.CRCAR_CREDIT_LIMIT_FAM') }} AS EU_CREDIT_LIMIT_FAM,
    A.CRCAR_NUM_ATM_ALTERN AS NM_NUM_ATM_ALTERN,
    {{ custom_to_date('A.CRCAR_DATA_POSITIVO') }} AS DT_DATA_POSITIVO,
    A.CRCAR_TERZA_TRACCIA AS DS_TERZA_TRACCIA,
    A.CRCAR_ULTIMO_PAN AS CD_ULTIMO_PAN,
    A.CRCAR_AREA AS CD_AREA,
    {{ custom_to_date('A.CRCAR_DATA_CREAZIONE') }} AS DT_DATA_CREAZIONE,
    {{ custom_to_date('A.CRCAR_DATA_SOSTITUZIONE') }} AS DT_DATA_SOSTITUZIONE,
    {{ custom_to_date('A.CRCAR_DATA_RIENTRO_POSITIVO') }} AS DT_DATA_RIENTRO_POSITIVO,
    {{ custom_to_date('A.CRCAR_DATA_POS') }} AS DT_DATA_POS,
    A.CRCAR_NUM_POS_GG AS NM_NUM_POS_GG,
    A.CRCAR_NUM_POS_MM AS NM_NUM_POS_MM,
    {{ custom_to_decimal('A.CRCAR_IMP_POS_GG') }} AS EU_IMP_POS_GG,
    {{ custom_to_decimal('A.CRCAR_IMP_POS_MM') }} AS EU_IMP_POS_MM,
    {{ custom_to_date('A.CRCAR_DATA_PTR') }} AS DT_DATA_PTR,
    A.CRCAR_NUM_PTR_GG AS NM_NUM_PTR_GG,
    A.CRCAR_NUM_PTR_MM AS NM_NUM_PTR_MM,
    {{ custom_to_decimal('A.CRCAR_IMP_PTR_GG') }} AS EU_IMP_PTR_GG,
    {{ custom_to_decimal('A.CRCAR_IMP_PTR_MM') }} AS EU_IMP_PTR_MM,
    A.CRCAR_ATM_GRATUITE AS NM_ATM_GRATUITE,
    A.CRCAR_ST_BOLLO_CONTRATTO AS TP_ST_BOLLO_CONTRATTO,
    A.CRCAR_IMPORTO_1 AS NM_IMPORTO_1,
    A.CRCAR_TIPO_IMPOSTA AS TP_TIPO_IMPOSTA,
    {{ custom_to_decimal('A.CRCAR_IMP_IMPOSTA') }} AS EU_IMP_IMPOSTA,
    {{ custom_to_date('A.CRCAR_DT_ADD_IMPOSTA') }} AS DT_ADD_IMPOSTA,
    A.CRCAR_FASE_IMPOSTA AS CD_FASE_IMPOSTA,
    A.CRCAR_PROG_LOG_IMPOSTA AS CD_PROG_LOG_IMPOSTA,
    A.CRCAR_IMPORTO_3 AS NM_IMPORTO_3,
    A.CRCAR_IMPORTO_4 AS NM_IMPORTO_4,
    {{ custom_to_date('A.CRCAR_ACCOUNT_OPEN_DATE') }} AS DT_ACCOUNT_OPEN_DATE,
    A.CRCAR_PIEDINO AS CD_PIEDINO,
    A.CRCAR_SEC_SIMULTANEA AS FL_SEC_SIMULTANEA,
    A.CRCAR_MOTIVO_ESI AS TP_MOTIVO_ESI,
    A.CRCAR_RUOLO_DELIBERANTE AS TP_RUOLO_DELIBERANTE,
    A.CRCAR_BRANCH_CODE AS CD_BRANCH_CODE,
    A.CRCAR_CONTRATTO_RIF AS CD_CONTRATTO_RIF,
    A.CRCAR_TIPOLOGIA AS TP_TIPOLOGIA,
    A.CRCAR_ESPONENTE1 AS NM_ESPONENTE1,
    A.CRCAR_ESPONENTE2 AS NM_ESPONENTE2,
    A.CRCAR_ESPONENTE3 AS NM_ESPONENTE3,
    A.CRCAR_ESPONENTE4 AS NM_ESPONENTE4,
    A.CRCAR_ESPONENTE5 AS NM_ESPONENTE5,
    {{ custom_to_decimal('A.CRCAR_PLAFOND') }} AS EU_PLAFOND,
    A.LASTMODIFIEDDATA AS LASTMODIFIEDDATA

FROM {{ ref('crcar') }} A

LEFT JOIN {{ ref('cremep') }} B
    ON A.CRCAR_EME = B.CEMPR_EMETTITORE
    AND A.CRCAR_PRODOTTO = B.CEMPR_PRODOTTO
    AND B.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND B.FL_DELETED = 'N'
LEFT JOIN {{ ref('cremee') }} C
    ON A.CRCAR_EME = C.CEMEM_EMETTITORE
    AND C.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND C.FL_DELETED = 'N'
LEFT JOIN {{ ref('crtabsta') }} D
    ON A.CRCAR_STATO = D.CRTSTA_STATO
    AND 'CA' = D.CRTSTA_PROCEDURA
    AND D.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND D.FL_DELETED = 'N'
LEFT JOIN {{ ref('crblocchi') }} E
    ON A.CRCAR_BLOCCO = E.CRB_BLOCCO
    AND 'CA' = E.CRB_PROVENIENZA
    AND E.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND E.FL_DELETED = 'N'
LEFT JOIN {{ ref('crteg') }} F 
    ON A.CRCAR_KEY_N = F.CRTEG_CARTA
    AND F.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND F.FL_DELETED = 'N'
LEFT JOIN cactfpan_1 G
    ON A.CRCAR_KEY_N = G.CACTPAN_CONTRATTO
LEFT JOIN crvouf_1 H
    ON A.CRCAR_KEY_N = H.CRVOC_CARTA
    AND 1 = H.KEY_PROG