SELECT
    A.BAINT_PROCEDURA AS TP_PROCEDURA,
    A.BAINT_PRATICA AS CD_PRATICA,
    A.BAINT_PROGRESSIVO AS CD_PROGRESSIVO,
    A.BAINT_RETE_VENDITA AS CD_RETE_VENDITA,
    A.BAINT_AGENTE AS CD_AGENTE,
    A.BAINT_SUB_AGENTE AS CD_SUB_AGENTE,
    A.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
FROM {{ ref('bapratint') }} A
WHERE A.BAINT_PROGRESSIVO > 0