with SOURCE_CQ as (
    select
        'CQ' AS TP_PROCEDURA
        ,CQTBB_TABELLA AS CD_TABELLA_FINANZIARIA
        ,TS_INIZIO_VALIDITA AS TS_INIZIO_VALIDITA
        ,TS_FINE_VALIDITA AS TS_FINE_VALIDITA
        ,CQTBB_DESCRIZIONE AS DS_TABELLA_FINANZIARIA
        ,'CQ' AS TP_TABELLA_FINANZIARIA
        ,CQTBB_ANNULLO AS FL_ANNULLO
        ,CQTBB_FLAG_CAMPAGNA AS FL_CAMPAGNA
        ,NULL AS CD_ATTRIBUTO_TT
        ,LASTMODIFIEDDATA AS LASTMODIFIEDDATA
    from {{ ref('cqtbftafb') }} as a
    WHERE TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND FL_DELETED = 'N'
)

, dedup_cq AS (
    SELECT
        TP_PROCEDURA
        ,CD_TABELLA_FINANZIARIA
        ,TS_INIZIO_VALIDITA
        ,TS_FINE_VALIDITA
        ,DS_TABELLA_FINANZIARIA
        ,TP_TABELLA_FINANZIARIA
        ,FL_ANNULLO
        ,FL_CAMPAGNA
        ,CD_ATTRIBUTO_TT
        ,LASTMODIFIEDDATA
        ,{{ hash_cols([
            'TP_PROCEDURA',
            'CD_TABELLA_FINANZIARIA',
            'DS_TABELLA_FINANZIARIA',
            'TP_TABELLA_FINANZIARIA',
            'FL_ANNULLO',
            'FL_CAMPAGNA',
            'CD_ATTRIBUTO_TT'
        ]) }} AS HASHED_COLS
    FROM SOURCE_CQ
    {{ is_incremental_S1('TP_PROCEDURA, CD_TABELLA_FINANZIARIA') }}
)

, SOURCE_CO as (
    select
        'CO' AS TP_PROCEDURA
        ,a.OXTB_CODICE AS CD_TABELLA_FINANZIARIA
        ,a.TS_INIZIO_VALIDITA AS TS_INIZIO_VALIDITA
        ,a.TS_FINE_VALIDITA AS TS_FINE_VALIDITA
        ,a.OXTB_DESCRIZIONE AS DS_TABELLA_FINANZIARIA
        ,a.OXTB_TIPO_CALCOLO AS TP_TABELLA_FINANZIARIA
        ,a.OXTB_ANNULLO AS FL_ANNULLO
        ,a.OXTB_CAMPAGNA AS FL_CAMPAGNA
        ,b.TFIAT_CODICE AS CD_ATTRIBUTO_TT
        ,a.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
    from {{ ref('oxprftafb') }} as a
   
    left join {{ ref('pltfinatt') }} as b
        on a.OXTB_CODICE = b.TFIAT_TAB_FIN 
        AND b.TFIAT_ATTRIBUTO = 'TT'
        AND B.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    
    WHERE A.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND A.FL_DELETED = 'N'
)

, dedup_co AS (
    SELECT
        TP_PROCEDURA
        ,CD_TABELLA_FINANZIARIA
        ,TS_INIZIO_VALIDITA
        ,TS_FINE_VALIDITA
        ,DS_TABELLA_FINANZIARIA
        ,TP_TABELLA_FINANZIARIA
        ,FL_ANNULLO
        ,FL_CAMPAGNA
        ,CD_ATTRIBUTO_TT
        ,LASTMODIFIEDDATA
        ,{{ hash_cols([
            'TP_PROCEDURA',
            'CD_TABELLA_FINANZIARIA',
            'DS_TABELLA_FINANZIARIA',
            'TP_TABELLA_FINANZIARIA',
            'FL_ANNULLO',
            'FL_CAMPAGNA',
            'CD_ATTRIBUTO_TT'
        ]) }} AS HASHED_COLS
    FROM SOURCE_CO
    {{ is_incremental_S1('TP_PROCEDURA, CD_TABELLA_FINANZIARIA') }}
)

SELECT
    TP_PROCEDURA
    ,CD_TABELLA_FINANZIARIA
    ,TS_INIZIO_VALIDITA
    ,{{ ts_fine_validita('TP_PROCEDURA, CD_TABELLA_FINANZIARIA', 'TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA
    ,DS_TABELLA_FINANZIARIA
    ,TP_TABELLA_FINANZIARIA
    ,FL_ANNULLO
    ,FL_CAMPAGNA
    ,CD_ATTRIBUTO_TT
    ,LASTMODIFIEDDATA
FROM dedup_cq
UNION ALL
SELECT 
    TP_PROCEDURA
    ,CD_TABELLA_FINANZIARIA
    ,TS_INIZIO_VALIDITA
    ,{{ ts_fine_validita('TP_PROCEDURA, CD_TABELLA_FINANZIARIA', 'TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA
    ,DS_TABELLA_FINANZIARIA
    ,TP_TABELLA_FINANZIARIA
    ,FL_ANNULLO
    ,FL_CAMPAGNA
    ,CD_ATTRIBUTO_TT
    ,LASTMODIFIEDDATA
FROM dedup_co
