select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(AICTSTL_PRATICA AS NUMBER(12,0)) AS aictstl_pratica,
  TRY_CAST(AICTSTL_PRATICA AS NUMBER(12,0)) AS aictstl_pratica,
  TRY_CAST(IFF(RTRIM(AICTSTL_STATO) = '', ' ', RTRIM(AICTSTL_STATO)) AS VARCHAR(2)) AS aictstl_stato,
  TRY_CAST(IFF(RTRIM(AICTSTL_STATO) = '', ' ', RTRIM(AICTSTL_STATO)) AS VARCHAR(2)) AS aictstl_stato,
  TRY_CAST(IFF(RTRIM(AICTSTL_ATTRIBUTO) = '', ' ', RTRIM(AICTSTL_ATTRIBUTO)) AS VARCHAR(2)) AS aictstl_attributo,
  TRY_CAST(IFF(RTRIM(AICTSTL_ATTRIBUTO) = '', ' ', RTRIM(AICTSTL_ATTRIBUTO)) AS VARCHAR(2)) AS aictstl_attributo,
  TRY_CAST(AICTSTL_DATA AS NUMBER(8,0)) AS aictstl_data,
  TRY_CAST(AICTSTL_DATA AS NUMBER(8,0)) AS aictstl_data,
  TRY_CAST(AICTSTL_ORA AS NUMBER(8,0)) AS aictstl_ora,
  TRY_CAST(AICTSTL_ORA AS NUMBER(8,0)) AS aictstl_ora,
  TRY_CAST(IFF(RTRIM(AICTSTL_UTENTE) = '', ' ', RTRIM(AICTSTL_UTENTE)) AS VARCHAR(10)) AS aictstl_utente,
  TRY_CAST(IFF(RTRIM(AICTSTL_UTENTE) = '', ' ', RTRIM(AICTSTL_UTENTE)) AS VARCHAR(10)) AS aictstl_utente,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','aictfstl') }}
