select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(AICTPT_PRATICA AS NUMBER(12,0)) AS aictpt_pratica,
  TRY_CAST(AICTPT_INTERMEDIARIO AS NUMBER(9,0)) AS aictpt_intermediario,
  TRY_CAST(IFF(RTRIM(AICTPT_TIPO_ANA) = '', ' ', RTRIM(AICTPT_TIPO_ANA)) AS VARCHAR(2)) AS aictpt_tipo_ana,
  TRY_CAST(IFF(RTRIM(AICTPT_TIPO_CARIC) = '', ' ', RTRIM(AICTPT_TIPO_CARIC)) AS VARCHAR(2)) AS aictpt_tipo_caric,
  TRY_CAST(IFF(RTRIM(AICTPT_CANALE_ACQ) = '', ' ', RTRIM(AICTPT_CANALE_ACQ)) AS VARCHAR(3)) AS aictpt_canale_acq,
  TRY_CAST(IFF(RTRIM(AICTPT_ORIGINE) = '', ' ', RTRIM(AICTPT_ORIGINE)) AS VARCHAR(3)) AS aictpt_origine,
  TRY_CAST(IFF(RTRIM(AICTPT_FILIALE) = '', ' ', RTRIM(AICTPT_FILIALE)) AS VARCHAR(3)) AS aictpt_filiale,
  TRY_CAST(IFF(RTRIM(AICTPT_STATO) = '', ' ', RTRIM(AICTPT_STATO)) AS VARCHAR(2)) AS aictpt_stato,
  TRY_CAST(IFF(RTRIM(AICTPT_ATTRIBUTO) = '', ' ', RTRIM(AICTPT_ATTRIBUTO)) AS VARCHAR(2)) AS aictpt_attributo,
  TRY_CAST(AICTPT_DATA_INSERIMENTO AS NUMBER(8,0)) AS aictpt_data_inserimento,
  TRY_CAST(IFF(RTRIM(AICTPT_UTENTE_INSERIMENTO) = '', ' ', RTRIM(AICTPT_UTENTE_INSERIMENTO)) AS VARCHAR(10)) AS aictpt_utente_inserimento,
  TRY_CAST(AICTPT_ORA_INSERIMENTO AS NUMBER(8,0)) AS aictpt_ora_inserimento,
  TRY_CAST(AICTPT_DATA_ATTIVAZIONE AS NUMBER(8,0)) AS aictpt_data_attivazione,
  TRY_CAST(AICTPT_DATA_CHIUSURA AS NUMBER(8,0)) AS aictpt_data_chiusura,
  TRY_CAST(IFF(RTRIM(AICTPT_UTENTE) = '', ' ', RTRIM(AICTPT_UTENTE)) AS VARCHAR(10)) AS aictpt_utente,
  TRY_CAST(AICTPT_DATA AS NUMBER(8,0)) AS aictpt_data,
  TRY_CAST(AICTPT_ORA AS NUMBER(8,0)) AS aictpt_ora,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','aictfpt') }}
