select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(AIPARTL_SEZIONE) = '', ' ', RTRIM(AIPARTL_SEZIONE)) AS VARCHAR(1)) AS aipartl_sezione,
  TRY_CAST(IFF(RTRIM(AIPARTL_SEZIONE) = '', ' ', RTRIM(AIPARTL_SEZIONE)) AS VARCHAR(1)) AS aipartl_sezione,
  TRY_CAST(AIPARTL_PRATICA AS NUMBER(12,0)) AS aipartl_pratica,
  TRY_CAST(AIPARTL_PRATICA AS NUMBER(12,0)) AS aipartl_pratica,
  TRY_CAST(AIPARTL_PROGRESSIVO AS NUMBER(9,0)) AS aipartl_progressivo,
  TRY_CAST(AIPARTL_PROGRESSIVO AS NUMBER(9,0)) AS aipartl_progressivo,
  TRY_CAST(IFF(RTRIM(AIPARTL_TIPO_PARTITA) = '', ' ', RTRIM(AIPARTL_TIPO_PARTITA)) AS VARCHAR(2)) AS aipartl_tipo_partita,
  TRY_CAST(IFF(RTRIM(AIPARTL_TIPO_PARTITA) = '', ' ', RTRIM(AIPARTL_TIPO_PARTITA)) AS VARCHAR(2)) AS aipartl_tipo_partita,
  TRY_CAST(AIPARTL_DATA_COMP AS NUMBER(8,0)) AS aipartl_data_comp,
  TRY_CAST(AIPARTL_DATA_COMP AS NUMBER(8,0)) AS aipartl_data_comp,
  TRY_CAST(AIPARTL_DATA_SCADENZA AS NUMBER(8,0)) AS aipartl_data_scadenza,
  TRY_CAST(AIPARTL_DATA_SCADENZA AS NUMBER(8,0)) AS aipartl_data_scadenza,
  TRY_CAST(AIPARTL_PRATICA_AI_DEST AS NUMBER(12,0)) AS aipartl_pratica_ai_dest,
  TRY_CAST(AIPARTL_PRATICA_AI_DEST AS NUMBER(12,0)) AS aipartl_pratica_ai_dest,
  TRY_CAST(AIPARTL_PROG_VAR AS NUMBER(9,0)) AS aipartl_prog_var,
  TRY_CAST(AIPARTL_PROG_VAR AS NUMBER(9,0)) AS aipartl_prog_var,
  TRY_CAST(AIPARTL_DATA_VARIAZIONE AS NUMBER(8,0)) AS aipartl_data_variazione,
  TRY_CAST(AIPARTL_DATA_VARIAZIONE AS NUMBER(8,0)) AS aipartl_data_variazione,
  TRY_CAST(AIPARTL_ORA_VARIAZIONE AS NUMBER(8,0)) AS aipartl_ora_variazione,
  TRY_CAST(AIPARTL_ORA_VARIAZIONE AS NUMBER(8,0)) AS aipartl_ora_variazione,
  TRY_CAST(IFF(RTRIM(AIPARTL_OPERATORE) = '', ' ', RTRIM(AIPARTL_OPERATORE)) AS VARCHAR(10)) AS aipartl_operatore,
  TRY_CAST(IFF(RTRIM(AIPARTL_OPERATORE) = '', ' ', RTRIM(AIPARTL_OPERATORE)) AS VARCHAR(10)) AS aipartl_operatore,
  TRY_CAST(IFF(RTRIM(AIPARTL_TIPO_OPERAZIONE) = '', ' ', RTRIM(AIPARTL_TIPO_OPERAZIONE)) AS VARCHAR(1)) AS aipartl_tipo_operazione,
  TRY_CAST(IFF(RTRIM(AIPARTL_TIPO_OPERAZIONE) = '', ' ', RTRIM(AIPARTL_TIPO_OPERAZIONE)) AS VARCHAR(1)) AS aipartl_tipo_operazione,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','aiecfpartl') }}
