select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(AIECPART_SEZIONE) = '', ' ', RTRIM(AIECPART_SEZIONE)) AS VARCHAR(1)) AS aiecpart_sezione,
  TRY_CAST(IFF(RTRIM(AIECPART_SEZIONE) = '', ' ', RTRIM(AIECPART_SEZIONE)) AS VARCHAR(1)) AS aiecpart_sezione,
  TRY_CAST(AIECPART_PRATICA AS NUMBER(12,0)) AS aiecpart_pratica,
  TRY_CAST(AIECPART_PRATICA AS NUMBER(12,0)) AS aiecpart_pratica,
  TRY_CAST(AIECPART_PROGRESSIVO AS NUMBER(9,0)) AS aiecpart_progressivo,
  TRY_CAST(AIECPART_PROGRESSIVO AS NUMBER(9,0)) AS aiecpart_progressivo,
  TRY_CAST(IFF(RTRIM(AIECPART_TIPO_PARTITA) = '', ' ', RTRIM(AIECPART_TIPO_PARTITA)) AS VARCHAR(2)) AS aiecpart_tipo_partita,
  TRY_CAST(IFF(RTRIM(AIECPART_TIPO_PARTITA) = '', ' ', RTRIM(AIECPART_TIPO_PARTITA)) AS VARCHAR(2)) AS aiecpart_tipo_partita,
  TRY_CAST(AIECPART_DATA_COMP AS NUMBER(8,0)) AS aiecpart_data_comp,
  TRY_CAST(AIECPART_DATA_COMP AS NUMBER(8,0)) AS aiecpart_data_comp,
  TRY_CAST(AIECPART_DATA_SCADENZA AS NUMBER(8,0)) AS aiecpart_data_scadenza,
  TRY_CAST(AIECPART_DATA_SCADENZA AS NUMBER(8,0)) AS aiecpart_data_scadenza,
  TRY_CAST(AIECPART_PRATICA_AI_DEST AS NUMBER(12,0)) AS aiecpart_pratica_ai_dest,
  TRY_CAST(AIECPART_PRATICA_AI_DEST AS NUMBER(12,0)) AS aiecpart_pratica_ai_dest,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','aiecfpart') }}
