select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(EXFDFLUS_ANNO AS NUMBER(4,0)) AS exfdflus_anno,
  TRY_CAST(EXFDFLUS_MESE AS NUMBER(2,0)) AS exfdflus_mese,
  TRY_CAST(EXFDFLUS_VOCE AS NUMBER(5,0)) AS exfdflus_voce,
  TRY_CAST(EXFDFLUS_SOTTOVOCE AS NUMBER(2,0)) AS exfdflus_sottovoce,
  TRY_CAST(IFF(RTRIM(EXFDFLUS_PROVENIENZA) = '', ' ', RTRIM(EXFDFLUS_PROVENIENZA)) AS VARCHAR(2)) AS exfdflus_provenienza,
  TRY_CAST(EXFDFLUS_PRATICA AS NUMBER(12,0)) AS exfdflus_pratica,
  TRY_CAST(EXFDFLUS_IMPORTO AS NUMBER(13,0)) AS exfdflus_importo,
  TRY_CAST(EXFDFLUS_CLIENTE AS NUMBER(9,0)) AS exfdflus_cliente,
  TRY_CAST(EXFDFLUS_COD_SPORTELLO AS NUMBER(5,0)) AS exfdflus_cod_sportello,
  TRY_CAST(EXFDFLUS_MESE_RIF AS NUMBER(2,0)) AS exfdflus_mese_rif,
  TRY_CAST(EXFDFLUS_IMPORTO_IAS AS NUMBER(13,0)) AS exfdflus_importo_ias,
  TRY_CAST(IFF(RTRIM(EXFDFLUS_SAE) = '', ' ', RTRIM(EXFDFLUS_SAE)) AS VARCHAR(3)) AS exfdflus_sae,
  TRY_CAST(IFF(RTRIM(EXFDFLUS_NOTA_INT) = '', ' ', RTRIM(EXFDFLUS_NOTA_INT)) AS VARCHAR(1)) AS exfdflus_nota_int,
  TRY_CAST(IFF(RTRIM(EXFDFLUS_QUADRO) = '', ' ', RTRIM(EXFDFLUS_QUADRO)) AS VARCHAR(20)) AS exfdflus_quadro,
  TRY_CAST(IFF(RTRIM(EXFDFLUS_TIPO_DINAMICA) = '', ' ', RTRIM(EXFDFLUS_TIPO_DINAMICA)) AS VARCHAR(20)) AS exfdflus_tipo_dinamica,
  TRY_CAST(IFF(RTRIM(EXFDFLUS_FT_BONIS) = '', ' ', RTRIM(EXFDFLUS_FT_BONIS)) AS VARCHAR(1)) AS exfdflus_ft_bonis,
  TRY_CAST(IFF(RTRIM(EXFDFLUS_FT_NUOVE_POS) = '', ' ', RTRIM(EXFDFLUS_FT_NUOVE_POS)) AS VARCHAR(1)) AS exfdflus_ft_nuove_pos,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','ccexfdflus') }}
