SELECT
    P.BAPV_PROCEDURA AS TP_PROCEDURA,
    P.BAPV_NUM_PRATICA AS CD_PRATICA,
    P.BAPV_PROTOCOLLO AS CD_PROTOCOLLO,
    P.BAPV_PROTOCOLLO_RIGA AS CD_PROTOCOLLO_RIGA,
    P.BAPV_PROTOCOLLO_PROGR AS PR_PROTOCOLLO,
    P.BAPV_NUM_CESPITE AS CD_CESPITE,
    P.BAPV_SERVIZIO AS CD_SERVIZIO,
    P.BAPV_EMETTITORE AS CD_EMETTITORE,
    P.BAPV_PRODOTTO AS CD_PRODOTTO,
    P.BAPV_COD_CAMPAGNA AS CD_CAMPAGNA,
    P.BAPV_ANNOMESE AS NM_ANNOMESE_MATURAZIONE,
    P.BAPV_TIPO_PROVVIGIONE AS TP_PROVVIGIONE,
    P.BAPV_TIPO_PREMIO AS TP_PREMIO,
    P.BAPV_INTERMEDIARIO AS CD_INTERMEDIARIO,
    P.BAPV_TIPO_INTERMEDIARIO AS TP_INTERMEDIARIO,
    P.BAPV_FLAG_STORNO AS FL_STORNO,
    -- DT_COMPETENZA: MAX tra le due date; GREATEST_IGNORE_NULLS gestisce il caso in cui BAPV_DATA_MATURAZ non sia valorizzata
    -- FIX: data model had "DATE('GREATEST_IGNORE_NULLS(...)')" (intera espressione tra apici)
    TRY_TO_DATE(GREATEST_IGNORE_NULLS(P.BAPV_DATA_CALCOLO, P.BAPV_DATA_MATURAZ)::VARCHAR, 'YYYYMMDD') AS DT_COMPETENZA,
    -- FL_RETTIFICA: BAPV_TIPO_PREMIO e' un codice a 4 byte, il 3 carattere = 'R' indica rettifica
    CASE WHEN SUBSTR(P.BAPV_TIPO_PREMIO, 3, 1) = 'R' THEN 'S' ELSE 'N' END AS FL_RETTIFICA,
    -- EU_IMPORTO_1: segno invertito se storno
    CASE WHEN P.BAPV_FLAG_STORNO = 'S' THEN P.BAPV_IMPORTO_1 * -1 / 100 ELSE P.BAPV_IMPORTO_1 / 100 END AS EU_IMPORTO_1,
    P.BAPV_BASE_CALCOLO_1 AS CD_BASE_CALCOLO_1,
    P.BAPV_PERC_CALCOLO_1 AS PC_CALCOLO_1,
    P.BAPV_INDICE_RIF_1 AS CD_INDICE_RIF_1,
    {{ custom_to_decimal('P.BAPV_IMPONIBILE_1', 13, 2) }} AS EU_IMPONIBILE_1,
    -- EU_IMPORTO_2: segno invertito se storno
    CASE WHEN P.BAPV_FLAG_STORNO = 'S' THEN P.BAPV_IMPORTO_2 * -1 / 100 ELSE P.BAPV_IMPORTO_2 / 100 END AS EU_IMPORTO_2,
    P.BAPV_BASE_CALCOLO_2 AS CD_BASE_CALCOLO_2,
    P.BAPV_PERC_CALCOLO_2 AS PC_CALCOLO_2,
    P.BAPV_INDICE_RIF_2 AS CD_INDICE_RIF_2,
    {{ custom_to_decimal('P.BAPV_IMPONIBILE_2', 13, 2) }} AS EU_IMPONIBILE_2,
    P.BAPV_TIPO_IMPORTO AS TP_IMPORTO,
    -- EU_IMPORTO_FISSO: segno invertito se storno
    -- WARN: EU_IMPORTO_FISSO - la RT usa P.BAPV_FISSO_1 (ramo storno) e P.BAPV_FISSO (ramo else), ma SORGENTE CAMPI indica BAPV_IMPORTO_FISSO; colonne non allineate, verificare col data model
    CASE WHEN P.BAPV_FLAG_STORNO = 'S' THEN P.BAPV_IMPORTO_FISSO * -1 / 100 ELSE P.BAPV_IMPORTO_FISSO / 100 END AS EU_IMPORTO_FISSO,
    -- EU_TOTALE: segno invertito se storno
    -- WARN: EU_TOTALE - la RT usa P.BAPV_TOTALE_1 (ramo storno) e P.BAPV_TOTALE (ramo else), ma SORGENTE CAMPI indica BAPV_TOTALE; colonne non allineate, verificare col data model
    CASE WHEN P.BAPV_FLAG_STORNO = 'S' THEN P.BAPV_TOTALE * -1 / 100 ELSE P.BAPV_TOTALE / 100 END AS EU_TOTALE,
    TRY_TO_DATE(P.BAPV_DATA_CALCOLO::VARCHAR, 'YYYYMMDD') AS DT_CALCOLO,
    TRY_TO_DATE(P.BAPV_DATA_MATURAZ::VARCHAR, 'YYYYMMDD') AS DT_MATURAZIONE,
    TRY_TO_DATE(P.BAPV_DATA_LIQUIDAZIONE::VARCHAR, 'YYYYMMDD') AS DT_LIQUIDAZIONE,
    P.BAPV_CAT_PROVV AS TP_CATEGORIA_PROVV,
    P.BAPV_CATENA AS PR_CATENA,
    P.BAPV_DESTINATARIO AS CD_DESTINATARIO,
    P.BAPV_TIPO_DESTINATARIO AS TP_DESTINATARIO,
    P.BAPV_DA_LIQUIDARE AS FL_DA_LIQUIDARE,
    P.BAPV_DOC_LIQUIDAZIONE AS CD_DOC_LIQUIDAZIONE,
    RA.RAMTTR_PERIODICITA_CAL AS CD_PERIODICITA_CALC_RAPP,
    RA.RAMTTR_PERIODICITA_LIQ AS CD_PERIODICITA_LIQ_RAPP,
    P.BAPV_TIPO_OPERAZ AS TP_OPERAZIONE,
    P.BAPV_PROGR_OPERAZ AS PR_OPERAZIONE,
    P.BAPV_DESTINAT_PAG AS CD_DESTINATARIO_PAG,
    P.BAPV_TIPO_DESTINAT_PAG AS TP_DESTINATARIO_PAG,
    P.BAPV_CATEGORIA_COR AS TP_CATEGORIA_COR,
    P.BAPV_CORRETTIVO_COR AS CD_CORRETTIVO_COR,
    P.BAPV_TIPO_CHK_COR AS TP_CHK_COR,
    P.BAPV_PERC_1_COR AS PC_1_COR,
    P.BAPV_PERC_2_COR AS PC_2_COR,
    P.BAPV_PERC_F_COR AS PC_F_COR,
    {{ custom_to_decimal('P.BAPV_IMP_MIN_COR', 13, 2) }} AS EU_IMP_MIN_COR,
    {{ custom_to_decimal('P.BAPV_IMP_MAX_COR', 13, 2) }} AS EU_IMP_MAX_COR,
    {{ custom_to_decimal('P.BAPV_IMPORTO_RIF', 13, 2) }} AS EU_IMPORTO_RIF,
    P.BAPV_PROGR_FATT_DET AS PR_FATTURA_DETT,
    P.BAPV_FATT_PROVV_SE AS FL_DETTAGLIO_SERVIZI,
    P.BAPV_BLOCCO_RICALCOLO AS FL_BLOCCO_RICALCOLO,
    P.BAPV_INTERM_RIF AS CD_INTERM_RIF,
    P.BAPV_TIPO_INTERM_RIF AS TP_INTERM_RIF,
    -- WARN: DT_SOPRAVVENIENZA - prefisso DT_ ma tipo NUMBER(8) nel data model (probabile data YYYYMMDD numerica); mappata diretta senza custom_to_date, coerente col FORMATO dichiarato
    P.BAPV_DATA_SOPRAVV AS DT_SOPRAVVENIENZA,
    P.BAPV_PERIODO_MATURAZ AS NM_PERIODO_MATURAZ,
    P.BAPV_TIPO_PERIODO_MATURAZ AS TP_PERIODO_MATURAZ,
    P.BAPV_TIPO_MATURAZ AS TP_MATURAZIONE,
    P.BAPV_PROGR_CUMULO AS PR_CUMULO,
    P.BAPV_PROCEDURA_RIF AS TP_PROCEDURA_RIF,
    P.BAPV_PRATICA_RIF AS CD_PRATICA_RIF,
    P.BAPV_IND_ORDIN_LE AS NM_ORDIN_LEASING
FROM {{ ref('bapratpv') }} P
LEFT JOIN {{ ref('ccramttr') }} RA
    ON P.BAPV_TIPO_PREMIO = RA.RAMTTR_TRATT_RAPPEL
    --AND P.BAPV_DATA_CALCOLO >= RA.TS_INIZIO_VALIDITA
    --AND P.BAPV_DATA_CALCOLO < RA.TS_FINE_VALIDITA
    AND TRY_TO_DATE(P.BAPV_DATA_CALCOLO::VARCHAR, 'YYYYMMDD') >= RA.TS_INIZIO_VALIDITA
    AND TRY_TO_DATE(P.BAPV_DATA_CALCOLO::VARCHAR, 'YYYYMMDD') < RA.TS_FINE_VALIDITA
    -- FIX: data model had "P.TP_PROVVIGIONE" (nome campo target sulla sorgente P -> colonna inesistente su bapratpv)
    AND P.BAPV_TIPO_PROVVIGIONE = 'RA'
    AND RA.FL_DELETED = 'N'
