-- INCASSI_DETTAGLIO | Storicizzazione S4 (insert_overwrite) | SA: PAGAMENTI E CONTABILITA
-- Sorgente principale: OXINFREPD (cluster A2 -> FL_DELETED)
SELECT
    d.OXINREPD_EVENTO AS CD_EVENTO_INCASSO,
    d.OXINREPD_PROGR_DETT AS PR_DETT_INCASSO,
    d.OXINREPD_PROGR_EVENTO_DETT AS CD_EVENTO_DETT,
    d.OXINREPD_PROCEDURA AS TP_PROCEDURA,
    d.OXINREPD_PRATICA AS CD_PRATICA,
    d.OXINREPD_NUM_PARTITA AS NM_PARTITA,
    d.OXINREPD_NUM_RIGA AS NM_RIGA,
    d.OXINREPD_TIPO_PARTITA AS TP_PARTITA,
    d.OXINREPD_DES_PARTITA AS DS_PARTITA,
    {{ custom_to_decimal('d.OXINREPD_IMPORTO', 13, 2) }} AS EU_INCASSO,
    d.OXINREPD_CAUSALE AS CD_CAUSALE,
    d.OXINREPD_DES_CAUSALE AS DS_CAUSALE,
    d.OXINREPD_SEZIONALE AS FL_SEZIONALE
FROM {{ ref('oxinfrepd') }} d
WHERE d.FL_DELETED = 'N'
