-- INCASSI_TESTATA | Storicizzazione S4 (insert_overwrite) | SA: PAGAMENTI E CONTABILITA
-- Sorgente principale: OXINFREPT (cluster A2 -> FL_DELETED)
-- Storno: self-join su OXINREPT_EV_INC_ST (che punta all'EVENTO dello storno)
SELECT
    t.OXINREPT_EVENTO AS CD_EVENTO_INCASSO,
    t.OXINREPT_PROCEDURA AS TP_PROCEDURA,
    t.OXINREPT_PRATICA AS CD_PRATICA,
    {{ custom_to_date('t.OXINREPT_DATA_REGISTRAZIONE') }} AS DT_REGISTRAZIONE,
    {{ custom_to_date('t.OXINREPT_DATA_VALUTA') }} AS DT_VALUTA,
    t.OXINREPT_MM_AAAA_RENDICNT AS NM_MESE_ANNO_RENDICONTAZIONE,
    {{ custom_to_decimal('t.OXINREPT_IMPORTO', 13, 2) }} AS EU_INCASSO,
    CAST(NULL AS NUMBER(11)) AS CD_EVENTO_INCASSO_STORNO,
    -- t.OXINREPT_EV_INC_ST AS CD_EVENTO_INCASSO_STORNO,
    t.OXINREPT_ORIGINE AS CD_ORIGINE,
    t.OXINREPT_FORMA_PAGAMENTO AS TP_FORMA_PAGAMENTO,
    t.OXINREPT_DES_FORMA AS DS_FORMA_PAGAMENTO,
    t.OXINREPT_TIPO_MOV AS TP_MOVIMENTO,
    t.OXINREPT_CAUSALE AS CD_CAUSALE,
    t.OXINREPT_FILE_DETTAGLIO AS CD_FILE_DETTAGLIO,
    t.OXINREPT_FUNZIONE AS CD_FUNZIONE,
    t.OXINREPT_OPERAZIONE AS CD_OPERAZIONE,
    t.OXINREPT_SEZIONALE AS FL_SEZIONALE
FROM {{ ref('oxinfrept') }} t
WHERE t.FL_DELETED = 'N'