-- L2 OPERAZIONI_CAMBIALE
-- Subject area: PAGAMENTI E CONTABILITA
-- Storicizzazione S4 (insert_overwrite) - confermata dall'utente (non presente nel data model)
-- Sorgente main: EFEXFEDPS (cluster A2 -> FL_DELETED)
-- WARN: cluster di IFESFLT / GAEFARC / EFEXFINCDE non noto dal data model:
--       se A1/A2/C aggiungere "AND <alias>.FL_DELETED = 'N'" nelle rispettive ON

SELECT
    EDPS.DPS_PROCEDURA AS TP_PROCEDURA,
    EDPS.DPS_PRATICA AS CD_PRATICA,
    {{ custom_to_date('EDPS.DPS_DATA_SCAD_TIT') }} AS DT_SCADENZA_TITOLO,
    EDPS.DPS_OPERAZIONE AS CD_OPERAZIONE,
    EDPS.DPS_EFFETTO_OCS AS CD_CAMBIALE,
    EDPS.DPS_ESITO_OCS AS CD_ESITO_OCS,
    EDPS.DPS_CD_ESITO_OPE AS CD_ESITO_OPERAZIONE,
    EDPS.DPS_CD_STATO_TIT AS CD_STATO_TITOLO,
    EDPS.DPS_MARCATURA AS CD_MARCATURA,
    EDPS.DPS_IDE_DOWNLOAD_T AS CD_LOTTO_DOWNLOAD_T,
    EDPS.DPS_IDE_DOWNLOAD_D AS CD_LOTTO_DOWNLOAD_D,
    {{ custom_to_timestamp_ntz('FLT_D.IFESLT_DATA', 'FLT_D.IFESLT_ORA') }} AS TS_DOWNLOAD,
    EDPS.DPS_IDE_UPLOAD_T AS CD_LOTTO_UPLOAD_T,
    EDPS.DPS_IDE_UPLOAD_D AS CD_LOTTO_UPLOAD_D,
    {{ custom_to_timestamp_ntz('FLT_U.IFESLT_DATA', 'FLT_U.IFESLT_ORA') }} AS TS_UPLOAD,
    CDE.EFEXCDE_FL_SP_PRES AS FL_SPESE_PRES
FROM AGOS_DEV_16000.L1_O_EFF.EFEXFEDPS_TEST EDPS            --TODO sostituire con puntamento a tabella ufficiale
LEFT JOIN AGOS_DEV_16000.L1_O_EFF.IFESFLT_TEST FLT_D        --TODO
    ON EDPS.DPS_IDE_DOWNLOAD_T = FLT_D.IFESLT_IDE_LOTTO     
LEFT JOIN AGOS_DEV_16000.L1_O_EFF.IFESFLT_TEST FLT_U        --TODO
    ON EDPS.DPS_IDE_UPLOAD_T = FLT_U.IFESLT_IDE_LOTTO       
LEFT JOIN {{ ref('gaefarc') }} ARC           
    ON EDPS.DPS_EFFETTO_OCS = ARC.EF_NUM_EFFETTO
LEFT JOIN {{ ref('efexfincde') }} CDE
    ON ARC.EF_RECUPERATORE = CDE.EFEXCDE_RECUPERATORE
    AND ARC.EF_RAPPORTINO = CDE.EFEXCDE_RAPPORTINO
    AND ARC.EF_PROG_INC_RAP = CDE.EFEXCDE_PROGR_INC
WHERE EDPS.FL_DELETED = 'N'

