-- Modello L2: PAGAMENTI_VIDAUT
-- Subject Area: PAGAMENTI E CONTABILITA (schema L2_PRD_PGM)
-- Sorgente main: CCRIMBO (cluster C -> TS gia' in L1)



    SELECT
        T.CCRIM_PROGRESSIVO AS CD_PAG_VIDAUT,
        T.CCRIM_PROVENIENZA AS TP_PROCEDURA,
        T.CCRIM_NUM_PRATICA AS CD_PRATICA,
        T.CCRIM_TIPO_RECORD AS TP_MOTIVO,
        T.CCRIM_STATO AS CD_STATO,
        T.CCRIM_ATTRIBUTO AS CD_ATTRIBUTO,
        T.CCRIM_BANCA_INTE AS CD_BANCA_INTERNA,
        T.CCRIM_ABI_BAN_PAGAM AS CD_ABI_BAN_PAGAM,
        T.CCRIM_CAB_BAN_PAGAM AS CD_CAB_BAN_PAGAM,
        {{ custom_to_date('T.CCRIM_DATA_PAGAMENTO') }} AS DT_PAGAMENTO,
        {{ custom_to_date('T.CCRIM_DATA_VALUTA') }} AS DT_VALUTA,
        {{ custom_to_date('T.CCRIM_DATA_REG_CONTAB') }} AS DT_REG_CONTABILE,
        {{ custom_to_date('T.CCRIM_DATA_SCADENZA') }} AS DT_SCADENZA,
        -- FIX: la RT del data model riportava colonna 'OXINREPT_IMPORTO' (refuso,
        --      la SORGENTE CAMPI e' CCRIM_IMPORTO) e una parentesi mancante.
        --      La macro custom_to_decimal implementa /100 + CAST NUMBER(13,2) della RT.
        {{ custom_to_decimal('T.CCRIM_IMPORTO', 13, 2) }} AS EU_PAGAMENTO,
        T.CCRIM_DESTINAT AS CD_DESTINATARIO,
        T.CCRIM_TIPO_DESTINAT AS TP_DESTINATARIO,
        T.CCRIM_COD_LETTERA AS CD_LETTERA_DESTINATARIO,
        T.CCRIM_ABI_CLI AS CD_ABI_DESTINATARIO,
        T.CCRIM_CAB_CLI AS CD_CAB_DESTINATARIO,
        T.CCRIM_CC_CLI AS CD_CC_DESTINATARIO,
        T.CCRIM_BANK_CODE_CLI AS CD_BANK_CODE_DESTINATARIO,
        T.CCRIM_SUB_NUMBER_CLI AS CD_SUB_NUMBER_DESTINATARIO,
        T.CCRIM_FLAG_CONTR_ANTIRIC AS FL_CONTR_ANTIRICICLAGGIO,
        {{ custom_to_date('T.CCRIM_DATA_CONTR_ANTIRIC') }} AS DT_CONTR_ANTIRICICLAGGIO,
        T.CCRIM_EMISSIONE_AS AS TP_EMISSIONE_ASSEGNO,
        T.CCRIM_FNE_ORIGINE AS CD_ORIGINE_PAGAMENTO,
        T.CCRIM_NUM_OPERAZ_PAG AS CD_NUM_OPERAZ_PAG,
        T.CCRIM_OPE_REG_CONTAB AS CD_OPE_REG_CONTAB,
        T.CCRIM_ARTICOLO_CONT AS CD_ARTICOLO_CONT,
        T.CCRIM_KEY_EC AS CD_KEY_EC,
        T.CCRIM_KEY_EC_RIM AS CD_KEY_EC_RIM,
        T.CCRIM_PROGR_PRAT AS PR_PRATICA,
        T.CCRIM_CUMULATO AS FL_CUMULATO,
        T.CCRIM_CONTROPARTE_CNT AS CD_CONTROPARTE_CNT,
        T.CCRIM_PRESENTAZIONE AS PR_PRESENTAZIONE,
        T.CCRIM_PROGR_NUOVO_PAG AS PR_NUOVO_PAG_RIEMISSIONE,
        T.CCRIM_CRO AS CD_CRO,
        T.CCRIM_FILIALE AS CD_FILIALE,
        T.CCRIM_SOTTOCAUSALE AS CD_SOTTOCAUSALE,
        T.CCRIM_ID_CARTA AS CD_ID_CARTA,
        T.CCRIM_PRODOTTO_CARTA AS CD_PRODOTTO_CARTA,
        T.CCRIM_CAU_RIFIUTO AS CD_CAU_RIFIUTO,
        T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
    FROM {{ ref('ccrimbo') }} T
    WHERE T.FL_DELETED = 'N'



