-- Procedura 1: OCS
SELECT
    'OCS' AS TP_SORGENTE,
    O.OXSRQIQU_TIPO_INTEST AS TP_CONTROPARTE,
    CAST(COALESCE (B.BAPCT_CONTROPARTE, 0) AS VARCHAR(45)) AS CD_CONTROPARTE,
    O.OXSRQIQU_PROCEDURA AS TP_PROCEDURA,
    CAST(O.OXSRQIQU_NUM_PRATICA AS VARCHAR(45)) AS CD_PRATICA,
    CAST(O.OXSRQIQU_QUESTION AS VARCHAR(11)) AS CD_QUESTIONARIO,
    CAST(O.OXSRQIQU_LIVELLO AS NUMBER(11,0)) AS NM_LIVELLO,
    CASE
        WHEN O.OXSRQIQU_LIVELLO = 1 THEN 'D&N'
        WHEN O.OXSRQIQU_LIVELLO = 2 THEN 'Adeguatezza'
        WHEN O.OXSRQIQU_LIVELLO = 3 THEN 'Sicurezza'
    END AS DS_LIVELLO,
    CASE
        WHEN O.OXSRQIQU_ADEGUATO = 'A' THEN 'A'
        ELSE 'KO'
    END AS CD_ADEGUATO,
    O.OXSRQIQU_ABBINATO AS FL_ABBINATO,
    {{ custom_to_date('OI.OXSRQIT_DATA_IVASS') }} AS DT_SOMMINISTRAZIONE,
    TO_DATE('31:12:9999', 'DD:MM:YYYY') AS DT_SCADENZA,
    B.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
FROM {{ ref('oxsrfqiqu') }} O
LEFT JOIN {{ ref('bapratct') }} B
    ON B.BAPCT_NUM_PRATICA = O.OXSRQIQU_NUM_PRATICA
    AND B.BAPCT_PROCEDURA = O.OXSRQIQU_PROCEDURA
    AND B.BAPCT_RAPPORTO = O.OXSRQIQU_TIPO_INTEST
LEFT JOIN {{ ref('oxsrfqit') }} OI
    ON O.OXSRQIQU_PROCEDURA = OI.OXSRQIT_PROCEDURA
    AND O.OXSRQIQU_NUM_PRATICA = OI.OXSRQIT_NUM_PRATICA
    AND O.OXSRQIQU_EVENTO_PSVT = OI.OXSRQIT_EVENTO_PSVT
    AND CURRENT_TIMESTAMP >= OI.TS_INIZIO_VALIDITA AND CURRENT_TIMESTAMP < OI.TS_FINE_VALIDITA
    AND OI.FL_DELETED = 'N'
WHERE CURRENT_TIMESTAMP >= O.TS_INIZIO_VALIDITA AND CURRENT_TIMESTAMP < O.TS_FINE_VALIDITA AND O.FL_DELETED = 'N'
UNION ALL
-- Procedura 2: FEA
SELECT
    'FEA' AS TP_SORGENTE,
    'CL' AS TP_CONTROPARTE,
    CAST(COALESCE (QC.codice_cliente, 0) AS VARCHAR(45)) AS CD_CONTROPARTE,
    NULL AS TP_PROCEDURA,
    AP.numero_polizza AS CD_PRATICA,
    CAST (QC.idQuestionarioContraente AS VARCHAR(11)) AS CD_QUESTIONARIO,
    QC.idQuestionario AS NM_LIVELLO,
    CASE
        WHEN QR.tipo  = 1 THEN 'D&N LONG'
        WHEN QR.tipo  = 2 THEN 'D&N SHORT'
        WHEN QR.tipo  = 3 THEN 'D&N LONG PG'
        WHEN QR.tipo  = 4 THEN 'NCP'
        WHEN QR.tipo  = 5 THEN 'DEALERS'
    END AS DS_LIVELLO,
    CASE WHEN QRO.esito = 'KO' THEN 'KO' ELSE 'A' END AS CD_ADEGUATO,
    CASE WHEN AP.numero_polizza IS NOT NULL THEN 'S' ELSE 'N' END AS FL_ABBINATO,
    {{ custom_to_date('QC.data_creazione') }} AS DT_SOMMINISTRAZIONE,
    TO_DATE('31:12:9999', 'DD:MM:YYYY') AS DT_SCADENZA,
    NULL AS LASTMODIFIEDDATA
FROM {{ ref('tblquestionaricontraenti') }} QC
LEFT JOIN {{ ref('tblquestionari') }} QR 
    ON QR.idQuestionario = QC.idQuestionario
    AND CURRENT_TIMESTAMP >= QR.TS_INIZIO_VALIDITA AND CURRENT_TIMESTAMP < QR.TS_FINE_VALIDITA
LEFT JOIN {{ ref('tblquestionario') }} QRO 
    ON QRO.idQuestionario = QC.idQuestionario
    AND CURRENT_TIMESTAMP >= QRO.TS_INIZIO_VALIDITA AND CURRENT_TIMESTAMP < QRO.TS_FINE_VALIDITA
LEFT JOIN {{ ref('tblpreventivo') }} AP 
    ON AP.idQuestionario = QC.idQuestionario
    AND CURRENT_TIMESTAMP >= AP.TS_INIZIO_VALIDITA AND CURRENT_TIMESTAMP < AP.TS_FINE_VALIDITA
WHERE CURRENT_TIMESTAMP >= QC.TS_INIZIO_VALIDITA AND CURRENT_TIMESTAMP < QC.TS_FINE_VALIDITA
