-- Procedura 1: CO (PLPRATSERV)
SELECT
    'CO' AS TP_PROCEDURA,
    CAST(A.PLSE_NUM_PRATICA AS NUMBER(12, 0)) AS CD_PRATICA,
    A.PLSE_CODICE_SERVIZIO AS CD_SERVIZIO,
    A.DT_OSSERVAZIONE AS DT_OSSERVAZIONE,
    A.PLSE_TIPO_SERVIZIO AS TP_SERVIZIO,
    S.CSER_DESCRIZIONE AS DS_SERVIZIO,
    S.CSER_TIPO_POLIZZA AS TP_POLIZZA,
    A.PLSE_CODICE_PACCHETTO AS CD_PACCHETTO_SERVIZI,
    P.TCP_DESCRIZIONE AS DS_PACCHETTO_SERVIZI,
    CAST(P.TCP_TIPO_PACCHETTO AS VARCHAR(5)) AS TP_PACCHETTO,
    CAST(P.TCP_CLASSE_PACCHETTO AS VARCHAR(3)) AS TP_CLASSE,
    CAST(P.TCP_FAMIGLIA_PACCHETTO AS VARCHAR(5)) AS TP_FAMIGLIA_PRODOTTO,
    CAST(N.OXSRNUME_PROGRESSIVO AS NUMBER(9)) AS CD_PARTITA,
    BPR.PLC_CLIENTE AS CD_CLIENTE,
    S.CSER_COD_FORN AS CD_COMPAGNIA,
    B.AC_RAG_SOCIALE_1 AS DS_COMPAGNIA,
    CASE
        WHEN {{ custom_to_date('A.PLSE_FINE_COPERTURA') }} <= CURRENT_DATE - 1
        THEN 'AP' ELSE 'CH'
    END AS CD_STATO_ASSIC,
    CASE
        WHEN {{ custom_to_date('A.PLSE_FINE_COPERTURA') }} <= CURRENT_DATE - 1
        THEN 'Servizio Aperto' ELSE 'Servizio Chiuso'
    END AS DS_STATO_ASSIC,
    {{ custom_to_date('A.PLSE_INIZIO_COPERTURA') }} AS DT_ADESIONE,
    {{ custom_to_date('A.PLSE_FINE_COPERTURA') }} AS DT_CHIUSURA,
    {{ custom_to_date('A.PLSE_DATA_STORNO') }} AS DT_STORNO,
    {{ custom_to_date('A.PLSE_DATA_DEC_RECESSO') }} AS DT_RECESSO,
    CAST(NULL AS DATE) AS DT_RINNOVO,
    {{ custom_to_decimal('A.PLSE_IMP_ATTIVO') }} AS EU_PREMIO_LORDO,
    {{ custom_to_decimal('A.PLSE_IMP_ATTIVO - COALESCE(D.OXSRSERD_IMP_IMPOSTE, 0)') }}
        AS EU_PREMIO_NETTO,
    {{ custom_to_decimal('A.PLSE_IMP_ATTIVO - A.PLSE_IMP_PASSIVO') }}
        AS EU_INCASSO_PREMIO,
    NULL AS FL_PNF,
    A.PLSE_SINISTRO_ATTIVO AS FL_SINISTRO_ATTIVO
FROM {{ ref('plpratserv_m') }} AS A
LEFT JOIN {{ ref('cctabser') }} AS S
    ON A.PLSE_CODICE_SERVIZIO = S.CSER_COD_SERVIZIO
    AND A.DT_OSSERVAZIONE >= S.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < S.TS_FINE_VALIDITA
    AND S.FL_DELETED = 'N'
LEFT JOIN {{ ref('cctabpacc') }} AS P
    ON A.PLSE_CODICE_PACCHETTO = P.TCP_CODICE_PACCHETTO
    AND A.DT_OSSERVAZIONE >= P.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < P.TS_FINE_VALIDITA
    AND P.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxsrfnume') }} N
    ON N.OXSRNUME_TIPO = P.TCP_TIPO_PACCHETTO
    AND A.DT_OSSERVAZIONE >= N.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < N.TS_FINE_VALIDITA
    AND N.FL_DELETED = 'N'
LEFT JOIN {{ ref('plprat') }} AS BPR
    ON A.PLSE_NUM_PRATICA = BPR.PLC_NUM_PRATICA
LEFT JOIN {{ ref('ccanagr') }} AS B
    ON S.CSER_COD_FORN = B.AC_CODICE
LEFT JOIN {{ ref('oxsrfserd') }} AS D
    ON D.OXSRSERD_PROCEDURA = 'CO'
    AND A.PLSE_NUM_PRATICA = D.OXSRSERD_NUM_PRATICA
    AND D.OXSRSERD_COD_SERVIZIO = A.PLSE_CODICE_SERVIZIO
    AND A.DT_OSSERVAZIONE >= D.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < D.TS_FINE_VALIDITA
    AND D.FL_DELETED = 'N'
UNION ALL
-- Procedura 2: CA (CASRFSER)
SELECT
    'CA' AS TP_PROCEDURA,
    CAST(A.CASRSER_CARTA AS NUMBER(12, 0)) AS CD_PRATICA,
    A.CASRSER_SERVIZIO AS CD_SERVIZIO,
    A.DT_OSSERVAZIONE AS DT_OSSERVAZIONE,
    NULL AS TP_SERVIZIO,
    S.CSER_DESCRIZIONE AS DS_SERVIZIO,
    S.CSER_TIPO_POLIZZA AS TP_POLIZZA,
    A.CASRSER_PACCHETTO AS CD_PACCHETTO_SERVIZI,
    P.TCP_DESCRIZIONE AS DS_PACCHETTO_SERVIZI,
    CAST(P.TCP_TIPO_PACCHETTO AS VARCHAR(5)) AS TP_PACCHETTO,
    CAST(P.TCP_CLASSE_PACCHETTO AS VARCHAR(3)) AS TP_CLASSE,
    CAST(P.TCP_FAMIGLIA_PACCHETTO AS VARCHAR(5)) AS TP_FAMIGLIA_PRODOTTO,
    CAST(N.OXSRNUME_PROGRESSIVO AS VARCHAR(2)) AS CD_PARTITA,
    BCR.CRCAR_CLIENTE AS CD_CLIENTE,
    S.CSER_COD_FORN AS CD_COMPAGNIA,
    CAN.AC_RAG_SOCIALE_1 AS DS_COMPAGNIA,
    A.CASRSER_STATO AS CD_STATO_ASSIC,
    CAST(O.OTSQDOV_DESCRIPTION AS VARCHAR(30)) AS DS_STATO_ASSIC,
    {{ custom_to_date('A.CASRSER_DATA_ADE_SERV') }} AS DT_ADESIONE,
    {{ custom_to_date('A.CASRSER_DATA_CHI_SERV') }} AS DT_CHIUSURA,
    NULL AS DT_STORNO,
    CASE
        WHEN LENGTH(A.CASRSER_ANNO_EC_RECESSO) < 4 OR NOT (0 < A.CASRSER_MESE_EC_RECESSO < 13) THEN NULL
        ELSE LAST_DAY(TO_DATE(A.CASRSER_ANNO_EC_RECESSO || LPAD(A.CASRSER_MESE_EC_RECESSO, 2, '0') || '01', 'YYYYMMDD'))
    END AS DT_RECESSO,
    CAST(NULL AS DATE) AS DT_RINNOVO,
    {{ custom_to_decimal('A.CASRSER_IMP_ADDEBITI') }} AS EU_PREMIO_LORDO,
    {{ custom_to_decimal('A.CASRSER_IMP_ADDEBITI - COALESCE(D.OXSRSERD_IMP_IMPOSTE, 0)') }}
        AS EU_PREMIO_NETTO,
    {{ custom_to_decimal('A.CASRSER_IMP_ADDEBITI - A.CASRSER_IMP_TOT_PASSIVA - COALESCE(D.OXSRSERD_IMP_IMPOSTE, 0)') }}
        AS EU_INCASSO_PREMIO,
    NULL AS FL_PNF,
    NULL AS FL_SINISTRO_ATTIVO
FROM {{ ref('casrfser_m') }} AS A
LEFT JOIN {{ ref('cctabser') }} AS S
    ON A.CASRSER_SERVIZIO = S.CSER_COD_SERVIZIO
    AND A.DT_OSSERVAZIONE >= S.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < S.TS_FINE_VALIDITA
    AND S.FL_DELETED = 'N'
LEFT JOIN {{ ref('cctabpacc') }} AS P
    ON A.CASRSER_PACCHETTO = P.TCP_CODICE_PACCHETTO
    AND A.DT_OSSERVAZIONE >= P.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < P.TS_FINE_VALIDITA
    AND P.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxsrfnume') }} N
    ON N.OXSRNUME_TIPO = P.TCP_TIPO_PACCHETTO
    AND A.DT_OSSERVAZIONE >= N.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < N.TS_FINE_VALIDITA
    AND N.FL_DELETED = 'N'
LEFT JOIN {{ ref('crcar_m') }} AS BCR
    ON A.CASRSER_CARTA = BCR.CRCAR_KEY_N
    AND BCR.DT_OSSERVAZIONE = A.DT_OSSERVAZIONE
LEFT JOIN {{ ref('oxsrfserd') }} AS D
    ON D.OXSRSERD_PROCEDURA = 'CA'
    AND A.CASRSER_CARTA = D.OXSRSERD_NUM_PRATICA
    AND D.OXSRSERD_COD_SERVIZIO = A.CASRSER_SERVIZIO
    AND A.DT_OSSERVAZIONE >= D.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < D.TS_FINE_VALIDITA
    AND D.FL_DELETED = 'N'
LEFT JOIN {{ ref('ccanagr') }} AS CAN
    ON S.CSER_COD_FORN = CAN.AC_CODICE
LEFT JOIN {{ ref('otsqfdov') }} AS O
    ON O.OTSQDOV_DOMINIO = 'CAR_ASS_ST'
    AND A.CASRSER_STATO = O.OTSQDOV_VARIABLE
    AND A.DT_OSSERVAZIONE >= O.TS_INIZIO_VALIDITA AND A.DT_OSSERVAZIONE < O.TS_FINE_VALIDITA

{% if is_incremental() %}
    WHERE A.DT_OSSERVAZIONE = {{ last_day_past_month() }}
{% endif %}
