-- Anagrafica intermediari agenti con storicizzazione SCD2 S1 da CCINTLAG e CCANAINAG
-- Co-authored with CoCo
-- WARN: storicizzazione N/A nel catalog, inferita S1 da presenza di TS_INIZIO_VALIDITA in PK
-- FIX: data model had 'TS_INIZIO VALIDITA' (con spazio) → rinominato TS_INIZIO_VALIDITA
WITH base AS (
    SELECT
        COALESCE(L.INTLAG_INTERM, A.IAG_CODICE) AS CD_INTERMEDIARIO,
        COALESCE(L.INTLAG_TIPO_INTERM, A.IAG_TIPO_ANA) AS TP_INTERMEDIARIO,
        COALESCE(L.INTLAG_PROCEDURA, 'NA') AS TP_PROCEDURA,
        {{ custom_to_timestamp_ntz('L.INTLAG_DATA', 'L.INTLAG_ORA') }} AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita(
            "COALESCE(L.INTLAG_INTERM, A.IAG_CODICE), COALESCE(L.INTLAG_TIPO_INTERM, A.IAG_TIPO_ANA), COALESCE(L.INTLAG_PROCEDURA, 'NA')",
            custom_to_timestamp_ntz('L.INTLAG_DATA', 'L.INTLAG_ORA')
        ) }} AS TS_FINE_VALIDITA,
        {{ custom_to_date('COALESCE(L.INTLAG_DATA_INIZIO_CONV, A.IAG_DATA_CONVENZIONE)', zero='min') }} AS DT_INIZIO_CONV,
        {{ custom_to_date('COALESCE(L.INTLAG_DATA_FINE_CONV, A.IAG_DATA_FINE_CONVENZIONE)', zero ='max') }} AS DT_FINE_CONV,
        COALESCE(L.INTLAG_CAU_ANNULLO, A.IAG_CAU_ANNULLO) AS CD_CAUSALE_ANNULLO,
        COALESCE(L.INTLAG_RETE_VENDITA, A.IAG_RETE_VENDITA) AS CD_RETE_VENDITA,
        COALESCE(L.INTLAG_RESPONSABILE, A.IAG_RESPONSABILE) AS CD_RESPONSABILE,
        COALESCE(L.INTLAG_GEST_SA, A.IAG_SUBAGENTI) AS FL_GESTIONE_SA,
        COALESCE(L.INTLAG_GEST_VE, A.IAG_VENDITORI) AS FL_GESTIONE_VE,
        L.LASTMODIFIEDDATA AS LASTMODIFIEDDATA,
        ROW_NUMBER() OVER (
            PARTITION BY L.INTLAG_INTERM, L.INTLAG_TIPO_INTERM, L.INTLAG_PROCEDURA, L.INTLAG_DATA, L.INTLAG_ORA
            ORDER BY L.ROWID
        )::NUMBER(38, 0) AS PR_PK
    FROM {{ ref('ccintlag') }} L
    LEFT JOIN {{ ref('ccanaiag') }} A
    --LEFT JOIN AGOS_DEV_16000.L0.CCANAIAG A
        ON (
            L.INTLAG_INTERM = A.IAG_CODICE
            AND L.INTLAG_TIPO_INTERM = A.IAG_TIPO_ANA
        )
    WHERE L.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        PR_PK,
        DT_INIZIO_CONV,
        DT_FINE_CONV,
        CD_CAUSALE_ANNULLO,
        CD_RETE_VENDITA,
        CD_RESPONSABILE,
        FL_GESTIONE_SA,
        FL_GESTIONE_VE,
        LASTMODIFIEDDATA,
        {{ hash_cols(['CD_INTERMEDIARIO', 'TP_INTERMEDIARIO', 'TP_PROCEDURA', 'DT_INIZIO_CONV', 'DT_FINE_CONV', 'CD_CAUSALE_ANNULLO', 'CD_RETE_VENDITA', 'CD_RESPONSABILE', 'FL_GESTIONE_SA', 'FL_GESTIONE_VE']) }} AS HASHED_COLS
    FROM base {{ is_incremental_S1('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA',order_extra='PR_PK') }}
),

DEDUP_FV AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        --TS_FINE_VALIDITA,
        {{ ts_fine_validita('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', 'TS_INIZIO_VALIDITA') }} AS TS_FV_NEXT,
        PR_PK,
        DT_INIZIO_CONV,
        DT_FINE_CONV,
        CD_CAUSALE_ANNULLO,
        CD_RETE_VENDITA,
        CD_RESPONSABILE,
        FL_GESTIONE_SA,
        FL_GESTIONE_VE,
        LASTMODIFIEDDATA      
    FROM dedup 
)

SELECT
    H.CD_INTERMEDIARIO,
    H.TP_INTERMEDIARIO,
    H.TP_PROCEDURA,
    H.TS_INIZIO_VALIDITA,
    MAX(H.TS_FV_NEXT) OVER (
        PARTITION BY H.CD_INTERMEDIARIO, H.TP_INTERMEDIARIO, H.TP_PROCEDURA, H.TS_INIZIO_VALIDITA
    ) AS TS_FINE_VALIDITA,
    H.PR_PK,
    H.DT_INIZIO_CONV,
    H.DT_FINE_CONV,
    H.CD_CAUSALE_ANNULLO,
    H.CD_RETE_VENDITA,
    H.CD_RESPONSABILE,
    H.FL_GESTIONE_SA,
    H.FL_GESTIONE_VE,
    H.LASTMODIFIEDDATA
FROM DEDUP_FV AS H 
