-- Anagrafica intermediari convenzionati con storicizzazione SCD2 S1 da CCINTLCV e CCANAINCV
-- Co-authored with CoCo
-- WARN: storicizzazione N/A nel catalog, inferita S1 da RTs (TS_INIZIO_VALIDITA / TS_FINE_VALIDITA con LEAD)
-- WARN: LASTMODIFIEDDATA non presente nel data model, aggiunto da sorgente principale CCINTLCV

WITH base AS (
    SELECT
        COALESCE(L.INTLCV_INTERM, A.ICV_CODICE) AS CD_INTERMEDIARIO,
        COALESCE(L.INTLCV_TIPO_INTERM, A.ICV_TIPO_ANA) AS TP_INTERMEDIARIO,
        COALESCE(L.INTLCV_PROCEDURA, 'NA') AS TP_PROCEDURA,
        {{ custom_to_timestamp_ntz('L.INTLCV_DATA', 'L.INTLCV_ORA') }} AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita(
            "COALESCE(L.INTLCV_INTERM, A.ICV_CODICE), COALESCE(L.INTLCV_TIPO_INTERM, A.ICV_TIPO_ANA), COALESCE(L.INTLCV_PROCEDURA, 'NA')",
            custom_to_timestamp_ntz('L.INTLCV_DATA', 'L.INTLCV_ORA')
        ) }} AS TS_FINE_VALIDITA,
        {{ custom_to_date('COALESCE(L.INTLCV_DATA_INIZIO_CNV, A.ICV_DATA_CONVENZIONE)', zero='min') }} AS DT_INIZIO_CONV,
        COALESCE(L.INTLCV_ANNO_INIZIO_RAPPORTO, A.ICV_ANNO_INIZIO) AS NM_ANNO_INIZIO,
        {{ custom_to_date('COALESCE(L.INTLCV_DATA_FINE_CNV, A.ICV_DATA_FINE_CONVENZIONE)', zero='max') }} AS DT_FINE_CONV,
        COALESCE(L.INTLCV_CAU_ANNULLO, A.ICV_CAU_ANNULLO) AS CD_CAUSALE_ANNULLO,
        COALESCE(L.INTLCV_AGENTE, A.ICV_AGENTE) AS CD_AGENTE_SA,
        COALESCE(L.INTLCV_RESPONSABILE, A.ICV_RESPONSABILE) AS CD_RESPONSABILE,
        COALESCE(L.INTLCV_GES_PV, A.ICV_PUNTI_VENDITA) AS FL_GESTIONE_PV,
        COALESCE(L.INTLCV_GES_VE, A.ICV_VENDITORI) AS FL_GESTIONE_VE,
        COALESCE(L.INTLCV_GES_VE_AGG, A.ICV_VENDITORI_AGG) AS FL_GESTIONE_VE_AGG,
        COALESCE(L.INTLCV_SETTORE_MERC, A.ICV_SETTORE_MERC) AS CD_SETTORE_MERC,
        COALESCE(L.INTLCV_INSEGNA, A.ICV_INSEGNA) AS DS_INSEGNA,
        {{ custom_to_decimal('COALESCE(L.INTLCV_PLAFOND, A.ICV_PLAFOND)') }} AS EU_PLAFOND,
        {{ custom_to_decimal('COALESCE(L.INTLCV_VOLUME_AFFARI, A.ICV_VOLUME_AFFARI)') }} AS EU_VOLUME_AFFARI,
        COALESCE(L.INTLCV_TIPO_RAPPORTO, A.ICV_TIPO_RAPPORTO) AS TP_RAPPORTO,
        COALESCE(L.INTLCV_PAGAMENTO_A_TERZI, A.ICV_PAGAMENTO_A_TERZO) AS FL_PAGA_TERZI,
        COALESCE(L.INTLCV_TERZO_DA_LIQ, A.ICV_TERZO_LIQ) AS CD_TERZO_LIQ,
        COALESCE(L.INTLCV_OBBL_DOC, A.ICV_OBB_LIQ) AS FL_OBB_DOC,
        L.LASTMODIFIEDDATA AS LASTMODIFIEDDATA,
        ROW_NUMBER() OVER (
            PARTITION BY L.INTLCV_INTERM, L.INTLCV_TIPO_INTERM, L.INTLCV_PROCEDURA, L.INTLCV_DATA, L.INTLCV_ORA
            ORDER BY L.ROWID
        )::NUMBER(38, 0) AS PR_PK
    FROM {{ ref('ccintlcv') }} L
    LEFT JOIN {{ ref('ccanaicv') }} A
        ON (
            L.INTLCV_INTERM      = A.ICV_CODICE
            AND L.INTLCV_TIPO_INTERM = A.ICV_TIPO_ANA
        )
    WHERE L.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        PR_PK,
        DT_INIZIO_CONV,
        NM_ANNO_INIZIO,
        DT_FINE_CONV,
        CD_CAUSALE_ANNULLO,
        CD_AGENTE_SA,
        CD_RESPONSABILE,
        FL_GESTIONE_PV,
        FL_GESTIONE_VE,
        FL_GESTIONE_VE_AGG,
        CD_SETTORE_MERC,
        DS_INSEGNA,
        EU_PLAFOND,
        EU_VOLUME_AFFARI,
        TP_RAPPORTO,
        FL_PAGA_TERZI,
        CD_TERZO_LIQ,
        FL_OBB_DOC,
        LASTMODIFIEDDATA,
        {{ hash_cols(['CD_INTERMEDIARIO', 'TP_INTERMEDIARIO', 'TP_PROCEDURA', 'DT_INIZIO_CONV', 'NM_ANNO_INIZIO', 'DT_FINE_CONV', 'CD_CAUSALE_ANNULLO', 'CD_AGENTE_SA', 'CD_RESPONSABILE', 'FL_GESTIONE_PV', 'FL_GESTIONE_VE', 'FL_GESTIONE_VE_AGG', 'CD_SETTORE_MERC', 'DS_INSEGNA', 'EU_PLAFOND', 'EU_VOLUME_AFFARI', 'TP_RAPPORTO', 'FL_PAGA_TERZI', 'CD_TERZO_LIQ', 'FL_OBB_DOC']) }} AS HASHED_COLS
    FROM base {{ is_incremental_S1('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', order_extra='PR_PK') }}
),

DEDUP_FV AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        --TS_FINE_VALIDITA,
        {{ ts_fine_validita('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', 'TS_INIZIO_VALIDITA') }} AS TS_FV_NEXT,
        PR_PK,
        DT_INIZIO_CONV,
        NM_ANNO_INIZIO,
        DT_FINE_CONV,
        CD_CAUSALE_ANNULLO,
        CD_AGENTE_SA,
        CD_RESPONSABILE,
        FL_GESTIONE_PV,
        FL_GESTIONE_VE,
        FL_GESTIONE_VE_AGG,
        CD_SETTORE_MERC,
        DS_INSEGNA,
        EU_PLAFOND,
        EU_VOLUME_AFFARI,
        TP_RAPPORTO,
        FL_PAGA_TERZI,
        CD_TERZO_LIQ,
        FL_OBB_DOC,
        LASTMODIFIEDDATA      
    FROM dedup 
)

SELECT
    H.CD_INTERMEDIARIO,
    H.TP_INTERMEDIARIO,
    H.TP_PROCEDURA,
    H.TS_INIZIO_VALIDITA,
    MAX(H.TS_FV_NEXT) OVER (
        PARTITION BY H.CD_INTERMEDIARIO, H.TP_INTERMEDIARIO, H.TP_PROCEDURA, H.TS_INIZIO_VALIDITA
    ) AS TS_FINE_VALIDITA,
    H.PR_PK,
    H.DT_INIZIO_CONV,
    H.NM_ANNO_INIZIO,
    H.DT_FINE_CONV,
    H.CD_CAUSALE_ANNULLO,
    H.CD_AGENTE_SA,
    H.CD_RESPONSABILE,
    H.FL_GESTIONE_PV,
    H.FL_GESTIONE_VE,
    H.FL_GESTIONE_VE_AGG,
    H.CD_SETTORE_MERC,
    H.DS_INSEGNA,
    H.EU_PLAFOND,
    H.EU_VOLUME_AFFARI,
    H.TP_RAPPORTO,
    H.FL_PAGA_TERZI,
    H.CD_TERZO_LIQ,
    H.FL_OBB_DOC,
    H.LASTMODIFIEDDATA
FROM DEDUP_FV AS H
