-- Anagrafica intermediari rete vendita con storicizzazione SCD2 S1 da CCINTLRV e CCANAINRV
-- Co-authored with CoCo
-- WARN: storicizzazione N/A nel catalog, inferita S1 da presenza di TS_INIZIO_VALIDITA in PK

WITH base AS (
    SELECT
        COALESCE(L.INTLRV_INTERM, A.IRV_CODICE) AS CD_INTERMEDIARIO,
        COALESCE(L.INTLRV_TIPO_INTERM, A.IRV_TIPO_ANA) AS TP_INTERMEDIARIO,
        COALESCE(L.INTLRV_PROCEDURA, 'NA') AS TP_PROCEDURA,
        {{ custom_to_timestamp_ntz('L.INTLRV_DATA', 'L.INTLRV_ORA') }} AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita(
            "COALESCE(L.INTLRV_INTERM, A.IRV_CODICE), COALESCE(L.INTLRV_TIPO_INTERM, A.IRV_TIPO_ANA), COALESCE(L.INTLRV_PROCEDURA, 'NA')",
            custom_to_timestamp_ntz('L.INTLRV_DATA', 'L.INTLRV_ORA')
        ) }} AS TS_FINE_VALIDITA,
        COALESCE(L.INTLRV_CAU_ANNULLO, A.IRV_CAU_ANNULLO) AS CD_CAUSALE_ANNULLO,
        COALESCE(L.INTLRV_GEST_AG, A.IRV_AGENTI) AS FL_GESTIONE_AGENTI,
        COALESCE(L.INTLRV_SETTORE_MERC, A.IRV_SETTORE_MERC) AS CD_SETTORE_MERC,
        COALESCE(L.INTLRV_RESPONSABILE_AP, A.IRV_RESPONSABILE_AP) AS CD_RESP_PARTNER,
        COALESCE(L.INTLRV_RESPONSABILE_AC, A.IRV_RESPONSABILE_AC) AS CD_RESP_CREDITO,
        COALESCE(L.INTLRV_RESPONSABILE_IT, A.IRV_RESPONSABILE_IT) AS CD_RESP_IT,
        COALESCE(L.INTLRV_RESPONSABILE_MK, A.IRV_RESPONSABILE_MK) AS CD_RESP_MARKETING,
        COALESCE(L.INTLRV_RESPONSABILE_AL, A.IRV_RESPONSABILE_AL) AS CD_RESP_LEGALE,
        L.LASTMODIFIEDDATA AS LASTMODIFIEDDATA,
        ROW_NUMBER() OVER (
            PARTITION BY L.INTLRV_INTERM, L.INTLRV_TIPO_INTERM, L.INTLRV_PROCEDURA, L.INTLRV_DATA, L.INTLRV_ORA
            ORDER BY L.ROWID
        )::NUMBER(38, 0) AS PR_PK
    FROM {{ ref('ccintlrv') }} L
    --LEFT JOIN AGOS_DEV_16000.L0.CCANAIRV A
    LEFT JOIN {{ ref('ccanairv') }} A
        ON (
            L.INTLRV_INTERM      = A.IRV_CODICE
            AND L.INTLRV_TIPO_INTERM = A.IRV_TIPO_ANA
        )
    WHERE L.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        PR_PK,
        CD_CAUSALE_ANNULLO,
        FL_GESTIONE_AGENTI,
        CD_SETTORE_MERC,
        CD_RESP_PARTNER,
        CD_RESP_CREDITO,
        CD_RESP_IT,
        CD_RESP_MARKETING,
        CD_RESP_LEGALE,
        LASTMODIFIEDDATA,
        {{ hash_cols(['CD_INTERMEDIARIO', 'TP_INTERMEDIARIO', 'TP_PROCEDURA', 'CD_CAUSALE_ANNULLO', 'FL_GESTIONE_AGENTI', 'CD_SETTORE_MERC', 'CD_RESP_PARTNER', 'CD_RESP_CREDITO', 'CD_RESP_IT', 'CD_RESP_MARKETING', 'CD_RESP_LEGALE']) }} AS HASHED_COLS
    FROM base {{ is_incremental_S1('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', order_extra='PR_PK') }}
),

DEDUP_FV AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        --TS_FINE_VALIDITA,
        {{ ts_fine_validita('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', 'TS_INIZIO_VALIDITA') }} AS TS_FV_NEXT,
        PR_PK,
        CD_CAUSALE_ANNULLO,
        FL_GESTIONE_AGENTI,
        CD_SETTORE_MERC,
        CD_RESP_PARTNER,
        CD_RESP_CREDITO,
        CD_RESP_IT,
        CD_RESP_MARKETING,
        CD_RESP_LEGALE,
        LASTMODIFIEDDATA    
    FROM dedup 
)

SELECT
    H.CD_INTERMEDIARIO,
    H.TP_INTERMEDIARIO,
    H.TP_PROCEDURA,
    H.TS_INIZIO_VALIDITA,
    MAX(H.TS_FV_NEXT) OVER (
        PARTITION BY H.CD_INTERMEDIARIO, H.TP_INTERMEDIARIO, H.TP_PROCEDURA, H.TS_INIZIO_VALIDITA
    ) AS TS_FINE_VALIDITA,
    H.PR_PK,
    H.CD_CAUSALE_ANNULLO,
    H.FL_GESTIONE_AGENTI,
    H.CD_SETTORE_MERC,
    H.CD_RESP_PARTNER,
    H.CD_RESP_CREDITO,
    H.CD_RESP_IT,
    H.CD_RESP_MARKETING,
    H.CD_RESP_LEGALE,
    H.LASTMODIFIEDDATA
FROM DEDUP_FV H