-- WARN: DS_DISTRETTO_FILIALE - RT contiene 'FROM CCANATFI LEFT JOIN CCANATFI' (doppio alias su stessa tabella);
--       interpretato come 'FROM CCANATFI LEFT JOIN CCANATDI' in base alla chiave di aggancio e al campo sorgente.
--       FIX: data model had 'FROM CCANATFI LEFT JOIN CCANATFI ON ( CCANATFI.ANATFI_DISTRETTO = CCANATDI.ANATDI_DISTRETTO )'
-- WARN: CD_ REPOSNSABILE - nome campo con spazio e probabile typo ("REPOSNSABILE"); trascritto as-is dal data model.
--       Nessun TAB/COL/RT definiti: valorizzato NULL.
 
SELECT
    T.ANATFI_FILIALE AS CD_FILIALE,
    T.ANATFI_DESCRIZIONE AS DS_FILIALE,
    T.ANATFI_DISTRETTO AS CD_DISTRETTO_FILIALE,
    DI.ANATDI_DESCRIZIONE AS DS_DISTRETTO_FILIALE,
    T.ANATFI_AREA AS CD_AREA_FILIALE,
    AR.TABARE_DESCRIZIONE AS DS_AREA_FILIALE,
    T.ANATFI_VIRTUALE AS FL_VIRTUALE_FILIALE,
    T.ANATFI_ABIL_WEB AS FL_ABILITAZIONE_WEB_FILIALE
FROM {{ ref('ccanatfi') }} T
LEFT JOIN {{ ref('ccanatdi') }} DI
    ON T.ANATFI_DISTRETTO = DI.ANATDI_DISTRETTO
    AND DI.FL_DELETED = 'N'
    AND DI.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
LEFT JOIN {{ ref('cctabare') }} AR
    ON T.ANATFI_AREA = AR.TABARE_AREA
    AND AR.FL_DELETED = 'N'
    AND AR.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')