-- Anagrafica intermediari punto vendita con storicizzazione SCD2 S1 da CCINTLPV e CCANAINPV
-- Co-authored with CoCo
-- WARN: storicizzazione N/A nel catalog, inferita S1 da presenza di TS_INIZIO_VALIDITA in PK
-- FIX: data model had 'TS_INIZIO VALIDITA' (con spazio) → rinominato TS_INIZIO_VALIDITA

WITH base AS (
    SELECT
        COALESCE(L.INTLPV_INTERM, A.IPV_CODICE) AS CD_INTERMEDIARIO,
        COALESCE(L.INTLPV_TIPO_INTERM, A.IPV_TIPO_ANA) AS TP_INTERMEDIARIO,
        COALESCE(L.INTLPV_PROCEDURA, 'NA') AS TP_PROCEDURA,
        {{ custom_to_timestamp_ntz('L.INTLPV_DATA', 'L.INTLPV_ORA') }} AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita(
            "COALESCE(L.INTLPV_INTERM, A.IPV_CODICE), COALESCE(L.INTLPV_TIPO_INTERM, A.IPV_TIPO_ANA), COALESCE(L.INTLPV_PROCEDURA, 'NA')",
            custom_to_timestamp_ntz('L.INTLPV_DATA', 'L.INTLPV_ORA')
        ) }} AS TS_FINE_VALIDITA,
        COALESCE(L.INTLPV_ANNO_INIZIO_RAPPORTO, A.IPV_ANNO_INIZIO) AS NM_ANNO_INIZIO,
        {{ custom_to_date('COALESCE(L.INTLPV_DATA_INIZIO_CNV, A.IPV_DATA_CONVENZIONE)',zero='min') }} AS DT_INIZIO_CONV,
        COALESCE(L.INTLPV_CAU_ANNULLO, A.IPV_CAU_ANNULLO) AS CD_CAUSALE_ANNULLO,
        COALESCE(L.INTLPV_CONVENZIONATO, A.IPV_CONVENZIONATO) AS CD_CONVENZIONATO,
        COALESCE(L.INTLPV_AGENTE, A.IPV_AGENTE) AS CD_AGENTE,
        COALESCE(L.INTLPV_RESPONSABILE, A.IPV_RESPONSABILE) AS CD_RESPONSABILE,
        COALESCE(L.INTLPV_GES_VE, A.IPV_VENDITORI) AS FL_GESTIONE_VE,
        COALESCE(L.INTLPV_GES_VE_AGG, A.IPV_VENDITORI_AGG) AS FL_GESTIONE_VE_AGG,
        COALESCE(L.INTLPV_SETTORE_MERC, A.IPV_SETTORE_MERC) AS CD_SETTORE_MERC,
        COALESCE(L.INTLPV_INSEGNA, A.IPV_INSEGNA) AS DS_INSEGNA,
        COALESCE(L.INTLPV_FATT_CONTRIBUTI, A.IPV_FATTURA_CONTRIBUTI) AS CD_FATT_CONTRIBUTI,
        {{ custom_to_decimal('COALESCE(L.INTLPV_PLAFOND, A.IPV_PLAFOND)') }} AS EU_PLAFOND,
        {{ custom_to_decimal('COALESCE(L.INTLPV_VOLUME_AFFARI, A.IPV_VOLUME_AFFARI)') }} AS EU_VOLUME_AFFARI,
        L.LASTMODIFIEDDATA AS LASTMODIFIEDDATA,
        ROW_NUMBER() OVER (
            PARTITION BY L.INTLPV_INTERM, L.INTLPV_TIPO_INTERM, L.INTLPV_PROCEDURA, L.INTLPV_DATA, L.INTLPV_ORA
            ORDER BY L.ROWID
        )::NUMBER(38, 0) AS PR_PK
    FROM {{ ref('ccintlpv') }} L
    LEFT JOIN {{ ref('ccanaipv') }} A
        ON (
            L.INTLPV_INTERM      = A.IPV_CODICE
            AND L.INTLPV_TIPO_INTERM = A.IPV_TIPO_ANA
        )
    WHERE L.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        PR_PK,
        NM_ANNO_INIZIO,
        DT_INIZIO_CONV,
        CD_CAUSALE_ANNULLO,
        CD_CONVENZIONATO,
        CD_AGENTE,
        CD_RESPONSABILE,
        FL_GESTIONE_VE,
        FL_GESTIONE_VE_AGG,
        CD_SETTORE_MERC,
        DS_INSEGNA,
        CD_FATT_CONTRIBUTI,
        EU_PLAFOND,
        EU_VOLUME_AFFARI,
        LASTMODIFIEDDATA,
        {{ hash_cols(['CD_INTERMEDIARIO', 'TP_INTERMEDIARIO', 'TP_PROCEDURA', 'NM_ANNO_INIZIO', 'DT_INIZIO_CONV', 'CD_CAUSALE_ANNULLO', 'CD_CONVENZIONATO', 'CD_AGENTE', 'CD_RESPONSABILE', 'FL_GESTIONE_VE', 'FL_GESTIONE_VE_AGG', 'CD_SETTORE_MERC', 'DS_INSEGNA', 'CD_FATT_CONTRIBUTI', 'EU_PLAFOND', 'EU_VOLUME_AFFARI']) }} AS HASHED_COLS
    FROM base {{ is_incremental_S1('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', order_extra='PR_PK') }}
),

DEDUP_FV AS ( 
   SELECT CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA, 
       {{ ts_fine_validita('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', 'TS_INIZIO_VALIDITA') }} AS TS_FV_NEXT,
       PR_PK,
        NM_ANNO_INIZIO,
        DT_INIZIO_CONV,
        CD_CAUSALE_ANNULLO,
        CD_CONVENZIONATO,
        CD_AGENTE,
        CD_RESPONSABILE,
        FL_GESTIONE_VE,
        FL_GESTIONE_VE_AGG,
        CD_SETTORE_MERC,
        DS_INSEGNA,
        CD_FATT_CONTRIBUTI,
        EU_PLAFOND,
        EU_VOLUME_AFFARI,
        LASTMODIFIEDDATA 
   FROM dedup
)


SELECT
    H.CD_INTERMEDIARIO,
    H.TP_INTERMEDIARIO,
    H.TP_PROCEDURA,
    H.TS_INIZIO_VALIDITA,
    MAX(H.TS_FV_NEXT) OVER (
        PARTITION BY H.CD_INTERMEDIARIO, H.TP_INTERMEDIARIO, H.TP_PROCEDURA, H.TS_INIZIO_VALIDITA
    ) AS TS_FINE_VALIDITA,
    H.PR_PK,
    H.NM_ANNO_INIZIO,
    H.DT_INIZIO_CONV,
    H.CD_CAUSALE_ANNULLO,
    H.CD_CONVENZIONATO,
    H.CD_AGENTE,
    H.CD_RESPONSABILE,
    H.FL_GESTIONE_VE,
    H.FL_GESTIONE_VE_AGG,
    H.CD_SETTORE_MERC,
    H.DS_INSEGNA,
    H.CD_FATT_CONTRIBUTI,
    H.EU_PLAFOND,
    H.EU_VOLUME_AFFARI,
    H.LASTMODIFIEDDATA
FROM DEDUP_FV H