-- Anagrafica intermediari subagenti con storicizzazione SCD2 S1 da CCINTLSA e CCANAINSA
-- Co-authored with CoCo
-- WARN: storicizzazione N/A nel catalog, inferita S1 da presenza di TS_INIZIO_VALIDITA in PK
-- FIX: data model had 'TS_INIZIO VALIDITA' (con spazio) → rinominato TS_INIZIO_VALIDITA
-- WARN: FL_GESTIONE_VE e CD_RESPONSABILE hanno TAB/COL invertite nel data model — seguite RT come fonte autoritativa

WITH base AS ( 
    SELECT
        COALESCE(L.INTLSA_INTERM, A.ISA_CODICE) AS CD_INTERMEDIARIO,
        COALESCE(L.INTLSA_TIPO_INTERM, A.ISA_TIPO_ANA) AS TP_INTERMEDIARIO,
        COALESCE(L.INTLSA_PROCEDURA, 'NA') AS TP_PROCEDURA,
        {{ custom_to_timestamp_ntz('L.INTLSA_DATA', 'L.INTLSA_ORA') }} AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita(
            "COALESCE(L.INTLSA_INTERM, A.ISA_CODICE), COALESCE(L.INTLSA_TIPO_INTERM, A.ISA_TIPO_ANA), COALESCE(L.INTLSA_PROCEDURA, 'NA')",
            custom_to_timestamp_ntz('L.INTLSA_DATA', 'L.INTLSA_ORA')
        ) }} AS TS_FINE_VALIDITA,
        {{ custom_to_date('COALESCE(L.INTLSA_DATA_INIZIO_CONV, A.ISA_DATA_CONVENZIONE)', zero='min') }} AS DT_INIZIO_CONV,
        {{ custom_to_date('COALESCE(L.INTLSA_DATA_FINE_CONV, A.ISA_DATA_FINE_CONVENZIONE)', zero = 'max') }} AS DT_FINE_CONV,
        COALESCE(L.INTLSA_CAU_ANNULLO, A.ISA_CAU_ANNULLO) AS CD_CAUSALE_ANNULLO,
        COALESCE(L.INTLSA_AGENTE, A.ISA_AGENTE) AS CD_AGENTE,
        COALESCE(L.INTLSA_RESPONSABILE, A.ISA_RESPONSABILE) AS CD_RESPONSABILE,
        COALESCE(L.INTLSA_GEST_VE, A.ISA_VENDITORI) AS FL_GESTIONE_VE,
        L.LASTMODIFIEDDATA AS LASTMODIFIEDDATA,
        ROW_NUMBER() OVER (
            PARTITION BY L.INTLSA_INTERM, L.INTLSA_TIPO_INTERM, L.INTLSA_PROCEDURA, L.INTLSA_DATA, L.INTLSA_ORA
            ORDER BY L.ROWID
        )::NUMBER(38, 0) AS PR_PK
    FROM {{ ref('ccintlsa') }} L 
    LEFT JOIN {{ ref('ccanaisa') }} A
    --LEFT JOIN AGOS_DEV_16000.L0.CCANAISA A
        ON (
            L.INTLSA_INTERM = A.ISA_CODICE
            AND L.INTLSA_TIPO_INTERM = A.ISA_TIPO_ANA
        )
    WHERE L.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        PR_PK,
        DT_INIZIO_CONV,
        DT_FINE_CONV,
        CD_CAUSALE_ANNULLO,
        CD_AGENTE,
        FL_GESTIONE_VE,
        CD_RESPONSABILE,
        LASTMODIFIEDDATA,      
        {{ hash_cols(['CD_INTERMEDIARIO', 'TP_INTERMEDIARIO', 'TP_PROCEDURA', 'DT_INIZIO_CONV', 'DT_FINE_CONV', 'CD_CAUSALE_ANNULLO', 'CD_AGENTE',  'FL_GESTIONE_VE', 'CD_RESPONSABILE']) }} AS HASHED_COLS
    FROM base {{ is_incremental_S1('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', order_extra='PR_PK') }}
),

DEDUP_FV AS (
    SELECT
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        --TS_FINE_VALIDITA,
        {{ ts_fine_validita('CD_INTERMEDIARIO, TP_INTERMEDIARIO, TP_PROCEDURA', 'TS_INIZIO_VALIDITA') }} AS TS_FV_NEXT,
        PR_PK,
        DT_INIZIO_CONV,
        DT_FINE_CONV,
        CD_CAUSALE_ANNULLO,
        CD_AGENTE,
        FL_GESTIONE_VE,
        CD_RESPONSABILE,
        LASTMODIFIEDDATA      
    FROM dedup 
)

SELECT
    H.CD_INTERMEDIARIO,
    H.TP_INTERMEDIARIO,
    H.TP_PROCEDURA,
    H.TS_INIZIO_VALIDITA,
    MAX(H.TS_FV_NEXT) OVER (
        PARTITION BY H.CD_INTERMEDIARIO, H.TP_INTERMEDIARIO, H.TP_PROCEDURA, H.TS_INIZIO_VALIDITA
    ) AS TS_FINE_VALIDITA,
    H.PR_PK,
    H.DT_INIZIO_CONV,
    H.DT_FINE_CONV,
    H.CD_CAUSALE_ANNULLO,
    H.CD_AGENTE,
    H.FL_GESTIONE_VE,
    H.CD_RESPONSABILE,
    H.LASTMODIFIEDDATA
FROM DEDUP_FV AS H