-- PROPOSTA: riscrittura di raw/dwh-code/models/L2/ANAGR_CONTROPARTE/indirizzi_postalizzazione.sql
-- Vedi queries/ottimizzazione-indirizzi-postalizzazione-scd2.md per il contesto.
-- Non testata su dati reali. Config (materialized/incremental_strategy/unique_key/pre_hook)
-- resta quella di indirizzi_postalizzazione.yml, invariata.

WITH COMBINED AS (
    -- ramo 1: righe nuove/modificate dal source (solo il delta)
    SELECT
        AG.BAAG_PRATICA AS CD_PRATICA,
        AG.BAAG_PROCEDURA AS TP_PROCEDURA,
        AG.TS_INIZIO_VALIDITA,
        AG.BAAG_COINTESTAZ AS CD_COOINTESTATO,
        AG.BAAG_COR_RAG_SOCIALE_1 AS CD_RAG_SOCIALE_1,
        AG.BAAG_COR_RAG_SOCIALE_2 AS CD_RAG_SOCIALE_2,
        AG.BAAG_COR_INDIRIZZO_1 AS DS_COR_INDIRIZZO_1,
        AG.BAAG_COR_INDIRIZZO_2 AS DS_COR_INDIRIZZO_2,
        AG.BAAG_COR_LOCALITA AS DS_COR_COMUNE,
        AG.BAAG_COR_CAB_COMUNE AS CD_CAB_COMUNE,
        AG.BAAG_COR_NAZIONE AS CD_COR_NAZIONE,
        AG.BAAG_COR_CAP AS CD_COR_CAP,
        AG.BAAG_COR_PROVINCIA AS CD_COR_PROVINCIA,
        AG.BAAG_COR_TELEFONO_CEL AS NM_COR_TELEFONO_CEL,
        AG.BAAG_COR_EMAIL AS DS_COR_EMAIL,
        AG.BAAG_MOD_INVIO_TRASP_CL AS TP_INVIO_TRASP_CL,
        AG.BAAG_MOD_INVIO_TRASP_CO AS TP_INVIO_TRASP_COOB_1,
        AG.BAAG_MOD_INVIO_TRASP_C2 AS TP_INVIO_TRASP_COOB_2,
        AG.BAAG_MOD_INVIO_TRASP_C3 AS TP_INVIO_TRASP_COOB_3,
        AG.BAAG_MOD_INVIO_TRASP_C4 AS TP_INVIO_TRASP_COOB_4,
        AG.BAAG_MOD_INVIO_TRASP_C5 AS TP_INVIO_TRASP_COOB_5,
        AG.BAAG_MOD_INVIO_TRASP_G1 AS TP_INVIO_TRASP_GAR_1,
        AG.BAAG_MOD_INVIO_TRASP_G2 AS TP_INVIO_TRASP_GAR_2,
        AG.BAAG_MOD_INVIO_TRASP_G3 AS TP_INVIO_TRASP_GAR_3,
        AG.BAAG_RIF_CIG AS CD_RIFERIMENTO_CIG,
        AG.BAAG_RIF_CUP AS CD_RIFERIMENTO_CUP,
        AG.BAAG_NOTE AS DS_NOTE,
        AG.BAAG_UTENTE_VAR AS CD_UTENTE_VAR,
        {{ custom_to_date('AG.BAAG_DATA_VAR') }} AS DT_VARIAZIONE,
        {{ custom_to_time('AG.BAAG_ORA_VAR') }} AS NM_ORA_VARIAZIONE,
        AG.BAAG_CONFERMA_DATI AS TP_CONFERMA_DATI,
        AG.LASTMODIFIEDDATA,
        CAST(NULL AS TIMESTAMP_NTZ) AS OLD_TS_FINE_VALIDITA,
        FALSE AS IS_EXISTING
    FROM {{ ref('bapratag') }} AS AG
    WHERE AG.FL_DELETED = 'N'
    {% if is_incremental() %}
    AND AG.LASTMODIFIEDDATA > (
        SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }}
    )

    UNION ALL

    -- ramo 2: riga aperta nel target per le pratiche toccate dal ramo 1
    SELECT
        T.CD_PRATICA,
        T.TP_PROCEDURA,
        T.TS_INIZIO_VALIDITA,
        T.CD_COOINTESTATO,
        T.CD_RAG_SOCIALE_1,
        T.CD_RAG_SOCIALE_2,
        T.DS_COR_INDIRIZZO_1,
        T.DS_COR_INDIRIZZO_2,
        T.DS_COR_COMUNE,
        T.CD_CAB_COMUNE,
        T.CD_COR_NAZIONE,
        T.CD_COR_CAP,
        T.CD_COR_PROVINCIA,
        T.NM_COR_TELEFONO_CEL,
        T.DS_COR_EMAIL,
        T.TP_INVIO_TRASP_CL,
        T.TP_INVIO_TRASP_COOB_1,
        T.TP_INVIO_TRASP_COOB_2,
        T.TP_INVIO_TRASP_COOB_3,
        T.TP_INVIO_TRASP_COOB_4,
        T.TP_INVIO_TRASP_COOB_5,
        T.TP_INVIO_TRASP_GAR_1,
        T.TP_INVIO_TRASP_GAR_2,
        T.TP_INVIO_TRASP_GAR_3,
        T.CD_RIFERIMENTO_CIG,
        T.CD_RIFERIMENTO_CUP,
        T.DS_NOTE,
        T.CD_UTENTE_VAR,
        T.DT_VARIAZIONE,
        T.NM_ORA_VARIAZIONE,
        T.TP_CONFERMA_DATI,
        T.LASTMODIFIEDDATA,
        T.TS_FINE_VALIDITA AS OLD_TS_FINE_VALIDITA,
        TRUE AS IS_EXISTING
    FROM {{ this }} AS T
    WHERE T.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
      AND (T.CD_PRATICA, T.TP_PROCEDURA) IN (
          SELECT DISTINCT AG2.BAAG_PRATICA, AG2.BAAG_PROCEDURA
          FROM {{ ref('bapratag') }} AS AG2
          WHERE AG2.FL_DELETED = 'N'
            AND AG2.LASTMODIFIEDDATA > (
                SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }}
            )
      )
    {% endif %}
),

DEDUP AS (
    SELECT
        CD_PRATICA,
        TP_PROCEDURA,
        TS_INIZIO_VALIDITA,
        CD_COOINTESTATO,
        CD_RAG_SOCIALE_1,
        CD_RAG_SOCIALE_2,
        DS_COR_INDIRIZZO_1,
        DS_COR_INDIRIZZO_2,
        DS_COR_COMUNE,
        CD_CAB_COMUNE,
        CD_COR_NAZIONE,
        CD_COR_CAP,
        CD_COR_PROVINCIA,
        NM_COR_TELEFONO_CEL,
        DS_COR_EMAIL,
        TP_INVIO_TRASP_CL,
        TP_INVIO_TRASP_COOB_1,
        TP_INVIO_TRASP_COOB_2,
        TP_INVIO_TRASP_COOB_3,
        TP_INVIO_TRASP_COOB_4,
        TP_INVIO_TRASP_COOB_5,
        TP_INVIO_TRASP_GAR_1,
        TP_INVIO_TRASP_GAR_2,
        TP_INVIO_TRASP_GAR_3,
        CD_RIFERIMENTO_CIG,
        CD_RIFERIMENTO_CUP,
        DS_NOTE,
        CD_UTENTE_VAR,
        DT_VARIAZIONE,
        NM_ORA_VARIAZIONE,
        TP_CONFERMA_DATI,
        LASTMODIFIEDDATA,
        OLD_TS_FINE_VALIDITA,
        IS_EXISTING,
        {{ hash_cols(['CD_PRATICA','TP_PROCEDURA','CD_COOINTESTATO','CD_RAG_SOCIALE_1','CD_RAG_SOCIALE_2','DS_COR_INDIRIZZO_1','DS_COR_INDIRIZZO_2','DS_COR_COMUNE','CD_CAB_COMUNE','CD_COR_NAZIONE','CD_COR_CAP','CD_COR_PROVINCIA','NM_COR_TELEFONO_CEL','DS_COR_EMAIL','TP_INVIO_TRASP_CL','TP_INVIO_TRASP_COOB_1','TP_INVIO_TRASP_COOB_2','TP_INVIO_TRASP_COOB_3','TP_INVIO_TRASP_COOB_4','TP_INVIO_TRASP_COOB_5','TP_INVIO_TRASP_GAR_1','TP_INVIO_TRASP_GAR_2','TP_INVIO_TRASP_GAR_3','CD_RIFERIMENTO_CIG','CD_RIFERIMENTO_CUP','DS_NOTE','CD_UTENTE_VAR','DT_VARIAZIONE','NM_ORA_VARIAZIONE','TP_CONFERMA_DATI']) }}
            AS HASHED_COLS
    FROM COMBINED
    QUALIFY HASHED_COLS IS DISTINCT FROM LAG(HASHED_COLS) OVER (
        PARTITION BY CD_PRATICA, TP_PROCEDURA ORDER BY TS_INIZIO_VALIDITA
    )
),

DEDUP_FV AS (
    SELECT
        D.*,
        {{ ts_fine_validita('CD_PRATICA, TP_PROCEDURA', 'TS_INIZIO_VALIDITA') }}
            AS TS_FV_NEXT
    FROM DEDUP AS D
)

SELECT
    H.CD_PRATICA,
    H.TP_PROCEDURA,
    H.TS_INIZIO_VALIDITA,
    MAX(H.TS_FV_NEXT) OVER (
        PARTITION BY H.CD_PRATICA, H.TP_PROCEDURA, H.TS_INIZIO_VALIDITA
    ) AS TS_FINE_VALIDITA,
    H.CD_COOINTESTATO,
    H.CD_RAG_SOCIALE_1,
    H.CD_RAG_SOCIALE_2,
    H.DS_COR_INDIRIZZO_1,
    H.DS_COR_INDIRIZZO_2,
    H.DS_COR_COMUNE,
    H.CD_CAB_COMUNE,
    H.CD_COR_NAZIONE,
    H.CD_COR_CAP,
    H.CD_COR_PROVINCIA,
    H.NM_COR_TELEFONO_CEL,
    H.DS_COR_EMAIL,
    H.TP_INVIO_TRASP_CL,
    H.TP_INVIO_TRASP_COOB_1,
    H.TP_INVIO_TRASP_COOB_2,
    H.TP_INVIO_TRASP_COOB_3,
    H.TP_INVIO_TRASP_COOB_4,
    H.TP_INVIO_TRASP_COOB_5,
    H.TP_INVIO_TRASP_GAR_1,
    H.TP_INVIO_TRASP_GAR_2,
    H.TP_INVIO_TRASP_GAR_3,
    H.CD_RIFERIMENTO_CIG,
    H.CD_RIFERIMENTO_CUP,
    H.DS_NOTE,
    H.CD_UTENTE_VAR,
    H.DT_VARIAZIONE,
    H.NM_ORA_VARIAZIONE,
    H.TP_CONFERMA_DATI,
    H.LASTMODIFIEDDATA
FROM DEDUP_FV AS H
{%- if is_incremental() %}
QUALIFY NOT (H.IS_EXISTING AND H.TS_FV_NEXT = H.OLD_TS_FINE_VALIDITA)
{%- endif %}
