WITH CTE_MA AS (

    SELECT
        CD_CONTROPARTE,
        CD_CONTROPARTE_DI
    FROM {{ ref('legame_ditte_individuali') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CD_CONTROPARTE_DI ORDER BY TS_INSERIMENTO DESC) = 1

),

CTE_TRUFFE AS (

    SELECT
        CD_PRATICA,
        TP_PROCEDURA,
        MIN(TO_DATE(TS_INSERIMENTO)) AS DT_INSERIMENTO  --lascerei TO_DATE poichè non rientra nei casi della macro essendo TS_INSERIMENTO un timestamp NTZ
    FROM {{ ref('gestione_truffe') }}
    WHERE FL_SUBITA = 'S' OR FL_SVENTATA = 'S'
    GROUP BY CD_PRATICA, TP_PROCEDURA  

),

BASE AS (

    SELECT
        'GESTIONALE' AS TP_SALDO,
        CD_PRATICA,
        TP_PROCEDURA,
        CD_PRATICA_CLIENTE,
        CD_CONTROPARTE,
        DT_OSSERVAZIONE,
        NULL AS EU_ON_BALANCE,
        EU_IMPIEGO_GESTIONALE,
        EU_CAPITALE_SCADERE,
        EU_INTERESSI_SCADERE,
        EU_SPESE_SCADERE,
        EU_CAPITALE_SCADUTO,
        EU_INTERESSI_SCADUTO,
        EU_SPESE,
        EU_MORA,
        EU_SALDO_AVERE,
        EU_ANTICIPI_EROGATI,
        EU_PAG_ESUB_NON_ALLOCATI,
        EU_INTERESSI_MATURATI_SCADERE,
        EU_RATEO,
        EU_RISCONTI,
        EU_RISCONTI_ALTRI,
        EU_RISCONTI_INTERESSI
    FROM {{ ref('saldo_gestionale_m') }}
    {% if is_incremental() %}
    WHERE DT_OSSERVAZIONE = {{ last_day_past_month() }}  /* ci entra dalla seconda volta che gira il modello */
    {% endif %}


    UNION ALL


    SELECT
        'CONTABILE' AS TP_SALDO,
        CD_PRATICA,
        TP_PROCEDURA,
        CD_PRATICA_CLIENTE,
        CD_CONTROPARTE,
        DT_OSSERVAZIONE,
        EU_ON_BALANCE,
        NULL AS EU_IMPIEGO_GESTIONALE,
        EU_CAPITALE_SCADERE,
        EU_INTERESSI_SCADERE,
        EU_SPESE_SCADERE,
        EU_CAPITALE_SCADUTO,
        EU_INTERESSI_SCADUTO,
        EU_SPESE,
        EU_MORA,
        EU_SALDO_AVERE,
        EU_ANTICIPI_EROGATI,
        EU_PAG_ESUB_NON_ALLOCATI,
        EU_INTERESSI_MATURATI_SCADERE,
        EU_RATEO,
        EU_RISCONTI,
        EU_RISCONTI_ALTRI,
        EU_RISCONTI_INTERESSI
    FROM {{ ref('saldo_contabile_m') }}
    {% if is_incremental() %}
    WHERE DT_OSSERVAZIONE = {{ last_day_past_month() }}
    {% endif %}

)

SELECT
    B.TP_SALDO,
    B.CD_PRATICA,
    B.TP_PROCEDURA,
    B.CD_PRATICA_CLIENTE,
    TO_NUMBER(B.CD_CONTROPARTE) AS CD_CONTROPARTE,
    COALESCE(MA.CD_CONTROPARTE, TO_NUMBER(B.CD_CONTROPARTE)) AS CD_CONTROPARTE_CLIENTE,
    B.DT_OSSERVAZIONE,
    B.EU_ON_BALANCE,
    B.EU_IMPIEGO_GESTIONALE,
    B.EU_CAPITALE_SCADERE,
    B.EU_INTERESSI_SCADERE,
    B.EU_SPESE_SCADERE,
    B.EU_CAPITALE_SCADUTO,
    B.EU_INTERESSI_SCADUTO,
    B.EU_SPESE,
    B.EU_MORA,
    B.EU_SALDO_AVERE,
    B.EU_ANTICIPI_EROGATI,
    B.EU_PAG_ESUB_NON_ALLOCATI,
    B.EU_INTERESSI_MATURATI_SCADERE,
    B.EU_RATEO,
    B.EU_RISCONTI,
    B.EU_RISCONTI_ALTRI,
    B.EU_RISCONTI_INTERESSI,
    CASE WHEN TR.CD_PRATICA IS NOT NULL THEN 'S' ELSE 'N' END AS FL_TRUFFA
FROM BASE B
LEFT JOIN CTE_MA MA
    ON TO_NUMBER(B.CD_CONTROPARTE) = MA.CD_CONTROPARTE_DI
LEFT JOIN CTE_TRUFFE TR
    ON B.CD_PRATICA = TR.CD_PRATICA
    AND B.TP_PROCEDURA = TR.TP_PROCEDURA
	AND B.DT_OSSERVAZIONE >= TR.DT_INSERIMENTO

