WITH TRUFFE AS (

    SELECT
        CD_PRATICA,
        TP_PROCEDURA,
        TO_DATE(TS_INSERIMENTO) AS DT_INSERIMENTO
    FROM {{ ref('gestione_truffe') }}
    WHERE FL_SUBITA = 'S' OR FL_SVENTATA = 'S'

),

BASE AS (

    SELECT
        'GESTIONALE' AS TP_SALDO,
        G.CD_PRATICA_CLIENTE,
        G.TP_PROCEDURA,
        G.DT_OSSERVAZIONE,
        0 AS EU_ON_BALANCE,
        G.EU_IMPIEGO_GESTIONALE,
        G.EU_CAPITALE_SCADERE,
        G.EU_INTERESSI_SCADERE,
        G.EU_SPESE_SCADERE,
        G.EU_CAPITALE_SCADUTO,
        G.EU_INTERESSI_SCADUTO,
        G.EU_SPESE,
        G.EU_MORA,
        G.EU_SALDO_AVERE,
        G.EU_ANTICIPI_EROGATI,
        G.EU_PAG_ESUB_NON_ALLOCATI,
        G.EU_INTERESSI_MATURATI_SCADERE,
        G.EU_RATEO,
        G.EU_RISCONTI,
        G.EU_RISCONTI_ALTRI,
        G.EU_RISCONTI_INTERESSI
    FROM {{ ref('saldo_gestionale_m') }} G
    LEFT JOIN TRUFFE T
        ON G.CD_PRATICA = T.CD_PRATICA
        AND G.TP_PROCEDURA = T.TP_PROCEDURA
        AND G.DT_OSSERVAZIONE >= T.DT_INSERIMENTO
    WHERE T.CD_PRATICA IS NULL  /* prendo solo le pratiche che non sono truffe */
    {% if is_incremental() %}
    AND G.DT_OSSERVAZIONE = {{ last_day_past_month() }}
    {% endif %}
	
	
	UNION ALL
	

    SELECT
        'CONTABILE' AS TP_SALDO,
        C.CD_PRATICA_CLIENTE,
        C.TP_PROCEDURA,
        C.DT_OSSERVAZIONE,
        C.EU_ON_BALANCE,
        0 AS EU_IMPIEGO_GESTIONALE,
        C.EU_CAPITALE_SCADERE,
        C.EU_INTERESSI_SCADERE,
        C.EU_SPESE_SCADERE,
        C.EU_CAPITALE_SCADUTO,
        C.EU_INTERESSI_SCADUTO,
        C.EU_SPESE,
        C.EU_MORA,
        C.EU_SALDO_AVERE,
        C.EU_ANTICIPI_EROGATI,
        C.EU_PAG_ESUB_NON_ALLOCATI,
        C.EU_INTERESSI_MATURATI_SCADERE,
        C.EU_RATEO,
        C.EU_RISCONTI,
        C.EU_RISCONTI_ALTRI,
        C.EU_RISCONTI_INTERESSI
    FROM {{ ref('saldo_contabile_m') }} C
    LEFT JOIN TRUFFE T
        ON C.CD_PRATICA = T.CD_PRATICA
        AND C.TP_PROCEDURA = T.TP_PROCEDURA
        AND C.DT_OSSERVAZIONE >= T.DT_INSERIMENTO
    WHERE T.CD_PRATICA IS NULL
    {% if is_incremental() %}
    AND C.DT_OSSERVAZIONE = {{ last_day_past_month() }}
    {% endif %}

)

SELECT
    TP_SALDO,
    CD_PRATICA_CLIENTE,
    TP_PROCEDURA,
    MAX(DT_OSSERVAZIONE) AS DT_OSSERVAZIONE,
    SUM(EU_ON_BALANCE) AS EU_ON_BALANCE,
    SUM(EU_IMPIEGO_GESTIONALE) AS EU_IMPIEGO_GESTIONALE,
    SUM(EU_CAPITALE_SCADERE) AS EU_CAPITALE_SCADERE,
    SUM(EU_INTERESSI_SCADERE) AS EU_INTERESSI_SCADERE,
    SUM(EU_SPESE_SCADERE) AS EU_SPESE_SCADERE,
    SUM(EU_CAPITALE_SCADUTO) AS EU_CAPITALE_SCADUTO,
    SUM(EU_INTERESSI_SCADUTO) AS EU_INTERESSI_SCADUTO,
    SUM(EU_SPESE) AS EU_SPESE,
    SUM(EU_MORA) AS EU_MORA,
    SUM(EU_SALDO_AVERE) AS EU_SALDO_AVERE,
    SUM(EU_ANTICIPI_EROGATI) AS EU_ANTICIPI_EROGATI,
    SUM(EU_PAG_ESUB_NON_ALLOCATI) AS EU_PAG_ESUB_NON_ALLOCATI,
    SUM(EU_INTERESSI_MATURATI_SCADERE) AS EU_INTERESSI_MATURATI_SCADERE,
    SUM(EU_RATEO) AS EU_RATEO,
    SUM(EU_RISCONTI) AS EU_RISCONTI,
    SUM(EU_RISCONTI_ALTRI) AS EU_RISCONTI_ALTRI,
    SUM(EU_RISCONTI_INTERESSI) AS EU_RISCONTI_INTERESSI
FROM BASE
GROUP BY TP_SALDO, CD_PRATICA_CLIENTE, TP_PROCEDURA
/* schiaccio per pratica CO, CA, CQ (CO per cartolarizzazione, CQ per ATC, per CA non dovrebbe cambiare nulla rispetto L2) */




