WITH BASE AS (

    SELECT
        TP_SALDO,
        CD_CONTROPARTE_CLIENTE,
        DT_OSSERVAZIONE,
        EU_ON_BALANCE,
        EU_IMPIEGO_GESTIONALE,
        EU_CAPITALE_SCADERE,
        EU_INTERESSI_SCADERE,
        EU_SPESE_SCADERE,
        EU_CAPITALE_SCADUTO,
        EU_INTERESSI_SCADUTO,
        EU_SPESE,
        EU_MORA,
        EU_SALDO_AVERE,
        EU_ANTICIPI_EROGATI,
        EU_PAG_ESUB_NON_ALLOCATI,
        EU_INTERESSI_MATURATI_SCADERE,
        EU_RATEO,
        EU_RISCONTI,
        EU_RISCONTI_ALTRI,
        EU_RISCONTI_INTERESSI
    FROM {{ ref('dm_saldo_pratica_m') }}
    WHERE FL_TRUFFA = 'N'
    {% if is_incremental() %}
    AND DT_OSSERVAZIONE = {{ last_day_past_month() }}  /* anche il DM_SALDO_PRATICA è mensile, quindi serve filtrare dal secondo giro */
    {% endif %}

)

SELECT
    TP_SALDO,
    CD_CONTROPARTE_CLIENTE AS CD_CONTROPARTE,
    MAX(DT_OSSERVAZIONE) AS DT_OSSERVAZIONE,  /* max per group by, ma la data è univoca poichè ho filtrato in precedenza */
    SUM(EU_ON_BALANCE) AS EU_ON_BALANCE,
    SUM(EU_IMPIEGO_GESTIONALE) AS EU_IMPIEGO_GESTIONALE,
    SUM(EU_CAPITALE_SCADERE) AS EU_CAPITALE_SCADERE,
    SUM(EU_INTERESSI_SCADERE) AS EU_INTERESSI_SCADERE,
    SUM(EU_SPESE_SCADERE) AS EU_SPESE_SCADERE,
    SUM(EU_CAPITALE_SCADUTO) AS EU_CAPITALE_SCADUTO,
    SUM(EU_INTERESSI_SCADUTO) AS EU_INTERESSI_SCADUTO,
    SUM(EU_SPESE) AS EU_SPESE,
    SUM(EU_MORA) AS EU_MORA,
    SUM(EU_SALDO_AVERE) AS EU_SALDO_AVERE,
    SUM(EU_ANTICIPI_EROGATI) AS EU_ANTICIPI_EROGATI,
    SUM(EU_PAG_ESUB_NON_ALLOCATI) AS EU_PAG_ESUB_NON_ALLOCATI,
    SUM(EU_INTERESSI_MATURATI_SCADERE) AS EU_INTERESSI_MATURATI_SCADERE,
    SUM(EU_RATEO) AS EU_RATEO,
    SUM(EU_RISCONTI) AS EU_RISCONTI,
    SUM(EU_RISCONTI_ALTRI) AS EU_RISCONTI_ALTRI,
    SUM(EU_RISCONTI_INTERESSI) AS EU_RISCONTI_INTERESSI
FROM BASE
GROUP BY TP_SALDO, CD_CONTROPARTE_CLIENTE




