select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(BALOG_PROCEDURA) = '', ' ', RTRIM(BALOG_PROCEDURA)) AS VARCHAR(2)) AS balog_procedura,
  TRY_CAST(BALOG_PRATICA AS NUMBER(12,0)) AS balog_pratica,
  TRY_CAST(BALOG_PRG_PSV AS NUMBER(11,0)) AS balog_prg_psv,
  TRY_CAST(BALOG_PROGRESSIVO AS NUMBER(5,0)) AS balog_progressivo,
  TRY_CAST(IFF(RTRIM(BALOG_FUNZIONE) = '', ' ', RTRIM(BALOG_FUNZIONE)) AS VARCHAR(3)) AS balog_funzione,
  TRY_CAST(IFF(RTRIM(BALOG_APPLICAZIONE) = '', ' ', RTRIM(BALOG_APPLICAZIONE)) AS VARCHAR(1)) AS balog_applicazione,
  TRY_CAST(IFF(RTRIM(BALOG_APPL_MASFE) = '', ' ', RTRIM(BALOG_APPL_MASFE)) AS VARCHAR(1)) AS balog_appl_masfe,
  TRY_CAST(IFF(RTRIM(BALOG_ATTIVITA) = '', ' ', RTRIM(BALOG_ATTIVITA)) AS VARCHAR(10)) AS balog_attivita,
  TRY_CAST(IFF(RTRIM(BALOG_UTENTE) = '', ' ', RTRIM(BALOG_UTENTE)) AS VARCHAR(10)) AS balog_utente,
  TRY_CAST(BALOG_DATA_INIZIO_ESAME AS NUMBER(8,0)) AS balog_data_inizio_esame,
  TRY_CAST(BALOG_ORA_INIZIO_ESAME AS NUMBER(8,0)) AS balog_ora_inizio_esame,
  TRY_CAST(BALOG_DATA_INIZIO_DEL AS NUMBER(8,0)) AS balog_data_inizio_del,
  TRY_CAST(BALOG_ORA_INIZIO_DEL AS NUMBER(8,0)) AS balog_ora_inizio_del,
  TRY_CAST(BALOG_DATA_FINE_ELABORAZIONE AS NUMBER(8,0)) AS balog_data_fine_elaborazione,
  TRY_CAST(BALOG_ORA_FINE_ELABORAZIONE AS NUMBER(8,0)) AS balog_ora_fine_elaborazione,
  TRY_CAST(IFF(RTRIM(BALOG_CODICE_OPERAZIONE) = '', ' ', RTRIM(BALOG_CODICE_OPERAZIONE)) AS VARCHAR(10)) AS balog_codice_operazione,
  TRY_CAST(IFF(RTRIM(BALOG_CODICE_ERRORE) = '', ' ', RTRIM(BALOG_CODICE_ERRORE)) AS VARCHAR(4)) AS balog_codice_errore,
  TRY_CAST(IFF(RTRIM(BALOG_CODICE_ERRORE_PAR) = '', ' ', RTRIM(BALOG_CODICE_ERRORE_PAR)) AS VARCHAR(20)) AS balog_codice_errore_par,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','balogesapp') }}
