WITH stato_vigente AS (

    SELECT
        S.PCCOCOML_ID_CONTATTO AS CD_CONTATTO,
        S.PCCOCOML_PROCEDURA AS TP_PROCEDURA,
        S.PCCOCOML_SIMULAZ AS CD_PREVENTIVO,
        ST.PCCOCOSL_STATO AS CD_STATO_PREV,
        ST.PCCOCOSL_ATTRIBUTO AS CD_ATTRIBUTO,
        C.PCCOCON_ORIGINE_CONTATTO AS CD_ORIGINE_CONTATTO,
        C.PCCOCON_CANALE_ACQ AS CD_CANALE_ACQ,
        C.PCCOCON_SPORTELLO AS DS_SPORTELLO,
        ROW_NUMBER() OVER (
            PARTITION BY S.PCCOCOML_ID_CONTATTO, S.PCCOCOML_PROCEDURA, S.PCCOCOML_SIMULAZ
            ORDER BY ST.PCCOCOSL_DATA DESC, ST.PCCOCOSL_ORA DESC, ST.PCCOCOSL_PROGRESSIVO_LOG DESC
        ) AS RN
    FROM {{ ref('pccofcoml') }} S
    LEFT JOIN {{ ref('pccofcosl') }} ST
        ON ST.PCCOCOSL_ID_CONTATTO = S.PCCOCOML_ID_CONTATTO
       AND (
            ST.PCCOCOSL_DATA < S.PCCOCOML_DATA
            OR (ST.PCCOCOSL_DATA = S.PCCOCOML_DATA AND ST.PCCOCOSL_ORA <= S.PCCOCOML_ORA)
       )
    LEFT JOIN {{ ref('pccofcon') }} C
        ON C.PCCOCON_ID_CONTATTO = S.PCCOCOML_ID_CONTATTO
    -- WARN: CD_STATO_PREV/DS_STATO_PREV non avevano una propria RT nel data model; riusata la stessa finestra "stato vigente al momento della simulazione" gia' usata per CD_ATTRIBUTO/CD_ORIGINE_CONTATTO/CD_CANALE_ACQ/DS_SPORTELLO, stessa fonte PCCOFCOSL

)

, stato_vigente_dedup AS (

    SELECT * FROM stato_vigente WHERE RN = 1

)

, pratiche_assicurate_raw AS (

    SELECT PLSE_NUM_PRATICA AS CD_PRATICA FROM {{ ref('plpratserv') }}
    UNION ALL
    SELECT CASRSER_CARTA AS CD_PRATICA FROM {{ ref('casrfser') }}

)

, pratiche_assicurate AS (

    SELECT CD_PRATICA
    FROM pratiche_assicurate_raw
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CD_PRATICA ORDER BY CD_PRATICA) = 1

)

, fl_assicurazione_raw AS (

    SELECT
        COO.PCCOCOO_ID_CONTATTO AS CD_CONTATTO,
        'S' AS FL_ASSICURAZIONE
    FROM {{ ref('pccofcoo') }} COO
    INNER JOIN pratiche_assicurate PA
        ON COO.PCCOCOO_PER_PRATICA = PA.CD_PRATICA

)

, fl_assicurazione AS (

    SELECT CD_CONTATTO, FL_ASSICURAZIONE
    FROM fl_assicurazione_raw
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CD_CONTATTO ORDER BY CD_CONTATTO) = 1

)

SELECT
    S.PCCOCOML_ID_CONTATTO AS CD_PREVENTIVO,
    O.PCCOCOO_PER_PRATICA AS CD_PRATICA,
    S.PCCOCOML_SIMULAZ AS NM_SIMULAZIONE,
    S.PCCOCOML_PROCEDURA AS TP_PROCEDURA,
    O.PCCOCOO_CAR_CLIENTE AS CD_CLIENTE,
    SV.CD_STATO_PREV,
    SV.CD_STATO_PREV AS DS_STATO_PREV, -- WARN: nessuna RT/colonna di decodifica dedicata a DS_STATO_PREV nel data model, riusato lo stesso codice di CD_STATO_PREV
    {{ custom_to_timestamp_ntz('S.PCCOCOML_DATA', 'S.PCCOCOML_ORA') }} AS TS_INSERIMENTO,
    SV.CD_ATTRIBUTO,
    SV.CD_ORIGINE_CONTATTO,
    SV.CD_CANALE_ACQ,
    SV.DS_SPORTELLO,
    FA.FL_ASSICURAZIONE,
    CASE WHEN O.PCCOCOO_PER_PRATICA IS NOT NULL THEN 'S' ELSE 'N' END AS FL_CONVERTITO_PRATICA
FROM {{ ref('pccofcoml') }} S
LEFT JOIN {{ ref('pccofcoo') }} O
    ON O.PCCOCOO_ID_CONTATTO = S.PCCOCOML_ID_CONTATTO
   AND O.PCCOCOO_PROCEDURA = S.PCCOCOML_PROCEDURA
   AND O.PCCOCOO_ASS_SIMULAZ = S.PCCOCOML_SIMULAZ
LEFT JOIN stato_vigente_dedup SV
    ON SV.CD_CONTATTO = S.PCCOCOML_ID_CONTATTO
   AND SV.TP_PROCEDURA = S.PCCOCOML_PROCEDURA
   AND SV.CD_PREVENTIVO = S.PCCOCOML_SIMULAZ
LEFT JOIN fl_assicurazione FA
    ON FA.CD_CONTATTO = S.PCCOCOML_ID_CONTATTO
-- WARN: nessun LASTMODIFIEDDATA nel data model per questa entita'; storicizzazione trattata come S2 per la presenza di TS_INSERIMENTO, ma senza LASTMODIFIEDDATA non e' possibile scrivere il blocco incrementale standard - da chiarire col team
-- WARN: TAB per CD_PREVENTIVO/NM_SIMULAZIONE/TP_PROCEDURA dichiara '2442_PCCOFCOML' e per CD_STATO_PREV/CD_ATTRIBUTO '2447_PCCOFCOSL': usati i nomi tabella reali (PCCOFCOML/PCCOFCOSL) coerenti col resto del progetto e con le RT stesse
