select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(RECPR_CATEGORIA) = '', ' ', RTRIM(RECPR_CATEGORIA)) AS VARCHAR(3)) AS recpr_categoria,
  TRY_CAST(IFF(RTRIM(RECPR_PROCEDURA) = '', ' ', RTRIM(RECPR_PROCEDURA)) AS VARCHAR(2)) AS recpr_procedura,
  TRY_CAST(IFF(RTRIM(RECPR_FASCIA_OPER) = '', ' ', RTRIM(RECPR_FASCIA_OPER)) AS VARCHAR(2)) AS recpr_fascia_oper,
  TRY_CAST(IFF(RTRIM(RECPR_COD_ESITO) = '', ' ', RTRIM(RECPR_COD_ESITO)) AS VARCHAR(3)) AS recpr_cod_esito,
  TRY_CAST(IFF(RTRIM(RECPR_PAGAMENTO) = '', ' ', RTRIM(RECPR_PAGAMENTO)) AS VARCHAR(2)) AS recpr_pagamento,
  TRY_CAST(RECPR_RAP_RATE AS NUMBER(6,3)) AS recpr_rap_rate,
  TRY_CAST(IFF(RTRIM(RECPR_FLAG_INCASSO) = '', ' ', RTRIM(RECPR_FLAG_INCASSO)) AS VARCHAR(1)) AS recpr_flag_incasso,
  TRY_CAST(RECPR_DATA_INIZIO AS NUMBER(8,0)) AS recpr_data_inizio,
  TRY_CAST(IFF(RTRIM(RECPR_BASE_01) = '', ' ', RTRIM(RECPR_BASE_01)) AS VARCHAR(1)) AS recpr_base_01,
  TRY_CAST(RECPR_PERCENTUALE_01 AS NUMBER(6,3)) AS recpr_percentuale_01,
  TRY_CAST(IFF(RTRIM(RECPR_BASE_02) = '', ' ', RTRIM(RECPR_BASE_02)) AS VARCHAR(1)) AS recpr_base_02,
  TRY_CAST(RECPR_PERCENTUALE_02 AS NUMBER(6,3)) AS recpr_percentuale_02,
  TRY_CAST(IFF(RTRIM(RECPR_BASE_03) = '', ' ', RTRIM(RECPR_BASE_03)) AS VARCHAR(1)) AS recpr_base_03,
  TRY_CAST(RECPR_PERCENTUALE_03 AS NUMBER(6,3)) AS recpr_percentuale_03,
  TRY_CAST(IFF(RTRIM(RECPR_BASE_04) = '', ' ', RTRIM(RECPR_BASE_04)) AS VARCHAR(1)) AS recpr_base_04,
  TRY_CAST(RECPR_PERCENTUALE_04 AS NUMBER(6,3)) AS recpr_percentuale_04,
  TRY_CAST(RECPR_IMPORTO_FISSO AS NUMBER(13,0)) AS recpr_importo_fisso,
  TRY_CAST(RECPR_RATE_ECCESSO AS NUMBER(3,0)) AS recpr_rate_eccesso,
  TRY_CAST(RECPR_DATA_FINE AS NUMBER(8,0)) AS recpr_data_fine,
  TRY_CAST(RECPR_RAP_TOTALE AS NUMBER(6,3)) AS recpr_rap_totale,
  TRY_CAST(IFF(RTRIM(RECPR_FLAG_MOD_RIM) = '', ' ', RTRIM(RECPR_FLAG_MOD_RIM)) AS VARCHAR(1)) AS recpr_flag_mod_rim,
  TRY_CAST(RECPR_RAP_SPESE AS NUMBER(6,3)) AS recpr_rap_spese,
  TRY_CAST(RECPR_RAP_N_RATE AS NUMBER(6,3)) AS recpr_rap_n_rate,
  TRY_CAST(RECPR_EFFETTI_IMMED AS NUMBER(2,0)) AS recpr_effetti_immed,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','re2catprv') }}
