-- ============================================================================
-- Entita' L2: PRESCREENING_INPUT   |  Subject Area: SCORING  |  Storicizzazione: S2
-- Sorgente: landing XML CDE (payload StrategyOneRequest, ProcessCode = 'PRESCREENING')
-- Grana: per Applicant (PK = CD_INQUIRYCODE + CD_RUOLO)
-- NOTA storicizzazione: su richiesta, il campo tecnico TS_INSERIMENTO NON e' valorizzato
--   con CURRENT_TIMESTAMP() ne' con LASTMODIFIEDDATA: si usa TS_RIFERIMENTO della
--   tabella sorgente L1 (CDE), rinominato in TS_INSERIMENTO. La strategia incrementale
--   append filtra sullo stesso TS_RIFERIMENTO (non esiste LASTMODIFIEDDATA in questa landing).
-- ============================================================================

WITH src AS (

    SELECT
        TS_RIFERIMENTO,
        VALUE AS xml_doc
    FROM {{ ref('cde') }}          -- ASSUNZIONE: modello landing CDE = ref('cde'); VALIDARE nome reale
    WHERE XMLGET(XMLGET(XMLGET(VALUE, 'StrategyOneRequest'), 'Header'), 'ProcessCode'):"$"::VARCHAR = 'PRESCREENING'
    {% if is_incremental() %}
      AND TS_RIFERIMENTO > (SELECT COALESCE(MAX(TS_INSERIMENTO), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
    {% endif %}

),

-- Nodi intermedi riusati: si scende prima nel root StrategyOneRequest, poi Body/Richiesta
nodes AS (

    SELECT
        TS_RIFERIMENTO,
        xml_doc,
        XMLGET(XMLGET(xml_doc, 'StrategyOneRequest'), 'Header')                                          AS n_header,
        XMLGET(XMLGET(XMLGET(XMLGET(xml_doc, 'StrategyOneRequest'), 'Body'), 'Richiesta'), 'Variables')  AS n_req_var,
        XMLGET(XMLGET(XMLGET(XMLGET(xml_doc, 'StrategyOneRequest'), 'Body'), 'Richiesta'), 'Categories') AS n_categories
    FROM src

),

-- Espansione degli Applicant ripetuti (grana finale = per soggetto)
applicant AS (

    SELECT
        n.TS_RIFERIMENTO,
        n.n_header,
        n.n_req_var,
        XMLGET(F.value, 'Variables') AS n_app_var
    FROM nodes n,
    {{ flatten_xml('n_categories', 'APPLICANT', 'F') }}

),

-- 1. ESTRAZIONE: tutti i campi in VARCHAR (una sola macro get_xml_path per espressione)
raw AS (

    SELECT
        TS_RIFERIMENTO,
        -- PK
        {{ get_xml_path('n_header', 'InquiryCode', 'VARCHAR') }}                        AS CD_INQUIRYCODE,
        {{ get_xml_path('n_app_var', 'RUOLO', 'VARCHAR') }}                             AS CD_RUOLO,
        -- ProcessCode: estratto dal payload (mai hardcodato)
        {{ get_xml_path('n_header', 'ProcessCode', 'VARCHAR') }}                        AS CD_PROCESSCODE,
        -- Livello richiesta (Richiesta/Variables)
        {{ get_xml_path('n_req_var', 'CODICE_INTERROGAZIONE', 'VARCHAR') }}             AS CD_INTERROGAZIONE_RAW,
        {{ get_xml_path('n_req_var', 'USER_CODE', 'VARCHAR') }}                         AS CD_USER_CODE,
        {{ get_xml_path('n_req_var', 'DATA_RICHIESTA', 'VARCHAR') }}                    AS DT_RICHIESTA_RAW,
        {{ get_xml_path('n_req_var', 'CODICE_PROCEDURA', 'VARCHAR') }}                  AS TP_PROCEDURA,
        {{ get_xml_path('n_req_var', 'CODICE_PRATICA', 'VARCHAR') }}                    AS CD_PRATICA_RAW,
        {{ get_xml_path('n_req_var', 'DESTINAZIONE_FINANZIAMENTO', 'VARCHAR') }}        AS CD_DESTINAZIONE_FINANZIAMENTO,
        {{ get_xml_path('n_req_var', 'CODICE_AREA', 'VARCHAR') }}                       AS CD_AREA,
        {{ get_xml_path('n_req_var', 'CODICE_DISTRETTO', 'VARCHAR') }}                  AS CD_DISTRETTO,
        {{ get_xml_path('n_req_var', 'CODICE_FILIALE', 'VARCHAR') }}                    AS CD_FILIALE,
        {{ get_xml_path('n_req_var', 'RETE_VENDITA', 'VARCHAR') }}                      AS CD_RETE_VENDITA,
        {{ get_xml_path('n_req_var', 'MacroArea_Rete_Vendita', 'VARCHAR') }}            AS CD_MACROAREA_RETE_VENDITA,
        {{ get_xml_path('n_req_var', 'Stato_Rete_Vendita', 'VARCHAR') }}               AS CD_STATO_RETE_VENDITA,
        {{ get_xml_path('n_req_var', 'Attributo_Rete_Vendita', 'VARCHAR') }}           AS CD_ATTRIBUTO_RETE_VENDITA,
        {{ get_xml_path('n_req_var', 'Tipologia_Rete_Vendita', 'VARCHAR') }}           AS TP_RETE_VENDITA,
        {{ get_xml_path('n_req_var', 'AGENTE', 'VARCHAR') }}                            AS CD_AGENTE,
        {{ get_xml_path('n_req_var', 'MacroArea_Agente', 'VARCHAR') }}                  AS CD_MACROAREA_AGENTE,
        {{ get_xml_path('n_req_var', 'Stato_Agente', 'VARCHAR') }}                     AS CD_STATO_AGENTE,
        {{ get_xml_path('n_req_var', 'Attributo_Agente', 'VARCHAR') }}                 AS CD_ATTRIBUTO_AGENTE,
        {{ get_xml_path('n_req_var', 'Tipologia_Agente', 'VARCHAR') }}                 AS TP_AGENTE,
        {{ get_xml_path('n_req_var', 'SUBAGENTE', 'VARCHAR') }}                         AS CD_SUBAGENTE,
        {{ get_xml_path('n_req_var', 'MacroArea_Subagente', 'VARCHAR') }}              AS CD_MACROAREA_SUBAGENTE,
        {{ get_xml_path('n_req_var', 'Stato_Subagente', 'VARCHAR') }}                  AS CD_STATO_SUBAGENTE,
        {{ get_xml_path('n_req_var', 'Attributo_Subagente', 'VARCHAR') }}              AS CD_ATTRIBUTO_SUBAGENTE,
        {{ get_xml_path('n_req_var', 'Tipologia_Subagente', 'VARCHAR') }}              AS TP_SUBAGENTE,
        {{ get_xml_path('n_req_var', 'CONVENZIONATO', 'VARCHAR') }}                     AS CD_CONVENZIONATO,
        {{ get_xml_path('n_req_var', 'MacroArea_Convenzionato', 'VARCHAR') }}          AS CD_MACROAREA_CONVENZIONATO,
        {{ get_xml_path('n_req_var', 'Stato_Convenzionato', 'VARCHAR') }}              AS CD_STATO_CONVENZIONATO,
        {{ get_xml_path('n_req_var', 'Attributo_Convenzionato', 'VARCHAR') }}          AS CD_ATTRIBUTO_CONVENZIONATO,
        {{ get_xml_path('n_req_var', 'Tipologia_Convenzionato', 'VARCHAR') }}          AS TP_CONVENZIONATO,
        {{ get_xml_path('n_req_var', 'PUNTO_VENDITA', 'VARCHAR') }}                     AS CD_PUNTO_VENDITA,
        {{ get_xml_path('n_req_var', 'MacroArea_Punto_vendita', 'VARCHAR') }}          AS CD_MACROAREA_PUNTO_VENDITA,
        {{ get_xml_path('n_req_var', 'Stato_Punto_vendita', 'VARCHAR') }}              AS CD_STATO_PUNTO_VENDITA,
        {{ get_xml_path('n_req_var', 'Attributo_Punto_vendita', 'VARCHAR') }}          AS CD_ATTRIBUTO_PUNTO_VENDITA,
        {{ get_xml_path('n_req_var', 'Tipologia_Punto_vendita', 'VARCHAR') }}          AS TP_PUNTO_VENDITA,
        {{ get_xml_path('n_req_var', 'VENDITORE', 'VARCHAR') }}                         AS CD_VENDITORE,
        {{ get_xml_path('n_req_var', 'MacroArea_Venditore', 'VARCHAR') }}              AS CD_MACROAREA_VENDITORE,
        {{ get_xml_path('n_req_var', 'Stato_Venditore', 'VARCHAR') }}                  AS CD_STATO_VENDITORE,
        {{ get_xml_path('n_req_var', 'Attributo_Venditore', 'VARCHAR') }}             AS CD_ATTRIBUTO_VENDITORE,
        {{ get_xml_path('n_req_var', 'Tipologia_Venditore', 'VARCHAR') }}             AS TP_VENDITORE,
        {{ get_xml_path('n_req_var', 'CODICE_INTERMEDIARIO', 'VARCHAR') }}             AS CD_INTERMEDIARIO,
        {{ get_xml_path('n_req_var', 'TIPO_INTERMEDIARIO', 'VARCHAR') }}               AS TP_INTERMEDIARIO,
        {{ get_xml_path('n_req_var', 'STATO_INTERMEDIARIO', 'VARCHAR') }}              AS CD_STATO_INTERMEDIARIO,
        {{ get_xml_path('n_req_var', 'ATTRIBUTO_INTERMEDIARIO', 'VARCHAR') }}          AS CD_ATTRIBUTO_INTERMEDIARIO,
        {{ get_xml_path('n_req_var', 'TIPOLOGIA_INTERMEDIARIO', 'VARCHAR') }}          AS DS_TIPOLOGIA_INTERMEDIARIO,
        {{ get_xml_path('n_req_var', 'PREZZO_BENE', 'VARCHAR') }}                       AS EU_PREZZO_BENE_RAW,
        {{ get_xml_path('n_req_var', 'IMPORTO_FINANZIATO', 'VARCHAR') }}                AS EU_IMPORTO_FINANZIATO_RAW,
        {{ get_xml_path('n_req_var', 'ANTICIPO', 'VARCHAR') }}                          AS EU_ANTICIPO,
        {{ get_xml_path('n_req_var', 'TIPO_PRODOTTO', 'VARCHAR') }}                     AS TP_PRODOTTO,
        {{ get_xml_path('n_req_var', 'PRODOTTO', 'VARCHAR') }}                          AS CD_PRODOTTO,
        {{ get_xml_path('n_req_var', 'DATA_GIA_CORRENTISTA', 'VARCHAR') }}              AS DT_GIA_CORRENTISTA_RAW,
        {{ get_xml_path('n_req_var', 'CANALE', 'VARCHAR') }}                            AS CD_CANALE,
        {{ get_xml_path('n_req_var', 'CANALE_WEB', 'VARCHAR') }}                        AS FL_CANALE_WEB,
        {{ get_xml_path('n_req_var', 'EMETTITORE', 'VARCHAR') }}                        AS CD_EMETTITORE,
        {{ get_xml_path('n_req_var', 'TIPO_VENDITA_CONGIUNTA', 'VARCHAR') }}            AS FL_TIPO_VENDITA_CONGIUNTA,
        {{ get_xml_path('n_req_var', 'FLG_MORATORIA_ATTIVA', 'VARCHAR') }}              AS FL_MORATORIA_ATTIVA,
        {{ get_xml_path('n_req_var', 'CD_ORIGINE_MORATORIA_ATTIVA', 'VARCHAR') }}       AS CD_ORIGINE_MORATORIA_ATTIVA,
        {{ get_xml_path('n_req_var', 'NM_INSLV_CO_CA_120M', 'VARCHAR') }}               AS NM_INSLV_CO_CA_120M_RAW,
        {{ get_xml_path('n_req_var', 'NM_INSLV_TOT_120M', 'VARCHAR') }}                 AS NM_INSLV_TOT_120M_RAW,
        {{ get_xml_path('n_req_var', 'RIVALUTAZIONE_PRESCREENING_KO', 'VARCHAR') }}     AS FL_RIVALUTAZIONE_PRESCREENING_KO,
        {{ get_xml_path('n_req_var', 'ESITO_SIA_BANCOMAT', 'VARCHAR') }}                AS CD_ESITO_SIA_BANCOMAT,
        -- Livello soggetto (Applicant/Variables)
        {{ get_xml_path('n_app_var', 'RIVALUTAZIONE_FLG_CTC', 'VARCHAR') }}             AS FL_RIVALUTAZIONE_FLG_CTC,
        {{ get_xml_path('n_app_var', 'RIVALUTAZIONE_FLG_PROTESTI', 'VARCHAR') }}        AS FL_RIVALUTAZIONE_FLG_PROTESTI,
        {{ get_xml_path('n_app_var', 'RIVALUTAZIONE_FLG_CAI', 'VARCHAR') }}             AS FL_RIVALUTAZIONE_FLG_CAI,
        {{ get_xml_path('n_app_var', 'CODICE_ANAGRAFICA', 'VARCHAR') }}                 AS CD_ANAGRAFICA,
        {{ get_xml_path('n_app_var', 'FLAG_DIPENDENTE', 'VARCHAR') }}                   AS FL_DIPENDENTE,
        {{ get_xml_path('n_app_var', 'CITTADINANZA', 'VARCHAR') }}                      AS CD_CITTADINANZA,
        {{ get_xml_path('n_app_var', 'CODICE_FISCALE', 'VARCHAR') }}                    AS CD_FISCALE,
        {{ get_xml_path('n_app_var', 'DATA_NASCITA', 'VARCHAR') }}                      AS DT_NASCITA_RAW,
        {{ get_xml_path('n_app_var', 'NAZIONE_NASCITA', 'VARCHAR') }}                   AS CD_NAZIONE_NASCITA,
        {{ get_xml_path('n_app_var', 'PROVINCIA_NASCITA', 'VARCHAR') }}                 AS CD_PROVINCIA_NASCITA,
        {{ get_xml_path('n_app_var', 'LUOGO_NASCITA', 'VARCHAR') }}                     AS DS_LUOGO_NASCITA,
        {{ get_xml_path('n_app_var', 'CODICE_LUOGO_NASCITA', 'VARCHAR') }}              AS CD_LUOGO_NASCITA,
        {{ get_xml_path('n_app_var', 'NAZIONE_RESIDENZA', 'VARCHAR') }}                 AS CD_NAZIONE_RESIDENZA,
        {{ get_xml_path('n_app_var', 'PROVINCIA_RESIDENZA', 'VARCHAR') }}               AS CD_PROVINCIA_RESIDENZA,
        {{ get_xml_path('n_app_var', 'CAP_RESIDENZA', 'VARCHAR') }}                     AS CD_CAP_RESIDENZA,
        {{ get_xml_path('n_app_var', 'LUOGO_RESIDENZA', 'VARCHAR') }}                   AS DS_LUOGO_RESIDENZA,
        {{ get_xml_path('n_app_var', 'CODICE_LUOGO_RESIDENZA', 'VARCHAR') }}            AS CD_LUOGO_RESIDENZA,
        {{ get_xml_path('n_app_var', 'CD_TIPO_CLIENTE', 'VARCHAR') }}                   AS TP_CLIENTE,
        {{ get_xml_path('n_app_var', 'NEWDOD_FLAG_DEFAULT_EBA', 'VARCHAR') }}           AS FL_NEWDOD_DEFAULT_EBA,
        {{ get_xml_path('n_app_var', 'NEWDOD_FLAG_FORBORNE', 'VARCHAR') }}              AS FL_NEWDOD_FORBORNE,
        {{ get_xml_path('n_app_var', 'NEWDOD_GIORNI_SUPERAMENTO_SOGLIA_MATERIALITA', 'VARCHAR') }} AS NM_NEWDOD_GIORNI_SUPERAMENTO_SOGLIA_MATERIALITA,
        {{ get_xml_path('n_app_var', 'CUMULO_AGOS_APPLICANT', 'VARCHAR') }}             AS EU_CUMULO_AGOS_APPLICANT_RAW,
        {{ get_xml_path('n_app_var', 'CUMULO_AGOS_OVR_APPLICANT', 'VARCHAR') }}         AS EU_CUMULO_AGOS_OVR_APPLICANT_RAW,
        {{ get_xml_path('n_app_var', 'DATA_INIZIO_RESIDENZA', 'VARCHAR') }}             AS DT_INIZIO_RESIDENZA_RAW,
        {{ get_xml_path('n_app_var', 'FLAG_TRUFFATORE', 'VARCHAR') }}                   AS FL_TRUFFATORE,
        {{ get_xml_path('n_app_var', 'FLAG_TRUFFATO', 'VARCHAR') }}                     AS FL_TRUFFATO,
        {{ get_xml_path('n_app_var', 'FLG_BUON_CLIENTE', 'VARCHAR') }}                  AS FL_BUON_CLIENTE,
        {{ get_xml_path('n_app_var', 'FLG_CTC', 'VARCHAR') }}                           AS FL_CTC,
        {{ get_xml_path('n_app_var', 'FLG_PROTESTI', 'VARCHAR') }}                      AS FL_PROTESTI,
        {{ get_xml_path('n_app_var', 'FLG_TERRORISTI', 'VARCHAR') }}                    AS FL_TERRORISTI,
        {{ get_xml_path('n_app_var', 'FLG_CAI', 'VARCHAR') }}                           AS FL_CAI,
        {{ get_xml_path('n_app_var', 'FORMA_GIURIDICA', 'VARCHAR') }}                   AS CD_FORMA_GIURIDICA,
        {{ get_xml_path('n_app_var', 'PARTITA_IVA', 'VARCHAR') }}                       AS CD_PARTITA_IVA,
        {{ get_xml_path('n_app_var', 'NUMERO_MENSILITA', 'VARCHAR') }}                  AS NM_MENSILITA
    FROM applicant

),

-- 2. CONVERSIONE: tipizzazione sui VARCHAR gia' estratti (TRY_CAST/TRY_TO_DATE, mai annidata su get_xml_path)
conv AS (

    SELECT
        CD_INQUIRYCODE,
        CD_RUOLO,
        CD_PROCESSCODE,
        TRY_CAST(CD_INTERROGAZIONE_RAW AS NUMBER(16,0))                 AS CD_INTERROGAZIONE,
        CD_USER_CODE,
        TRY_TO_DATE(DT_RICHIESTA_RAW)                                  AS DT_RICHIESTA,
        TP_PROCEDURA,
        TRY_CAST(CD_PRATICA_RAW AS NUMBER(16,0))                       AS CD_PRATICA,
        CD_DESTINAZIONE_FINANZIAMENTO,
        CD_AREA,
        CD_DISTRETTO,
        CD_FILIALE,
        CD_RETE_VENDITA,
        CD_MACROAREA_RETE_VENDITA,
        CD_STATO_RETE_VENDITA,
        CD_ATTRIBUTO_RETE_VENDITA,
        TP_RETE_VENDITA,
        CD_AGENTE,
        CD_MACROAREA_AGENTE,
        CD_STATO_AGENTE,
        CD_ATTRIBUTO_AGENTE,
        TP_AGENTE,
        CD_SUBAGENTE,
        CD_MACROAREA_SUBAGENTE,
        CD_STATO_SUBAGENTE,
        CD_ATTRIBUTO_SUBAGENTE,
        TP_SUBAGENTE,
        CD_CONVENZIONATO,
        CD_MACROAREA_CONVENZIONATO,
        CD_STATO_CONVENZIONATO,
        CD_ATTRIBUTO_CONVENZIONATO,
        TP_CONVENZIONATO,
        CD_PUNTO_VENDITA,
        CD_MACROAREA_PUNTO_VENDITA,
        CD_STATO_PUNTO_VENDITA,
        CD_ATTRIBUTO_PUNTO_VENDITA,
        TP_PUNTO_VENDITA,
        CD_VENDITORE,
        CD_MACROAREA_VENDITORE,
        CD_STATO_VENDITORE,
        CD_ATTRIBUTO_VENDITORE,
        TP_VENDITORE,
        CD_INTERMEDIARIO,
        TP_INTERMEDIARIO,
        CD_STATO_INTERMEDIARIO,
        CD_ATTRIBUTO_INTERMEDIARIO,
        DS_TIPOLOGIA_INTERMEDIARIO,
        TRY_CAST(EU_PREZZO_BENE_RAW AS NUMBER(13,2))            AS EU_PREZZO_BENE,
        TRY_CAST(EU_IMPORTO_FINANZIATO_RAW AS NUMBER(13,2))     AS EU_IMPORTO_FINANZIATO,
        -- WARN: EU_ANTICIPO ha TIPO VARCHAR(13,2) nel data model (tipo anomalo per un EU_); mantenuto come stringa grezza
        EU_ANTICIPO,
        TP_PRODOTTO,
        CD_PRODOTTO,
        TRY_TO_DATE(DT_GIA_CORRENTISTA_RAW)                           AS DT_GIA_CORRENTISTA,
        CD_CANALE,
        FL_CANALE_WEB,
        CD_EMETTITORE,
        FL_TIPO_VENDITA_CONGIUNTA,
        FL_MORATORIA_ATTIVA,
        CD_ORIGINE_MORATORIA_ATTIVA,
        TRY_CAST(NM_INSLV_CO_CA_120M_RAW AS NUMBER(16,0))             AS NM_INSLV_CO_CA_120M,
        TRY_CAST(NM_INSLV_TOT_120M_RAW AS NUMBER(16,0))              AS NM_INSLV_TOT_120M,
        FL_RIVALUTAZIONE_PRESCREENING_KO,
        CD_ESITO_SIA_BANCOMAT,
        FL_RIVALUTAZIONE_FLG_CTC,
        FL_RIVALUTAZIONE_FLG_PROTESTI,
        FL_RIVALUTAZIONE_FLG_CAI,
        CD_ANAGRAFICA,
        FL_DIPENDENTE,
        CD_CITTADINANZA,
        CD_FISCALE,
        TRY_TO_DATE(DT_NASCITA_RAW)                                  AS DT_NASCITA,
        CD_NAZIONE_NASCITA,
        CD_PROVINCIA_NASCITA,
        DS_LUOGO_NASCITA,
        CD_LUOGO_NASCITA,
        CD_NAZIONE_RESIDENZA,
        CD_PROVINCIA_RESIDENZA,
        CD_CAP_RESIDENZA,
        DS_LUOGO_RESIDENZA,
        CD_LUOGO_RESIDENZA,
        TP_CLIENTE,
        FL_NEWDOD_DEFAULT_EBA,
        FL_NEWDOD_FORBORNE,
        NM_NEWDOD_GIORNI_SUPERAMENTO_SOGLIA_MATERIALITA,
        TRY_CAST(EU_CUMULO_AGOS_APPLICANT_RAW AS NUMBER(16,2)) AS EU_CUMULO_AGOS_APPLICANT,
        TRY_CAST(EU_CUMULO_AGOS_OVR_APPLICANT_RAW AS NUMBER(16,2)) AS EU_CUMULO_AGOS_OVR_APPLICANT,
        TRY_TO_DATE(DT_INIZIO_RESIDENZA_RAW)                         AS DT_INIZIO_RESIDENZA,
        FL_TRUFFATORE,
        FL_TRUFFATO,
        FL_BUON_CLIENTE,
        FL_CTC,
        FL_PROTESTI,
        FL_TERRORISTI,
        FL_CAI,
        CD_FORMA_GIURIDICA,
        CD_PARTITA_IVA,
        NM_MENSILITA,
        -- Campo tecnico di storicizzazione: TS_RIFERIMENTO della L1 rinominato in TS_INSERIMENTO
        TS_RIFERIMENTO AS TS_INSERIMENTO
    FROM raw

)

SELECT
    -- PK
    CD_INQUIRYCODE,
    CD_RUOLO,
    -- campo tecnico di storicizzazione (S2)
    TS_INSERIMENTO,
    -- business
    CD_PROCESSCODE,
    CD_INTERROGAZIONE,
    CD_USER_CODE,
    DT_RICHIESTA,
    TP_PROCEDURA,
    CD_PRATICA,
    CD_DESTINAZIONE_FINANZIAMENTO,
    CD_AREA,
    CD_DISTRETTO,
    CD_FILIALE,
    CD_RETE_VENDITA,
    CD_MACROAREA_RETE_VENDITA,
    CD_STATO_RETE_VENDITA,
    CD_ATTRIBUTO_RETE_VENDITA,
    TP_RETE_VENDITA,
    CD_AGENTE,
    CD_MACROAREA_AGENTE,
    CD_STATO_AGENTE,
    CD_ATTRIBUTO_AGENTE,
    TP_AGENTE,
    CD_SUBAGENTE,
    CD_MACROAREA_SUBAGENTE,
    CD_STATO_SUBAGENTE,
    CD_ATTRIBUTO_SUBAGENTE,
    TP_SUBAGENTE,
    CD_CONVENZIONATO,
    CD_MACROAREA_CONVENZIONATO,
    CD_STATO_CONVENZIONATO,
    CD_ATTRIBUTO_CONVENZIONATO,
    TP_CONVENZIONATO,
    CD_PUNTO_VENDITA,
    CD_MACROAREA_PUNTO_VENDITA,
    CD_STATO_PUNTO_VENDITA,
    CD_ATTRIBUTO_PUNTO_VENDITA,
    TP_PUNTO_VENDITA,
    CD_VENDITORE,
    CD_MACROAREA_VENDITORE,
    CD_STATO_VENDITORE,
    CD_ATTRIBUTO_VENDITORE,
    TP_VENDITORE,
    CD_INTERMEDIARIO,
    TP_INTERMEDIARIO,
    CD_STATO_INTERMEDIARIO,
    CD_ATTRIBUTO_INTERMEDIARIO,
    DS_TIPOLOGIA_INTERMEDIARIO,
    EU_PREZZO_BENE,
    EU_IMPORTO_FINANZIATO,
    EU_ANTICIPO,
    TP_PRODOTTO,
    CD_PRODOTTO,
    DT_GIA_CORRENTISTA,
    CD_CANALE,
    FL_CANALE_WEB,
    CD_EMETTITORE,
    FL_TIPO_VENDITA_CONGIUNTA,
    FL_MORATORIA_ATTIVA,
    CD_ORIGINE_MORATORIA_ATTIVA,
    NM_INSLV_CO_CA_120M,
    NM_INSLV_TOT_120M,
    FL_RIVALUTAZIONE_PRESCREENING_KO,
    CD_ESITO_SIA_BANCOMAT,
    FL_RIVALUTAZIONE_FLG_CTC,
    FL_RIVALUTAZIONE_FLG_PROTESTI,
    FL_RIVALUTAZIONE_FLG_CAI,
    CD_ANAGRAFICA,
    FL_DIPENDENTE,
    CD_CITTADINANZA,
    CD_FISCALE,
    DT_NASCITA,
    CD_NAZIONE_NASCITA,
    CD_PROVINCIA_NASCITA,
    DS_LUOGO_NASCITA,
    CD_LUOGO_NASCITA,
    CD_NAZIONE_RESIDENZA,
    CD_PROVINCIA_RESIDENZA,
    CD_CAP_RESIDENZA,
    DS_LUOGO_RESIDENZA,
    CD_LUOGO_RESIDENZA,
    TP_CLIENTE,
    FL_NEWDOD_DEFAULT_EBA,
    FL_NEWDOD_FORBORNE,
    NM_NEWDOD_GIORNI_SUPERAMENTO_SOGLIA_MATERIALITA,
    EU_CUMULO_AGOS_APPLICANT,
    EU_CUMULO_AGOS_OVR_APPLICANT,
    DT_INIZIO_RESIDENZA,
    FL_TRUFFATORE,
    FL_TRUFFATO,
    FL_BUON_CLIENTE,
    FL_CTC,
    FL_PROTESTI,
    FL_TERRORISTI,
    FL_CAI,
    CD_FORMA_GIURIDICA,
    CD_PARTITA_IVA,
    NM_MENSILITA
FROM conv