-- L2 ONBOARDING - DOC_ISTRUTTORIA
-- Storicizzazione: S4 (incremental / insert_overwrite) - nessun blocco incremental, nessun LASTMODIFIEDDATA
-- Tabella main: OXDOFD (cluster C). Da data model: tutte le tabelle sorgente sono cluster C e vengono attualizzate.

SELECT
    D.OXDOD_CARTELLA AS CD_CARTELLA,
    D.OXDOD_ELEMENTO AS CD_ELEMENTO,
    D.OXDOD_VERSIONE_DOC AS CD_VERSIONE_DOC,
    T.OXDOT_SET AS CD_SET_DOC,
    T.OXDOT_GRUPPO AS CD_GRUPPO,
    PR.OXDOTPR_PROCEDURA AS TP_PROCEDURA,
    PR.OXDOTPR_PRATICA AS CD_PRATICA,
    CV.OXDOTCV_PRATICA AS CD_PRATICA_CONV,
    D.OXDOD_CONTROPARTE AS CD_CONTROPARTE,
    D.OXDOD_TIPO_DOCU AS CD_TIPO_DOC,
    TD.OXTBDOC_DESCRIZIONE AS DS_TIPO_DOC,
    D.OXDOD_SOTTOTIPO_DOCU AS CD_SOTTOTIPO_DOC,
    BST.OXDOTBST_DESCRIZIONE AS DS_SOTTOTIPO_DOC,
    COALESCE(
        SEDO.OXDOTSEDO_OPE_BLOCCATA,
        CASE PR.OXDOTPR_PROCEDURA
            WHEN 'CO' THEN PL.PLDOCR_OPE_BLOCCATA
            WHEN 'CA' THEN CA.CADOTDO_OPE_BLOCCATA
            WHEN 'CQ' THEN QT.QTDRI_OPE_BLOCCATA
        END
    )  AS CD_FASE_OBBLIGATORIETA,
    D.OXDOD_SITUAZIONE AS CD_SITUAZIONE,
    --SI.OXDOTSI_DESCRIZIONE AS DS_SITUAZIONE, --TODO da sostituire quando ci sarà la tabella
    NULL AS DS_SITUAZIONE,
    D.OXDOD_GIORNI AS NM_GG_RIENTRO_CONCESSI,
    D.OXDOD_ANNULLO AS FL_ANNULLO_DOC,
    D.OXDOD_MOTIVO_ANN AS CD_ANNULLO_DOC,
    {{ custom_to_timestamp_ntz('D.OXDOD_DATA_ANN', 'D.OXDOD_ORA_ANN') }} AS TS_ANNULLO_DOC,
    D.OXDOD_UTENTE_ANN AS CD_UTENTE_ANNULLO_DOC,
    {{ custom_to_timestamp_ntz('D.OXDOD_DATA_INS', 'D.OXDOD_ORA_INS') }} AS TS_INSERIMENTO_DOC,
    D.OXDOD_UTENTE_INS AS CD_UTENTE_INSERIMENTO_DOC,
    T.OXDOT_ANNULLO AS FL_ANNULLO_CARTELLA,
    {{ custom_to_timestamp_ntz('T.OXDOT_DATA_ANN', 'T.OXDOT_ORA_ANN') }} AS TS_ANNULLO_CARTELLA,
    T.OXDOT_UTENTE_ANN AS CD_UTENTE_ANNULLO_CARTELLA,
    {{ custom_to_timestamp_ntz('T.OXDOT_DATA_INS', 'T.OXDOT_ORA_INS') }} AS TS_INSERIMENTO_CARTELLA,
    T.OXDOT_UTENTE_INS AS CD_UTENTE_INSERIMENTO_CARTELLA,
    D.OXDOD_MOTIVO_INS AS CD_MOTIVO_INS,
    D.OXDOD_RAPPORTO_INS AS CD_RAPPORTO_INS
FROM {{ ref('oxdofd') }} D
LEFT JOIN {{ ref('oxdoft') }} T
    ON D.OXDOD_CARTELLA = T.OXDOT_CARTELLA
    AND T.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND T.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxdoftpr') }} PR
    ON D.OXDOD_CARTELLA = PR.OXDOTPR_CARTELLA
    AND PR.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND PR.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxdoftcv') }} CV
    ON D.OXDOD_CARTELLA = CV.OXDOTCV_CARTELLA
    AND CV.OXDOTCV_ANNULLO <> 'S'
    AND CV.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND CV.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxtbfdoc') }} TD
    ON D.OXDOD_TIPO_DOCU = TD.OXTBDOC_CODICE
    AND TD.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND TD.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxdoftbst') }} BST
    ON D.OXDOD_SOTTOTIPO_DOCU = BST.OXDOTBST_CODICE
    AND BST.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND BST.FL_DELETED = 'N'
--TODO da mettere quando ci sarà la tabella
--LEFT JOIN { reff('oxdoftsi') } SI 
--    ON SI.OXDOTSI_CODICE = D.OXDOD_SITUAZIONE
--    AND SI.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxdoftsedo') }} SEDO
       -- ON SEDO.OXDOTSEDO_PROCEDURA = PR.OXDOTPR_PROCEDURA
       ON SEDO.OXDOTSEDO_SET = T.OXDOT_SET
       AND SEDO.OXDOTSEDO_DOCUMENTO = D.OXDOD_TIPO_DOCU
       AND SEDO.OXDOTSEDO_SOTTOTIPO_DOCU = D.OXDOD_SOTTOTIPO_DOCU
       AND SEDO.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
       AND SEDO.FL_DELETED = 'N'
LEFT JOIN {{ ref('pltbfdocr') }} PL
    ON PR.OXDOTPR_PROCEDURA = 'CO'
    AND PL.PLDOCR_CODICE = T.OXDOT_SET
    AND PL.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND PL.FL_DELETED = 'N'
LEFT JOIN {{ ref('cadoftdo') }} CA
    ON PR.OXDOTPR_PROCEDURA = 'CA'
    AND CA.CADOTDO_CODICE = T.OXDOT_SET
    AND CA.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND CA.FL_DELETED = 'N'
LEFT JOIN {{ ref('qstabdri') }} QT
    ON PR.OXDOTPR_PROCEDURA = 'CQ'
    AND QT.QTDRI_DOCUMENTO = T.OXDOT_SET
    AND QT.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    AND QT.FL_DELETED = 'N'
WHERE D.FL_DELETED = 'N'
    AND D.TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
