-- L2 ONBOARDING - WFL_SOTTOFASE
-- Storicizzazione: S1 (incremental / merge). Sorgente WFISFSF cluster C (TS_INIZIO/FINE_VALIDITA gia' in L1).

WITH base AS (
    SELECT
        T.WFISSF_ISTANZA AS CD_ISTANZA,
        T.WFISSF_FASE AS CD_FASE,
        T.WFISSF_SOTTOFASE AS CD_SOTTOFASE,
        T.TS_INIZIO_VALIDITA AS TS_INIZIO_VALIDITA,
        T.TS_FINE_VALIDITA AS TS_FINE_VALIDITA,
        T.WFISSF_STATO AS CD_STATO_SOTTOFASE,
        CASE
            WHEN T.WFISSF_STATO IS NULL OR T.WFISSF_STATO = ' ' THEN 'Attiva'
            WHEN T.WFISSF_STATO = 'A' THEN 'Annullata'
            WHEN T.WFISSF_STATO = 'C' THEN 'Chiusa'
            WHEN T.WFISSF_STATO = 'I' THEN 'Istanza'
            WHEN T.WFISSF_STATO = 'S' THEN 'Sospesa'
            ELSE T.WFISSF_STATO
        END AS DS_STATO_SOTTOFASE,
        T.WFISSF_FASE_DESTINAZIONE AS CD_FASE_DESTINAZIONE,
        T.WFISSF_SOTTOFASE_PREC AS CD_SOTTOFASE_PREC,
        T.WFISSF_SOTTOFASE_PREC_2 AS CD_SOTTOFASE_PREC_2,
        T.WFISSF_SOTTOFASE_PREC_3 AS CD_SOTTOFASE_PREC_3,
        T.WFISSF_SOTTOFASE_PREC_4 AS CD_SOTTOFASE_PREC_4,
        T.WFISSF_SOTTOFASE_PREC_5 AS CD_SOTTOFASE_PREC_5,
        T.WFISSF_SOTTOFASE_PREC_6 AS CD_SOTTOFASE_PREC_6,
        T.WFISSF_SOTTOFASE_PREC_7 AS CD_SOTTOFASE_PREC_7,
        T.WFISSF_SOTTOFASE_PREC_8 AS CD_SOTTOFASE_PREC_8,
        T.WFISSF_SOTTOFASE_PREC_9 AS CD_SOTTOFASE_PREC_9,
        T.WFISSF_SOTTOFASE_PREC_10 AS CD_SOTTOFASE_PREC_10,
        T.WFISSF_SOTTOFASE_PREC_11 AS CD_SOTTOFASE_PREC_11,
        T.WFISSF_SOTTOFASE_PREC_12 AS CD_SOTTOFASE_PREC_12,
        T.WFISSF_SOTTOFASE_PREC_13 AS CD_SOTTOFASE_PREC_13,
        T.WFISSF_SOTTOFASE_PREC_14 AS CD_SOTTOFASE_PREC_14,
        T.WFISSF_SOTTOFASE_PREC_15 AS CD_SOTTOFASE_PREC_15,
        T.WFISSF_SOTTOFASE_PREC_16 AS CD_SOTTOFASE_PREC_16,
        T.WFISSF_SOTTOFASE_PREC_17 AS CD_SOTTOFASE_PREC_17,
        T.WFISSF_SOTTOFASE_PREC_18 AS CD_SOTTOFASE_PREC_18,
        T.WFISSF_SOTTOFASE_PREC_19 AS CD_SOTTOFASE_PREC_19,
        T.WFISSF_SOTTOFASE_PREC_20 AS CD_SOTTOFASE_PREC_20,
        T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
    FROM {{ ref('wfisfsf') }} T
    WHERE T.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_ISTANZA,
        CD_FASE,
        CD_SOTTOFASE,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        CD_STATO_SOTTOFASE,
        DS_STATO_SOTTOFASE,
        CD_FASE_DESTINAZIONE,
        CD_SOTTOFASE_PREC,
        CD_SOTTOFASE_PREC_2,
        CD_SOTTOFASE_PREC_3,
        CD_SOTTOFASE_PREC_4,
        CD_SOTTOFASE_PREC_5,
        CD_SOTTOFASE_PREC_6,
        CD_SOTTOFASE_PREC_7,
        CD_SOTTOFASE_PREC_8,
        CD_SOTTOFASE_PREC_9,
        CD_SOTTOFASE_PREC_10,
        CD_SOTTOFASE_PREC_11,
        CD_SOTTOFASE_PREC_12,
        CD_SOTTOFASE_PREC_13,
        CD_SOTTOFASE_PREC_14,
        CD_SOTTOFASE_PREC_15,
        CD_SOTTOFASE_PREC_16,
        CD_SOTTOFASE_PREC_17,
        CD_SOTTOFASE_PREC_18,
        CD_SOTTOFASE_PREC_19,
        CD_SOTTOFASE_PREC_20,
        LASTMODIFIEDDATA,
        {{ hash_cols([
            'CD_ISTANZA',
            'CD_FASE',
            'CD_SOTTOFASE',
            'CD_STATO_SOTTOFASE',
            'DS_STATO_SOTTOFASE',
            'CD_FASE_DESTINAZIONE',
            'CD_SOTTOFASE_PREC',
            'CD_SOTTOFASE_PREC_2',
            'CD_SOTTOFASE_PREC_3',
            'CD_SOTTOFASE_PREC_4',
            'CD_SOTTOFASE_PREC_5',
            'CD_SOTTOFASE_PREC_6',
            'CD_SOTTOFASE_PREC_7',
            'CD_SOTTOFASE_PREC_8',
            'CD_SOTTOFASE_PREC_9',
            'CD_SOTTOFASE_PREC_10',
            'CD_SOTTOFASE_PREC_11',
            'CD_SOTTOFASE_PREC_12',
            'CD_SOTTOFASE_PREC_13',
            'CD_SOTTOFASE_PREC_14',
            'CD_SOTTOFASE_PREC_15',
            'CD_SOTTOFASE_PREC_16',
            'CD_SOTTOFASE_PREC_17',
            'CD_SOTTOFASE_PREC_18',
            'CD_SOTTOFASE_PREC_19',
            'CD_SOTTOFASE_PREC_20'
        ]) }} AS HASHED_COLS
    FROM base
    {{ is_incremental_S1('CD_ISTANZA, CD_FASE, CD_SOTTOFASE') }}
)

SELECT
    H.CD_ISTANZA,
    H.CD_FASE,
    H.CD_SOTTOFASE,
    H.TS_INIZIO_VALIDITA,
    {{ ts_fine_validita('H.CD_ISTANZA, H.CD_FASE, H.CD_SOTTOFASE', 'H.TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA,
    H.CD_STATO_SOTTOFASE,
    H.DS_STATO_SOTTOFASE,
    H.CD_FASE_DESTINAZIONE,
    H.CD_SOTTOFASE_PREC,
    H.CD_SOTTOFASE_PREC_2,
    H.CD_SOTTOFASE_PREC_3,
    H.CD_SOTTOFASE_PREC_4,
    H.CD_SOTTOFASE_PREC_5,
    H.CD_SOTTOFASE_PREC_6,
    H.CD_SOTTOFASE_PREC_7,
    H.CD_SOTTOFASE_PREC_8,
    H.CD_SOTTOFASE_PREC_9,
    H.CD_SOTTOFASE_PREC_10,
    H.CD_SOTTOFASE_PREC_11,
    H.CD_SOTTOFASE_PREC_12,
    H.CD_SOTTOFASE_PREC_13,
    H.CD_SOTTOFASE_PREC_14,
    H.CD_SOTTOFASE_PREC_15,
    H.CD_SOTTOFASE_PREC_16,
    H.CD_SOTTOFASE_PREC_17,
    H.CD_SOTTOFASE_PREC_18,
    H.CD_SOTTOFASE_PREC_19,
    H.CD_SOTTOFASE_PREC_20,
    H.LASTMODIFIEDDATA
FROM dedup H
