-- Storicizzazione: S1 (incremental / merge). Sorgente WFISFWFL cluster C (TS_INIZIO/FINE_VALIDITA gia' in L1).

WITH base AS (
    SELECT
        T.WFISWFL_ISTANZA AS CD_ISTANZA,
        T.TS_INIZIO_VALIDITA AS TS_INIZIO_VALIDITA,
        T.TS_FINE_VALIDITA AS TS_FINE_VALIDITA,
        T.WFISWFL_PRATICA AS CD_PRATICA,
        T.WFISWFL_WORKFLOW AS CD_WORKFLOW,
        T.WFISWFL_AREA_WF AS CD_AREA_WORKFLOW,
        T.WFISWFL_ZONA AS CD_ZONA,
        T.WFISWFL_STATO AS CD_STATO_ISTANZA,
        CASE
            WHEN {{ custom_is_null('T.WFISWFL_STATO') }} THEN 'Attiva'
            WHEN T.WFISWFL_STATO = 'C' THEN 'Chiusa'
            ELSE T.WFISWFL_STATO
        END AS DS_STATO_ISTANZA,
        {{ custom_to_timestamp_ntz('T.WFISWFL_DATA_CREAZIONE', 'T.WFISWFL_ORA_CREAZIONE') }} AS TS_CREAZIONE_ISTANZA,
        T.WFISWFL_UTENTE_MODIFICA AS CD_UTENTE_ULT_MODIFICA_ISTANZA,
        {{ custom_to_timestamp_ntz('T.WFISWFL_DATA_MODIFICA', 'T.WFISWFL_ORA_MODIFICA') }} AS TS_ULT_MODIFICA_ISTANZA,
        CASE
            WHEN T.WFISWFL_STATO = 'C'
                THEN {{ custom_to_timestamp_ntz('T.WFISWFL_DATA_MODIFICA', 'T.WFISWFL_ORA_MODIFICA') }}
            ELSE NULL
        END AS TS_CHIUSURA_ISTANZA,
        T.WFISWFL_PRG_SIN AS CD_PRG_SIN,
        T.WFISWFL_PRG_PSV AS CD_PRG_PSV,
        T.WFISWFL_AZIONE_PSV AS CD_AZIONE_PSV,
        T.WFISWFL_PROG_RICICLO AS CD_PROG_RICICLO,
        T.WFISWFL_PRG_RET AS CD_PRG_RET,
        T.WFISWFL_LIQ_SC AS CD_LIQ_SC,
        {{ custom_to_date('T.WFISWFL_DATA_COM_SIN') }} AS DT_COM_SIN,
        T.WFISWFL_CODICE_SIN AS CD_SIN,
        T.WFISWFL_CLASS_SIN AS CD_CLASS_SIN,
        T.WFISWFL_TIPO_SIN AS TP_SIN,
        T.WFISWFL_STATO_SIN AS CD_STATO_SIN,
        T.WFISWFL_ASS_SIN AS CD_ASS_SIN,
        T.WFISWFL_STATO_PSV AS CD_STATO_PSV,
        T.WFISWFL_BLOCCO_PSV AS CD_BLOCCO_PSV,
        T.WFISWFL_PRG_PSV_EXT AS PR_PSV_EXT,
        T.WFISWFL_NOTE AS DS_NOTE,
        T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
    FROM {{ ref('wfisfwfl') }} T
    WHERE T.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_ISTANZA, TS_INIZIO_VALIDITA, TS_FINE_VALIDITA, CD_PRATICA, CD_WORKFLOW, CD_AREA_WORKFLOW,
        CD_ZONA, CD_STATO_ISTANZA, DS_STATO_ISTANZA, TS_CREAZIONE_ISTANZA, CD_UTENTE_ULT_MODIFICA_ISTANZA,
        TS_ULT_MODIFICA_ISTANZA, TS_CHIUSURA_ISTANZA, CD_PRG_SIN, CD_PRG_PSV, CD_AZIONE_PSV,
        CD_PROG_RICICLO, CD_PRG_RET, CD_LIQ_SC, DT_COM_SIN, CD_SIN, CD_CLASS_SIN, TP_SIN, CD_STATO_SIN,
        CD_ASS_SIN, CD_STATO_PSV, CD_BLOCCO_PSV, PR_PSV_EXT, DS_NOTE, LASTMODIFIEDDATA,
        {{ hash_cols(['CD_ISTANZA', 'CD_PRATICA', 'CD_WORKFLOW', 'CD_AREA_WORKFLOW', 'CD_ZONA',
            'CD_STATO_ISTANZA', 'DS_STATO_ISTANZA', 'TS_CREAZIONE_ISTANZA', 'CD_UTENTE_ULT_MODIFICA_ISTANZA',
            'TS_ULT_MODIFICA_ISTANZA', 'TS_CHIUSURA_ISTANZA', 'CD_PRG_SIN', 'CD_PRG_PSV', 'CD_AZIONE_PSV',
            'CD_PROG_RICICLO', 'CD_PRG_RET', 'CD_LIQ_SC', 'DT_COM_SIN', 'CD_SIN', 'CD_CLASS_SIN', 'TP_SIN',
            'CD_STATO_SIN', 'CD_ASS_SIN', 'CD_STATO_PSV', 'CD_BLOCCO_PSV', 'PR_PSV_EXT', 'DS_NOTE'
        ]) }} AS HASHED_COLS
    FROM base
    {{ is_incremental_S1('CD_ISTANZA') }}
)

SELECT
    H.CD_ISTANZA, H.TS_INIZIO_VALIDITA,
    {{ ts_fine_validita('H.CD_ISTANZA', 'H.TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA,
    H.CD_PRATICA, H.CD_WORKFLOW, H.CD_AREA_WORKFLOW, H.CD_ZONA, H.CD_STATO_ISTANZA, H.DS_STATO_ISTANZA,
    H.TS_CREAZIONE_ISTANZA, H.CD_UTENTE_ULT_MODIFICA_ISTANZA, H.TS_ULT_MODIFICA_ISTANZA, H.TS_CHIUSURA_ISTANZA,
    H.CD_PRG_SIN, H.CD_PRG_PSV, H.CD_AZIONE_PSV, H.CD_PROG_RICICLO, H.CD_PRG_RET, H.CD_LIQ_SC, H.DT_COM_SIN,
    H.CD_SIN, H.CD_CLASS_SIN, H.TP_SIN, H.CD_STATO_SIN, H.CD_ASS_SIN, H.CD_STATO_PSV, H.CD_BLOCCO_PSV,
    H.PR_PSV_EXT, H.DS_NOTE, H.LASTMODIFIEDDATA
FROM dedup H
