-- Storicizzazione: S1 (incremental / merge). Sorgente WFISFFA cluster C (TS_INIZIO/FINE_VALIDITA gia' in L1).

WITH base AS (
    SELECT
        T.WFISFA_ISTANZA AS CD_ISTANZA,
        T.WFISFA_FASE AS CD_FASE,
        T.TS_INIZIO_VALIDITA AS TS_INIZIO_VALIDITA,
        T.TS_FINE_VALIDITA AS TS_FINE_VALIDITA,
        T.WFISFA_WORKFLOW AS CD_WORKFLOW,
        T.WFISFA_STATO AS CD_STATO_FASE,
        CASE
            WHEN {{ custom_is_null('T.WFISFA_STATO') }} THEN 'Attiva'
            WHEN T.WFISFA_STATO = 'F' THEN 'Forzabile'
            WHEN T.WFISFA_STATO = 'C' THEN 'Chiusa'
            WHEN T.WFISFA_STATO = 'I' THEN 'Istanza'
            WHEN T.WFISFA_STATO = 'A' THEN 'Annullata'
            ELSE T.WFISFA_STATO
        END AS DS_STATO_FASE,
        {{ custom_to_timestamp_ntz('T.WFISFA_DATA_APERTURA', 'T.WFISFA_ORA_APERTURA') }} AS TS_APERTURA_FASE,
        {{ custom_to_timestamp_ntz('T.WFISFA_DATA_CHIUSURA', 'T.WFISFA_ORA_CHIUSURA') }} AS TS_CHIUSURA_FASE,
        T.WFISFA_RILAVORATA AS FL_RILAVORATA,
        T.WFISFA_RIAPRIBILE AS FL_RIAPRIBILE,
        T.WFISFA_FASE_PREC AS CD_FASE_PREC,
        T.WFISFA_FASE_PREC_2 AS CD_FASE_PREC_2,
        T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
    FROM {{ ref('wfisffa') }} T
    WHERE T.FL_DELETED = 'N'
),

dedup AS (
    SELECT
        CD_ISTANZA, CD_FASE,  TS_INIZIO_VALIDITA, TS_FINE_VALIDITA, CD_WORKFLOW, CD_STATO_FASE, DS_STATO_FASE,
        TS_APERTURA_FASE, TS_CHIUSURA_FASE, FL_RILAVORATA, FL_RIAPRIBILE, CD_FASE_PREC, CD_FASE_PREC_2, LASTMODIFIEDDATA,
        {{ hash_cols(['CD_ISTANZA', 'CD_FASE', 'CD_WORKFLOW', 'CD_STATO_FASE', 'DS_STATO_FASE', 'TS_APERTURA_FASE',
            'TS_CHIUSURA_FASE', 'FL_RILAVORATA', 'FL_RIAPRIBILE', 'CD_FASE_PREC', 'CD_FASE_PREC_2'
        ]) }} AS HASHED_COLS
    FROM base
    {{ is_incremental_S1('CD_ISTANZA, CD_FASE') }}
)

SELECT
    H.CD_ISTANZA, H.CD_FASE, H.TS_INIZIO_VALIDITA,
    {{ ts_fine_validita('H.CD_ISTANZA, H.CD_FASE', 'H.TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA,
    H.CD_WORKFLOW, H.CD_STATO_FASE, H.DS_STATO_FASE, H.TS_APERTURA_FASE, H.TS_CHIUSURA_FASE, H.FL_RILAVORATA,
    H.FL_RIAPRIBILE, H.CD_FASE_PREC, H.CD_FASE_PREC_2, H.LASTMODIFIEDDATA
FROM dedup H
