SELECT
  T.CACTPAN_CONTRATTO AS CD_PRATICA,
  'CA' AS TP_PROCEDURA,
  T.CACTPAN_PROGRESSIVO AS CD_PROGRESSIVO,
  {{ custom_to_timestamp_ntz('T.CACTPAN_DATA_STATO', 'T.CACTPAN_ORA_STATO', 'current') }} AS TS_INSERIMENTO, --TODO: verificare data_stato a 0
  T.CACTPAN_PAN AS CD_PAN,
  T.CACTPAN_PAN_SEQ_NUM AS CD_SEQ_NUM,
  T.CACTPAN_CIRCUITO AS CD_CIRCUITO,
  T.CACTPAN_ORIGINE AS CD_ORIGINE,
  {{ custom_to_date('T.CACTPAN_DATA_VALIDITA') }} AS DT_INIZIO_VALIDITA,
  {{ custom_to_date('T.CACTPAN_DATA_SCADENZA') }} AS DT_SCADENZA,
  {{ custom_to_timestamp_ntz('T.CACTPAN_DATA_ATTIVAZIONE', 'T.CACTPAN_ORA_ATTIVAZIONE') }} AS TS_ATTIVAZIONE,
  T.CACTPAN_EMETTITORE AS CD_EMETTITORE,
  T.CACTPAN_PRODOTTO AS CD_PRODOTTO,
  T.CACTPAN_RIF_EST_PROV AS CD_PROVIDER,
  T.CACTPAN_STATO AS CD_STATO,
  T.CACTPAN_PRG_PROVENIENZA AS PR_PAN_PROVENIENZA,
  T.CACTPAN_INTESTAZIONE AS DS_INTESTAZIONE,
  T.CACTPAN_TENTATIVI_PIN AS NM_TENTATIVI_PIN,
  T.CACTPAN_FLAG_TP_TECN AS TP_TESSERA,
  {{ custom_to_timestamp_ntz('T.CACTPAN_DATA_OPER', 'T.CACTPAN_ORA_OPER') }} AS TS_INSERIMENTO_OPERATORE,
  T.CACTPAN_UTE_OPER AS CD_OPERATORE,
  T.CACTPAN_DUAL_INTERFACE AS CD_CONTACT_LESS,
  {{ custom_to_date('T.CACTPAN_DATA_ATT_NFC') }} AS DT_ATTIV_NFC,
  {{ custom_to_date('T.CACTPAN_DATA_BL_AUTORIZ') }} AS DT_INZIO_BLOCCO_AUTORIZ,
  T.CACTPAN_COD_BLOCCO AS CD_BLOCCO,
  {{ custom_to_date('T.CACTPAN_BLOCCO_DATA_DA') }} AS DT_INIZIO_BLOCCO,
  T.LASTMODIFIEDDATA
FROM {{ ref('cactfpan') }} T
WHERE T.FL_DELETED = 'N'
{% if is_incremental() %}
AND T.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
