WITH blocchi_attivi AS (
  SELECT CAB_PRATICA, CAB_COD_BLOCCO_OCS, CAB_DATA_INIZIO, CAB_DATA_FINE
  FROM {{ ref('crcarblo') }}
  WHERE CAB_STATO = ' '
    AND CAB_ANNULLO = ' '
    AND CAB_COD_BLOCCO_OCS IN ('PP', 'CC')
),
blocchi_rt AS (
  SELECT CAB_PRATICA, CAB_COD_BLOCCO_OCS, CAB_DATA_INIZIO, CAB_DATA_FINE
  FROM {{ ref('crcarblo') }}
  WHERE CAB_STATO = ' '
    AND CAB_ANNULLO = ' '
    AND CAB_COD_BLOCCO_OCS = 'RT'
)
SELECT
  T.OXTRTRU_PRATICA AS CD_PRATICA,
  T.OXTRTRU_PROCEDURA AS TP_PROCEDURA,
  T.OXTRTRU_PROGRESSIVO AS PR_TRUFFA,
  {{ custom_to_timestamp_ntz('T.OXTRTRU_DATA_VARIAZIONE', 'T.OXTRTRU_ORA_VARIAZIONE') }} AS TS_INSERIMENTO,
  T.OXTRTRU_TRUFFA AS CD_TRUFFA,
  CASE
    WHEN T.OXTRTRU_PROCEDURA = 'CO' AND T.OXTRTRU_STATO = 'Accert' AND P.PLC_STATO IN ('50', '90', '55', '95', '96', '97') THEN 'Y'
    WHEN T.OXTRTRU_PROCEDURA = 'CA' AND T.OXTRTRU_STATO = 'Accert' AND (C.CRCAR_STATO IN ('30', '40', '55', '60', '70') OR EXISTS (SELECT 1 FROM blocchi_attivi B WHERE B.CAB_PRATICA = C.CRCAR_KEY_N AND B.CAB_DATA_INIZIO >= TO_CHAR(T.OXTRTRU_DATA_VARIAZIONE, 'YYYYMMDD') AND B.CAB_DATA_FINE < TO_CHAR(T.OXTRTRU_DATA_VARIAZIONE, 'YYYYMMDD'))) THEN 'Y'
    ELSE 'N'
  END AS FL_SUBITA,
  CASE
    WHEN T.OXTRTRU_PROCEDURA = 'CO' AND T.OXTRTRU_STATO = 'Accert' AND (P.PLC_STATO IN ('05', '10', '20', '30') OR P.PLC_ATTRIBUTO IN ('RE', 'RT')) THEN 'Y'
    WHEN T.OXTRTRU_PROCEDURA = 'CA' AND T.OXTRTRU_STATO = 'Accert' AND (C.CRCAR_STATO IN ('05', '10', '20', '35') OR EXISTS (SELECT 1 FROM blocchi_rt B WHERE B.CAB_PRATICA = C.CRCAR_KEY_N AND B.CAB_DATA_INIZIO >= TO_CHAR(T.OXTRTRU_DATA_VARIAZIONE, 'YYYYMMDD') AND B.CAB_DATA_FINE < TO_CHAR(T.OXTRTRU_DATA_VARIAZIONE, 'YYYYMMDD'))) THEN 'Y'
    ELSE 'N'
  END AS FL_SVENTATA,
  T.OXTRTRU_STATO AS CD_STATO_TRUFFA,
  CASE
    WHEN T.OXTRTRU_TRUFFA IN (FTP.OXTRPTR_TRUFFA_CLI, FTP.OXTRPTR_TRUFFA_CLI_2, FTP.OXTRPTR_TRUFFA_CLI_3, FTP.OXTRPTR_TRUFFA_CLI_4, FTP.OXTRPTR_TRUFFA_CLI_5) THEN 'TRUFFA_CLI'
    WHEN T.OXTRTRU_TRUFFA IN (FTP.OXTRPTR_TRUFFA_FURTO_IDE, FTP.OXTRPTR_TRUFFA_FURTO_IDE_2, FTP.OXTRPTR_TRUFFA_FURTO_IDE_3, FTP.OXTRPTR_TRUFFA_FURTO_IDE_4, FTP.OXTRPTR_TRUFFA_FURTO_IDE_5) THEN 'TRUFFA_FURTO_IDE'
    WHEN T.OXTRTRU_TRUFFA IN (FTP.OXTRPTR_TRUFFA_CV, FTP.OXTRPTR_TRUFFA_CV_2, FTP.OXTRPTR_TRUFFA_CV_3, FTP.OXTRPTR_TRUFFA_CV_4, FTP.OXTRPTR_TRUFFA_CV_5) THEN 'TRUFFA_CV'
    WHEN T.OXTRTRU_TRUFFA IN (FTP.OXTRPTR_TRUFFA_AG, FTP.OXTRPTR_TRUFFA_AG_2, FTP.OXTRPTR_TRUFFA_AG_3, FTP.OXTRPTR_TRUFFA_AG_4, FTP.OXTRPTR_TRUFFA_AG_5) THEN 'TRUFFA_AG'
    ELSE 'NON_CLASSIFICATA'
  END AS TP_TRUFFA,
  --TR.OXTRTTR_DESCRIZIONE AS DS_TRUFFA,
  NULL as DS_TRUFFA,
  T.OXTRTRU_ULTIMO_PRG AS FL_TRUFFA_ATTIVA,
  {{ custom_to_timestamp_ntz('T.OXTRTRU_DATA_INS', 'T.OXTRTRU_ORA_INS') }} AS TS_INS_TRUFFA,
  T.OXTRTRU_UTENTE_INS AS CD_UTENTE_INS_TRUFFA,
  {{ custom_to_timestamp_ntz('T.OXTRTRU_DATA_VARIAZIONE', 'T.OXTRTRU_ORA_VARIAZIONE') }} AS TS_VAR_TRUFFA,
  T.OXTRTRU_UTENTE_VARIAZIONE AS CD_UTENTE_VAR_TRUFFA,
  {{ custom_to_timestamp_ntz('T.OXTRTRU_DATA_ANNULLO', 'T.OXTRTRU_ORA_ANNULLO') }} AS TS_ANNULLO_TRUFFA,
  T.OXTRTRU_UTENTE_ANNULLO AS CD_UTENTE_ANNULLO_TRUFFA,
  {{ custom_to_timestamp_ntz('T.OXTRTRU_DATA_ACCERT', 'T.OXTRTRU_ORA_ACCERT') }} AS TS_ACCERTAM_TRUFFA,
  T.OXTRTRU_UTENTE_ACCERT AS CD_UTENTE_ACCERTAM_TRUFFA,
  {{ custom_to_timestamp_ntz('T.OXTRTRU_DATA_SOSPET', 'T.OXTRTRU_ORA_SOSPET') }} AS TS_SOSPETTO_TRUFFA,
  T.OXTRTRU_UTENTE_SOSPET AS CD_UTENTE_SOSPETTO_TRUFFA,
  T.LASTMODIFIEDDATA
FROM AGOS_DEV_16000.L0.OXTRFTRU_TEST T--{# {{ ref('oxtrftru') }} #} T
LEFT JOIN {{ ref('plprat') }} P ON T.OXTRTRU_PROCEDURA = 'CO' AND P.PLC_NUM_PRATICA = T.OXTRTRU_PRATICA
LEFT JOIN {{ ref('crcar') }} C ON T.OXTRTRU_PROCEDURA = 'CA' AND C.CRCAR_KEY_N = T.OXTRTRU_PRATICA
INNER JOIN AGOS_DEV_16000.L0.OXTRFPTR_TEST FTP --{# {{ ref('oxtrfptr') }} FTP #}
ON T.OXTRTRU_TRUFFA IN (FTP.OXTRPTR_TRUFFA_CLI, FTP.OXTRPTR_TRUFFA_CLI_2, FTP.OXTRPTR_TRUFFA_CLI_3, FTP.OXTRPTR_TRUFFA_CLI_4, FTP.OXTRPTR_TRUFFA_CLI_5, FTP.OXTRPTR_TRUFFA_FURTO_IDE, FTP.OXTRPTR_TRUFFA_FURTO_IDE_2, FTP.OXTRPTR_TRUFFA_FURTO_IDE_3, FTP.OXTRPTR_TRUFFA_FURTO_IDE_4, FTP.OXTRPTR_TRUFFA_FURTO_IDE_5, FTP.OXTRPTR_TRUFFA_CV, FTP.OXTRPTR_TRUFFA_CV_2, FTP.OXTRPTR_TRUFFA_CV_3, FTP.OXTRPTR_TRUFFA_CV_4, FTP.OXTRPTR_TRUFFA_CV_5, FTP.OXTRPTR_TRUFFA_AG, FTP.OXTRPTR_TRUFFA_AG_2, FTP.OXTRPTR_TRUFFA_AG_3, FTP.OXTRPTR_TRUFFA_AG_4, FTP.OXTRPTR_TRUFFA_AG_5)
AND TS_INSERIMENTO >= FTP.TS_INIZIO_VALIDITA
AND TS_INSERIMENTO < FTP.TS_FINE_VALIDITA
AND FTP.FL_DELETED = 'N'
--{# LEFT JOIN {{ ref('oxtrttr') }} TR ON T.OXTRTRU_TRUFFA = TR.OXTRTTR_TRUFFA #} --TODO archivio mancante
WHERE T.FL_DELETED = 'N'
AND T.OXTRTRU_ULTIMO_PRG = 'S'
{% if is_incremental() %}
AND T.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA),'1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
