select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(ITEMNUM AS NUMBER(10,0)) AS itemnum,
  COALESCE(TRY_TO_TIMESTAMP(ITEMDATE,'DD/MM/YYYY HH24:MI'), TRY_TO_TIMESTAMP(ITEMDATE,'DD/MM/YYYY')) as itemdate,
  TRY_CAST(CODICEPRATICA AS VARCHAR(25)) AS codicepratica,
  TRY_CAST(NUMEROPAGINE AS NUMBER(5,0)) AS numeropagine,
  TRY_CAST(TIPOARCHIVIAZIONE AS VARCHAR(25)) AS tipoarchiviazione,
  TRY_CAST(TIPOPRATICA AS VARCHAR(100)) AS tipopratica,
  TRY_CAST(AZIONESUFILE AS VARCHAR(15)) AS azionesufile,
  TRY_TO_TIMESTAMP(DATAORAFLUSSO,'DD/MM/YYYY HH24:MI') AS dataoraflusso,
  TRY_TO_TIMESTAMP(ONLINEPERAGOSDATAORA,'DD/MM/YYYY HH24:MI') AS onlineperagosdataora,
  TRY_CAST(ONLINEPERAGOS AS VARCHAR(5)) AS onlineperagos,
  TRY_TO_TIMESTAMP(DATAORACONSEGNATA,'DD/MM/YYYY HH24:MI') AS dataoraconsegnata,
  TRY_CAST(SLA AS NUMBER(2,0)) AS sla
from {{ source('source_l0','xerox_sla') }}
