SELECT
    T.DPRES_PROVENIENZA AS TP_PROVENIENZA,
    T.DPRES_PRATICA AS CD_PRATICA,
    {{ custom_to_date('T.DPRES_DATA') }} AS DT_OSSERVAZIONE,
    T.DPRES_AZIONE AS CD_AZIONE,
    B.REAZ_DES_AZIONE AS DS_AZIONE,
    T.DPRES_AZIONE_SISTEMA AS FL_AZIONE_SISTEMA,
    B.REAZ_TIPO_DOCUMENTO AS TP_DOCUMENTO,
    T.DPRES_DOCUMENTO AS DS_DOCUMENTO,
    {{ custom_to_date('B.REAZ_NUOVA_SCADENZA') }} AS DT_NUOVA_SCADENZA,
    B.REAZ_TIPO_SCADENZA AS TP_SCADENZA,
    B.REAZ_GIORNI AS NM_GIORNI,
    T.DPRES_ESITO AS TP_ESITO,
    B.REAZ_RIASS_OPERATORE AS DS_RIASS_OPERATORE,
    {{ custom_to_decimal('T.DPRES_IMPORTO', 13, 2) }} AS EU_IMPORTO,
    T.DPRES_UTENTE AS CD_UTENTE,
    T.DPRES_RECUPER AS CD_RECUPERATORE,
    T.DPRES_LEGALE AS CD_LEGALE
FROM {{ ref('re2praes') }} T
LEFT JOIN {{ ref('re2tabazi') }} B
    ON T.DPRES_AZIONE = B.REAZ_AZIONE
WHERE T.FL_DELETED = 'N'