-- PROCEDURA CONSUMO
SELECT
    'CO' AS TP_PROCEDURA,
    T.CHC_PRATICA AS CD_PRATICA,
    1 AS PR_CESSIONE,
    {{ custom_to_date('T.CHC_DATA_SITUAZIONE') }} AS DT_CESSIONE,
    {{ custom_to_decimal('T.CHC_CES_SCADUTO', 13, 2) }} AS EU_CESSIONE,
    {{ custom_to_decimal('T.CHC_CES_PERDITA', 13, 2) }} AS EU_PERDITA_CESSIONE,
    {{ custom_to_decimal('T.CHC_INCASSI_CUT_OFF', 13, 2) }} AS EU_INCASSO_CESSIONE,
    T.CHC_CESSIONARIO AS CD_CESSIONARIO
FROM {{ ref('plchices') }} T

UNION ALL

-- PROCEDURA CARTE
SELECT
    'CA' AS TP_PROCEDURA,
    T.CACSCES_CARTA AS CD_PRATICA,
    T.CACSCES_PROGRESSIVO AS PR_CESSIONE,
    {{ custom_to_date('T.CACSCES_DATA_ESTRAZIONE') }} AS DT_CESSIONE,
    {{ custom_to_decimal('T.CACSCES_TOT_CEDUTO', 13, 2) }} AS EU_CESSIONE,
    {{ custom_to_decimal('T.CACSCES_TOT_PERDITA', 13, 2) }} AS EU_PERDITA_CESSIONE,
    {{ custom_to_decimal('T.CACSCES_TOT_INC_CESSION', 13, 2) }} AS EU_INCASSO_CESSIONE,
    T.CACSCES_COD_CESSIONARIO AS CD_CESSIONARIO
FROM {{ ref('cacsfces') }} T