-- Procedura CONSUMO (CCPSVT + LEFT JOIN PLCHIEST)
SELECT
    T.PSVT_PROCEDURA AS TP_PROCEDURA,
    T.PSVT_PRATICA AS CD_PRATICA,
    T.PSVT_PROGRESSIVO AS PR_POSTVENDITA,
    {{ custom_to_date('T.PSVT_DATA_STATO') }} AS DT_CONTEGGIO,
    {{ custom_to_decimal('C.CHE_IMPORTO_RECUPERAT', 13, 2) }} AS EU_ESTINTO
FROM {{ ref('ccpsvt') }} T
LEFT JOIN {{ ref('plchiest') }} C
    ON T.PSVT_PRATICA = C.CHE_PRATICA
WHERE T.FL_DELETED = 'N'
  AND T.PSVT_PROCEDURA = 'CO'
  AND T.PSVT_STATO = '30'
  AND T.PSVT_BLOCCO = 'AC'

UNION ALL

-- Procedura CARTE (CCPSVT + LEFT JOIN CCPSVDEST)
SELECT
    T.PSVT_PROCEDURA AS TP_PROCEDURA,
    T.PSVT_PRATICA AS CD_PRATICA,
    T.PSVT_PROGRESSIVO AS PR_POSTVENDITA,
    {{ custom_to_date('T.PSVT_DATA_STATO') }} AS DT_CONTEGGIO,
    {{ custom_to_decimal('D.PSVD_EST_IMP_MIN_DOVUTO', 13, 2) }} AS EU_ESTINTO
FROM {{ ref('ccpsvt') }} T
LEFT JOIN {{ ref('ccpsvdest') }} D
    ON T.PSVT_PROGRESSIVO = D.PSVD_EST_PROGRESSIVO
WHERE T.FL_DELETED = 'N'
  AND T.PSVT_PROCEDURA = 'CA'
  AND T.PSVT_AZIONE = 'EST'

UNION ALL

-- Procedura CQS (QSESTINZ)
SELECT
    'CQ' AS TP_PROCEDURA,
    T.QESTI_NUM_PRATICA AS CD_PRATICA,
    1 AS PR_POSTVENDITA,
    {{ custom_to_date('T.QESTI_DATA_CALCOLO') }} AS DT_CONTEGGIO,
    {{ custom_to_decimal('T.QESTI_CED_TOTALE', 13, 2) }} AS EU_ESTINTO
FROM {{ ref('qsestinz') }} T