-- Procedura CONSUMO (PLCHIPERD)
SELECT
    'CO' AS TP_PROCEDURA,
    T.CHI_PRATICA AS CD_PRATICA,
    {{ custom_to_date('T.CHI_DATA_SITUAZIONE') }} AS DT_PERDITA,
    T.CHI_TIPOLOGIA AS TP_PERDITA,
    CASE
        WHEN T.CHI_TIPOLOGIA = 'BB' AND  COALESCE(B.TABTPP_CONCORDATA, 'N') = 'S' THEN 'S'
        ELSE 'N'
    END AS FL_SALDI_STRALCIO,
    T.CHI_CLASS_RISCHIO AS CD_FASCIA,
    {{ custom_to_decimal('T.CHI_CAPITALE_RESIDUO', 13, 2) }} AS EU_DOVUTO,
    {{ custom_to_decimal('T.CHI_TOTALE_IMPAGATO', 13, 2) }} AS EU_PROPOSTA,
    {{ custom_to_decimal('T.CHI_PERDITA', 13, 2) }} AS EU_PERDITA,
    T.CHI_OPERATORE AS CD_OPERATORE,
    T.CHI_CLIENTE AS CD_CLIENTE
FROM {{ ref('plchiperd') }} T
LEFT JOIN {{ ref('cctabtpp') }} B
    ON T.CHI_TIPOLOGIA = B.TABTPP_TIPO
    AND T.CHI_TIPOLOGIA = 'BB'
    AND B.FL_DELETED = 'N'

UNION ALL

-- Procedura CARTE (CACHFPER)
SELECT
    'CA' AS TP_PROCEDURA,
    T.CACHPER_CARTA AS CD_PRATICA,
    {{ custom_to_date('T.CACHPER_DATA_ESTRAZIONE') }} AS DT_PERDITA,
    T.CACHPER_TIPOL_PASPERD AS TP_PERDITA,
    CASE
        WHEN T.CACHPER_TIPOL_PASPERD = 'BB' AND COALESCE(B.TABTPP_CONCORDATA, 'N') = 'S' THEN 'S'
        ELSE 'N'
    END AS FL_SALDI_STRALCIO,
    NULL AS CD_FASCIA,
    {{ custom_to_decimal('T.CACHPER_TOT_IMPAGATO', 13, 2) }} AS EU_DOVUTO,
    {{ custom_to_decimal('T.CACHPER_CAPITALE_RESIDUO', 13, 2) }} AS EU_PROPOSTA,
    {{ custom_to_decimal('T.CACHPER_TOT_PERDITA', 13, 2) }} AS EU_PERDITA,
    NULL AS CD_OPERATORE,
    NULL AS CD_CLIENTE
FROM {{ ref('cachfper') }} T
LEFT JOIN {{ ref('cctabtpp') }} B
    ON T.CACHPER_TIPOL_PASPERD = B.TABTPP_TIPO
    AND T.CACHPER_TIPOL_PASPERD = 'BB'
    AND B.FL_DELETED = 'N'
WHERE T.FL_DELETED = 'N'