WITH CTE_AUMENTO_FIDO AS ( 
    SELECT 
        c.CRCAR_KEY_N,
        '01' AS CD_LIMITAZIONE,
        'AUMENTO_FIDO'  AS DS_LIMITAZIONE,
        MIN(B.CAB_DATA_INIZIO) AS DT_INIZIO_EFFETTO,  
        MAX(B.CAB_DATA_FINE) AS DT_FINE_EFFETTO
    FROM {{ ref('crcarblo') }} B
    JOIN {{ ref('crcar') }} C
    ON C.CRCAR_KEY_N = B.CAB_PRATICA
    WHERE  B.CAB_PROVENIENZA = 'CA'
      AND (B.CAB_COD_BLOCCO_OCS <> 'FF' OR B.CAB_COD_BLOCCO_OCS IS NULL)
    GROUP BY B.CAB_PRATICA,c.CRCAR_KEY_N
),
CTE_UTILIZZO AS (
    SELECT 
        c.CRCAR_KEY_N,
        '02' AS CD_LIMITAZIONE,
        'UTILIZZO'  AS DS_LIMITAZIONE,
        v.TS_INIZIO_VALIDITA AS DT_INIZIO_EFFETTO,
        v.TS_FINE_VALIDITA AS DT_FINE_EFFETTO 
    FROM {{ ref('crcar') }} C
    JOIN {{ ref('variazioni_stato_prat') }} v
    ON C.CRCAR_KEY_N = V.CD_PRATICA
    WHERE V.cd_stato = 60 
)
SELECT
    CRCAR_KEY_N AS CD_PRATICA,
    'CA' AS TP_PROCEDURA,
    CD_LIMITAZIONE,
    DS_LIMITAZIONE,
    {{ custom_to_date('DT_INIZIO_EFFETTO') }} AS DT_INIZIO_EFFETTO,
    {{ custom_to_date('DT_FINE_EFFETTO') }} AS DT_FINE_EFFETTO
FROM CTE_AUMENTO_FIDO
    UNION ALL 
SELECT
    CRCAR_KEY_N AS CD_PRATICA,
    'CA' AS TP_PROCEDURA,
    CD_LIMITAZIONE,
    DS_LIMITAZIONE,
    date(DT_INIZIO_EFFETTO) AS DT_INIZIO_EFFETTO,
    date(DT_FINE_EFFETTO) AS DT_FINE_EFFETTO
FROM CTE_UTILIZZO