SELECT
    CAST(T.CRMCC_CARTA_N AS NUMBER(16,0)) AS CD_PRATICA,
    CAST(T.CRMCC_EMETTITORE AS NUMBER(3,0)) AS CD_EMETTITORE,
    CAST('CA' AS VARCHAR(2)) AS TP_PROCEDURA,
    TO_DATE(
         CAST(T.CRMCC_DATA_AA AS NUMBER(4,0))  || '-' || LPAD(CAST(T.CRMCC_DATA_MM AS NUMBER(2,0)), 2, '0') || '-01',
        'YYYY-MM-DD'
    ) AS DT_OSSERVAZIONE,
    CAST(T.CRMCC_DATA_AA AS NUMBER(4,0)) AS NM_ANNO,
    CAST(T.CRMCC_DATA_MM AS NUMBER(2,0)) AS NM_MESE,
    {{ ole_to_date('T.CRMCC_DATA_V') }} AS DT_MOVIMENTO,
    CAST(T.CRMCC_PROGRESSIVO AS NUMBER(3,0)) AS NM_PROGRESSIVO,
    {{ custom_to_decimal('T.CRMCC_IMPORTO')}} AS EU_MOVIMENTO,
    {{ custom_to_decimal('T.CRMCC_TOTALE')}} AS EU_TOT_MOVIMENTO,
    CAST(T.CRMCC_CAUSALE AS NUMBER(3,0)) AS CD_CAUSALE_MOVIMENTO,
    CAST(T.CRMCC_DESCRIZIONE AS VARCHAR(60)) AS DS_MOVIMENTO,
    CAST(T.CRMCC_PROVENIENZA AS VARCHAR(1)) AS CD_PROVENIENZA_MOVIMENTO,
    CAST(T.CRMCC_TIPO_RECORD AS VARCHAR(1)) AS CD_TIPO_RECORD,
    COALESCE(TRY_CAST(T.CRMCC_CONTABILIZZATO AS BOOLEAN), FALSE) AS FL_CONTABILIZZATO,
    CAST(T.CRMCC_TIPO_RATA AS VARCHAR(1)) AS TP_RATA,
    CAST(T.CRMCC_RATA AS NUMBER(2,0)) AS NM_RATA,
    CAST(T.CRMCC_MESI_DILAZ AS NUMBER(3,0)) AS NM_MESI_DILAZIONE,
    CAST(T.CRMCC_NUM_RATE AS NUMBER(3,0)) AS NM_RATE_CAMPAGNA,
    {{ ole_to_date('T.CRMCC_DATA_ACQUISTO') }} AS DT_ACQUISTO,
    {{ ole_to_date('T.CRMCC_DATA_REGISTRAZIONE') }} AS DT_REGISTRAZIONE_TRANSAZIONE,
    {{ ole_to_date('T.CRMCC_DATA_VALUTA') }} AS DT_VALUTA
FROM {{ ref('creccc') }} T
WHERE T.FL_DELETED = 'N'
{% if is_incremental() %} 
AND DT_OSSERVAZIONE = {{ get_dt_osservazione() }} 
{% endif %} 