SELECT
    CAST(T.CRMCS_CARTA_N AS NUMBER(16)) AS CD_PRATICA,
    CAST(T.CRMCS_EMETTITORE AS NUMBER(3)) AS CD_EMETTITORE,
    CAST('CA' AS VARCHAR(2)) AS TP_PROCEDURA,
    TO_DATE(
        CAST(T.CRMCS_DATA_AA AS NUMBER(4)) || '-' || LPAD(CAST(T.CRMCS_DATA_MM AS NUMBER(2)), 2, '0') || '-01',
        'YYYY-MM-DD'
    ) AS DT_OSSERVAZIONE,
    CAST(T.CRMCS_DATA_AA AS NUMBER(4)) AS NM_ANNO,
    CAST(T.CRMCS_DATA_MM AS NUMBER(2)) AS NM_MESE,
    CAST(T.CRMCS_MOD_CALC_RATA AS VARCHAR(1)) AS TP_RATA,
    {{ custom_to_decimal('T.CRMCS_CREDIT_LIMIT')}} AS EU_CREDIT_LIMIT,
    T.CRMCS_PAG_FORMA AS TP_PAGAMENTO,
    N.CRECCAN_MOD_INVIO_EC AS TP_MODALITA_INVIO,
    T.CRMCS_NUM_PAGAMENTI AS NM_PAGAMENTI,
    T.CRMCS_NUM_INSOLUTI AS NM_INSOLUTI,
    T.CRMCS_NUM_ACQUISTI AS NM_ACQUISTI,
    T.CRMCS_NUM_ACQ_CAMP AS NM_ACQUISTI_CAMPAGNA,
    T.CRMCS_PROG_NUM_INSOLUTI AS NM_INSOLUTI_M,
    T.CRMCS_PROG_NUM_RATE_NONPERV AS NM_RATE_NON_PERVENUTE,
    {{ custom_to_decimal('T.CRMCS_SALDO_INIZIALE')}} AS EU_SALDO_INZIALE,
    {{ custom_to_decimal('T.CRMCS_PAGAMENTI')}} AS EU_PAGAMENTI_TOT,
    {{ custom_to_decimal('T.CRMCS_INSOLUTI')}} AS EU_INSOLUTI_TOT,
    {{ custom_to_decimal('T.CRMCS_ACQUISTI')}} AS EU_ACQUISTI_TOT,
    {{ custom_to_decimal('T.CRMCS_ACQ_CAMP')}} AS EU_ACQUISTI_TOT_CAMPAGNA,
    {{ custom_to_decimal('T.CRMCS_SALDO_FINALE')}} AS EU_SALDO_TOT,
    {{ custom_to_decimal('T.CRMCS_SALDO_FINALE_TOT')}} AS EU_SALDO_TOT_CAMPAGNA,
    {{ custom_to_decimal('T.CRMCS_DISPONIBILITA')}} AS EU_DISPONIBILITA_M,
    {{ custom_to_decimal('T.CRMCS_INIZ_CAPITALE')}} AS EU_CAPITALE_INIZIALE,
    {{ custom_to_decimal('T.CRMCS_CAPITALE_FINALE')}} AS EU_CAPITALE_FINALE,
    {{ custom_to_decimal('T.CRMCS_CAPITALE_FINALE_TOT')}} AS EU_CAPITALE_FINALE_TOT,
    CAST(T.CRMCS_TASSO_MENSILE AS NUMBER(7)) AS PC_TASSO,
    {{ custom_to_decimal('T.CRMCS_INIZ_INTERESSI_FIN')}} AS EU_INTERESSI_INIZIO,
    {{ custom_to_decimal('T.CRMCS_INIZ_INTERESSI_MORA')}} AS EU_INTERESSI_MORA_INIZIO,
    {{ custom_to_decimal('T.CRMCS_INTERESSI_FIN')}} AS EU_INTERESSI_FINE,
    {{ custom_to_decimal('T.CRMCS_INTERESSI_MORA')}} AS EU_INTERESSI_MORA_FINE,
    {{ custom_to_decimal('T.CRMCS_INTERESSI_CAMP')}} AS EU_INTERESSI_CAMPAGNA,
    {{ custom_to_decimal('T.CRMCS_RATE_ACQ_CAMP')}} AS EU_RATE_ACQ_CAMPAGNA,
    {{ custom_to_decimal('T.CRMCS_RATA_MINIMA')}} AS EU_RATA_MINIMA,
    {{ custom_to_decimal('T.CRMCS_RATA_EXTENDED')}} AS EU_RATA_EXTENDED
FROM {{ ref('crecca') }} T
LEFT JOIN {{ ref('creccanecs') }} N 
    ON T.CRMCS_CARTA_N = N.CRECCAN_CARTA_N
    AND T.CRMCS_EMETTITORE = N.CRECCAN_EMETTITORE
    AND T.CRMCS_DATA_AA = N.CRECCAN_DATA_AA
    AND T.CRMCS_DATA_MM = N.CRECCAN_DATA_MM
    AND N.FL_DELETED = 'N'
WHERE T.FL_DELETED = 'N'
{% if is_incremental() %} 
AND DT_OSSERVAZIONE = {{ last_day_past_month() }} 
{% endif %} 
