SELECT
    T.CAB_PRATICA AS CD_PRATICA,
    T.CAB_PROVENIENZA AS TP_PROCEDURA,
    T.CAB_PROGRESSIVO AS CD_PROGRESSIVO,
    T.CAB_COD_BLOCCO_OCS AS CD_BLOCCO_OCS,
    {{ custom_to_timestamp_ntz('T.CAB_DATA_IMMISSIONE', 'T.CAB_ORA_IMMISSIONE') }} AS TS_INSERIMENTO,
    T.CAB_AUTOMATICO AS FL_BLOCCO_AUTOMATICO,
    T.CAB_TIPO_BLOCCO AS TP_BLOCCO,
    {{ custom_to_date('T.CAB_DATA_INIZIO') }} AS DT_APERTURA_BLOCCO,
    {{ custom_to_date(column='T.CAB_DATA_FINE') }} AS DT_CHIUSURA_BLOCCO, -- FIX gestione manuale: CAB_DATA_FINE è NUMBER --> 99999999 non viene interpretato bene dalla macro to_date()
    CASE WHEN T.CAB_STATO = ' ' THEN 'Y' ELSE 'N' END AS FL_ATTIVO,
    {{ custom_to_date('T.CAB_DATA_IMMISSIONE') }} AS DT_INSERIMENTO,
    T.CAB_ORA_IMMISSIONE::TIMESTAMP_NTZ AS ORA_INSERIMENTO,
    T.CAB_OPE_IMMISSIONE AS CD_UTENTE_IMMISSIONE,
    T.CAB_PROGRAMMA_IMMISSIONE AS CD_PROGRAMMA_IMMISSIONE,
    T.CAB_PERIODO_EC_BLOCCO AS DS_EC_BLOCCANTE,
    {{ custom_to_timestamp_ntz('T.CAB_DATA_ANNULLO', 'T.CAB_ORA_ANNULLO') }} AS TS_ANNULLO,
    T.CAB_OPE_ANNULLO AS CD_UTENTE_ANNULLO,
    T.CAB_PROGRAMMA_ANNULLO AS CD_PROGRAMMA_ANNULLO,
    T.CAB_ANNULLO AS TP_ANNULLO,
    T.CAB_PERIODO_EC_SBLOCCO AS DS_EC_SBLOCCANTE,
    T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA -- WARN: LASTMODIFIEDDATA non presente nel data model, aggiunto dalla sorgente per S2
FROM {{ ref('crcarblo') }} T
WHERE T.FL_DELETED = 'N'
{% if is_incremental() %}
AND T.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
