SELECT
    a.CRAUT_AUTORIZZAZIONE AS CD_AUTORIZZAZIONE,
    a.CRAUT_EMETTITORE AS CD_EMETTITORE,
    'CA' AS CD_PROCEDURA,
    a.CRAUT_CARTA AS CD_PRATICA,
    a.TS_INIZIO_VALIDITA AS TS_INIZIO_VALIDITA,
    a.TS_FINE_VALIDITA AS TS_FINE_VALIDITA,
    a.CRAUT_TERM_POS AS CD_TERMINALE,
    a.CRAUT_PROVENIENZA AS TP_TERMINALE,
    a.CRAUT_STATO AS CD_STATO,
    a.CRAUT_ESITO AS CD_ESITO,
    a.CRAUT_MOTIVO AS CD_MOTIVO,
    a.CRAUT_CONVENZIONATO AS CD_CONVENZIONATO,
    a.CRAUT_TIPO AS TP_AUTORIZZAZIONE,
    a.CRAUT_TRANS_INTERNET AS TP_CANALE_TRANSAZIONE,
    {{ ole_to_timestamp('a.CRAUT_DATA','a.CRAUT_TIME') }}::TIMESTAMP_NTZ AS TS_AUTORIZZAZIONE,
    {{ ole_to_date('a.CRAUT_DATA_ACQUISTO')}} AS DT_ACQUISTO,
    {{ custom_to_decimal('a.CRAUT_IMPORTO',precision=11)}} AS EU_IMPORTO,
    {{ custom_to_decimal('a.CRAUT_COMM_ATM')}} AS EU_COMM_ATM,
    a.CRAUT_COMM_ATM_EXCL AS TP_COMM_ATM,
    a.CRAUT_CAMPAGNA AS CD_CAMPAGNA_FL_CAMPAGNA,
    s.SPATMSG_CARD_ACCEPTOR_ID AS CD_ESERCENTE,
    s.SPATMSG_CAT_MERC AS CD_MERC,
    p.SICCOD_MCC_DES AS DS_MERC,
    s.SPATMSG_NOME AS DS_ESERC,
    s.SPATMSG_ACQUIRER_ID AS CD_ACQUIRER,
    s.SPATMSG_POSTAL_CODE AS CD_CAP_ESERC,
    s.SPATMSG_NOME AS DS_NOME_ESERC,
    s.SPATMSG_LOCALITA AS DS_CITTA_ESERC,
    s.SPATMSG_COUNTRY AS CD_NAZIONE_ESERC,
    a.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
FROM {{ ref('craut') }} a
LEFT JOIN {{ ref('spatfmsg') }} s
    ON  s.SPATMSG_EME = a.CRAUT_EMETTITORE
    AND s.SPATMSG_AUT = a.CRAUT_AUTORIZZAZIONE
LEFT JOIN {{ ref('pssiccod') }} p
    ON  p.SICCOD_MCC_CODE = s.SPATMSG_CAT_MERC
    AND p.SICCOD_TABLE_NAME = 'SPATFMSG'
{% if is_incremental() %}
WHERE a.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA),'1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
OR (
    a.TS_FINE_VALIDITA > (SELECT COALESCE(MAX(TS_INIZIO_VALIDITA),'1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
    AND a.TS_FINE_VALIDITA < TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
)
{% endif %}
