select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(TAS_PROCEDURA) = '', ' ', RTRIM(TAS_PROCEDURA)) AS VARCHAR(2)) AS tas_procedura,
  TRY_CAST(TAS_AMMINISTRAZIONE AS NUMBER(9,0)) AS tas_amministrazione,
  TRY_CAST(IFF(RTRIM(TAS_PRODOTTO) = '', ' ', RTRIM(TAS_PRODOTTO)) AS VARCHAR(2)) AS tas_prodotto,
  TRY_CAST(IFF(RTRIM(TAS_CLASSE_IMPORTO) = '', ' ', RTRIM(TAS_CLASSE_IMPORTO)) AS VARCHAR(2)) AS tas_classe_importo,
  TRY_CAST(TAS_DURATA_FINO_A AS NUMBER(3,0)) AS tas_durata_fino_a,
  TRY_CAST(TAS_ETA_CLI_SCAD AS NUMBER(3,0)) AS tas_eta_cli_scad,
  TRY_CAST(TAS_TASSO_TAEG AS NUMBER(5,2)) AS tas_tasso_taeg,
  TRY_CAST(TAS_TASSO_TEG AS NUMBER(5,2)) AS tas_tasso_teg,
  TRY_CAST(TAS_PERC_DIMIN_TAEG AS NUMBER(5,2)) AS tas_perc_dimin_taeg,
  TRY_CAST(TAS_PERC_DIMIN_TEG AS NUMBER(5,2)) AS tas_perc_dimin_teg,
  TRY_CAST(IFF(RTRIM(TAS_SEDE) = '', ' ', RTRIM(TAS_SEDE)) AS VARCHAR(3)) AS tas_sede,
  TRY_CAST(TAS_PROGRESSIVO AS NUMBER(7,0)) AS tas_progressivo,
  TRY_CAST(IFF(RTRIM(TAS_CONVENZIONE) = '', ' ', RTRIM(TAS_CONVENZIONE)) AS VARCHAR(2)) AS tas_convenzione,
  TRY_CAST(IFF(RTRIM(TAS_CATEGORIA) = '', ' ', RTRIM(TAS_CATEGORIA)) AS VARCHAR(3)) AS tas_categoria,
  TRY_CAST(TAS_IMPORTO_FINO_A AS NUMBER(13,0)) AS tas_importo_fino_a,
  TRY_CAST(IFF(RTRIM(TAS_TEG_RIFERIMENTO) = '', ' ', RTRIM(TAS_TEG_RIFERIMENTO)) AS VARCHAR(1)) AS tas_teg_riferimento,
  TRY_CAST(TAS_TEG_PERC_DIMIN_TEGM AS NUMBER(5,2)) AS tas_teg_perc_dimin_tegm,
  TRY_CAST(TAS_TEG_PERC_AUMEN_TEGM AS NUMBER(5,2)) AS tas_teg_perc_aumen_tegm,
  TRY_CAST(TAS_TAEG_PERC_DIMIN_TEGM AS NUMBER(5,2)) AS tas_taeg_perc_dimin_tegm,
  TRY_CAST(TAS_TAEG_PERC_AUMEN_TEGM AS NUMBER(5,2)) AS tas_taeg_perc_aumen_tegm,
  TRY_CAST(TAS_DT_INI_VAL_DETT AS NUMBER(8,0)) AS tas_dt_ini_val_dett,
  TRY_CAST(TAS_DT_END_VAL_DETT AS NUMBER(8,0)) AS tas_dt_end_val_dett,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','ccbitasamm') }}
