-- Entita L2: BUDGET_ESTINZIONI_ANT_FILIALE  |  Storicizzazione: S4 (insert_overwrite)  |  Mapping 1:1
SELECT
    T.TP_BUDGET AS TP_BUDGET,
    T.DT_INIZIO_VALIDITA::TIMESTAMP_NTZ AS DT_INIZIO_VALIDITA,
    T.DT_FINE_VALIDITA::TIMESTAMP_NTZ AS DT_FINE_VALIDITA,
    T.NM_ANNO AS NM_ANNO,
    T.NM_MESE AS NM_MESE,
    T.TP_PROCEDURA AS TP_PROCEDURA,
    T.CD_GER_TERRITORIALE_1 AS CD_GER_TERRITORIALE_1,
    T.CD_GER_TERRITORIALE_2 AS CD_GER_TERRITORIALE_2,
    T.CD_GER_TERRITORIALE_3 AS CD_GER_TERRITORIALE_3,
    T.CD_GER_TERRITORIALE_4 AS CD_GER_TERRITORIALE_4,
    T.CD_NODO_FOGLIA AS CD_NODO_FOGLIA,
    T.CD_MERCATO_1 AS CD_MERCATO_1,
    T.CD_MERCATO_2 AS CD_MERCATO_2,
    T.CD_MERCATO_3 AS CD_MERCATO_3,
    T.CD_MERCATO_4 AS CD_MERCATO_4,
    T.EU_BDG_EST_ANT_TOT AS EU_BDG_EST_ANT_TOT,
    T.EU_BDG_EST_ANT_ESTERNE AS EU_BDG_EST_ANT_ESTERNE,
    T.PC_BDG_EST_ANT_ESTERN_SU_IMPIEG AS PC_BDG_EST_ANT_ESTERN_SU_IMPIEG
FROM {{ ref('budget_estinzioni_ant_filiale') }} T
