WITH PERIMETRO AS (
    SELECT
        p.CD_PRATICA,
        p.DT_OSSERVAZIONE,
        o.DRPRA_CAP_RESIDUO_VIGI,
        COALESCE(o.DRPRA_CAP_RESIDUO_VIGI, 0)
      + COALESCE(o.DRPRA_SCADUTO_IMPAGATO, 0)
      + COALESCE(o.DRPRA_SPE_INC_FUTURE, 0)
      + COALESCE(o.DRPRA_SALDO_MORA, 0)
      + COALESCE(o.DRPRA_ALTRI_ADDEBITI_TOTALI, 0)
      + COALESCE(o.DRPRA_BOLLO, 0)
      + COALESCE(o.DRPRA_COMMISSIONI_DILAZIONE, 0)
      - COALESCE(o.DRPRA_PAG_ANTICIPATI, 0)
      + COALESCE(o.DRPRA_RATEO_INTERESSI, 0)
        AS VALORE_DEFAULT
    FROM {{ ref('legame_cartolarizzazioni') }} p
    INNER JOIN {{ ref('oxdrfpra') }} o
        ON p.CD_PRATICA_CARTOLARIZZATA = o.DRPRA_PRATICA
        AND o.FL_DELETED = 'N'
),

FORB AS (
    SELECT
        p.CD_PRATICA,
        p.DT_OSSERVAZIONE,
        f.DT_RISTRUTTURAZIONE
    FROM PERIMETRO p
    LEFT JOIN {{ ref('forbearance_m') }} f
        ON f.CD_PRATICA = p.CD_PRATICA
       AND f.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
),

CTE_RATE_CAST AS (
    SELECT 
        DRPRA_PRATICA,
        {{ custom_to_date('DRPRA_DATA_ESTRAZIONE') }} AS DT_OSSERVAZIONE,
        DRPRA_N_RATE_SCADUTE_IMPAGATE
    FROM {{ ref('oxdrfpra') }}
    WHERE FL_DELETED = 'N'
),

RATE AS (
    SELECT
        p.CD_PRATICA,
        p.DT_OSSERVAZIONE,
        r.DRPRA_N_RATE_SCADUTE_IMPAGATE 
    FROM PERIMETRO p
    LEFT JOIN CTE_RATE_CAST r
        ON r.DRPRA_PRATICA = p.CD_PRATICA
        AND r.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
),

PRAT AS (
    SELECT
        p.CD_PRATICA,
        p.DT_OSSERVAZIONE,
        m.DT_PASSAGGIO_PERDITA,
        m.DT_CESSIONE
    FROM PERIMETRO p
    LEFT JOIN {{ ref('pratica_m') }} M
        ON m.CD_PRATICA = p.CD_PRATICA
       AND m.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
),

STATO_CRED AS(
    SELECT 
        CD_PRATICA,
        DT_OSSERVAZIONE,
        FL_DFLT_EBA
        FROM {{ ref('stato_creditizio_m') }}
),

STATUS_LOAN AS (
    SELECT
        p.CD_PRATICA,
        p.DT_OSSERVAZIONE,
        CASE
            WHEN COALESCE(rt.DRPRA_N_RATE_SCADUTE_IMPAGATE, 0) = 0
             AND COALESCE(p.DRPRA_CAP_RESIDUO_VIGI, 0) = 0
             AND COALESCE(p.VALORE_DEFAULT, 0) > 0
             AND pr.DT_CESSIONE IS NULL
             AND pr.DT_PASSAGGIO_PERDITA IS NULL
            THEN 'RDMD'

            WHEN COALESCE(rt.DRPRA_N_RATE_SCADUTE_IMPAGATE, 0) = 0
             AND COALESCE(p.DRPRA_CAP_RESIDUO_VIGI, 0) = 0
             AND COALESCE(p.VALORE_DEFAULT, 0) > 0
             AND (
                    pr.DT_CESSIONE IS NOT NULL
                 OR pr.DT_PASSAGGIO_PERDITA IS NOT NULL
                 )
            THEN 'DFLT'

            WHEN (
                    COALESCE(rt.DRPRA_N_RATE_SCADUTE_IMPAGATE, 0) <> 0
                 OR COALESCE(p.DRPRA_CAP_RESIDUO_VIGI, 0) <> 0
                 )
             AND st.FL_DFLT_EBA = 'S' -- FIX utilizzato fl_dflt_eba da stato creditizio
            THEN 'DFLT'

            WHEN COALESCE(rt.DRPRA_N_RATE_SCADUTE_IMPAGATE, 0) > 0
             AND fb.DT_RISTRUTTURAZIONE IS NOT NULL
            THEN 'RARR'

            WHEN COALESCE(rt.DRPRA_N_RATE_SCADUTE_IMPAGATE, 0) > 0
             AND fb.DT_RISTRUTTURAZIONE IS NULL
            THEN 'ARRE'

            WHEN COALESCE(rt.DRPRA_N_RATE_SCADUTE_IMPAGATE, 0) = 0
             AND fb.DT_RISTRUTTURAZIONE IS NOT NULL
            THEN 'RNAR'

            WHEN COALESCE(rt.DRPRA_N_RATE_SCADUTE_IMPAGATE, 0) = 0
             AND fb.DT_RISTRUTTURAZIONE IS NULL
            THEN 'RNAR'

            ELSE 'RESS'
        END AS COD_STATO
    FROM PERIMETRO p
    LEFT JOIN RATE rt
        ON rt.CD_PRATICA = p.CD_PRATICA
       AND rt.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
    LEFT JOIN FORB fb
        ON fb.CD_PRATICA = p.CD_PRATICA
       AND fb.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
    LEFT JOIN PRAT pr
        ON pr.CD_PRATICA = p.CD_PRATICA
       AND pr.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
    LEFT JOIN STATO_CRED st
        ON st.CD_PRATICA = p.CD_PRATICA
        AND st.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
)

SELECT
    CAST(LC.CD_PRATICA_CARTOLARIZZATA AS VARCHAR(2)) AS TP_PROCEDURA,
    PA.SCPRA_NUM_PRATICA AS CD_PRATICA,
    LC.DT_OSSERVAZIONE AS DT_OSSERVAZIONE,
    TR.OXCNTRAN_COD_VEICOLO AS CD_SOCIETA_VEICOLO,
    {{ custom_to_date('PA.SCPRA_DATA_CESSIONE') }} AS DT_SECUR,
    {{ custom_to_date('PA.SCPRA_DATA_RIACQUISTO') }} AS DT_RIACQUISTO,
    PA.SCPRA_RATA_CEDUTA_DAL AS NM_RATA_CEDUTA_DAL,
    PA.SCPRA_RATA_CEDUTA_AL AS NM_RATA_CEDUTA_AL,
    {{ custom_to_date('PA.SCPRA_SCAD_RATA_CED_DAL') }} AS DT_SCAD_RATA_CED_DAL,
    {{ custom_to_date('PA.SCPRA_SCAD_RATA_CED_AL') }} AS DT_SCAD_RATA_CED_AL,
    SL.COD_STATO AS TP_STATUS_LOAN,
    NULL AS FL_SRT, -- WARN: Da aggiungere campo in attesa
    PA.SCPRA_PRODOTTO AS CD_PRODOTTO,
    PA.SCPRA_TAB_FINANZ AS CD_TAB_FINANZ,
    PA.SCPRA_CLIENTE AS CD_CLIENTE,
    PA.SCPRA_FILIALE AS CD_FILIALE,
    PA.SCPRA_TIPO_PRODOTTO AS TP_TIPO_PRODOTTO,
    PA.SCPRA_CATEGORIA AS TP_CATEGORIA,
    PA.SCPRA_PROG_CESSIONE AS PR_PROG_CESSIONE,
    PA.SCPRA_PRG_TRAS_CESS AS PR_PRG_TRAS_CESS,
    PA.SCPRA_PRG_TRAS_RIAC AS PR_PRG_TRAS_RIAC,
    {{ custom_to_date('PA.SCPRA_DATA_DEC_PRAT') }} AS DT_DATA_DEC_PRAT, 
    {{ custom_to_date('PA.SCPRA_DATA_COMPET_CESSIONE') }} AS DT_DATA_COMPET_CESSIONE, 
    {{ custom_to_date('PA.SCPRA_DATA_CHIUSURA_TRANS') }} AS DT_DATA_CHIUSURA_TRANS, 
    {{ custom_to_decimal('PA.SCPRA_TOT_SPESE_INC_CED') }} AS EU_TOT_SPESE_INC_CED,
    {{ custom_to_decimal('PA.SCPRA_TOT_QINT_CED') }} AS EU_TOT_QINT_CED, 
    {{ custom_to_decimal('PA.SCPRA_TOT_QCAP_CED') }} AS EU_TOT_QCAP_CED, 
    {{ custom_to_decimal('PA.SCPRA_IMP_NOMIN_CED') }} AS EU_IMP_NOMIN_CED,
    {{ custom_to_decimal('PA.SCPRA_TOT_IMP_ASSICURAZ') }} AS EU_TOT_IMP_ASSICURAZ, 
    PA.SCPRA_RATEO_CESSIONE AS NM_RATEO_CESSIONE,
    PA.SCPRA_TAN_MODIF_PRAT AS PC_TAN_MODIF_PRAT,
    PA.SCPRA_DILAZ_RIPARTITA AS NM_DILAZ_RIPARTITA,
    PA.SCPRA_LETTERA_CESS AS FL_LETTERA_CESS,
    PA.SCPRA_LETTERA_RIAC AS FL_LETTERA_RIAC
FROM {{ ref('legame_cartolarizzazioni') }} LC
INNER JOIN {{ ref('plsecpra') }} PA
    ON PA.SCPRA_NUM_PRATICA = LC.CD_PRATICA
LEFT JOIN {{ ref('oxcnfces') }} CES
    ON PA.SCPRA_PROG_CESSIONE = CES.OXCNCES_PROGR_CSS
    AND CES.FL_DELETED = 'N'
LEFT JOIN {{ ref('oxcnftran') }} TR
    ON TR.OXCNTRAN_TRANSAZIONE = CES.OXCNCES_TRANSAZIONE
    AND TR.FL_DELETED='N'
LEFT JOIN STATUS_LOAN SL
    ON SL.CD_PRATICA = LC.CD_PRATICA_CARTOLARIZZATA
   AND SL.DT_OSSERVAZIONE = LC.DT_OSSERVAZIONE
{% if is_incremental() %} 
WHERE LC.DT_OSSERVAZIONE = {{ last_day_past_month() }} 
{% endif %} 