-- CONSUMO procedure
SELECT
    CASE 
        WHEN T.CONST_PROV_PRA_NEW = 'CO' THEN T.CONST_PROV_PRA_NEW 
        ELSE NULL 
    END AS TP_PROC_CONSOLIDANTE,
    T.CONST_NUM_PRA_NEW AS CD_PRATICA_CONSOLIDANTE,
    D.CONSD_NUM_RIGA AS NM_PROGRESSIVO,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS TS_INSERIMENTO, -- WARN: TS_INSERIMENTO specificato nel data model come CURRENT_TIMESTAMP()
    {{ custom_to_date('T.CONST_DATA_ULT_MOD') }} AS DT_DECORRENZA, -- -->  CONST_DATA_FINE non presente in L1
    D.CONSD_PROV_PRA_OLD AS TP_PROC_CONSOLIDATA,
    D.CONSD_NUM_PRA_OLD AS CD_PRATICA_CONSOLIDATA,
    T.CONST_STATO AS CD_STATO_CONSOLIDAMENTO,
    CASE 
        WHEN T.CONST_PRODOTTO = 'PRODOTTO CONSOLIDANTE' THEN T.CONST_PRODOTTO  
        ELSE NULL 
    END AS FL_A_RECUPERO,
    D.CONSD_TIPO_IMPEGNO AS TP_CONSOLIDAMENTO,
    T.CONST_COD_CLIENTE AS CD_CLIENTE,
    {{ custom_to_decimal('T.CONST_IMPORTO_TOTALE') }} AS EU_CONSOLIDAMENTO_TOT, -- FIX CONST_IMPORTO_TOTALE --> CONST_IMP_TOT
    {{ custom_to_decimal('T.CONST_IMPORTO_TOT_INT') }} AS EU_CONSOLIDAMENTO_TOT_INTERNO, -- FIX CONST_IMPORTO_TOTALE --> CONST_IMP_TOT_INT
    T.CONST_UTENTE_CARIC AS CD_UTENTE_CARICAMENTO,
    T.CONST_UTENTE_ULT_MOD AS CD_UTENTE_ULTIMA_MODIFICA,
    T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
FROM {{ ref('oxcofcocd') }} D 
LEFT JOIN {{ ref('oxcofcoct') }} T
ON D.CONSD_NUM_CONS = T.CONST_NUM_CONS
AND D.FL_DELETED='N'
WHERE T.CONST_PROV_PRA_NEW = 'CO' 
AND T.FL_DELETED='N' 
{% if is_incremental() %}
AND T.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}

UNION ALL

-- CQS procedure
SELECT
    'CQ' AS TP_PROC_CONSOLIDANTE, -- FIX: data model had 'CQS', adjusted to 'CQ' for VARCHAR(2) constraint
    A.QPRAL_NUM_PRATICA AS CD_PRATICA_CONSOLIDANTE,
    A.QPRAL_PROGRESSIVO AS NM_PROGRESSIVO, 
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS TS_INSERIMENTO, -- WARN: TS_INSERIMENTO non specificato nel data model, usato CURRENT_TIMESTAMP()
    {{ custom_to_date('A.QPRAL_DATA_DECORRENZA') }} AS DT_DECORRENZA, -- WARN: DT_FINE - TAB/COL non specificati per CQS
    A.QPRAL_PROV_PROCEDURA AS TP_PROC_CONSOLIDATA, 
    A.QPRAL_PRATICA AS CD_PRATICA_CONSOLIDATA,
    'UT' AS CD_STATO_CONSOLIDAMENTO,
    Q.QPR_PRODOTTO AS FL_A_RECUPERO,
    A.QPRAL_TIPO AS TP_CONSOLIDAMENTO,
    NULL AS CD_CLIENTE, -- WARN: CD_CLIENTE - TAB/COL non specificati per CQS
    {{ custom_to_decimal('A.QPRAL_RESIDUO') }} AS EU_CONSOLIDAMENTO_TOT,
    {{ custom_to_decimal('A.QPRAL_FONDO') }} AS EU_CONSOLIDAMENTO_TOT_INTERNO,
    NULL AS CD_UTENTE_CARICAMENTO, -- WARN: CD_UTENTE_CARICAMENTO - TAB/COL non specificati per CQS
    NULL AS CD_UTENTE_ULTIMA_MODIFICA, -- WARN: CD_UTENTE_ULTIMA_MODIFICA - TAB/COL non specificati per CQS
    A.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
FROM {{ ref('qspraal') }} A
LEFT JOIN {{ ref('qspra') }} Q ON A.QPRAL_NUM_PRATICA = Q.QPR_NUM_PRATICA
WHERE A.QPRAL_TIPO = 'I'
AND A.QPRAL_DA_ESTINGUERE = 'S'
AND A.QPRAL_FONDO = 0
AND A.FL_DELETED = 'N'
{% if is_incremental() %}
AND A.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}