WITH perimetro AS (
    SELECT
        T.PSVT_PRATICA AS CD_PRATICA,
        T.PSVT_PROCEDURA AS TP_PROCEDURA,
        -- WARN: DT_OSSERVAZIONE e DT_VARIAZIONE_PIANO condividono la stessa sorgente COL PSVT_DATA_STATO
        T.PSVT_DATA_STATO,
        T.PSVT_ORIGINE_RICHIESTA,
        T.PSVT_AZIONE,
        T.PSVT_DATA_INS,
        T.PSVT_BLOCCO,
        T.PSVT_TIPO_CARIC,
        T.PSVT_CANALE_ACQ,
        T.PSVT_TIPO_CONTATTO,
        T.PSVT_STATO,
        T.PSVT_STATO_PRAT_CAR,
        T.PSVT_GRIGLIA_SCORING,
        T.PSVT_ESITO_SCORING,
        T.PSVT_ESITO_APPROVAZIONE,
        T.PSVT_CAUS_RIFIUTO,
        T.PSVT_MOTIVO_OVERR,
        T.PSVT_ESITO_RICEZ,
        T.PSVT_PROGRAMMA,
        T.PSVT_MOTIVO_RICHIESTA,
        T.PSVT_MOTIVO_ESI,
        T.PSVT_PROGRESSIVO,
        T.PSVT_FILIALE,
        T.PSVT_AUTORE_OVERR,
        T.PSVT_KEY_EXT,
        T.PSVT_CAMPAGNA,
        T.PSVT_PROGRESSIVO_PAN,
        T.PSVT_PROGR_SIEBEL,
        T.PSVT_PRG_CAMPAGNA,
        T.PSVT_PROGRESSIVO_EXT,
        T.PSVT_DATA_TRASM,
        T.PSVT_DATA_RICEZ,
        T.PSVT_ATTRIB_BLOC,
        T.PSVT_CALCOLO_SCORING,
        T.PSVT_INVIO_COMUNICAZIONI,
        T.PSVT_LETTERA_RIFIUTO,
        T.PSVT_SCORE,
        T.PSVT_LIV_DELIBERA,
        T.PSVT_LIV_RESPINTA,
        T.PSVT_NOTE_1,
        T.PSVT_NOTE_2,
        T.LASTMODIFIEDDATA
    FROM {{ ref('ccpsvt') }} T
    LEFT JOIN {{ ref('plpsfdaif') }} P
        ON P.PLPSDAIF_EV_PSV_RIF = T.PSVT_PROGRESSIVO
        AND T.FL_DELETED = 'N'
    WHERE T.PSVT_STATO = '30'
        AND  {{ custom_is_not_null('T.PSVT_BLOCCO') }}
        AND T.PSVT_AZIONE IN ('RID', 'RIF')
        AND T.PSVT_ORIGINE_RICHIESTA = 'FLE'
        AND {{ custom_is_null('P.PLPSDAIF_DATA_REG') }}
)

SELECT
    -- PK
    A.CD_PRATICA,
    A.TP_PROCEDURA,
    {{ custom_to_date('A.PSVT_DATA_STATO') }} AS DT_OSSERVAZIONE,
    -- TS_INSERIMENTO (tecnico S2)
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS TS_INSERIMENTO,
    -- Campi business
    A.PSVT_DATA_STATO AS DT_VARIAZIONE_PIANO,
    -- WARN: DT_VARIAZIONE_PIANO ha tipo NUMBER(8) ma condivide PSVT_DATA_STATO con DT_OSSERVAZIONE; verificare se il mapping e' corretto
    CASE WHEN A.PSVT_ORIGINE_RICHIESTA = 'FLE' THEN 'S' END AS FL_FLESSIBILITA_CONTRATTUALE,
    CASE WHEN A.PSVT_AZIONE IN ('RID', 'RIF') THEN A.PSVT_AZIONE ELSE 'N' END AS TP_FLESSIBILITA,
    -- WARN: DT_FLESSIBILITA ha tipo NUMBER(8) nel data model ma la RT applica TO_DATE -> il tipo effettivo e' DATE
    CASE WHEN A.PSVT_AZIONE IN ('RID', 'RIF') THEN TO_DATE(A.PSVT_DATA_INS::VARCHAR, 'DD/MM/YYYY') END AS DT_FLESSIBILITA,
    A.PSVT_BLOCCO AS CD_BLOCCO_AZIONE,
    A.PSVT_ORIGINE_RICHIESTA AS CD_ORIGINE_RICHIESTA,
    A.PSVT_TIPO_CARIC AS TP_TIPO_CARIC,
    A.PSVT_CANALE_ACQ AS TP_CANALE_ACQ,
    A.PSVT_TIPO_CONTATTO AS TP_TIPO_CONTATTO,
    A.PSVT_AZIONE AS TP_AZIONE,
    A.PSVT_STATO AS TP_STATO,
    A.PSVT_STATO_PRAT_CAR AS TP_STATO_PRAT_CAR,
    A.PSVT_GRIGLIA_SCORING AS TP_GRIGLIA_SCORING,
    A.PSVT_ESITO_SCORING AS TP_ESITO_SCORING,
    A.PSVT_ESITO_APPROVAZIONE AS TP_ESITO_APPROVAZIONE,
    A.PSVT_CAUS_RIFIUTO AS TP_CAUS_RIFIUTO,
    A.PSVT_MOTIVO_OVERR AS TP_MOTIVO_OVERR,
    A.PSVT_ESITO_RICEZ AS TP_ESITO_RICEZ,
    A.PSVT_PROGRAMMA AS TP_PROGRAMMA,
    A.PSVT_ORIGINE_RICHIESTA AS TP_ORIGINE_RICHIESTA,
    A.PSVT_MOTIVO_RICHIESTA AS TP_MOTIVO_RICHIESTA,
    A.PSVT_MOTIVO_ESI AS TP_MOTIVO_ESI,
    A.PSVT_PROGRESSIVO AS PR_RICHEISTA,
    A.PSVT_FILIALE AS CD_FILIALE,
    A.PSVT_AUTORE_OVERR AS CD_AUTORE_OVERR,
    A.PSVT_KEY_EXT AS CD_KEY_EXT,
    A.PSVT_CAMPAGNA AS CD_CAMPAGNA,
    A.PSVT_PROGRESSIVO_PAN AS PR_PROGRESSIVO_PAN,
    A.PSVT_PROGR_SIEBEL AS PR_PROGR_SIEBEL,
    A.PSVT_PRG_CAMPAGNA AS PR_PRG_CAMPAGNA,
    A.PSVT_PROGRESSIVO_EXT AS PR_PROGRESSIVO_EXT,
    A.PSVT_DATA_STATO AS DT_DATA_STATO,
    A.PSVT_DATA_TRASM AS DT_DATA_TRASM,
    A.PSVT_DATA_RICEZ AS DT_DATA_RICEZ,
    A.PSVT_DATA_INS AS DT_DATA_INS,
    A.PSVT_ATTRIB_BLOC AS FL_ATTRIB_BLOC,
    A.PSVT_CALCOLO_SCORING AS FL_CALCOLO_SCORING,
    A.PSVT_BLOCCO AS FL_BLOCCO,
    A.PSVT_INVIO_COMUNICAZIONI AS FL_INVIO_COMUNICAZIONI,
    A.PSVT_LETTERA_RIFIUTO AS FL_LETTERA_RIFIUTO,
    A.PSVT_SCORE AS NM_SCORE,
    A.PSVT_LIV_DELIBERA AS NM_LIV_DELIBERA,
    A.PSVT_LIV_RESPINTA AS NM_LIV_RESPINTA,
    A.PSVT_NOTE_1 AS DS_NOTE_1,
    A.PSVT_NOTE_2 AS DS_NOTE_2,
    A.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
FROM perimetro A

{% if is_incremental() %}
WHERE A.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA),'1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}