SELECT
    OX.DRPRA_CLIENTE AS CD_CONTROPARTE,
    OX.DRPRA_PRATICA AS CD_PRATICA,
    OX.DRPRA_PROVENIENZA AS TP_PROCEDURA,
    {{ custom_to_timestamp_ntz('OX.DRPRA_DATA_ESTRAZIONE') }} AS TS_INSERIMENTO, 
    OX.DRPRA_GG_SCAD_IMPAGATO_CLI AS NM_GG_SCADUTO_EBA_CLI,
    OX.DRPRA_GG_SCADUTO_CLI AS NM_GG_SCADUTO_CLI,
    OX.DRPRA_GG_SCADUTO_CONT AS NM_GG_SCADUTO_CONT,
    {{ custom_to_decimal('OX.DRPRA_LIB588', decimal=3) }} AS EU_SCADUTO_IMPAG_EBA,
    {{ custom_to_decimal('(COALESCE(OX.DRPRA_SCADUTO_IMPAGATO, 0) + COALESCE(OX.DRPRA_CAP_RESIDUO_IAS_VIGI, 0) + COALESCE(OX.DRPRA_RATEO_INT_IAS, 0))', decimal=3) }} AS EU_IMPIEGO_TOT_EBA,
    LASTMODIFIEDDATA
FROM {{ ref('oxdrfpra') }} OX
WHERE OX.DRPRA_GG_SCAD_IMPAGATO_CLI > 0
   OR OX.DRPRA_GG_SCADUTO_CLI > 0
   OR OX.DRPRA_GG_SCADUTO_CONT > 0
   AND OX.FL_DELETED = 'N'
{% if is_incremental() %} 
AND LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA),'1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }}) 
{% endif %} 
