WITH progressivo_piano AS (
    SELECT
        OXCTPAFT_PROCEDURA,
        OXCTPAFT_NUM_PRATICA,
        OXCTPAFT_PROGRESSIVO
    FROM (
        SELECT
            OXCTPAFT_PROCEDURA,
            OXCTPAFT_NUM_PRATICA,
            OXCTPAFT_PROGRESSIVO,
            ROW_NUMBER() OVER (
                PARTITION BY OXCTPAFT_PROCEDURA, OXCTPAFT_NUM_PRATICA
                ORDER BY OXCTPAFT_PROGRESSIVO DESC, OXCTPAFT_VALIDITA_DAL DESC
            ) AS RN
        FROM {{ ref('oxctfpaft') }}
        WHERE FL_DELETED='N'
    ) T
    WHERE RN = 1 
),
accodate AS (
    SELECT
        D.OXCTPAFD_PROCEDURA,
        D.OXCTPAFD_NUM_PRATICA,
        COUNT(D.OXCTPAFD_PROCEDURA, D.OXCTPAFD_NUM_PRATICA, D.OXCTPAFD_PROGRESSIVO) OVER (
            PARTITION BY D.OXCTPAFD_PROCEDURA, D.OXCTPAFD_NUM_PRATICA, D.OXCTPAFD_PROGRESSIVO
        ) AS NM_RATE_ACCODATE
    FROM {{ ref('oxctfpafd') }} D
    JOIN progressivo_piano P
        ON D.OXCTPAFD_PROCEDURA = P.OXCTPAFT_PROCEDURA
        AND D.OXCTPAFD_NUM_PRATICA = P.OXCTPAFT_NUM_PRATICA
        AND D.OXCTPAFD_PROGRESSIVO = P.OXCTPAFT_PROGRESSIVO
    WHERE D.OXCTPAFD_DT_ACCODAMENTO IS NOT NULL
    AND D.FL_DELETED='N'
),
con AS (
    SELECT
        A.CD_PRATICA,
        A.TP_PROCEDURA,
        A.DT_OSSERVAZIONE,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 3  THEN DATEADD(MONTH, -3,  A.DT_PRIMA_SCADENZA) END AS DT_SIR_3,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 6  THEN DATEADD(MONTH, -6,  A.DT_PRIMA_SCADENZA) END AS DT_SIR_6,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 9  THEN DATEADD(MONTH, -9,  A.DT_PRIMA_SCADENZA) END AS DT_SIR_9,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 12 THEN DATEADD(MONTH, -12, A.DT_PRIMA_SCADENZA) END AS DT_SIR_12,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 18 THEN DATEADD(MONTH, -18, A.DT_PRIMA_SCADENZA) END AS DT_SIR_18,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 24 THEN DATEADD(MONTH, -24, A.DT_PRIMA_SCADENZA) END AS DT_SIR_24,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 30 THEN DATEADD(MONTH, -30, A.DT_PRIMA_SCADENZA) END AS DT_SIR_30,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 36 THEN DATEADD(MONTH, -36, A.DT_PRIMA_SCADENZA) END AS DT_SIR_36,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -3,  A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BCD.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_3,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -6,  A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BPLC.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_6,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -9,  A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BPLC.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_9,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -12, A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BPLC.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_12,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -18, A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BPLC.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_18,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -24, A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BPLC.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_24,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -30, A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BPLC.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_30,
        CASE WHEN DATEDIFF('month', DATEADD(MONTH, -36, A.DT_PRIMA_SCADENZA), A.DT_OSSERVAZIONE) = 0 AND BPLC.OXSSSSIM_CURDEL >= 2 THEN 'S' ELSE 'N' END AS FL_RATE_IMPAG_36,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 3  THEN 'S' ELSE 'N' END AS FL_SIR_3,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 6  THEN 'S' ELSE 'N' END AS FL_SIR_6,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 9  THEN 'S' ELSE 'N' END AS FL_SIR_9,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 12 THEN 'S' ELSE 'N' END AS FL_SIR_12,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 18 THEN 'S' ELSE 'N' END AS FL_SIR_18,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 24 THEN 'S' ELSE 'N' END AS FL_SIR_24,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 30 THEN 'S' ELSE 'N' END AS FL_SIR_30,
        CASE WHEN DATEDIFF('month', A.DT_PRIMA_SCADENZA, A.DT_OSSERVAZIONE) >= 36 THEN 'S' ELSE 'N' END AS FL_SIR_36,
        BCD.OXSSSSIM_CURDEL_M AS NM_IMPAGATE,
        BCD.OXSSSSIM_CURDEL   AS NM_MAX_RATE_IMPAGATE,
        CC.NM_RATE_ACCODATE
    FROM {{ ref('pratica_m') }} A
    LEFT JOIN {{ ref('oxssfssim') }} BCD
        ON A.CD_PRATICA = BCD.OXSSSSIM_PRATICA
        AND A.TP_PROCEDURA = BCD.OXSSSSIM_PROCEDURA
        AND BCD.FL_DELETED='N'
    LEFT JOIN {{ ref('oxssfssim') }} BPLC
        ON A.CD_PRATICA = BPLC.OXSSSSIM_PRATICA
        AND BPLC.FL_DELETED='N'
    LEFT JOIN accodate CC
        ON A.CD_PRATICA = CC.OXCTPAFD_NUM_PRATICA
        AND A.TP_PROCEDURA = CC.OXCTPAFD_PROCEDURA
),
car AS (
    SELECT
        A.CD_PRATICA,
        A.TP_PROCEDURA,
        A.DT_OSSERVAZIONE,
        CAST(NULL AS DATE)    AS DT_SIR_3,
        CAST(NULL AS DATE)    AS DT_SIR_6,
        CAST(NULL AS DATE)    AS DT_SIR_9,
        CAST(NULL AS DATE)    AS DT_SIR_12,
        CAST(NULL AS DATE)    AS DT_SIR_18,
        CAST(NULL AS DATE)    AS DT_SIR_24,
        CAST(NULL AS DATE)    AS DT_SIR_30,
        CAST(NULL AS DATE)    AS DT_SIR_36,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_3,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_6,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_9,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_12,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_18,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_24,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_30,
        CAST(NULL AS VARCHAR) AS FL_RATE_IMPAG_36,
        CAST(NULL AS VARCHAR) AS FL_SIR_3,
        CAST(NULL AS VARCHAR) AS FL_SIR_6,
        CAST(NULL AS VARCHAR) AS FL_SIR_9,
        CAST(NULL AS VARCHAR) AS FL_SIR_12,
        CAST(NULL AS VARCHAR) AS FL_SIR_18,
        CAST(NULL AS VARCHAR) AS FL_SIR_24,
        CAST(NULL AS VARCHAR) AS FL_SIR_30,
        CAST(NULL AS VARCHAR) AS FL_SIR_36,
        BCD.OXSSSSIM_CURDEL_M AS NM_IMPAGATE,
        BCD.OXSSSSIM_CURDEL   AS NM_MAX_RATE_IMPAGATE,
        CC.NM_RATE_ACCODATE
    FROM {{ ref('carta_m') }} A
    LEFT JOIN {{ ref('oxssfssim') }} BCD
        ON A.CD_PRATICA = BCD.OXSSSSIM_PRATICA
        AND A.TP_PROCEDURA = BCD.OXSSSSIM_PROCEDURA
        AND BCD.FL_DELETED='N'
    LEFT JOIN accodate CC
        ON A.CD_PRATICA = CC.OXCTPAFD_NUM_PRATICA
        AND A.TP_PROCEDURA = CC.OXCTPAFD_PROCEDURA
)

SELECT
    CD_PRATICA,
    TP_PROCEDURA,
    DT_OSSERVAZIONE,
    DT_SIR_3,
    DT_SIR_6,
    DT_SIR_9,
    DT_SIR_12,
    DT_SIR_18,
    DT_SIR_24,
    DT_SIR_30,
    DT_SIR_36,
    FL_RATE_IMPAG_3,
    FL_RATE_IMPAG_6,
    FL_RATE_IMPAG_9,
    FL_RATE_IMPAG_12,
    FL_RATE_IMPAG_18,
    FL_RATE_IMPAG_24,
    FL_RATE_IMPAG_30,
    FL_RATE_IMPAG_36,
    FL_SIR_3,
    FL_SIR_6,
    FL_SIR_9,
    FL_SIR_12,
    FL_SIR_18,
    FL_SIR_24,
    FL_SIR_30,
    FL_SIR_36,
    NM_IMPAGATE,
    NM_MAX_RATE_IMPAGATE,
    NM_RATE_ACCODATE
FROM (
    SELECT
        CD_PRATICA,
        TP_PROCEDURA,
        DT_OSSERVAZIONE,
        DT_SIR_3,
        DT_SIR_6,
        DT_SIR_9,
        DT_SIR_12,
        DT_SIR_18,
        DT_SIR_24,
        DT_SIR_30,
        DT_SIR_36,
        FL_RATE_IMPAG_3,
        FL_RATE_IMPAG_6,
        FL_RATE_IMPAG_9,
        FL_RATE_IMPAG_12,
        FL_RATE_IMPAG_18,
        FL_RATE_IMPAG_24,
        FL_RATE_IMPAG_30,
        FL_RATE_IMPAG_36,
        FL_SIR_3,
        FL_SIR_6,
        FL_SIR_9,
        FL_SIR_12,
        FL_SIR_18,
        FL_SIR_24,
        FL_SIR_30,
        FL_SIR_36,
        NM_IMPAGATE,
        NM_MAX_RATE_IMPAGATE,
        NM_RATE_ACCODATE
    FROM con
    UNION ALL
    SELECT
        CD_PRATICA,
        TP_PROCEDURA,
        DT_OSSERVAZIONE,
        DT_SIR_3,
        DT_SIR_6,
        DT_SIR_9,
        DT_SIR_12,
        DT_SIR_18,
        DT_SIR_24,
        DT_SIR_30,
        DT_SIR_36,
        FL_RATE_IMPAG_3,
        FL_RATE_IMPAG_6,
        FL_RATE_IMPAG_9,
        FL_RATE_IMPAG_12,
        FL_RATE_IMPAG_18,
        FL_RATE_IMPAG_24,
        FL_RATE_IMPAG_30,
        FL_RATE_IMPAG_36,
        FL_SIR_3,
        FL_SIR_6,
        FL_SIR_9,
        FL_SIR_12,
        FL_SIR_18,
        FL_SIR_24,
        FL_SIR_30,
        FL_SIR_36,
        NM_IMPAGATE,
        NM_MAX_RATE_IMPAGATE,
        NM_RATE_ACCODATE
    FROM car
) AS unioned
{% if is_incremental() %}
WHERE DT_OSSERVAZIONE = {{ get_dt_osservazione() }}
{% endif %}