{#
SEGNALAZIONE entità mensile ma con storicizzazione giornaliera S2
TS_INSERIMENTO --> CURRENT_TIMESTAMP()
#}

WITH PERIMETRO AS (
    SELECT
        CC.PSVT_PRATICA,
        CC.PSVT_PROCEDURA,
        {{ custom_to_date('CC.PSVT_DATA_STATO') }} AS PSVT_DATA_STATO,
        CC.PSVT_AZIONE,
        {{ custom_to_date('CC.PSVT_DATA_INS') }} AS PSVT_DATA_INS,
        CC.PSVT_TIPO_CARIC,
        CC.PSVT_CANALE_ACQ,
        CC.PSVT_TIPO_CONTATTO,
        CC.PSVT_STATO,
        CC.PSVT_STATO_PRAT_CAR,
        CC.PSVT_GRIGLIA_SCORING,
        CC.PSVT_ESITO_SCORING,
        CC.PSVT_ESITO_APPROVAZIONE,
        CC.PSVT_CAUS_RIFIUTO,
        CC.PSVT_MOTIVO_OVERR,
        CC.PSVT_ESITO_RICEZ,
        CC.PSVT_PROGRAMMA,
        CC.PSVT_ORIGINE_RICHIESTA,
        CC.PSVT_MOTIVO_RICHIESTA,
        CC.PSVT_MOTIVO_ESI,
        CC.PSVT_PROGRESSIVO,
        CC.PSVT_FILIALE,
        CC.PSVT_AUTORE_OVERR,
        CC.PSVT_KEY_EXT,
        CC.PSVT_CAMPAGNA,
        CC.PSVT_PROGRESSIVO_PAN,
        CC.PSVT_PROGR_SIEBEL,
        CC.PSVT_PRG_CAMPAGNA,
        CC.PSVT_PROGRESSIVO_EXT,
        {{ custom_to_date('CC.PSVT_DATA_TRASM') }} AS PSVT_DATA_TRASM, 
        {{ custom_to_date('CC.PSVT_DATA_RICEZ') }} AS PSVT_DATA_RICEZ, 
        CC.PSVT_ATTRIB_BLOC,
        CC.PSVT_CALCOLO_SCORING,
        CC.PSVT_BLOCCO,
        CC.PSVT_INVIO_COMUNICAZIONI,
        CC.PSVT_LETTERA_RIFIUTO,
        CC.PSVT_SCORE,
        CC.PSVT_LIV_DELIBERA,
        CC.PSVT_LIV_RESPINTA,
        CC.PSVT_NOTE_1,
        CC.PSVT_NOTE_2,
        CC.LASTMODIFIEDDATA,
        OX.OXPSRIO_MORATORIA,
        OX.OXPSRIO_ORIGINE_RICHIESTA
    FROM {{ ref('ccpsvt') }} CC
    LEFT JOIN {{ ref('oxpsfrio') }} OX
        ON OX.OXPSRIO_ORIGINE_RICHIESTA = CC.PSVT_MOTIVO_RICHIESTA
        AND OX.FL_DELETED='N'
    WHERE OX.OXPSRIO_ORIGINE_RICHIESTA IS NOT NULL
    AND CC.FL_DELETED='N' 
)

SELECT
    PERIMETRO.PSVT_PRATICA AS CD_PRATICA,
    PERIMETRO.PSVT_PROCEDURA AS TP_PROCEDURA,
    {{ custom_to_date('PERIMETRO.PSVT_DATA_STATO') }} AS DT_OSSERVAZIONE,
    CASE
        WHEN PERIMETRO.OXPSRIO_MORATORIA = 'S' THEN PERIMETRO.PSVT_AZIONE
    END AS TP_MORATORIA,
    CASE
        WHEN PERIMETRO.OXPSRIO_ORIGINE_RICHIESTA IS NOT NULL THEN 'S'
    END AS FL_MORATORIA,
    CASE
        WHEN PERIMETRO.OXPSRIO_MORATORIA = 'S' THEN {{ custom_to_date('PERIMETRO.PSVT_DATA_INS') }}
    END AS DT_MORATORIA,
    PERIMETRO.PSVT_TIPO_CARIC AS TP_TIPO_CARIC,
    PERIMETRO.PSVT_CANALE_ACQ AS TP_CANALE_ACQ,
    PERIMETRO.PSVT_TIPO_CONTATTO AS TP_TIPO_CONTATTO,
    PERIMETRO.PSVT_AZIONE AS TP_AZIONE,
    PERIMETRO.PSVT_STATO AS TP_STATO,
    PERIMETRO.PSVT_STATO_PRAT_CAR AS TP_STATO_PRAT_CAR,
    PERIMETRO.PSVT_GRIGLIA_SCORING AS TP_GRIGLIA_SCORING,
    PERIMETRO.PSVT_ESITO_SCORING AS TP_ESITO_SCORING,
    PERIMETRO.PSVT_ESITO_APPROVAZIONE AS TP_ESITO_APPROVAZIONE,
    PERIMETRO.PSVT_CAUS_RIFIUTO AS TP_CAUS_RIFIUTO,
    PERIMETRO.PSVT_MOTIVO_OVERR AS TP_MOTIVO_OVERR,
    PERIMETRO.PSVT_ESITO_RICEZ AS TP_ESITO_RICEZ,
    PERIMETRO.PSVT_PROGRAMMA AS TP_PROGRAMMA,
    PERIMETRO.PSVT_ORIGINE_RICHIESTA AS TP_ORIGINE_RICHIESTA,
    PERIMETRO.PSVT_MOTIVO_RICHIESTA AS TP_MOTIVO_RICHIESTA,
    PERIMETRO.PSVT_MOTIVO_ESI AS TP_MOTIVO_ESI,
    PERIMETRO.PSVT_PROGRESSIVO AS PR_RICHEISTA,
    PERIMETRO.PSVT_FILIALE AS CD_FILIALE,
    PERIMETRO.PSVT_AUTORE_OVERR AS CD_AUTORE_OVERR,
    PERIMETRO.PSVT_KEY_EXT AS CD_KEY_EXT,
    PERIMETRO.PSVT_CAMPAGNA AS CD_CAMPAGNA,
    PERIMETRO.PSVT_PROGRESSIVO_PAN AS PR_PROGRESSIVO_PAN,
    PERIMETRO.PSVT_PROGR_SIEBEL AS PR_PROGR_SIEBEL,
    PERIMETRO.PSVT_PRG_CAMPAGNA AS PR_PRG_CAMPAGNA,
    PERIMETRO.PSVT_PROGRESSIVO_EXT AS PR_PROGRESSIVO_EXT,
    PERIMETRO.PSVT_DATA_STATO AS DT_DATA_STATO,
    PERIMETRO.PSVT_DATA_TRASM AS DT_DATA_TRASM,
    PERIMETRO.PSVT_DATA_RICEZ AS DT_DATA_RICEZ,
    PERIMETRO.PSVT_DATA_INS AS DT_DATA_INS,
    PERIMETRO.PSVT_ATTRIB_BLOC AS FL_ATTRIB_BLOC,
    PERIMETRO.PSVT_CALCOLO_SCORING AS FL_CALCOLO_SCORING,
    PERIMETRO.PSVT_BLOCCO AS FL_BLOCCO,
    PERIMETRO.PSVT_INVIO_COMUNICAZIONI AS FL_INVIO_COMUNICAZIONI,
    PERIMETRO.PSVT_LETTERA_RIFIUTO AS FL_LETTERA_RIFIUTO,
    PERIMETRO.PSVT_SCORE AS NM_SCORE,
    PERIMETRO.PSVT_LIV_DELIBERA AS NM_LIV_DELIBERA,
    PERIMETRO.PSVT_LIV_RESPINTA AS NM_LIV_RESPINTA,
    PERIMETRO.PSVT_NOTE_1 AS DS_NOTE_1,
    PERIMETRO.PSVT_NOTE_2 AS DS_NOTE_2,
    PERIMETRO.LASTMODIFIEDDATA AS LASTMODIFIEDDATA,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS TS_INSERIMENTO -- WARN: non presente nel data model ma necessaria per storicizzazione S2
FROM PERIMETRO
{% if is_incremental() %}
WHERE PERIMETRO.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}