WITH
CTE_MAIN AS (
    SELECT
        DRPRA_PROVENIENZA AS TP_PROCEDURA,
        DRPRA_PRATICA AS CD_PRATICA,
        {{ custom_to_date('DRPRA_DATA_ESTRAZIONE') }} AS DT_OSSERVAZIONE,
        DRPRA_STATUS_RISCHIO AS CD_QUALITA_CREDITIZIA,
        DRPRA_STAGE AS CD_STAGE_BKI,
        CASE
        WHEN DRPRA_STATUS_RISCHIO IN ('SO','O2','IN')
        THEN 'S'
        ELSE 'N'
        END AS FL_DFLT_EBA,
        LASTMODIFIEDDATA
    FROM {{ ref('oxdrfpra') }}
    WHERE FL_DELETED = 'N'
),
CTE_LEGAME_CONTROPARTE AS (
    SELECT
        CD_PRATICA,
        TP_PROCEDURA,
        CD_CONTROPARTE AS CD_CONTROPARTE
    FROM {{ ref('legame_pratica_controparte') }}
)
SELECT
    M.TP_PROCEDURA,
    M.CD_PRATICA,
    M.DT_OSSERVAZIONE,
    LCONT.CD_CONTROPARTE,
    M.CD_QUALITA_CREDITIZIA,
    M.CD_STAGE_BKI,
    M.FL_DFLT_EBA,
    M.LASTMODIFIEDDATA
FROM CTE_MAIN AS M
LEFT JOIN CTE_LEGAME_CONTROPARTE AS LCONT
    ON M.CD_PRATICA = LCONT.CD_PRATICA AND M.TP_PROCEDURA = LCONT.TP_PROCEDURA
{% if is_incremental() %}
  WHERE M.DT_OSSERVAZIONE = {{ last_day_past_month() }}
{% endif %}
