{# SEGNALAZIONI DI SVILUPPO

In CTE_BASE la conversione in TO_DATE risulta con errore in quanto in campo SVCRSC_MESE_ESTRAZIONE è presente un valore non idoneo
2017-[13]-01. Al momento per la eseguibilità delle CTE utilizzato un CASE WHEN per superare log di errore bloccante.

svcrsc_voce_bilancio
#}
SELECT
    CURR.SVCRSC_PRATICA AS CD_PRATICA,
    CURR.SVCRSC_PROCEDURA AS TP_PROCEDURA,
    CASE
            WHEN CURR.SVCRSC_MESE_ESTRAZIONE > 12
            THEN TO_DATE(CURR.SVCRSC_ANNO_ESTRAZIONE || '-12-01', 'YYYY-MM-DD') -- aggiunto questo controllo perché c'è un data 2017-13-01
            ELSE
            LAST_DAY(
            TO_DATE(CURR.SVCRSC_ANNO_ESTRAZIONE || '-' || CURR.SVCRSC_MESE_ESTRAZIONE || '-01', 'YYYY-MM-DD')
            )
        END AS DT_OSSERVAZIONE,
    CASE
        WHEN NVL(PREV.SVCRSC_FONDO_TOTALE, 0) <> 0 AND NVL(CURR.SVCRSC_FONDO_TOTALE, 0) <> 0
             THEN 'UGU'
        WHEN NVL(PREV.SVCRSC_FONDO_TOTALE, 0) = 0  AND NVL(CURR.SVCRSC_FONDO_TOTALE, 0) <> 0
             THEN 'ENT'
        WHEN NVL(PREV.SVCRSC_FONDO_TOTALE, 0) <> 0 AND NVL(CURR.SVCRSC_FONDO_TOTALE, 0) = 0
             THEN 'USC'
        ELSE 'ND'
    END AS CD_STATO_SVALZ,
    {{ custom_to_decimal('CURR.SVCRSC_FONDO_TOTALE', precision=11) }} AS EU_SVALUTAZIONE,
    {{ custom_to_decimal('(NVL(CURR.SVCRSC_FSC_ACCANTONAMENTO, 0) + NVL(CART.SVCRSC_FSC_ACCANTONAMENTO,   0))', precision=11) }} AS EU_INCREMENTO,
    {{ custom_to_decimal('(NVL(CURR.SVCRSC_FSC_RIPRESA_VALUTAZ, 0) + NVL(CART.SVCRSC_FSC_RIPRESA_VALUTAZ, 0))', precision=11) }} AS EU_RIPRESA,
    {{ custom_to_decimal('(NVL(CURR.SVCRSC_FSC_RIPRESA_INCASSO, 0) + NVL(CART.SVCRSC_FSC_RIPRESA_INCASSO, 0))', precision=11) }} AS EU_REALIZZO,
    {{ custom_to_decimal('(NVL(CURR.SVCRSC_FSC_UTILIZZO_FONDO, 0) + NVL(CART.SVCRSC_FSC_UTILIZZO_FONDO,   0))', precision=11) }} AS EU_UTILIZZO_FONDO,
    {{ custom_to_decimal('(
        CASE
            WHEN CURR.SVCRSC_MESE_ESTRAZIONE = 1 THEN 0
            ELSE NVL(CURR.SVCRSC_FSC_RIPRESA_INCASSO, 0) - NVL(PREC_BASE.SVCRSC_FSC_RIPRESA_INCASSO, 0)
        END
        +
        CASE
            WHEN B.CD_PRATICA_CARTOLARIZZATA IS NULL THEN 0
            WHEN CURR.SVCRSC_MESE_ESTRAZIONE = 1 THEN 0
            ELSE NVL(CART.SVCRSC_FSC_RIPRESA_INCASSO, 0) - NVL(PREC_CART.SVCRSC_FSC_RIPRESA_INCASSO, 0)
        END
    )', precision=11) }} AS EU_UTILE_CESS,
    CURR.SVCRSC_STAGE_IFRS9 AS NM_STAGE,
    CASE
        WHEN  {{ custom_is_not_null('CURR.SVCRSC_COD_TRANSAZIONE') }} AND CURR.SVCRSC_COD_TRANSAZIONE <> '' THEN 'S'
        ELSE 'N'
    END AS FL_PRATICA_CARTOLARIZZATA, 
    CURR.SVCRSC_CLIENTE AS CD_CLIENTE,
    CURR.SVCRSC_FILIALE AS CD_FILIALE,
    CURR.SVCRSC_EMETTITORE AS CD_EMETTITORE,
    CURR.SVCRSC_COD_CEDENTE AS CD_COD_CEDENTE,
    CURR.SVCRSC_AZIENDA AS CD_AZIENDA,
    CURR.SVCRSC_AZIENDA_PAGANTE AS CD_AZIENDA_PAGANTE,
    CURR.SVCRSC_DURATA_RESIDUA AS NM_DURATA_RESIDUA,
    CURR.SVCRSC_DURATA_ORIG AS NM_DURATA_ORIG,
    CURR.SVCRSC_NUM_GG_SCAD_CONT AS NM_NUM_GG_SCAD_CONT,
    CURR.SVCRSC_MESI_ATTUALIZZAZ AS NM_MESI_ATTUALIZZAZ,
    CURR.SVCRSC_RATE_PRIMA_DB AS NM_RATE_PRIMA_DB,
    CURR.SVCRSC_ANNO_DBT AS NM_ANNO_DBT,
    CURR.SVCRSC_RATE_INSOLUTE AS NM_RATE_INSOLUTE,
    CURR.SVCRSC_MESI_ULT_INC AS NM_MESI_ULT_INC,
    CURR.SVCRSC_PRATICA_SIN AS CD_PRATICA_SIN,
    CURR.SVCRSC_NUM_PRATICA_ORIG AS CD_NUM_PRATICA_ORIG,
    CURR.SVCRSC_SK_SOLI_INT_MORA AS CD_SK_SOLI_INT_MORA,
    CURR.SVCRSC_DEBITORE_PAGANTE AS CD_DEBITORE_PAGANTE,
    CURR.SVCRSC_COD_LIBERO_1 AS CD_COD_LIBERO_1,
    CURR.SVCRSC_PRODOTTO AS CD_PRODOTTO,
    CURR.SVCRSC_STAGE_CACF AS TP_STAGE_CACF,
    CURR.SVCRSC_FASCIA_DPD_FM AS TP_FASCIA_DPD_FM,
    CURR.SVCRSC_STATO_CREDITIZIO AS TP_STATO_CREDITIZIO,
    CURR.SVCRSC_STATUS_RISCHIO AS TP_STATUS_RISCHIO,
    CURR.SVCRSC_CLASS_RISCHIO AS CD_CLASS_RISCHIO,
    CURR.SVCRSC_TIPO_SCHEDA AS TP_TIPO_SCHEDA,
    CURR.SVCRSC_VOCE_BILANCIO AS TP_VOCE_BILANCIO,
    CURR.SVCRSC_COD_TRANSAZIONE AS CD_COD_TRANSAZIONE,
    CURR.SVCRSC_TIPO_CONFERIMENTO AS TP_TIPO_CONFERIMENTO,
    {{ custom_to_date ('CURR.SVCRSC_DATA_CALC_IMPAIRMENT') }} AS DT_CALC_IMPAIRMENT,
    {{ custom_to_date ('CURR.SVCRSC_DATA_PREV_REALIZZO') }} AS DT_PREV_REALIZZO,
    {{ custom_to_date ('CURR.SVCRSC_DATA_ENTRATA_STATUS') }} AS DT_ENTRATA_STATUS,
    {{ custom_to_date ('CURR.SVCRSC_DATA_CONSOLIDAM') }} AS DT_CONSOLIDAM,
    {{ custom_to_date ('CURR.SVCRSC_DATA_VARIAZIONE') }} AS DT_VARIAZIONE,
    {{ custom_to_date ('CURR.SVCRSC_DATA_DBT') }} AS DT_DBT,
    {{ custom_to_date ('CURR.SVCRSC_DATA_ULT_SCAD') }} AS DT_ULT_SCAD,
    {{ custom_to_date ('CURR.SVCRSC_DATA_DECORRENZA') }} AS DT_DECORRENZA,
    CURR.SVCRSC_AGGRAVIO_COLLETTIVE AS FL_AGGRAVIO_COLLETTIVE,
    CURR.SVCRSC_ADESIONE_ACC_INPS AS FL_ADESIONE_ACC_INPS,
    CURR.SVCRSC_FLAG_LIBERO_1 AS FL_FLAG_LIBERO_1,
    CURR.SVCRSC_GARANTITO_RISCOSSO AS FL_GARANTITO_RISCOSSO,
    CURR.SVCRSC_PREFINANZIAMENTO AS FL_PREFINANZIAMENTO,
    CURR.SVCRSC_FLAG_PORTAFOGLIO AS FL_FLAG_PORTAFOGLIO,
    CURR.SVCRSC_USO_NEW_CLAS_SVAL AS FL_USO_NEW_CLAS_SVAL,
    CURR.SVCRSC_GIROFONDO AS FL_GIROFONDO,
    CURR.SVCRSC_CONSOLIDATO AS FL_CONSOLIDATO,
    CURR.SVCRSC_FLAG_CREA AS FL_FLAG_CREA,
    CURR.SVCRSC_FLAG_CNT_UT AS FL_FLAG_CNT_UT,
    CURR.SVCRSC_FLAG_CHIUSA AS FL_FLAG_CHIUSA,
    CURR.SVCRSC_FLAG_DBT AS FL_FLAG_DBT,
    CURR.SVCRSC_FLAG_PERDITA AS FL_FLAG_PERDITA,
    CURR.SVCRSC_STATO_SINISTRO AS TP_STATO_SINISTRO,
    CURR.SVCRSC_TIPO_SINISTRO AS TP_TIPO_SINISTRO,
    CURR.SVCRSC_SIN_SINISTRO AS TP_SIN_SINISTRO,
    {{ custom_to_decimal('CURR.SVCRSC_FSC_RIPRESA_ATTUALIZ') }} AS EU_FSC_RIPRESA_ATTUALIZ, -- NUMBER(13)
    {{ custom_to_decimal('CURR.SVCRSC_IMP_LIBERO_2') }} AS         EU_IMP_LIBERO_2, -- NUMBER(13)
    {{ custom_to_decimal('CURR.SVCRSC_INTERESSI_MORA') }} AS       EU_INTERESSI_MORA, -- NUMBER(13)
    {{ custom_to_decimal('CURR.SVCRSC_SCADERE_RIMONTATO') }} AS    EU_SCADERE_RIMONTATO, -- NUMBER(13)
    {{ custom_to_decimal('CURR.SVCRSC_IMP_LIBERO_1') }} AS         EU_IMP_LIBERO_1, -- NUMBER(13)
    {{ custom_to_decimal('CURR.SVCRSC_IMPORTO_GARANZIA') }} AS     EU_IMPORTO_GARANZIA, -- NUMBER(13)
    {{ custom_to_decimal('CURR.SVCRSC_IMP_ATTUALIZZATO', precision=11) }} AS     EU_IMP_ATTUALIZZATO,
    {{ custom_to_decimal('CURR.SVCRSC_BASE_CALC_IMPAIRMENT', precision=11)}} AS EU_BASE_CALC_IMPAIRMENT,
    {{ custom_to_decimal('CURR.SVCRSC_IMPAIRMENT_SCADERE', precision=11) }} AS   EU_IMPAIRMENT_SCADERE,
    {{ custom_to_decimal('CURR.SVCRSC_IMPAIRMENT_SCADUTO', precision=11) }} AS   EU_IMPAIRMENT_SCADUTO,
    {{ custom_to_decimal('CURR.SVCRSC_FSG_CAPR_VE', precision=11) }} AS          EU_FSG_CAPR_VE,
    {{ custom_to_decimal('CURR.SVCRSC_FSC_CRED_VE', precision=11) }} AS          EU_FSC_CRED_VE,
    {{ custom_to_decimal('CURR.SVCRSC_IMPORTI_PERDITA', precision=11) }} AS      EU_IMPORTI_PERDITA,
    {{ custom_to_decimal('CURR.SVCRSC_VARIAZIONE_SALDO', precision=11) }} AS     EU_VARIAZIONE_SALDO,
    {{ custom_to_decimal('CURR.SVCRSC_FSG_NETTO', precision=11) }} AS            EU_FSG_NETTO,
    {{ custom_to_decimal('CURR.SVCRSC_FSG_FONDO', precision=11) }} AS            EU_FSG_FONDO,
    {{ custom_to_decimal('CURR.SVCRSC_FSG_CAPITALE_RESIDUO', precision=11) }} AS EU_FSG_CAPITALE_RESIDUO,
    {{ custom_to_decimal('CURR.SVCRSC_FSC_NETTO', precision=11) }} AS EU_FSC_NETTO,
    {{ custom_to_decimal('CURR.SVCRSC_FSC_FONDO', precision=11) }} AS EU_FSC_FONDO,
    {{ custom_to_decimal('CURR.SVCRSC_FSC_CREDITO', precision=11) }} AS EU_FSC_CREDITO,
    CURR.SVCRSC_REGIONE_RES_CLI AS CD_REGIONE_RES_CLI,
    CURR.SVCRSC_PROVINCIA_RES_CLI AS CD_PROVINCIA_RES_CLI,
    CURR.SVCRSC_UTENTE_CALC_IMPAIRMENT AS CD_UTENTE_CALC_IMPAIRMENT,
    CURR.SVCRSC_UTENTE_CONSOLIDAM AS CD_UTENTE_CONSOLIDAM,
    CURR.SVCRSC_UTENTE_VARIAZIONE AS CD_UTENTE_VARIAZIONE,
    CURR.SVCRSC_OPERATORE_CTZ AS CD_OPERATORE_CTZ,
    CURR.SVCRSC_AZIONE_RECUPERO AS TP_AZIONE_RECUPERO,
    CURR.SVCRSC_CLASS_RECUPERO AS TP_CLASS_RECUPERO,
    CURR.SVCRSC_ATTRIBUTO_CTZ AS CD_ATTRIBUTO_CTZ,
    CURR.SVCRSC_STATO_CTZ AS CD_STATO_CTZ,
    CURR.SVCRSC_PERC_LIBERO_1 AS PC_PERC_LIBERO_1,
    CURR.SVCRSC_TASSO_ATTUALIZZAZ AS PC_TASSO_ATTUALIZZAZ,
    CURR.SVCRSC_TAN_CONTRATTO AS PC_TAN_CONTRATTO,
    CURR.SVCRSC_TASSO_IAS AS PC_TASSO_IAS,
    CURR.SVCRSC_FSG_PERC_EFFETTIVA AS PC_FSG_PERC_EFFETTIVA,
    CURR.SVCRSC_FSG_PERCENTUALE AS PC_FSG_PERCENTUALE,
    CURR.SVCRSC_FSC_PERC_EFFETTIVA AS PC_FSC_PERC_EFFETTIVA,
    CURR.SVCRSC_FSC_PERCENTUALE AS PC_FSC_PERCENTUALE,
    CURR.SVCRSC_CATEGORIA_ATC_SEGN AS TP_CATEGORIA_ATC_SEGN,
    CURR.SVCRSC_AREA AS TP_AREA,
    CURR.SVCRSC_CANALE_ACQ AS TP_CANALE_ACQ,
    CURR.SVCRSC_TIPO_CESSIONE AS TP_TIPO_CESSIONE,
    CURR.SVCRSC_TIPO_CONTRATTO AS TP_TIPO_CONTRATTO,
    CURR.SVCRSC_TP_RIF_SCHEDA_PREC AS TP_RIF_SCHEDA_PREC,
    CURR.SVCRSC_ATTR_QTASK AS TP_ATTR_QTASK,
    CURR.SVCRSC_STATO_QTASK AS TP_STATO_QTASK,
    CURR.SVCRSC_FASCIA_GAR AS TP_FASCIA_GAR,
    CURR.SVCRSC_ATTR_FORBORNE AS TP_ATTR_FORBORNE,
    CURR.SVCRSC_TIPO_PRATICA AS TP_TIPO_PRATICA,
    CURR.SVCRSC_ATECO_ATC AS TP_ATECO_ATC,
    CURR.SVCRSC_TIPO_PROVVISTA AS TP_TIPO_PROVVISTA,
    CURR.SVCRSC_TIPO_CATEGORIA_ATC AS TP_TIPO_CATEGORIA_ATC,
    CURR.SVCRSC_CATEGORIA_ATC AS TP_CATEGORIA_ATC,
    CURR.SVCRSC_FINANZIARIA AS TP_FINANZIARIA,
    CURR.SVCRSC_TIPO_CREAZIONE AS TP_TIPO_CREAZIONE,
    CURR.SVCRSC_ATTR_VIG AS TP_ATTR_VIG,
    CURR.SVCRSC_TIPO_PRODOTTO AS TP_TIPO_PRODOTTO,
    CURR.LASTMODIFIEDDATA,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS TS_INSERIMENTO 
FROM {{ ref('svesfcrsc') }} CURR
LEFT JOIN {{ ref('svesfcrsc') }} PREV
    ON  CURR.SVCRSC_PRATICA = PREV.SVCRSC_PRATICA
    AND CURR.SVCRSC_PROCEDURA = PREV.SVCRSC_PROCEDURA
    AND PREV.SVCRSC_ANNO_ESTRAZIONE = (CURR.SVCRSC_ANNO_ESTRAZIONE - 1)
    AND PREV.SVCRSC_MESE_ESTRAZIONE = 12 
LEFT JOIN {{ ref('legame_cartolarizzazioni') }} B
    ON  CURR.SVCRSC_PRATICA = B.CD_PRATICA
    AND CURR.SVCRSC_PROCEDURA = B.TP_PROCEDURA
    AND CURR.SVCRSC_ANNO_ESTRAZIONE = EXTRACT(YEAR FROM B.DT_OSSERVAZIONE)
    AND CURR.SVCRSC_MESE_ESTRAZIONE = EXTRACT(MONTH FROM B.DT_OSSERVAZIONE)
LEFT JOIN {{ ref('svesfcrsc') }} PREC_BASE
    ON  CURR.SVCRSC_PRATICA = PREC_BASE.SVCRSC_PRATICA
    AND CURR.SVCRSC_PROCEDURA = PREC_BASE.SVCRSC_PROCEDURA
    AND CURR.SVCRSC_ANNO_ESTRAZIONE = PREC_BASE.SVCRSC_ANNO_ESTRAZIONE
    AND PREC_BASE.SVCRSC_MESE_ESTRAZIONE = CURR.SVCRSC_MESE_ESTRAZIONE - 1
LEFT JOIN {{ ref('svesfcrsc') }} CART
    ON  B.CD_PRATICA_CARTOLARIZZATA = CART.SVCRSC_PRATICA
    AND CURR.SVCRSC_PROCEDURA = CART.SVCRSC_PROCEDURA
    AND CURR.SVCRSC_ANNO_ESTRAZIONE = CART.SVCRSC_ANNO_ESTRAZIONE
    AND CURR.SVCRSC_MESE_ESTRAZIONE = CART.SVCRSC_MESE_ESTRAZIONE
LEFT JOIN {{ ref('svesfcrsc') }} PREC_CART
    ON  B.CD_PRATICA_CARTOLARIZZATA = PREC_CART.SVCRSC_PRATICA
    AND CURR.SVCRSC_PROCEDURA = PREC_CART.SVCRSC_PROCEDURA
    AND CURR.SVCRSC_ANNO_ESTRAZIONE = PREC_CART.SVCRSC_ANNO_ESTRAZIONE
    AND PREC_CART.SVCRSC_MESE_ESTRAZIONE = CURR.SVCRSC_MESE_ESTRAZIONE - 1
-- IN ATTESA DI FL_DELETED IN L1
--  WHERE CURR.FL_DELETED = 'N' AND PREV.FL_DELETED = 'N' AND PREC_BASE.FL_DELETED = 'N' 
--    AND CART.FL_DELETED = 'N' AND PREC_CART = 'N'    
{% if is_incremental() %} 
    WHERE CURR.LASTMODIFIEDDATA > (SELECT COALESCE(MAX(LASTMODIFIEDDATA),'1900-01-01'::timestamp_ntz) FROM {{ this }}) 
{% endif %} 
