WITH base AS (
    SELECT
        M.CD_PRATICA,
        M.TP_PROCEDURA,
        M.DT_OSSERVAZIONE,
        M.TS_ESITO,
        M.DT_CHIUSURA_CARTA, -- WARN: campo duplicato nel data model, mantenuta la prima occorrenza
        M.CD_CHIUSURA_CARTA,
        M.CD_STATO,
        M.FL_PERDITA_CESSIONE,
        M.DT_PERDITA_CESSIONE,
        M.TS_COMUNICAZIONE_ESITO_DEF,
        M.TS_CARICAMENTO,
        M.DT_SCADENZA_PRIMA_RATA,
        M.DT_CHIUSURA,
        M.DT_DBT,
        M.DT_PRIMA_SCADENZA
    FROM {{ ref('pratica_m') }} AS M
    -- WARN: FREQ = Giornaliera ma la main PRATICA_M e' storicizzazione mensile (S_M); nessun filtro di riprocesso definito nel data model, verificare con l'owner
)

SELECT
    B.CD_PRATICA AS CD_PRATICA,
    B.TP_PROCEDURA AS TP_PROCEDURA,
    B.DT_OSSERVAZIONE AS DT_OSSERVAZIONE,
    SDD.EU_IMPORTO AS EU_IMPORTO,
    B.TS_ESITO AS TS_ESITO,
    SS.CD_CLEINTE AS CD_CLEINTE,
    B.DT_CHIUSURA_CARTA AS DT_CHIUSURA_CARTA,
    B.CD_CHIUSURA_CARTA AS CD_CHIUSURA_CARTA,
    BC.TP_BLOCCO AS TP_BLOCCO,
    CU.DT_ACQUISTO AS DT_ACQUISTO,
    B.CD_STATO AS CD_STATO, -- WARN: campo duplicato nel data model, mantenuta la prima occorrenza
    B.FL_PERDITA_CESSIONE AS FL_PERDITA_CESSIONE,
    SS.DT_PRIMO_UTILIZZO AS DT_PRIMO_UTILIZZO,
    B.DT_DBT AS DT_DBT, -- WARN: campo duplicato nel data model, mantenuta la prima occorrenza
    B.DT_PERDITA_CESSIONE AS DT_PERDITA_CESSIONE,
    B.TS_COMUNICAZIONE_ESITO_DEF AS TS_COMUNICAZIONE_ESITO_DEF,
    B.TS_CARICAMENTO AS TS_CARICAMENTO,
    B.DT_SCADENZA_PRIMA_RATA AS DT_SCADENZA_PRIMA_RATA,
    NULL AS SETTORE, -- WARN: RT = "calcolo da definire", nessuna logica nel data model
    B.DT_CHIUSURA AS DT_CHIUSURA,
    B.DT_PRIMA_SCADENZA AS DT_PRIMA_SCADENZA
FROM base AS B
LEFT JOIN {{ ref('sdd') }} AS SDD
    ON SDD.CD_PRATICA = B.CD_PRATICA
   AND SDD.TP_PROCEDURA = B.TP_PROCEDURA
   AND SDD.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
LEFT JOIN {{ ref('sociodemo_score') }} AS SS
    ON SS.CD_PRATICA = B.CD_PRATICA
   AND SS.TP_PROCEDURA = B.TP_PROCEDURA
   AND SS.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
LEFT JOIN {{ ref('blocchi_carte') }} AS BC
    ON BC.CD_PRATICA = B.CD_PRATICA
   AND BC.TP_PROCEDURA = B.TP_PROCEDURA
   AND BC.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
LEFT JOIN {{ ref('carte_utilizzi') }} AS CU
    ON CU.CD_PRATICA = B.CD_PRATICA
   AND CU.TP_PROCEDURA = B.TP_PROCEDURA
   AND CU.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
