WITH base AS (
    SELECT
        M.CD_PRATICA,
        M.TP_PROCEDURA,
        M.DT_OSSERVAZIONE
    FROM {{ ref('carte_blocchi') }} AS M
)

SELECT
    B.CD_PRATICA AS CD_PRATICA,
    B.TP_PROCEDURA AS TP_PROCEDURA,
    B.DT_OSSERVAZIONE AS DT_OSSERVAZIONE,
    SDD.EU_IMPORTO AS EU_IMPORTO,
    PM.TS_ESITO AS TS_ESITO,
    SS.CD_CLEINTE AS CD_CLEINTE,
    PM.DT_CHIUSURA_CARTA AS DT_CHIUSURA_CARTA, -- WARN: campo duplicato nel data model (stessa RT), mantenuta la prima occorrenza
    PM.CD_CHIUSURA_CARTA AS CD_CHIUSURA_CARTA,
    BC.TP_BLOCCO AS TP_BLOCCO,
    CU.DT_ACQUISTO AS DT_ACQUISTO,
    PM.CD_STATO AS CD_STATO, -- WARN: campo duplicato nel data model (stessa RT), mantenuta la prima occorrenza
    PM.FL_PERDITA_CESSIONE AS FL_PERDITA_CESSIONE,
    SS.DT_PRIMO_UTILIZZO AS DT_PRIMO_UTILIZZO,
    PM.DT_DBT AS DT_DBT, -- WARN: campo duplicato nel data model (stessa RT), mantenuta la prima occorrenza
    PM.DT_PERDITA_CESSIONE AS DT_PERDITA_CESSIONE,
    PM.TS_COMUNICAZIONE_ESITO_DEF AS TS_COMUNICAZIONE_ESITO_DEF,
    PM.TS_CARICAMENTO AS TS_CARICAMENTO,
    PM.DT_SCADENZA_PRIMA_RATA AS DT_SCADENZA_PRIMA_RATA,
    NULL AS SETTORE, -- WARN: RT = "calcolo da definire", nessuna logica nel data model
    PM.DT_CHIUSURA AS DT_CHIUSURA,
    PM.DT_PRIMA_SCADENZA AS DT_PRIMA_SCADENZA
FROM base AS B
LEFT JOIN {{ ref('sdd') }} AS SDD
    ON SDD.CD_PRATICA = B.CD_PRATICA
   AND SDD.TP_PROCEDURA = B.TP_PROCEDURA
   AND SDD.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
LEFT JOIN {{ ref('pratica_m') }} AS PM
    ON PM.CD_PRATICA = B.CD_PRATICA
   AND PM.TP_PROCEDURA = B.TP_PROCEDURA
   AND PM.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
LEFT JOIN {{ ref('sociodemo_score') }} AS SS
    ON SS.CD_PRATICA = B.CD_PRATICA
   AND SS.TP_PROCEDURA = B.TP_PROCEDURA
   AND SS.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
LEFT JOIN {{ ref('blocchi_carte') }} AS BC
    ON BC.CD_PRATICA = B.CD_PRATICA
   AND BC.TP_PROCEDURA = B.TP_PROCEDURA
   AND BC.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
LEFT JOIN {{ ref('carte_utilizzi') }} AS CU
    ON CU.CD_PRATICA = B.CD_PRATICA
   AND CU.TP_PROCEDURA = B.TP_PROCEDURA
   AND CU.DT_OSSERVAZIONE = B.DT_OSSERVAZIONE
-- WARN: FREQ = Giornaliera; nessun filtro di riprocesso definito nel data model. CARTE_BLOCCHI non presente in raw/dwh-code, non verificabile la sua storicizzazione
