select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(Id AS VARCHAR(18)) AS id,
  TRY_CAST(Account_ExternalKey__c AS VARCHAR(18)) AS account_externalkey__c,
  TRY_CAST(AreaAziendale__c AS VARCHAR(255)) AS areaaziendale__c,
  TRY_CAST(Assicurazione__c AS VARCHAR(255)) AS assicurazione__c,
  TRY_CAST(AutoritaDiVigilanzaCoinvolta__c AS VARCHAR) AS autoritadivigilanzacoinvolta__c,
  TRY_CAST(BeneficiarioLiquidazione__c AS VARCHAR(255)) AS beneficiarioliquidazione__c,
  TRY_CAST(CaseNumber AS VARCHAR(255)) AS casenumber,
  TRY_CAST(OwnerId AS VARCHAR(255)) AS ownerid,
  TRY_CAST(RecordType_Name AS VARCHAR(255)) AS recordtype_name,
  TRY_CAST(CoinvolgimentoAutoritaGiudiziaria__c AS BOOLEAN) AS coinvolgimentoautoritagiudiziaria__c,
  TRY_CAST(CompagniaAssicurativa__c AS VARCHAR(255)) AS compagniaassicurativa__c,
  TRY_CAST(ConsultataCACI__c AS BOOLEAN) AS consultatacaci__c,
  TRY_CAST(ConvenzionatoFiliale__c AS VARCHAR(255)) AS convenzionatofiliale__c,
  TRY_CAST(CreatedById AS VARCHAR) AS createdbyid,
  TRY_TO_TIMESTAMP_TZ(CreatedDate)::TIMESTAMP_NTZ AS CreatedDate,
  TRY_TO_DATE(DataEvento__c) AS dataevento__c,
  TRY_TO_TIMESTAMP_TZ(ClosedDate)::TIMESTAMP_NTZ AS closeddate,
  TRY_CAST(DecessoDormiente__c AS BOOLEAN) AS decessodormiente__c,
  TRY_CAST(Description AS VARCHAR(3200)) AS description,
  TRY_CAST(EmailCliente__c AS VARCHAR(255)) AS emailcliente__c,
  TRY_CAST(Entitlement_Name AS VARCHAR(255)) AS entitlement_name,
  TRY_CAST(EsclusivitaCompagnia__c AS VARCHAR(255)) AS esclusivitacompagnia__c,
  TRY_CAST(EsitoAnalisiMovimenti__c AS VARCHAR(255)) AS esitoanalisimovimenti__c,
  TRY_CAST(Esito__c AS VARCHAR(255)) AS esito__c,
  TRY_CAST(Garante__r_ExternalKey__c AS VARCHAR(255)) AS garante__r_externalkey__c,
  TRY_CAST(IBANBeneficiario__c AS VARCHAR(255)) AS ibanbeneficiario__c,
  TRY_CAST(ImportoFattura__c AS NUMBER(18,0)) AS importofattura__c,
  TRY_CAST(Importo__c AS NUMBER(18,0)) AS importo__c,
  TRY_CAST(InformazioniAggiuntive__c AS VARCHAR) AS informazioniaggiuntive__c,
  TRY_CAST(LastModifiedById AS VARCHAR) AS lastmodifiedbyid,
  TRY_CAST(LinkSospettoCliccato__c AS VARCHAR(255)) AS linksospettocliccato__c,
  TRY_CAST(MilestoneStatus AS VARCHAR(30)) AS milestonestatus,
  TRY_CAST(MilestoneTdLCompletata__c AS BOOLEAN) AS milestonetdlcompletata__c,
  TRY_CAST(ModalitaDiErogazione__c AS VARCHAR(255)) AS modalitadierogazione__c,
  TRY_CAST(Motivazione__c AS VARCHAR(255)) AS motivazione__c,
  TRY_CAST(MotivoContatto__c AS VARCHAR(255)) AS motivocontatto__c,
  TRY_CAST(MotivoSospensione__c AS VARCHAR(255)) AS motivosospensione__c,
  TRY_CAST(MotivoPicklist__c AS VARCHAR(255)) AS motivopicklist__c,
  TRY_CAST(NegoziazioneAssistita__c AS BOOLEAN) AS negoziazioneassistita__c,
  TRY_CAST(NomeAccount__c AS VARCHAR(255)) AS nomeaccount__c,
  TRY_CAST(NoteAntifrode__c AS VARCHAR(4000)) AS noteantifrode__c,
  TRY_CAST(NoteDiChiusura__c AS VARCHAR(4000)) AS notedichiusura__c,
  TRY_CAST(Origin AS VARCHAR(255)) AS origin,
  TRY_CAST(ParentId AS VARCHAR) AS parentid,
  TRY_CAST(Asset_ExternalKey__c AS VARCHAR(255)) AS asset_externalkey__c,
  TRY_CAST(Asset_Name AS VARCHAR(255)) AS asset_name,
  TRY_CAST(Asset_RecordTypeDevName__c AS VARCHAR(255)) AS asset_recordtypedevname__c,
  TRY_CAST(Priority AS VARCHAR(255)) AS priority,
  TRY_CAST(Procedura__c AS VARCHAR(255)) AS procedura__c,
  TRY_CAST(Richiedente__c AS VARCHAR(255)) AS richiedente__c,
  TRY_CAST(SceltaCliente__c AS VARCHAR(255)) AS sceltacliente__c,
  TRY_CAST(SottocategoriaPicklist__c AS VARCHAR(255)) AS sottocategoriapicklist__c,
  TRY_CAST(SpeseDaStornare__c AS VARCHAR(255)) AS spesedastornare__c,
  TRY_CAST(StatoPrecedente__c AS VARCHAR(255)) AS statoprecedente__c,
  TRY_CAST(Status AS VARCHAR(255)) AS status,
  TRY_CAST(Subject AS VARCHAR(255)) AS subject,
  TRY_CAST(SuggerimentoFornito__c AS VARCHAR(255)) AS suggerimentofornito__c,
  TRY_CAST(TaskCreati__c AS BOOLEAN) AS taskcreati__c,
  TRY_CAST(TerzaParte__r_ExternalKey__c AS VARCHAR(255)) AS terzaparte__r_externalkey__c,
  TRY_CAST(TipologiaPolizza__c AS VARCHAR(255)) AS tipologiapolizza__c,
  TRY_CAST(TipologiaProponente__c AS VARCHAR(255)) AS tipologiaproponente__c,
  TRY_CAST(TipologiaRichiesta__c AS VARCHAR(255)) AS tipologiarichiesta__c,
  TRY_CAST(TipologiaPicklist__c AS VARCHAR(255)) AS tipologiapicklist__c,
  TRY_CAST(ValoreEconomicoDelReclamo__c AS VARCHAR(255)) AS valoreeconomicodelreclamo__c,
  TRY_CAST(VerificaVariazione__c AS VARCHAR(255)) AS verificavariazione__c,
  TRY_TO_DATE(Apertura__c, 'YYYY-MM-DD HH24:MI:SS') AS apertura__c,
  TRY_TO_DATE(Chiusura__c, 'YYYY-MM-DD HH24:MI:SS') AS chiusura__c,
  TRY_CAST(ChiusuraAutomatica__c AS BOOLEAN) AS chiusuraautomatica__c,
  TRY_CAST(CodaLavorazione__c AS VARCHAR(255)) AS codalavorazione__c,
  TRY_CAST(CreatoDaPadre__c AS BOOLEAN) AS creatodapadre__c,
  TRY_TO_DATE(DataNotifica__c) AS datanotifica__c,
  TRY_CAST(DocumentoConforme__c AS VARCHAR(255)) AS documentoconforme__c,
  TRY_CAST(DocumentiMancanti__c AS VARCHAR(32768)) AS documentimancanti__c,
  TRY_CAST(EAPrecedenteAllaScadenzaPrimaRata__c AS BOOLEAN) AS eaprecedenteallascadenzaprimarata__c,
  TRY_CAST(EtaAccount__c AS NUMBER(18,0)) AS etaaccount__c,
  TRY_TO_TIMESTAMP_TZ(InizioLavorazioneCompagnia__c)::TIMESTAMP_NTZ AS iniziolavorazionecompagnia__c,
  TRY_TO_TIMESTAMP_TZ(InizioSospensione__c)::TIMESTAMP_NTZ AS iniziosospensione__c,
  TRY_CAST(IsOwnerQueue__c AS BOOLEAN) AS isownerqueue__c,
  TRY_CAST(IstruttoriaInCorso__c AS BOOLEAN) AS istruttoriaincorso__c,
  TRY_TO_TIMESTAMP_TZ(LastModifiedDate)::TIMESTAMP_NTZ AS lastmodifieddate,
  TRY_CAST(MostraPulsanteAccetta__c AS BOOLEAN) AS mostrapulsanteaccetta__c,
  TRY_CAST(RichiestaApprovazione__c AS BOOLEAN) AS richiestaapprovazione__c,
  TRY_CAST(SLARisoluzioneOre__c AS NUMBER(8,0)) AS slarisoluzioneore__c,
  TRY_CAST(TabellaFinanziaria__c AS VARCHAR(255)) AS tabellafinanziaria__c,
  TRY_CAST(Teg__c AS NUMBER(5,3)) AS teg__c,
  TRY_CAST(TempoTotaleInLavorazioneCompagnia__c AS NUMBER(16,2)) AS tempototaleinlavorazionecompagnia__c,
  TRY_CAST(TempoTotaleSospensione__c AS NUMBER(16,2)) AS tempototalesospensione__c,
  TRY_CAST(MostraPulsanteModReclami__c AS BOOLEAN) AS mostrapulsantemodreclami__c,
  TRY_CAST(TempoParzialeInLavorazioneCompagnia__c AS NUMBER(16,2)) AS tempoparzialeinlavorazionecompagnia__c,
  TRY_CAST(TempoParzialeSospensione__c AS NUMBER(16,2)) AS tempoparzialesospensione__c,
  TRY_CAST(TempoIncrementaleSospensione__c AS NUMBER(10,2)) AS tempoincrementalesospensione__c,
  TRY_CAST(TempoIncrementaleInLavorazioneCompagnia__c AS NUMBER(10,2)) AS tempoincrementaleinlavorazionecompagnia__c
from {{ source('source_l0','case') }}
