select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(Id AS VARCHAR(18)) AS id,
  TRY_CAST(IsDeleted AS BOOLEAN) AS isdeleted,
  TRY_CAST(Account_ExternalKey__c AS VARCHAR(255)) AS account_externalkey__c,
  TRY_CAST(IsPersonAccount AS BOOLEAN) AS ispersonaccount,
  TRY_CAST(LastName AS VARCHAR(255)) AS lastname,
  TRY_CAST(FirstName AS VARCHAR(255)) AS firstname,
  TRY_CAST(Salutation AS VARCHAR(40)) AS salutation,
  TRY_CAST(MiddleName AS VARCHAR(255)) AS middlename,
  TRY_CAST(Suffix AS VARCHAR(255)) AS suffix,
  TRY_CAST(Name AS VARCHAR(255)) AS name,
  TRY_CAST(RecordType_Name AS VARCHAR(255)) AS recordtype_name,
  TRY_CAST(Phone AS VARCHAR(40)) AS phone,
  TRY_CAST(MobilePhone AS VARCHAR(40)) AS mobilephone,
  TRY_CAST(HomePhone AS VARCHAR(40)) AS homephone,
  TRY_CAST(OtherPhone AS VARCHAR(40)) AS otherphone,
  TRY_CAST(Email AS VARCHAR(255)) AS email,
  TRY_CAST(Title AS VARCHAR(255)) AS title,
  TRY_CAST(Birthdate AS TIMESTAMP_NTZ) AS birthdate,
  TRY_CAST(Owner_FederationIdentifier AS VARCHAR(255)) AS owner_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(CreatedDate, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS CreatedDate,
  TRY_CAST(CreatedBy_FederationIdentifier AS VARCHAR(255)) AS createdby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(LastModifiedDate, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS LastModifiedDate,
  TRY_CAST(LastModifiedBy_FederationIdentifier AS VARCHAR(255)) AS lastmodifiedby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(LastActivityDate, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS LastActivityDate,
  TRY_TO_TIMESTAMP_TZ(LastViewedDate, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS LastViewedDate,
  TRY_TO_TIMESTAMP_TZ(LastReferencedDate, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS LastReferencedDate,
  TRY_CAST(Ruolo__c AS VARCHAR(255)) AS ruolo__c,
  TRY_CAST(NoteConcorrenza__c AS VARCHAR(32768)) AS noteconcorrenza__c
from {{ source('source_l0','contact') }}
