select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(Id AS VARCHAR(18)) AS id,
  TRY_CAST(Account_ExternalKey__c AS VARCHAR) AS account_externalkey__c,
  TRY_CAST(Account_Name AS VARCHAR(255)) AS account_name,
  TRY_TO_DATE(Birthdate, 'YYYY-MM-DD HH24:MI:SS') AS birthdate,
  TRY_CAST(CreatedById AS VARCHAR) AS createdbyid,
  TRY_CAST(CreatedBy_FederationIdentifier AS VARCHAR) AS createdby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(CreatedDate)::TIMESTAMP_NTZ AS CreatedDate,
  TRY_CAST(Email AS VARCHAR(255)) AS email,
  TRY_CAST(FirstName AS VARCHAR(255)) AS firstname,
  TRY_CAST(HomePhone AS VARCHAR) AS homephone,
  TRY_CAST(IsDeleted AS BOOLEAN) AS isdeleted,
  TRY_CAST(IsPersonAccount AS BOOLEAN) AS ispersonaccount,
  TRY_TO_DATE(LastActivityDate, 'YYYY-MM-DD HH24:MI:SS') AS lastactivitydate,
  TRY_CAST(LastModifiedById AS VARCHAR) AS lastmodifiedbyid,
  TRY_CAST(LastModifiedBy_FederationIdentifier AS VARCHAR) AS lastmodifiedby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(LastModifiedDate)::TIMESTAMP_NTZ AS lastmodifieddate,
  TRY_CAST(LastName AS VARCHAR(255)) AS lastname,
  TRY_TO_TIMESTAMP_TZ(LastReferencedDate)::TIMESTAMP_NTZ AS lastreferenceddate,
  TRY_TO_TIMESTAMP_TZ(LastViewedDate)::TIMESTAMP_NTZ AS lastvieweddate,
  TRY_CAST(MiddleName AS VARCHAR(255)) AS middlename,
  TRY_CAST(MobilePhone AS VARCHAR) AS mobilephone,
  TRY_CAST(Name AS VARCHAR(255)) AS name,
  TRY_CAST(OtherPhone AS VARCHAR) AS otherphone,
  TRY_CAST(OwnerId AS VARCHAR) AS ownerid,
  TRY_CAST(Owner_FederationIdentifier AS VARCHAR) AS owner_federationidentifier,
  TRY_CAST(Phone AS VARCHAR) AS phone,
  TRY_CAST(RecordType_Id AS VARCHAR) AS recordtype_id,
  TRY_CAST(RecordType_Name AS VARCHAR) AS recordtype_name,
  TRY_CAST(ReportsTo_Name AS VARCHAR(255)) AS reportsto_name,
  TRY_CAST(Ruolo__c AS VARCHAR(255)) AS ruolo__c,
  TRY_CAST(Salutation AS VARCHAR) AS salutation,
  TRY_CAST(Suffix AS VARCHAR(255)) AS suffix,
  TRY_CAST(Title AS VARCHAR(255)) AS title,
  TRY_CAST(NoteConcorrenza__c AS VARCHAR) AS noteconcorrenza__c
from {{ source('source_l0','contact') }}
