select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(Id AS VARCHAR(18)) AS id,
  TRY_CAST(Account_ExternalKey__c AS VARCHAR) AS account_externalkey__c,
  TRY_CAST(EsitoEvento__c AS VARCHAR) AS esitoevento__c,
  TRY_CAST(Iniziativa__r_Id AS VARCHAR) AS iniziativa__r_id,
  TRY_CAST(Iniziativa__r_IDIniziativa__c AS VARCHAR) AS iniziativa__r_idiniziativa__c,
  TRY_CAST(Iniziativa__r_Name AS VARCHAR) AS iniziativa__r_name,
  TRY_CAST(NoteEsito__c AS VARCHAR(255)) AS noteesito__c,
  TRY_CAST(ErogazioneEvento__c AS VARCHAR) AS erogazioneevento__c,
  TRY_CAST(IsAllDayEvent AS BOOLEAN) AS isalldayevent,
  TRY_CAST(Description AS VARCHAR) AS description,
  TRY_TO_TIMESTAMP_TZ(StartDateTime)::TIMESTAMP_NTZ AS StartDateTime,
  TRY_TO_TIMESTAMP_TZ(EndDateTime)::TIMESTAMP_NTZ AS EndDateTime,
  TRY_CAST(CreatedById AS VARCHAR) AS createdbyid,
  TRY_CAST(CreatedBy_FederationIdentifier AS VARCHAR) AS createdby_federationidentifier,
  TRY_CAST(RecordType_Id AS VARCHAR) AS recordtype_id,
  TRY_CAST(RecordType_Name AS VARCHAR) AS recordtype_name,
  TRY_CAST(LastModifiedById AS VARCHAR) AS lastmodifiedbyid,
  TRY_CAST(LastModifiedBy_FederationIdentifier AS VARCHAR) AS lastmodifiedby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(LastModifiedDate)::TIMESTAMP_NTZ AS lastmodifieddate,
from {{ source('source_l0','event') }}
