select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(Id AS VARCHAR(18)) AS id,
  TRY_CAST(EsitoEvento__c AS VARCHAR(255)) AS esitoevento__c,
  TRY_CAST(Iniziativa__r_IDIniziativa__c AS VARCHAR(255)) AS iniziativa__r_idiniziativa__c,
  TRY_CAST(Iniziativa__r_Name AS VARCHAR(255)) AS iniziativa__r_name,
  TRY_CAST(NoteEsito__c AS VARCHAR(255)) AS noteesito__c,
  TRY_CAST(ErogazioneEvento__c AS VARCHAR(255)) AS erogazioneevento__c,
  TRY_CAST(IsAllDayEvent AS BOOLEAN) AS isalldayevent,
  TRY_CAST(Description AS VARCHAR(32000)) AS description,
  TRY_CAST(Owner_FederationIdentifier AS VARCHAR(255)) AS owner_federationidentifier,
  TRY_CAST(CreatedBy_FederationIdentifier AS VARCHAR(255)) AS createdby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(StartDateTime, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS StartDateTime,
  TRY_TO_TIMESTAMP_TZ(EndDateTime, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS EndDateTime,
  TRY_CAST(What_Account_ExternalKey__c AS VARCHAR(255)) AS what_account_externalkey__c,
  TRY_CAST(What_MembriIniziativa__r_Name AS VARCHAR(255)) AS what_membriiniziativa__r_name,
  TRY_CAST(Account_ExternalKey__c AS VARCHAR(255)) AS account_externalkey__c,
  TRY_CAST(RecordType_Name AS VARCHAR(255)) AS recordtype_name,
  TRY_CAST(LastModifiedBy_FederationIdentifier AS VARCHAR(255)) AS lastmodifiedby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(LastModifiedDate, 'YYYY-MM-DDTHH24:MI:SS.FF3TZHTZM')::TIMESTAMP_NTZ AS LastModifiedDate,
from {{ source('source_l0','event') }}
