select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  TRY_CAST(Id AS VARCHAR(18)) AS id,
  TRY_CAST(OwnerId AS VARCHAR) AS ownerid,
  TRY_CAST(Description AS VARCHAR) AS description,
  TRY_CAST(What_Id AS VARCHAR(255)) AS what_id,
  TRY_CAST(CreatedById AS VARCHAR) AS createdbyid,
  TRY_CAST(CreatedBy_FederationIdentifier AS VARCHAR) AS createdby_federationidentifier,
  TRY_CAST(Subject AS VARCHAR(255)) AS subject,
  TRY_CAST(Priority AS VARCHAR) AS priority,
  TRY_TO_DATE(ActivityDate, 'YYYY-MM-DD HH24:MI:SS') AS activitydate,
  TRY_CAST(Status AS VARCHAR) AS status,
  TRY_CAST(RecordType_Id AS VARCHAR) AS recordtype_id,
  TRY_CAST(RecordType_Name AS VARCHAR) AS recordtype_name,
  TRY_CAST(LastModifiedById AS VARCHAR) AS lastmodifiedbyid,
  TRY_CAST(LastModifiedBy_FederationIdentifier AS VARCHAR) AS lastmodifiedby_federationidentifier,
  TRY_TO_TIMESTAMP_TZ(CreatedDate)::TIMESTAMP_NTZ AS CreatedDate,
  TRY_TO_TIMESTAMP_TZ(LastModifiedDate)::TIMESTAMP_NTZ AS LastModifiedDate,
  TRY_TO_TIMESTAMP_TZ(CompletedDateTime)::TIMESTAMP_NTZ AS CompletedDateTime,
  TRY_CAST(AzioneDispositiva__c AS VARCHAR(255)) AS azionedispositiva__c,
  TRY_CAST(TutteLeAzioni__c AS VARCHAR) AS tutteleazioni__c
from {{ source('source_l0','task') }}
