-- WARN: CD_PROCEDURA - la sorgente dichiarata nel data model (CRTABCAM.CRTCAM_PROCEDURA) non fa parte del perimetro
-- di join dell'entita' (OXCIFTCA/OXCIFTPR/OXCIFTSE/TRCA) e non ha una CHIAVE DI AGGANCIO specificata (CHIAVI = '-').
-- Verificare con il data model owner. In attesa di chiarimento, CD_PROCEDURA viene valorizzato con 'P1'.
-- WARN: cluster L1 (A1/A2/B1/C) non specificato nel Catalogo Entita' per questa entita' (STORICIZZAZIONE riportata
-- come testo descrittivo senza mappatura sorgente->cluster). Si e' assunto cluster non-C (SCD2 costruita in L2,
-- nessun filtro FL_DELETED) per OXCIFTCA/OXCIFTPR/OXCIFTSE: verificare il cluster reale.

WITH base AS (

    SELECT
        'P1' AS CD_PROCEDURA,
        CA.OXCITCA_CAMPAGNA AS CD_CAMPAGNA,
        SE.OXCITSE_SET AS CD_SET_CAMPAGNA,
        {{ custom_to_timestamp_ntz('SE.OXCITSE_DATA_INIZIO') }} AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita("CA.OXCITCA_CAMPAGNA, SE.OXCITSE_SET", custom_to_timestamp_ntz('SE.OXCITSE_DATA_INIZIO')) }} AS TS_FINE_VALIDITA,
        CA.OXCITCA_DESCRIZIONE AS DS_CAMPAGNA,
        TRY_TO_DATE(NULLIF(TO_VARCHAR(SE.OXCITSE_DATA_INIZIO), '0'), 'YYYYMMDD') AS DT_INIZIO_VALIDITA,
        TRY_TO_DATE(NULLIF(TO_VARCHAR(SE.OXCITSE_DATA_FINE), '0'), 'YYYYMMDD') AS DT_FINE_VALIDITA,
        CA.OXCITCA_GESTIONE_CA AS FL_GESTIONE_CARTE,
        CA.OXCITCA_GESTIONE_CO AS FL_GESTIONE_CONSUMO,
        CA.OXCITCA_ACCETTAZIONE_OBBL AS FL_ACCETTAZIONE_OBBLIGATORIA,
        PR.OXCITPR_PROPOSTA AS CD_PROPOSTA,
        PR.OXCITPR_DESCRIZIONE AS DS_PROPOSTA,
        PR.OXCITPR_ESTRAZIONE_STAT AS FL_ESTRAZIONE_STATISTICA,
        SE.OXCITSE_DESCRIZIONE AS DS_SET_CAMPAGNA,
        SE.OXCITSE_TIPO_ISTRUTTORIA AS TP_ISTRUTTORIA,
        SE.OXCITSE_GIORNI_VALIDITA AS NM_GIORNI_VALIDITA,
        SE.OXCITSE_PROMOZIONE AS CD_PROMOZIONE,
        SE.OXCITSE_EMETTITORE AS CD_EMETTITORE,
        SE.OXCITSE_PRODOTTO AS CD_PRODOTTO,
        SE.OXCITSE_TAB_FINANZ AS CD_TABELLA_FINANZIARIA,
        {{ custom_to_decimal('SE.OXCITSE_FIDO', 13, 2) }} AS EU_FIDO,
        {{ custom_to_decimal('SE.OXCITSE_RISERVA_PRINC', 13, 2) }} AS EU_RISERVA_PRINCIPALE,
        {{ custom_to_decimal('SE.OXCITSE_RISERVA_SALV', 13, 2) }} AS EU_RISERVA_SALVADANAIO,
        {{ custom_to_decimal('SE.OXCITSE_RISERVA_INTERN', 13, 2) }} AS EU_RISERVA_INTERNET,
        SE.OXCITSE_AGENTE AS CD_AGENTE,
        SE.OXCITSE_CHK_EMETTITORE AS FL_CONTROLLO_EMETTITORE,
        SE.OXCITSE_CHK_PRODOTTO AS FL_CONTROLLO_PRODOTTO,
        SE.OXCITSE_ESCLUSIONE_SEL AS FL_ESCLUSIONE_SELEZIONE,
        CA.LASTMODIFIEDDATA AS LASTMODIFIEDDATA
    FROM {{ ref('oxciftca') }} CA
    LEFT JOIN {{ ref('oxciftpr') }} PR
        ON CA.OXCITCA_PROPOSTA = PR.OXCITPR_PROPOSTA
    INNER JOIN {{ ref('oxciftse') }} SE
        ON CA.OXCITCA_CAMPAGNA = SE.OXCITSE_CAMPAGNA
    WHERE NULLIF(TRIM(TO_VARCHAR(SE.OXCITSE_DATA_INIZIO)), '') IS NOT NULL
      AND TRIM(TO_VARCHAR(SE.OXCITSE_DATA_INIZIO)) <> '0'

),

dedup AS (

    SELECT
        CD_PROCEDURA,
        CD_CAMPAGNA,
        CD_SET_CAMPAGNA,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        DS_CAMPAGNA,
        DT_INIZIO_VALIDITA,
        DT_FINE_VALIDITA,
        FL_GESTIONE_CARTE,
        FL_GESTIONE_CONSUMO,
        FL_ACCETTAZIONE_OBBLIGATORIA,
        CD_PROPOSTA,
        DS_PROPOSTA,
        FL_ESTRAZIONE_STATISTICA,
        DS_SET_CAMPAGNA,
        TP_ISTRUTTORIA,
        NM_GIORNI_VALIDITA,
        CD_PROMOZIONE,
        CD_EMETTITORE,
        CD_PRODOTTO,
        CD_TABELLA_FINANZIARIA,
        EU_FIDO,
        EU_RISERVA_PRINCIPALE,
        EU_RISERVA_SALVADANAIO,
        EU_RISERVA_INTERNET,
        CD_AGENTE,
        FL_CONTROLLO_EMETTITORE,
        FL_CONTROLLO_PRODOTTO,
        FL_ESCLUSIONE_SELEZIONE,
        LASTMODIFIEDDATA,
        {{ hash_cols([
            'CD_PROCEDURA', 'CD_CAMPAGNA', 'CD_SET_CAMPAGNA',
            'DS_CAMPAGNA', 'DT_INIZIO_VALIDITA', 'DT_FINE_VALIDITA',
            'FL_GESTIONE_CARTE', 'FL_GESTIONE_CONSUMO', 'FL_ACCETTAZIONE_OBBLIGATORIA',
            'CD_PROPOSTA', 'DS_PROPOSTA', 'FL_ESTRAZIONE_STATISTICA',
            'DS_SET_CAMPAGNA', 'TP_ISTRUTTORIA', 'NM_GIORNI_VALIDITA',
            'CD_PROMOZIONE', 'CD_EMETTITORE', 'CD_PRODOTTO', 'CD_TABELLA_FINANZIARIA',
            'EU_FIDO', 'EU_RISERVA_PRINCIPALE', 'EU_RISERVA_SALVADANAIO', 'EU_RISERVA_INTERNET',
            'CD_AGENTE', 'FL_CONTROLLO_EMETTITORE', 'FL_CONTROLLO_PRODOTTO', 'FL_ESCLUSIONE_SELEZIONE'
        ]) }} AS HASHED_COLS
    FROM base
    {{ is_incremental_S1(['CD_PROCEDURA', 'CD_CAMPAGNA', 'CD_SET_CAMPAGNA']) }}

)

SELECT
    H.CD_PROCEDURA,
    H.CD_CAMPAGNA,
    H.CD_SET_CAMPAGNA,
    H.TS_INIZIO_VALIDITA,
    {{ ts_fine_validita("H.CD_PROCEDURA, H.CD_CAMPAGNA, H.CD_SET_CAMPAGNA", "H.TS_INIZIO_VALIDITA") }} AS TS_FINE_VALIDITA,
    H.DS_CAMPAGNA,
    H.DT_INIZIO_VALIDITA,
    H.DT_FINE_VALIDITA,
    H.FL_GESTIONE_CARTE,
    H.FL_GESTIONE_CONSUMO,
    H.FL_ACCETTAZIONE_OBBLIGATORIA,
    H.CD_PROPOSTA,
    H.DS_PROPOSTA,
    H.FL_ESTRAZIONE_STATISTICA,
    H.DS_SET_CAMPAGNA,
    H.TP_ISTRUTTORIA,
    H.NM_GIORNI_VALIDITA,
    H.CD_PROMOZIONE,
    H.CD_EMETTITORE,
    H.CD_PRODOTTO,
    H.CD_TABELLA_FINANZIARIA,
    H.EU_FIDO,
    H.EU_RISERVA_PRINCIPALE,
    H.EU_RISERVA_SALVADANAIO,
    H.EU_RISERVA_INTERNET,
    H.CD_AGENTE,
    H.FL_CONTROLLO_EMETTITORE,
    H.FL_CONTROLLO_PRODOTTO,
    H.FL_ESCLUSIONE_SELEZIONE,
    H.LASTMODIFIEDDATA
FROM dedup H