SELECT
    T.TABICO_INIZIATIVA_COMM AS CD_INIZIATIVA,
    T.TABICO_DESCRIZIONE AS DS_INIZIATIVA,
    {{ custom_to_date('T.TABICO_DATA_INIZIO') }} AS DT_INIZIO_VALIDITA,
    {{ custom_to_date('T.TABICO_DATA_FINE') }} AS DT_FINE_VALIDITA,
    T.TABICO_SIGLA_SOCIETA AS SIGLA_SOCIETA,
    T.TABICO_COD_FILIALE_DEFAULT AS CD_FILIALE_DEFAULT,
    T.TABICO_CAMPAGNA_INDIVIDUALE AS CD_CAMPAGNA_INDIVIDUALE,
    T.TABICO_FLAG_ABIL_CARTE AS FL_ABIL_CARTE,
    T.TABICO_FLAG_ABIL_CONSUMO AS FL_ABIL_CONSUMO,
    T.TABICO_FLAG_NASCOSTO AS FL_NASCOSTO,
    T.TABICO_SOGGETTO_TERZO AS CD_SOGGETTO_TERZO,
    T.TABICO_RIUTILIZZO_SU_CLI AS FL_RIUTILIZZO_SU_CLI,
    T.TABICO_LETTERA_DBT_CL AS FL_LETTERA_DBT_CL,
    T.TABICO_LETTERA_DBT_CO AS FL_LETTERA_DBT_CO,
    T.TABICO_LETTERA_DBT_GA AS FL_LETTERA_DBT_GA,
    T.TABICO_EMIS_FATT_CONTRIB AS FL_EMIS_FATT_CONTRIB,
    -- WARN: FL_INIZIATIVA_ONLINE - data model indica sorgente composita "TIG + CCTABICO" (chiave CD_INIZIATIVA = TABICO_INIZIATIVA_COMM) ma non fornisce una Regola Tecnica che definisca la logica di calcolo (descrizione: "Se l'iniziativa arriva da TIG ed e' anche in OCS allora Y"). Impostato a NULL in attesa di RT.
    NULL AS FL_INIZIATIVA_ONLINE,
    -- WARN: TP_CATEGORIA_INZIATIVA - sorgente TIG indicata ma colonna sorgente (SORGENTE CAMPI L1) vuota e nessuna Regola Tecnica. Impostato a NULL in attesa di dettaglio sorgente.
    NULL AS TP_CATEGORIA_INZIATIVA,
    -- WARN: TP_MACROCATEGORIA_INIZIATIVA - sorgente TIG indicata ma colonna sorgente (SORGENTE CAMPI L1) vuota e nessuna Regola Tecnica. Impostato a NULL in attesa di dettaglio sorgente.
    NULL AS TP_MACROCATEGORIA_INIZIATIVA
FROM {{ ref('cctabico') }} T
-- LEFT JOIN { re('tig')}} G*** CORREGGI
-- ON CD_INIZIATIVA + TABICO_INIZIATIVA_COMM  *** DA VEDERE
WHERE T.FL_DELETED = 'N'