-- WARN: OXCSFCAM - cluster non specificato nel data model (colonna SORGENTI vuota per questa entita').
--       Trattata come non-C (nessun TS_INIZIO/FINE_VALIDITA gia' presente in L1): TS_INIZIO_VALIDITA e
--       TS_FINE_VALIDITA sono costruiti in L2. Nessun filtro FL_DELETED applicato (cluster non risulta A1/A2/C).
-- WARN: TS_INIZIO_VALIDITA e TS_FINE_VALIDITA sono derivati rispettivamente da OXCSCAM_DATA_INIZIO e
--       OXCSCAM_DATA_FINE. Quando OXCSCAM_DATA_FINE e' nullo, zero o non valido, viene utilizzata
--       la data convenzionale 9999-12-31.

WITH base AS (

    SELECT
        T.OXCSCAM_PRATICA AS CD_PRATICA,
        T.OXCSCAM_PROCEDURA AS TP_PROCEDURA,
        T.OXCSCAM_AZIONE AS CD_AZIONE_POSTVENDITA,
        T.OXCSCAM_CAMPAGNA AS CD_CAMPAGNA,
        T.OXCSCAM_PROGRESSIVO AS NM_PROGRESSIVO,
        {{ custom_to_timestamp_ntz('T.OXCSCAM_DATA_INIZIO', '00000000') }} AS TS_INIZIO_VALIDITA,
        --TRY_TO_TIMESTAMP_NTZ(
        --    NULLIF(TRIM(TO_VARCHAR(T.OXCSCAM_DATA_INIZIO)), '0'),
        --    'YYYYMMDD'
        --) AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita(
            "CD_PRATICA, TP_PROCEDURA, CD_AZIONE_POSTVENDITA, CD_CAMPAGNA, NM_PROGRESSIVO",
            custom_to_timestamp_ntz('T.OXCSCAM_DATA_FINE', '00000000')
        ) }} AS TS_FINE_VALIDITA,
        --COALESCE(
        --    TRY_TO_TIMESTAMP_NTZ(
        --        NULLIF(TRIM(TO_VARCHAR(T.OXCSCAM_DATA_FINE)), '0'),
        --        'YYYYMMDD'
        --    ),
        --    TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
        --) AS TS_FINE_VALIDITA,
        {{ custom_to_timestamp_ntz('T.OXCSCAM_DATA_INS', 'T.OXCSCAM_ORA_INS') }} AS TS_INSERIMENTO,
        {{ custom_to_date('T.OXCSCAM_DATA_INIZIO') }} AS DT_INIZIO_VALIDITA,
        {{ custom_to_date('T.OXCSCAM_DATA_FINE') }} AS DT_FINE_VALIDITA,
        --TRY_TO_DATE(
        --    NULLIF(TRIM(TO_VARCHAR(T.OXCSCAM_DATA_INIZIO)), '0'),
        --    'YYYYMMDD'
        --) AS DT_INIZIO_VALIDITA,
        --COALESCE(
        --    TRY_TO_DATE(
        --        NULLIF(TRIM(TO_VARCHAR(T.OXCSCAM_DATA_FINE)), '0'),
        --        'YYYYMMDD'
        --    ),
        --    TO_DATE('9999-12-31')
        --) AS DT_FINE_VALIDITA,
        T.OXCSCAM_STATO AS CD_STATO_CAMPAGNA,
        T.OXCSCAM_ANNULLO AS FL_ANNULLAMENTO_MANUALE,
        {{ custom_to_timestamp_ntz('T.OXCSCAM_ANN_DATA', 'T.OXCSCAM_ANN_ORA') }} AS TS_ANNULLAMENTO,
        T.OXCSCAM_ANN_UTENTE AS CD_UTENTE_ANNULLAMENTO,
        T.OXCSCAM_UTENTE_INS AS CD_UTENTE_INSERIMENTO,
        T.OXCSCAM_PGM_1_LIB AS CD_LIBRERIA_PROGRAMMA_ULTIMO,
        T.OXCSCAM_PGM_1 AS CD_PROGRAMMA_ULTIMO,
        T.OXCSCAM_PGM_2_LIB AS CD_LIBRERIA_PROGRAMMA_PRECEDENTE,
        T.OXCSCAM_PGM_2 AS CD_PROGRAMMA_PRECEDENTE,
        T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA

    FROM {{ ref('oxcsfcam') }} T

),

dedup AS (

    SELECT
        CD_PRATICA,
        TP_PROCEDURA,
        CD_AZIONE_POSTVENDITA,
        CD_CAMPAGNA,
        NM_PROGRESSIVO,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        TS_INSERIMENTO,
        DT_INIZIO_VALIDITA,
        DT_FINE_VALIDITA,
        CD_STATO_CAMPAGNA,
        FL_ANNULLAMENTO_MANUALE,
        TS_ANNULLAMENTO,
        CD_UTENTE_ANNULLAMENTO,
        CD_UTENTE_INSERIMENTO,
        CD_LIBRERIA_PROGRAMMA_ULTIMO,
        CD_PROGRAMMA_ULTIMO,
        CD_LIBRERIA_PROGRAMMA_PRECEDENTE,
        CD_PROGRAMMA_PRECEDENTE,
        LASTMODIFIEDDATA,
        {{ hash_cols([
            'CD_PRATICA', 'TP_PROCEDURA', 'CD_AZIONE_POSTVENDITA', 'CD_CAMPAGNA', 'NM_PROGRESSIVO',
            'TS_INSERIMENTO', 'DT_INIZIO_VALIDITA', 'DT_FINE_VALIDITA', 'CD_STATO_CAMPAGNA',
            'FL_ANNULLAMENTO_MANUALE', 'TS_ANNULLAMENTO', 'CD_UTENTE_ANNULLAMENTO', 'CD_UTENTE_INSERIMENTO',
            'CD_LIBRERIA_PROGRAMMA_ULTIMO', 'CD_PROGRAMMA_ULTIMO', 'CD_LIBRERIA_PROGRAMMA_PRECEDENTE',
            'CD_PROGRAMMA_PRECEDENTE'
        ]) }} AS HASHED_COLS

    FROM base
    {{ is_incremental_S1(['CD_PRATICA', 'TP_PROCEDURA', 'CD_AZIONE_POSTVENDITA', 'CD_CAMPAGNA', 'NM_PROGRESSIVO']) }}

)

SELECT
    H.CD_PRATICA,
    H.TP_PROCEDURA,
    H.CD_AZIONE_POSTVENDITA,
    H.CD_CAMPAGNA,
    H.NM_PROGRESSIVO,
    H.TS_INIZIO_VALIDITA,
    H.TS_FINE_VALIDITA,
    H.TS_INSERIMENTO,
    H.DT_INIZIO_VALIDITA,
    H.DT_FINE_VALIDITA,
    H.CD_STATO_CAMPAGNA,
    H.FL_ANNULLAMENTO_MANUALE,
    H.TS_ANNULLAMENTO,
    H.CD_UTENTE_ANNULLAMENTO,
    H.CD_UTENTE_INSERIMENTO,
    H.CD_LIBRERIA_PROGRAMMA_ULTIMO,
    H.CD_PROGRAMMA_ULTIMO,
    H.CD_LIBRERIA_PROGRAMMA_PRECEDENTE,
    H.CD_PROGRAMMA_PRECEDENTE,
    H.LASTMODIFIEDDATA

FROM dedup H