WITH 
-- cte per calcolare le substring
base_substr AS (
    SELECT
        --SUBSTR(_2DCOMM, 34, 13) AS ID_SPEDIZIONE, --???
        SUBSTR(T._2DCOMM, 65, 7) AS ID_SPEDIZIONE,
        SUBSTR(T._2DCOMM, 56, 9) AS CD_CLIENTE, 
        T.ID_POSTALIZZAZIONE AS ID_POSTALIZZAZIONE,
        T.DT_ACCETTAZIONE AS DT_ACCETTAZIONE,
        CAST(T.DT_ACCETTAZIONE AS TIMESTAMP_NTZ) AS TS_INIZIO_VALIDITA, 
        --T.TS_FINE_VALIDITA AS TS_FINE_VALIDITA,
        T.ID_SAP AS ID_SAP,
        T.DS_CENTRO_ACCETTANTE AS DS_CENTRO_ACCETTANTE,
        T.DT_PROSSIM_TENTATIVO_CONSEGNA AS DT_PROSSIMO_TENTATIVO_CONSEGNA,
        T.CAP AS CD_CAP,
        T.DS_LOCALITA AS DS_LOCALITA,
        T._2DCOMM AS CD_2DCOMM,
        T.CD_ESITO AS CD_ESITO,
        T.DS_CAUSALE AS DS_CAUSALE,
        T.ANOMALIA AS DS_ANOMALIA,
        --???
        -- SUBSTR(stringa, posizione_iniziale, lunghezza)
        T.TS_RIFERIMENTO AS LASTMODIFIEDDATA 
    FROM {{ ref('mailc_esiti_tgb') }} T
),


base AS (
    SELECT
        T.ID_SPEDIZIONE AS ID_SPEDIZIONE,
        T.CD_CLIENTE AS CD_CLIENTE,
        T.ID_POSTALIZZAZIONE AS ID_POSTALIZZAZIONE,
        T.TS_INIZIO_VALIDITA AS TS_INIZIO_VALIDITA,
        {{ ts_fine_validita('T.ID_SPEDIZIONE, T.CD_CLIENTE, T.ID_POSTALIZZAZIONE', 'T.TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA,
        --CAST(T.TS_INIZIO_VALIDITA AS TIMESTAMP_NTZ) AS TS_INIZIO_VALIDITA, dt_Accettazione
        --T.TS_FINE_VALIDITA AS TS_FINE_VALIDITA,
        T.ID_SAP AS ID_SAP,
        T.DT_ACCETTAZIONE AS DT_ACCETTAZIONE, -- TENGO?
        T.DS_CENTRO_ACCETTANTE AS DS_CENTRO_ACCETTANTE,
        T.DT_PROSSIMO_TENTATIVO_CONSEGNA AS DT_PROSSIMO_TENTATIVO_CONSEGNA,
        T.CD_CAP AS CD_CAP,
        T.DS_LOCALITA AS DS_LOCALITA,
        T.CD_2DCOMM AS CD_2DCOMM,
        T.CD_ESITO AS CD_ESITO,
        T.DS_CAUSALE AS DS_CAUSALE,
        T.DS_ANOMALIA AS DS_ANOMALIA,
        -- SUBSTR(stringa, posizione_iniziale, lunghezza)
        T.LASTMODIFIEDDATA AS LASTMODIFIEDDATA 
    FROM  base_substr T
    WHERE CD_CLIENTE != '0000000'
),

dedup AS (
    SELECT
        ID_SPEDIZIONE,
        CD_CLIENTE,
        ID_POSTALIZZAZIONE,
        TS_INIZIO_VALIDITA,
        TS_FINE_VALIDITA,
        
        ID_SAP,
        DT_ACCETTAZIONE,
        DS_CENTRO_ACCETTANTE,
        DT_PROSSIMO_TENTATIVO_CONSEGNA,
        CD_CAP,
        DS_LOCALITA,
        CD_2DCOMM,
        CD_ESITO,
        DS_CAUSALE,
        DS_ANOMALIA,
        
        LASTMODIFIEDDATA,
        {{ hash_cols([
            'ID_SPEDIZIONE',
            'CD_CLIENTE',
            'ID_POSTALIZZAZIONE',
            'ID_SAP',
            'DT_ACCETTAZIONE',
            'DS_CENTRO_ACCETTANTE',
            'DT_PROSSIMO_TENTATIVO_CONSEGNA',
            'CD_CAP',
            'DS_LOCALITA',
            'CD_2DCOMM',
            'CD_ESITO',
            'DS_CAUSALE',
            'DS_ANOMALIA'
            
        ]) }} AS HASHED_COLS
    FROM base
    {{ is_incremental_S1('ID_SPEDIZIONE, CD_CLIENTE, ID_POSTALIZZAZIONE') }}

)

SELECT
    H.ID_SPEDIZIONE,
    H.CD_CLIENTE,
    H.ID_POSTALIZZAZIONE,
    H.TS_INIZIO_VALIDITA,
    --H.TS_INIZIO_VALIDITA,
    {{ ts_fine_validita('H.ID_SPEDIZIONE, H.CD_CLIENTE, H.ID_POSTALIZZAZIONE', 'H.TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA, -- Problema qui, attendi
    
    H.ID_SAP,
    H.DT_ACCETTAZIONE,
    H.DS_CENTRO_ACCETTANTE,
    H.DT_PROSSIMO_TENTATIVO_CONSEGNA,
    H.CD_CAP,
    H.DS_LOCALITA,
    H.CD_2DCOMM,
    H.CD_ESITO,
    H.DS_CAUSALE,
    H.DS_ANOMALIA,
    
    H.LASTMODIFIEDDATA
FROM dedup H