SELECT
    Q.TARGET AS CD_TARGET,
    {{ custom_to_date('Q.DATA_TRIGGER') }} AS DT_TRIGGER,
    Q.COD_CLIENTE AS CD_CLIENTE,
    Q.COGNOME AS DS_COGNOME,
    Q.NOME AS DS_NOME,
    Q.SESSO AS CD_SESSO,
    Q.EMAIL AS DS_EMAIL,
    Q.COD_PRATICA AS CD_PRATICA,
    Q.STATO_PRATICA AS CD_STATO_PRATICA,
    Q.STATO_CLIENTE AS CD_STATO_CLIENTE,
    Q.CANALE_CONTATTO AS CD_CANALE_CONTATTO,
    Q.CALL_CENTER_ESTERNO AS CD_CALL_CENTER_ESTERNO,
    Q.COD_FILIALE AS CD_FILIALE,
    Q.AREA AS CD_AREA,
    Q.RETE AS CD_RETE,
    Q.BENE AS CD_BENE
FROM {{ ref('3937_qualtrics_input') }} Q
-- WARN: nessun campo tecnico di storicizzazione (LASTMODIFIEDDATA/DT_OSSERVAZIONE) nel data model; trattata come S4 (insert_overwrite, nessun filtro incrementale), da confermare col team
