version: 2
models:
  - name: survey_output
    config:
      materialized: incremental
      incremental_strategy: insert_overwrite
      query_tag: '{"app": "DBT", "schema": "L2_CONTATTI", "entita": "SURVEY_OUTPUT"}'
    constraints:
      - type: primary_key
        warn_unenforced: false
        columns: [CD_SURVEY, DT_INVIO_TRIGGER, CD_CLIENTE]
    columns:
      - name: CD_SURVEY
        data_type: CHAR(21)
      - name: DT_INVIO_TRIGGER
        data_type: DATE
      - name: CD_CLIENTE
        data_type: NUMBER(8)
      - name: DS_COGNOME
        data_type: VARCHAR(40)
      - name: DS_NOME
        data_type: VARCHAR(40)
      - name: CD_SESSO
        data_type: VARCHAR(10)
      - name: DS_EMAIL
        data_type: VARCHAR(128)
      - name: CD_PRATICA
        data_type: NUMBER(8)
      - name: CD_STATO_PRATICA
        data_type: VARCHAR(28)
      - name: CD_STATO_CLIENTE
        data_type: VARCHAR(17)
      - name: CD_CANALE_CONTATTO
        data_type: VARCHAR(26)
      - name: CD_CALL_CENTER_ESTERNO
        data_type: VARCHAR(100)
      - name: CD_FILIALE
        data_type: VARCHAR(3)
      - name: CD_AREA
        data_type: VARCHAR(30)
      - name: CD_RETE
        data_type: VARCHAR(20)
      - name: CD_BENE
        data_type: VARCHAR(30)
      - name: DS_Q1
        data_type: NUMBER(2)
      - name: DS_Q9
        data_type: NUMBER(2)
      - name: DS_Q5
        data_type: NUMBER(1)
      - name: DS_Q11
        data_type: NUMBER(2)
      - name: DS_QID88
        data_type: NUMBER(2)
      - name: DS_QID13
        data_type: NUMBER(2)
      - name: DS_QID93
        data_type: NUMBER(2)
      - name: DS_QID89
        data_type: NUMBER(2)
      - name: DS_QID151
        data_type: NUMBER(1)
      - name: DS_QID78
        data_type: NUMBER(1)
