WITH base AS (

    SELECT
        D.ID_DISPOSITIVO_PK AS ID_DISPOSITIVO,
        D.CODICE_CONTROPARTE AS CD_CLIENTE,
        {{ custom_to_timestamp_ntz('D.TIMESTAMP_CREAZIONE') }} AS TS_INIZIO_VALIDITA,
        CASE
            WHEN D.INDICATORE_ASSOCIAZIONE_ATTIVA = 'S' THEN TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
            ELSE {{ custom_to_timestamp_ntz('D.TIMESTAMP_MODIFICA') }}
        END AS TS_FINE_VALIDITA,
        D.CODICE_UUID_DISPOSITIVO AS CD_UUID_DISPOSITIVO,
        D.CODICE_MODELLO AS CD_MODELLO,
        D.DENOMINAZIONE_PRODUTTORE AS DS_PRODUTTORE,
        D.CODICE_SISTEMA_OPERATIVO AS CD_SISTEMA_OPERATIVO,
        D.CODICE_VERSIONE_SISTEMA_OPERATIVO AS CD_VERSIONE_SO,
        D.CODICE_FIREBASE AS CD_FIREBASE,
        D.CODICE_INTESI AS CD_INTESI,
        D.INDICATORE_ASSOCIAZIONE_ATTIVA AS FL_ASSOCIAZIONE_ATTIVA
    FROM {{ ref('dispositivo') }} D -- WARN: data model dichiara la tabella come 'PNE.DISPOSITIVO' (prefisso schema PNE); referenziata solo come 'dispositivo' via ref(), verificare nome modello dbt reale

)

, dedup AS (

    SELECT
        ID_DISPOSITIVO, CD_CLIENTE, TS_INIZIO_VALIDITA, TS_FINE_VALIDITA, CD_UUID_DISPOSITIVO,
        CD_MODELLO, DS_PRODUTTORE, CD_SISTEMA_OPERATIVO, CD_VERSIONE_SO, CD_FIREBASE,
        CD_INTESI, FL_ASSOCIAZIONE_ATTIVA,
        {{ hash_cols([
            'ID_DISPOSITIVO', 'CD_CLIENTE', 'CD_UUID_DISPOSITIVO', 'CD_MODELLO', 'DS_PRODUTTORE',
            'CD_SISTEMA_OPERATIVO', 'CD_VERSIONE_SO', 'CD_FIREBASE', 'CD_INTESI', 'FL_ASSOCIAZIONE_ATTIVA'
        ]) }} AS HASHED_COLS
    FROM base
    {{ is_incremental_S1('ID_DISPOSITIVO') }}

)

SELECT
    H.ID_DISPOSITIVO,
    H.CD_CLIENTE,
    H.TS_INIZIO_VALIDITA,
    {{ ts_fine_validita('H.ID_DISPOSITIVO', 'H.TS_INIZIO_VALIDITA') }} AS TS_FINE_VALIDITA,
    H.CD_UUID_DISPOSITIVO,
    H.CD_MODELLO,
    H.DS_PRODUTTORE,
    H.CD_SISTEMA_OPERATIVO,
    H.CD_VERSIONE_SO,
    H.CD_FIREBASE,
    H.CD_INTESI,
    H.FL_ASSOCIAZIONE_ATTIVA
FROM dedup H
-- WARN: nessun LASTMODIFIEDDATA nel data model per questa entita', da chiarire col team
