version: 2
models:
  - name: iscritti
    config:
      materialized: incremental
      incremental_strategy: insert_overwrite
      query_tag: '{"app": "DBT", "schema": "L2_DIGITAL", "entita": "ISCRITTI"}'
    constraints:
      - type: primary_key
        warn_unenforced: false
        columns: [CD_USER_LOGIN]
    columns:
      - name: CD_USER_LOGIN
        data_type: VARCHAR(10)
      - name: CD_CPART
        data_type: VARCHAR(10)
      - name: CD_ALIAS_LOGIN
        data_type: VARCHAR(10)
      - name: TS_LOGIN
        data_type: TIMESTAMP_NTZ
      - name: NM_ACCESSI
        data_type: NUMBER(10)
      - name: NM_TENT
        data_type: NUMBER(10)
      - name: TS_ULT_TENT
        data_type: TIMESTAMP_NTZ
      - name: IN_BLOCCO
        data_type: VARCHAR(10)
      - name: TS_CAMBIO_PSW
        data_type: TIMESTAMP_NTZ
      - name: TS_FINE_VALI
        data_type: TIMESTAMP_NTZ
      - name: CD_USER_INSE
        data_type: VARCHAR(10)
      - name: CD_TRANS_INSE
        data_type: VARCHAR(10)
      - name: TS_INSE
        data_type: TIMESTAMP_NTZ
      - name: CD_USER_VARZ
        data_type: VARCHAR(10)
      - name: CD_TRANS_VARZ
        data_type: VARCHAR(10)
      - name: TS_VARZ
        data_type: TIMESTAMP_NTZ
