version: 2
models:
  - name: ana_versioni_form
    config:
      materialized: incremental
      incremental_strategy: insert_overwrite
      query_tag: '{"app": "DBT", "schema": "L2_DIGITAL", "entita": "ANA_VERSIONI_FORM"}'
    constraints:
      - type: primary_key
        warn_unenforced: false
        columns: [CD_FORM, NR_VERSIONE, NR_STEP]
    columns:
      - name: CD_FORM
        data_type: VARCHAR(20)
      - name: NR_VERSIONE
        data_type: NUMBER(5)
      - name: NR_STEP
        data_type: NUMBER(3)
      - name: DS_STEP
        data_type: VARCHAR(200)
      - name: NR_ORDINE_STEP
        data_type: NUMBER(3)
      - name: CD_TIPO_STEP
        data_type: VARCHAR(20)
      - name: FL_ATTIVO
        data_type: VARCHAR(1)
      - name: DT_INIZIO_VALIDITA
        data_type: DATE
      - name: DT_FINE_VALIDITA
        data_type: DATE
      - name: TP_FORM
        data_type: VARCHAR(20)
