SELECT
    C.CAMPAIGNID::NUMBER(8) AS CD_CAMPAGNA,
    C.NAME AS DS_CAMPAGNA,
    NULL AS CD_INIZIATIVA_COMMERCIALE, --WARN cosa va messo? (da arrivare)
    C.CATEGORY AS CD_CATEGORIA,
    C.TYPE AS TP_CAMPAGNA,
    C.ROLE AS CD_RUOLO,
    C.ACTIVE AS FL_ATTIVA,
    C.SETSUBSIDIARYFROMZIPCODE AS FL_SUBSIDIARY_FROM_ZIP
FROM {{ ref('pp_campaign') }} C
