select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(OXCNCES_PROGR_CSS AS NUMBER(5,0)) AS oxcnces_progr_css,
  TRY_CAST(IFF(RTRIM(OXCNCES_TRANSAZIONE) = '', ' ', RTRIM(OXCNCES_TRANSAZIONE)) AS VARCHAR(2)) AS oxcnces_transazione,
  TRY_CAST(IFF(RTRIM(OXCNCES_TRANS_DA_FILE) = '', ' ', RTRIM(OXCNCES_TRANS_DA_FILE)) AS VARCHAR(1)) AS oxcnces_trans_da_file,
  TRY_CAST(OXCNCES_COD_CSS AS NUMBER(3,0)) AS oxcnces_cod_css,
  TRY_CAST(OXCNCES_PROGR_SIM AS NUMBER(5,0)) AS oxcnces_progr_sim,
  TRY_CAST(OXCNCES_IMP_CSS AS NUMBER(13,0)) AS oxcnces_imp_css,
  TRY_CAST(OXCNCES_DATA_CSS AS NUMBER(8,0)) AS oxcnces_data_css,
  TRY_CAST(OXCNCES_LIMITE_TAN AS NUMBER(5,3)) AS oxcnces_limite_tan,
  TRY_CAST(OXCNCES_NUM_RATE_INC AS NUMBER(3,0)) AS oxcnces_num_rate_inc,
  TRY_CAST(OXCNCES_SOGLIA_INSOL AS NUMBER(2,0)) AS oxcnces_soglia_insol,
  TRY_CAST(OXCNCES_SOGLIA_STO_INSOL AS NUMBER(2,0)) AS oxcnces_soglia_sto_insol,
  TRY_CAST(OXCNCES_DATA_DEC_DA AS NUMBER(8,0)) AS oxcnces_data_dec_da,
  TRY_CAST(OXCNCES_DATA_DEC_A AS NUMBER(8,0)) AS oxcnces_data_dec_a,
  TRY_CAST(OXCNCES_DATA_PRIMA_SCAD AS NUMBER(8,0)) AS oxcnces_data_prima_scad,
  TRY_CAST(OXCNCES_DATA_ULT_SCAD AS NUMBER(8,0)) AS oxcnces_data_ult_scad,
  TRY_CAST(OXCNCES_IMP_QUOTE_CAPIT_CED AS NUMBER(13,0)) AS oxcnces_imp_quote_capit_ced,
  TRY_CAST(OXCNCES_IMP_NOM_CEDUTO AS NUMBER(13,0)) AS oxcnces_imp_nom_ceduto,
  TRY_CAST(OXCNCES_NUM_CTR_CED AS NUMBER(7,0)) AS oxcnces_num_ctr_ced,
  TRY_CAST(OXCNCES_NUM_RATE_CED AS NUMBER(9,0)) AS oxcnces_num_rate_ced,
  TRY_CAST(OXCNCES_DURATA_MEDIA AS NUMBER(3,0)) AS oxcnces_durata_media,
  TRY_CAST(OXCNCES_DATA_COMPETENZA AS NUMBER(8,0)) AS oxcnces_data_competenza,
  TRY_CAST(OXCNCES_CAP_RESIDUO AS NUMBER(13,0)) AS oxcnces_cap_residuo,
  TRY_CAST(IFF(RTRIM(OXCNCES_CONTR_TERRITORIALE) = '', ' ', RTRIM(OXCNCES_CONTR_TERRITORIALE)) AS VARCHAR(1)) AS oxcnces_contr_territoriale,
  TRY_CAST(IFF(RTRIM(OXCNCES_CONTR_FORMA_PAG) = '', ' ', RTRIM(OXCNCES_CONTR_FORMA_PAG)) AS VARCHAR(1)) AS oxcnces_contr_forma_pag,
  TRY_CAST(IFF(RTRIM(OXCNCES_PERC_FISSE_DISTR) = '', ' ', RTRIM(OXCNCES_PERC_FISSE_DISTR)) AS VARCHAR(1)) AS oxcnces_perc_fisse_distr,
  TRY_CAST(OXCNCES_CAPITALE_MINIMO AS NUMBER(13,0)) AS oxcnces_capitale_minimo,
  TRY_CAST(OXCNCES_DATA_ULT_SCAD_SINTET AS NUMBER(8,0)) AS oxcnces_data_ult_scad_sintet,
  TRY_CAST(OXCNCES_DATA_SCAD_RATA_DA AS NUMBER(8,0)) AS oxcnces_data_scad_rata_da,
  TRY_CAST(OXCNCES_CAPIT_RESID_CLI_MAX AS NUMBER(13,0)) AS oxcnces_capit_resid_cli_max,
  TRY_CAST(OXCNCES_ASSIC_CEDIBILE_MIN AS NUMBER(13,0)) AS oxcnces_assic_cedibile_min,
  TRY_CAST(OXCNCES_INTER_CEDIBILI_MIN AS NUMBER(13,0)) AS oxcnces_inter_cedibili_min,
  TRY_CAST(IFF(RTRIM(OXCNCES_CONTR_TAN) = '', ' ', RTRIM(OXCNCES_CONTR_TAN)) AS VARCHAR(1)) AS oxcnces_contr_tan,
  TRY_CAST(IFF(RTRIM(OXCNCES_SEGN_CED_NON_CANC) = '', ' ', RTRIM(OXCNCES_SEGN_CED_NON_CANC)) AS VARCHAR(1)) AS oxcnces_segn_ced_non_canc,
  TRY_CAST(OXCNCES_COD_TRANS_BANKIT AS NUMBER(14,0)) AS oxcnces_cod_trans_bankit,
  TRY_CAST(OXCNCES_PERC_MAX_SIN_RIN AS NUMBER(5,2)) AS oxcnces_perc_max_sin_rin,
  TRY_CAST(OXCNCES_PERC_MAX_SIN_PRV AS NUMBER(5,2)) AS oxcnces_perc_max_sin_prv,
  TRY_CAST(OXCNCES_IMP_MAX_SIN_RIN AS NUMBER(13,0)) AS oxcnces_imp_max_sin_rin,
  TRY_CAST(OXCNCES_IMP_MAX_SIN_PRV AS NUMBER(13,0)) AS oxcnces_imp_max_sin_prv,
  TRY_CAST(OXCNCES_IMP_MAX_SIN_DEF AS NUMBER(13,0)) AS oxcnces_imp_max_sin_def,
  TRY_CAST(IFF(RTRIM(OXCNCES_ESC_CTR_TIT_CONTI) = '', ' ', RTRIM(OXCNCES_ESC_CTR_TIT_CONTI)) AS VARCHAR(1)) AS oxcnces_esc_ctr_tit_conti,
  TRY_CAST(IFF(RTRIM(OXCNCES_CONTR_ATC) = '', ' ', RTRIM(OXCNCES_CONTR_ATC)) AS VARCHAR(1)) AS oxcnces_contr_atc,
  TRY_CAST(IFF(RTRIM(OXCNCES_CONTR_ASS_VITA) = '', ' ', RTRIM(OXCNCES_CONTR_ASS_VITA)) AS VARCHAR(1)) AS oxcnces_contr_ass_vita,
  TRY_CAST(IFF(RTRIM(OXCNCES_CONTR_ASS_IMP) = '', ' ', RTRIM(OXCNCES_CONTR_ASS_IMP)) AS VARCHAR(1)) AS oxcnces_contr_ass_imp,
  TRY_CAST(OXCNCES_DT_CT_QUADRO AS NUMBER(8,0)) AS oxcnces_dt_ct_quadro,
  TRY_CAST(OXCNCES_DT_LETT_CESS_MASSIVA AS NUMBER(8,0)) AS oxcnces_dt_lett_cess_massiva,
  TRY_CAST(OXCNCES_DT_GAZZETTA AS NUMBER(8,0)) AS oxcnces_dt_gazzetta,
  TRY_CAST(OXCNCES_NUM_GAZZETTA AS NUMBER(3,0)) AS oxcnces_num_gazzetta,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','oxcnfces') }}
