-- =============================================================================
-- MODELLO   : dm_cmp_acc_co_campioni_m
-- PROCESSO  : Campioni Accettazione CO | LAYER: L3 - DataMart
-- DM_ID     : DM_38
-- PK        : CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE
-- NOTA      : nessuna deduplica applicata. Ogni sorgente e' letta alla sua
--             grana naturale; eventuali duplicati vanno risolti a monte.
-- =============================================================================

{% set dt_rif = "LAST_DAY(DATEADD('month', -1, CURRENT_DATE))" %}

WITH

-- ===================== PERIMETRO (CTE guida) =====================
perimetro AS (
    SELECT
        CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE, CD_CLIENTE, CD_STATO,
        DT_RITIRATA, DT_PASSAGGIO_PERDITA, CD_MACRO_PRODOTTO_4,
        DT_CHIUSURA_EFFETTIVA, EU_PREZZO_BENE
    FROM {{ ref('dm_cmp_acc_perimetro_co') }}
    WHERE CD_STATO IN ('30', '50', '51', '55', '97', '96')
    {% if is_incremental() %}
      AND DT_OSSERVAZIONE = {{ dt_rif }}
    {% endif %}
),

-- ===================== PRATICA_M =====================
-- Unica lettura di pratica_m: attributi di pratica + aggregazioni
-- cross-pratica del cliente via window function (nessun self-join).
pratica_m_base AS (
    SELECT
        PM.CD_PRATICA, PM.TP_PROCEDURA, PM.DT_OSSERVAZIONE, PM.CD_CLIENTE,
        PM.CD_ABI, PM.CD_AGENTE, PM.CD_CAB, PM.CD_CC,
        PM.CD_CANALE_ACQUISIZIONE, PM.CD_CONVENZIONATO, PM.CD_COOBLIGATO,
        PM.CD_DESTINAZIONE_BENE, PM.CD_FILIALE_PRAT AS CD_FILIALE,
        PM.CD_GIA_CLIENTE_MARKETING, PM.CD_IBAN,
        PM.CD_MACRO_PRODOTTO_1, PM.CD_MACRO_PRODOTTO_2, PM.CD_MACRO_PRODOTTO_3,
        PM.CD_MERCATO_1, PM.CD_MERCATO_2, PM.CD_MERCATO_3, PM.CD_MERCATO_4,
        PM.CD_PRODOTTO, PM.CD_PUNTO_VENDITA, PM.CD_RETE_VENDITA,
        PM.CD_SUB_AGENTE, PM.CD_TIPO_PRODOTTO, PM.CD_VENDITORE,
        PM.DS_DESTINAZIONE_BENE, PM.DS_INSEGNA,
        PM.DT_APPROVAZIONE, PM.DT_CARICAMENTO, PM.DT_CESSIONE,
        PM.DT_CHIUSURA_ANZIANITA, PM.DT_CHIUSURA_EFFETTIVA, PM.DT_CHIUSURA_REGOLARE,
        PM.DT_DBT, PM.DT_DECORRENZA, PM.DT_ESAMINATA, PM.DT_ESITO,
        PM.DT_ESTINZIONE_ANTICIPATA, PM.DT_LIQUIDAZIONE, PM.DT_MESSA_IN_MORA,
        PM.DT_PASSAGGIO_PERDITA, PM.DT_PRIMA_SCADENZA, PM.DT_PRIMA_SCADENZA_IST,
        PM.DT_RESPINTA, PM.DT_RITIRATA, PM.DT_STORNATA,
        PM.DT_ULTIMA_SCADENZA, PM.DT_ULTIMA_SCADENZA_IST, PM.DT_ULT_ACCODAMENTO,
        PM.EU_RATA, PM.FL_GIA_CLIENTE_CREDITI, PM.FL_GIA_CLIENTE_MARKETING,
        PM.FL_PERDITA_CESSIONE, PM.FL_WEB_CANALE_ACQ,
        PM.IN_FIRMA_DOPPIA, PM.TS_COMUNICAZIONE_ESITO_DEF,

        -- === CONSUMO_M (stessa grana: join 1:1) ===
        CM.CD_FREQ_RATA, CM.CD_MARCA_AUTO, CM.DS_MODELLO_AUTO,
        CM.FL_BENE_DETRAZ_FISCALE, CM.FL_MAXI_RATA_OPZIONATA,
        CM.NM_DURATA_FINANZ, CM.NM_MESI_DILAZIONE,
        CM.NM_TAEG1, CM.NM_TAEG2, CM.NM_TAN1, CM.NM_TAN2,
        CM.NM_TAN_PREAMM, CM.NM_TAN_RATE,
        CM.NM_TASSO_CLIENTE, CM.NM_TASSO_MORA,
        CM.EU_ANTICIPO, CM.EU_COMMISSIONI_IST, CM.EU_EROGATO, CM.EU_FRESH_CASH,
        CM.EU_INTERESSI_CONVENZ, CM.EU_INTERESSI_TERZ, CM.EU_MAXI_RATA,
        CM.EU_MONTANTE, CM.EU_SPESE_BOLLO_EC, CM.EU_SPESE_BOLLO_IST,
        CM.EU_SPESE_DILAZ_CONVENZ, CM.EU_SPESE_EC, CM.EU_SPESE_RICORRENTI,
        CM.EU_SPESE_RICORRENTI_TOT, CM.EU_SPESE_SMGP, CM.EU_SPESE_TOT_IST,
        CM.EU_SPESE_TRASPARENZA, CM.EU_TOT_CONTRIB_DA_INTER, CM.EU_TOT_INTERESSI,
        -- omonimi con PRATICA_M: alias esplicito
        CM.EU_RATA   AS EU_RATA_CONSUMO,
        CM.EU_RATA_2 AS EU_RATA_2_CONSUMO,
        CM.NM_RATE   AS NM_RATE_CONSUMO,
        CM.NM_RATE_2 AS NM_RATE_2_CONSUMO,

        -- === aggregazioni cross-pratica per cliente ===
        MIN(PM.DT_CARICAMENTO)    OVER (PARTITION BY PM.CD_CLIENTE) AS DT_CARICAMENTO_MIN,
        MIN(PM.DT_DECORRENZA)     OVER (PARTITION BY PM.CD_CLIENTE) AS DT_DECORRENZA_MIN,
        MIN(PM.DT_PRIMA_SCADENZA) OVER (PARTITION BY PM.CD_CLIENTE) AS DT_ACQUISTO_MIN,
        FIRST_VALUE(PM.CD_PRATICA) OVER (
            PARTITION BY PM.CD_CLIENTE ORDER BY PM.DT_CARICAMENTO ASC
        ) AS CD_PRATICA_CARICAMENTO_MIN,
        FIRST_VALUE(PM.CD_PRATICA) OVER (
            PARTITION BY PM.CD_CLIENTE ORDER BY PM.DT_DECORRENZA ASC
        ) AS CD_PRATICA_DECORRENZA_MIN,
        DATEDIFF('month', MIN(PM.DT_CARICAMENTO) OVER (PARTITION BY PM.CD_CLIENTE), PM.DT_OSSERVAZIONE) AS NM_MESI_CLIENTE

    FROM {{ ref('pratica_m') }} PM
    LEFT JOIN {{ ref('consumo_m') }} CM
        ON  CM.CD_PRATICA      = PM.CD_PRATICA
        AND CM.TP_PROCEDURA    = PM.TP_PROCEDURA
        AND CM.DT_OSSERVAZIONE = PM.DT_OSSERVAZIONE
    WHERE PM.TP_PROCEDURA = 'CO'
    {% if is_incremental() %}
      AND PM.DT_OSSERVAZIONE = {{ dt_rif }}
    {% endif %}
),

-- ===================== INDICE_RISCHIO_M + CONSOLIDAMENTI =====================
-- Stesso driver (perimetro) e stesse chiavi di GROUP BY: le due tabelle sono
-- lette una sola volta e tutti gli aggregati sono MAX(...), quindi il fan-out
-- tra le due sorgenti non altera i valori.
rischio_consolidamenti_agg AS (
    SELECT
        P.CD_PRATICA, P.TP_PROCEDURA, P.DT_OSSERVAZIONE,
        MAX(CASE WHEN IR.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN IR.NM_MAX_RATE_IMPAGATE END) AS MAX_INSOLVENZA_CLI_CURRENT,
        MAX(CASE WHEN IR.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN IR.NM_MAX_RATE_IMPAGATE END) AS MAX_INSOLVENZA_CLI_WORST,
        MAX(CASE WHEN IR.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN IR.NM_IMPAGATE END)          AS MAX_INSOLVENZA_CLIENTE,
        MAX(IR.NM_IMPAGATE)                                                                    AS MAX_INS_CLI_L120M,
        MAX(IR.NM_MAX_RATE_IMPAGATE)                                                           AS MAX_INS_CLI_L120M_WORST,
        MAX(CASE WHEN CONS.CD_PRATICA_CONSOLIDATA IS NOT NULL
                   OR CONS.CD_PRATICA_CONSOLIDANTE IS NOT NULL
                 THEN 'S' ELSE 'N' END)                                                        AS FL_CONSOLIDAMENTO
    FROM perimetro P
    LEFT JOIN {{ ref('indice_rischio_m') }} IR
        ON  IR.CD_CLIENTE      = P.CD_CLIENTE
        AND IR.DT_OSSERVAZIONE >= DATEADD('month', -120, P.DT_OSSERVAZIONE)
        AND IR.DT_OSSERVAZIONE <= P.DT_OSSERVAZIONE
    LEFT JOIN {{ ref('consolidamenti') }} CONS
        ON  CONS.CD_PRATICA_CONSOLIDATA  = P.CD_PRATICA
         OR CONS.CD_PRATICA_CONSOLIDANTE = P.CD_PRATICA
    GROUP BY P.CD_PRATICA, P.TP_PROCEDURA, P.DT_OSSERVAZIONE
),

-- ===================== VARIAZIONI_ANAGRAFICHE =====================
-- Lettura unica: CLI e COOB separati con aggregazione condizionata,
-- non con due alias della stessa tabella.
variazioni_anag AS (
    SELECT
        PMB.CD_PRATICA,
        MAX(CASE WHEN VA.CD_CONTROPARTE = PMB.CD_CLIENTE    THEN VA.CD_NAZIONE_NASCITA END) AS CD_NAZIONE_CLI,
        MAX(CASE WHEN VA.CD_CONTROPARTE = PMB.CD_CLIENTE    THEN VA.DS_CITTA_NASCITA   END) AS DS_CITTA_NASCITA,
        MAX(CASE WHEN VA.CD_CONTROPARTE = TRY_TO_NUMBER(PMB.CD_COOBLIGATO) THEN VA.CD_NAZIONE_NASCITA END) AS CD_NAZIONE_COOB
    FROM pratica_m_base PMB
    LEFT JOIN {{ ref('variazioni_anagrafiche') }} VA
        ON VA.CD_CONTROPARTE IN (PMB.CD_CLIENTE, TRY_TO_NUMBER(PMB.CD_COOBLIGATO))
    GROUP BY PMB.CD_PRATICA
),

-- ===================== ACCETTAZIONE_INPUT (+ PRAT_PREC) =====================
-- Lettura unica di accettazione_input: pivot per CD_RUOLO con aggregazione
-- condizionata. DT_UF_CLI / DT_UF_COBLGT arrivano da PRAT_PREC per ruolo.
accettazione_input AS (
    SELECT
        AI.CD_PRATICA,
        AI.TP_PROCEDURA,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.CD_ESITO_SCORE END)          AS CD_ESITO_SCORE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.FL_GIA_CLIENTE END)          AS FL_GIA_CLIENTE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.FL_GIA_CLIENTE END)          AS FL_GIA_CLIENTE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.CD_CERVED_RAE_CODICE END)    AS CD_CERVED_RAE_CODICE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.CD_CERVED_RAE_CODICE END)    AS CD_CERVED_RAE_CODICE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.CD_STATO_CIVILE END)         AS CD_STATO_CIVILE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.CD_STATO_CIVILE END)         AS CD_STATO_CIVILE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.EU_TOT_ENTRATE_MENSILI END)  AS EU_TOT_ENTRATE_MENSILI_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.EU_TOT_ENTRATE_MENSILI END)  AS EU_TOT_ENTRATE_MENSILI_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.EU_FIDO END)                 AS EU_FIDO_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.FL_PROTESTI END)             AS FL_PROTESTI_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.FL_PROTESTI END)             AS FL_PROTESTI_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN AI.FL_TRUFFATORE END)           AS FL_TRUFFATORE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.FL_TRUFFATORE END)           AS FL_TRUFFATORE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN APP.DT_LIQUIDAZIONE END)        AS DT_LIQUIDAZIONE_PRAT_PREC_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN APP.DT_LIQUIDAZIONE END)        AS DT_LIQUIDAZIONE_PRAT_PREC_COOB
    FROM {{ ref('accettazione_input') }} AI
    LEFT JOIN {{ ref('accettazione_input_prat_prec') }} APP
        ON APP.CD_PRATICA = AI.CD_PRATICA_PREV_APP
    WHERE AI.CD_RUOLO IN ('CLI', 'COOB')
    GROUP BY AI.CD_PRATICA, AI.TP_PROCEDURA
)

-- ===================== SELECT FINALE =====================
SELECT
    -- === PK ===
    P.CD_PRATICA, P.TP_PROCEDURA, P.CD_CLIENTE, P.DT_OSSERVAZIONE,

    -- === Campi specifici CO (destinazione bene / prezzo) ===
    PMB.CD_DESTINAZIONE_BENE, PMB.DS_DESTINAZIONE_BENE,
    P.EU_PREZZO_BENE,
    PMB.CD_PRODOTTO, PMB.CD_TIPO_PRODOTTO,
    PMB.CD_CANALE_ACQUISIZIONE, PMB.FL_WEB_CANALE_ACQ,

    -- === PRATICA_M - prodotto / mercato ===
    PMB.CD_MACRO_PRODOTTO_1, PMB.CD_MACRO_PRODOTTO_2, PMB.CD_MACRO_PRODOTTO_3,
    P.CD_MACRO_PRODOTTO_4,
    PMB.CD_MERCATO_1, PMB.CD_MERCATO_2, PMB.CD_MERCATO_3, PMB.CD_MERCATO_4,

    -- === ANA_STRUTTURA_INTERNA (no CD_FILIALE/DS_FILIALE per CO) ===
    ASI.CD_DISTRETTO_FILIALE, ASI.DS_DISTRETTO_FILIALE,
    ASI.CD_AREA_FILIALE, ASI.DS_AREA_FILIALE,

    -- === PRATICA_M - rete vendita ===
    PMB.CD_RETE_VENDITA, PMB.CD_AGENTE, PMB.CD_SUB_AGENTE, PMB.CD_CONVENZIONATO,
    PMB.CD_PUNTO_VENDITA, PMB.DS_INSEGNA, PMB.CD_VENDITORE,

    -- === CONSUMO_M - tassi ===
    PMB.NM_TAN1, PMB.NM_TAN2, PMB.NM_TAN_PREAMM, PMB.NM_TAN_RATE,
    PMB.NM_TAEG1, PMB.NM_TAEG2, PMB.NM_TASSO_MORA, PMB.NM_TASSO_CLIENTE,

    -- === PRATICA_M - date processo ===
    PMB.DT_CARICAMENTO, PMB.DT_ESAMINATA, PMB.DT_ESITO, PMB.DT_APPROVAZIONE,
    PMB.DT_RESPINTA, P.DT_RITIRATA, PMB.DT_LIQUIDAZIONE, PMB.DT_DECORRENZA,
    PMB.DT_STORNATA, PMB.DT_CHIUSURA_REGOLARE, PMB.DT_ESTINZIONE_ANTICIPATA,
    P.DT_PASSAGGIO_PERDITA, PMB.DT_CESSIONE, P.DT_CHIUSURA_EFFETTIVA,
    PMB.DT_MESSA_IN_MORA, PMB.DT_DBT, PMB.TS_COMUNICAZIONE_ESITO_DEF,
    PMB.DT_CHIUSURA_ANZIANITA, PMB.DT_ULT_ACCODAMENTO,
    PMB.DT_PRIMA_SCADENZA, PMB.DT_PRIMA_SCADENZA_IST,
    PMB.DT_ULTIMA_SCADENZA, PMB.DT_ULTIMA_SCADENZA_IST,

    -- === Aggregati per cliente ===
    PMB.DT_ACQUISTO_MIN, PMB.DT_CARICAMENTO_MIN, PMB.DT_DECORRENZA_MIN,

    -- === SOCIODEMO_SCORE ===
    SDC.DT_OSSERVAZIONE AS DT_CARICAMENTO_SCORE,

    -- === PRATICA_M - coordinate bancarie ===
    PMB.CD_ABI AS CD_ABI_CLIENTE,
    PMB.CD_CAB AS CD_CAB_CLIENTE,
    PMB.CD_CC  AS CD_CC_CLIENTE,

    -- === VARIAZIONI_ANAGRAFICHE ===
    VA.DS_CITTA_NASCITA AS CD_PAESE,
    PMB.CD_PRATICA_CARICAMENTO_MIN, PMB.CD_PRATICA_DECORRENZA_MIN,
    VA.CD_NAZIONE_CLI, VA.CD_NAZIONE_COOB,
    PMB.CD_COOBLIGATO AS CD_COOBBLIGATO,

    -- === CD_CIN (da CD_IBAN) ===
    SUBSTR(PMB.CD_IBAN, 4, 1) AS CD_CIN,

    -- === Flag CO specifici ===
    PMB.FL_MAXI_RATA_OPZIONATA AS FL_MAXIRATA,
    COALESCE(IRA.FL_CONSOLIDAMENTO, 'N') AS FL_CONSOLIDAMENTO,
    PMB.IN_FIRMA_DOPPIA AS FL_FIRMA_DOPPIA,
    PMB.FL_GIA_CLIENTE_MARKETING, PMB.CD_GIA_CLIENTE_MARKETING,
    PMB.FL_GIA_CLIENTE_CREDITI,
    PMB.FL_BENE_DETRAZ_FISCALE,

    -- === INDICE_RISCHIO_M ===
    IRA.MAX_INS_CLI_L120M, IRA.MAX_INS_CLI_L120M_WORST,
    IRA.MAX_INSOLVENZA_CLI_CURRENT, IRA.MAX_INSOLVENZA_CLI_WORST,
    IRA.MAX_INSOLVENZA_CLIENTE,

    -- === Calcolati ===
    YEAR(PMB.DT_DECORRENZA)  AS NM_ANNO_DECORRENZA,
    MONTH(PMB.DT_DECORRENZA) AS NM_MESE_DECORRENZA,
    PMB.NM_MESI_CLIENTE,

    -- === PRATICA_M - rata totale ===
    PMB.EU_RATA AS EU_RATA_TOT,

    -- === CONSUMO_M - rate / durata / importi ===
    PMB.NM_RATE_CONSUMO   AS NM_RATE,
    PMB.NM_RATE_2_CONSUMO AS NM_RATE_2,
    PMB.EU_RATA_CONSUMO   AS EU_RATA,
    PMB.EU_RATA_2_CONSUMO AS EU_RATA_2,
    PMB.NM_DURATA_FINANZ, PMB.CD_FREQ_RATA, PMB.NM_MESI_DILAZIONE,

    CAST(NULL AS DATE) AS DT_OPZIONE,
    CAST(NULL AS DATE) AS DT_SCADENZA_SPEC,

    -- === GESTIONE_TRUFFE ===
    GT.TP_TRUFFA, GT.CD_TRUFFA,

    -- === CONSUMO_M - dettaglio economico ===
    PMB.EU_EROGATO, PMB.EU_TOT_INTERESSI, PMB.EU_MAXI_RATA,
    PMB.EU_ANTICIPO, PMB.EU_MONTANTE, PMB.EU_FRESH_CASH,
    PMB.EU_COMMISSIONI_IST, PMB.EU_SPESE_BOLLO_IST, PMB.EU_SPESE_TOT_IST,
    PMB.EU_INTERESSI_TERZ, PMB.EU_INTERESSI_CONVENZ,
    PMB.EU_SPESE_DILAZ_CONVENZ, PMB.EU_TOT_CONTRIB_DA_INTER,
    PMB.EU_SPESE_RICORRENTI, PMB.EU_SPESE_SMGP, PMB.EU_SPESE_TRASPARENZA,
    PMB.EU_SPESE_EC, PMB.EU_SPESE_BOLLO_EC, PMB.EU_SPESE_RICORRENTI_TOT,
    PMB.CD_MARCA_AUTO AS DS_MARCA,
    PMB.DS_MODELLO_AUTO,

    -- === ACCETTAZIONE_INPUT ===
    AI.CD_ESITO_SCORE_CLI             AS CD_ESITO_PREC,
    AI.FL_GIA_CLIENTE_CLI             AS FL_GIACLIENTE_CLI,
    AI.FL_GIA_CLIENTE_COOB            AS FL_GIACLIENTE_COBLGT,
    AI.CD_CERVED_RAE_CODICE_CLI       AS CD_RAE_CLI,
    AI.CD_CERVED_RAE_CODICE_COOB      AS CD_RAE_COBLGT,
    AI.CD_STATO_CIVILE_CLI            AS CD_STATO_CIV_CLI,
    AI.CD_STATO_CIVILE_COOB           AS CD_STATO_CIV_COBLGT,
    CAST(NULL AS VARCHAR(50))         AS DT_INIZIO_CLI,
    CAST(NULL AS VARCHAR(50))         AS DT_INIZIO_COBLGT,
    AI.DT_LIQUIDAZIONE_PRAT_PREC_CLI  AS DT_LIQUIDAZIONE_UP,
    AI.DT_LIQUIDAZIONE_PRAT_PREC_CLI  AS DT_UF_CLI,
    AI.DT_LIQUIDAZIONE_PRAT_PREC_COOB AS DT_UF_COBLGT,
    AI.EU_TOT_ENTRATE_MENSILI_CLI     AS EU_ENTRATE_MENS_TOT_CLI,
    AI.EU_TOT_ENTRATE_MENSILI_COOB    AS EU_ENTRATE_MENS_TOT_COBLGT,
    AI.EU_FIDO_CLI                    AS EU_FIDO_ACCETTAZIONE,
    CAST(NULL AS VARCHAR(50))         AS FL_INSOLVENZE_PREC_CRIF_CLI,
    CAST(NULL AS VARCHAR(50))         AS IN_OPERAZ_NON_PERF_CRIF_CLI,
    AI.FL_PROTESTI_CLI,
    AI.FL_PROTESTI_COOB               AS FL_PROTESTI_COBLGT,
    AI.FL_TRUFFATORE_CLI,
    AI.FL_TRUFFATORE_COOB             AS FL_TRUFFATORE_COBLGT,

    -- === SINTESI_ACCETTAZIONE_TEST ===
    SA.CD_STATO_PRAT, SA.CD_ATTRIBUTO_PRAT, SA.CD_BLOCCO_PRAT,
    SA.CD_ESITO_PRAT, SA.DT_ESITO_PRAT, SA.CD_USER_ESITO_FINALE,
    SA.CD_MOTIVO_OVERRIDE, SA.TP_OVERRIDE, SA.CD_ESITO_ELAB_CDE,
    SA.DS_ESITO_ELAB_CDE, SA.CD_ESITO_CHIAMATA, SA.CD_ESITO_CODICE,
    SA.DS_ESITO_MESSAGGIO, SA.CD_OPERAZIONE, SA.NM_RICHIESTA,
    SA.NM_ID_GUID_CF, SA.CD_ESITO_AMLCHECK, SA.DS_ESITO_AMLCHECK,
    SA.FL_PRT_CAR_ORA_SERV, SA.CD_ESITO_ANTIFRAUD, SA.DS_ESITO_ANTIFRAUD,
    SA.CD_ESITO_GIANOS, SA.CD_ESITO_FIRCOSOFT, SA.CD_VALUTAZ_PRT,
    SA.FL_APAG_CON_SOSPENS, SA.FL_SCIPAFI_OBBL, SA.CD_LIVELLO_FIRMA_PRT,
    SA.CD_AREA_RISCHIO, SA.FL_TIPO_VENDITA_CONGIUNTA, SA.EU_FIDO_MASSIMO,
    SA.CD_MOTIVO_ESITO, SA.CD_FASCIA_RBP, SA.CD_FASCIA_RBP_LIGHT,
    SA.CD_TAB_FINANZ_IRR, SA.EU_FIDO_SCORE, SA.CD_UTENTE, SA.TS_RISPOSTA,
    SA.CD_SCORE_MODULO_1_OBJCODE, SA.NM_SCORE_MODULO_1_ALIGNED,
    SA.CD_SCORE_MODULO_2_OBJCODE, SA.NM_SCORE_MODULO_2_ALIGNED,
    SA.CD_SCORE_MODULO_3_OBJCODE, SA.NM_SCORE_MODULO_3_ALIGNED,
    SA.CD_SCORE_MODULO_8_OBJCODE, SA.NM_SCORE_MODULO_8_ALIGNED,
    SA.CD_SCORE_MODULO_9_OBJCODE, SA.NM_SCORE_MODULO_9_ALIGNED,
    SA.CD_SEGMENTAZIONE_CODICE,
    SA.NM_EURISC_CBSCORE_CLI, SA.NM_EURISC_CBSCORE_COO,
    SA.NM_EURISC_NOHIT_PUNTEGGIO_CLI, SA.NM_EURISC_NOHIT_PUNTEGGIO_COO,
    SA.TP_EURISC_FASCIA_SCORE_CLI, SA.TP_EURISC_FASCIA_SCORE_COO,
    SA.NM_CTCPOS_SCORE_COMPLETO_CLI, SA.NM_CTCPOS_SCORE_COMPLETO_COO,
    SA.TP_CTCPOS_SCORE_COMPLETO_FASCIA_CLI, SA.TP_CTCPOS_SCORE_COMPLETO_FASCIA_COO,
    SA.FL_CTCPOS_HIT_NOHIT_CLI, SA.FL_CTCPOS_HIT_NOHIT_COO,
    SA.FL_EURISC_HIT_NOHIT_CLI, SA.FL_EURISC_HIT_NOHIT_COO,
    SA.NM_OB_SCORE_CLI, SA.FL_OB_ESENZIONE_REDDITO_CLI, SA.CD_OB_STATO_CLI,
    SA.CD_CTCPOS_STATO_CLI, SA.CD_CTCPOS_STATO_COO,
    SA.CD_EURISC_CRIF_STATO_CLI, SA.CD_EURISC_CRIF_STATO_COO,
    SA.PC_DBR_PERC_INDEBITAMENTO_PRATICA, SA.CD_INQUIRYCODE, SA.CD_PROCESSCODE,
    SA.CD_INDICATORE_PREQUALIFICA_CLI, SA.CD_INDICATORE_PREQUALIFICA_COO,
    SA.CD_NEWS_BANCO_CLI, SA.CD_NEWS_BANCO_COO,
    SA.CD_SEGMENTO_PERSONAL_CLI, SA.CD_SEGMENTO_PERSONAL_COO,
    SA.NM_REGOLE_KO, SA.DS_REGOLE_KO, SA.NM_REGOLE_NC, SA.DS_REGOLE_NC,
    SA.FL_ESITO_POLICY, SA.NM_LIVELLO_FIRMA_MAX_KO,
    SA.NM_REGOLE_OVERRRIDE, SA.DS_REGOLE_OVERRIDE,
    SA.DS_REGOLA_180_MESSAGGIO, SA.DS_REGOLA_180_DESCRIZIONE_RULES,
    SA.DS_REGOLA_179_MESSAGGIO, SA.DS_REGOLA_179_DESCRIZIONE_RULES,
    SA.DS_REGOLA_194_MESSAGGIO, SA.DS_REGOLA_194_DESCRIZIONE_RULES,
    SA.DS_REGOLA_43_DESCRIZIONE_RULES,
    SA.TP_SCIPAFI_CLI, SA.TP_SCIPAFI_COO,
    SA.CD_ESITO_PRESCREENING, SA.DS_ESITO_PRESCREENING,
    SA.NM_POLICY_PRESCREENING_KO_CLI,

    -- === SOCIODEMO_SCORE_TEST ===
    SDC.DT_OSSERVAZIONE AS TS_INSERIMENTO,
    SDC.CD_CONTROPARTE, SDC.TP_RAPPORTO, SDC.TP_CONTROPARTE,
    SDC.DT_CARIC_ULT_PP_REMOTO, SDC.DT_ULTIMA_MORA, SDC.DT_PRIMO_UTILIZZO,
    SDC.DT_INIZIO_RAPP, SDC.DT_APERTURA_PRIMA_PRATICA,
    SDC.CD_SESSO, SDC.CD_CITTADINANZA, SDC.NM_FAMILIARI,
    SDC.CD_STATO_CIVILE, SDC.DS_STATO_CIVILE, SDC.CD_CONIUGE_GARANTE,
    SDC.CD_FORMA_GIURIDICA, SDC.DT_NASCITA, SDC.CD_PROVINCIA_NASCITA,
    SDC.CD_QUALITA, SDC.CD_QUALITA_CONV, SDC.CD_TIPO_AZIENDA,
    SDC.DT_INIZIO_RAPP_BANCA, SDC.TP_PRATICA_INTERNET, SDC.NM_PRATICHE,
    SDC.TP_ATTIVITA, SDC.TP_AMBITO_LAVORATIVO, SDC.DS_DATORE_LAVORO,
    SDC.CD_PARTITA_IVA_DATORE_LAVORO, SDC.CD_SETT_ATTIVITA, SDC.CD_OCCUPAZIONE,
    SDC.DT_INIZIO_OCCUP, SDC.TP_CONTRATTO_LAVORO, SDC.NM_MESI_DURATA,
    SDC.NM_MENSILITA, SDC.FL_ACCREDITO_STIP, SDC.CD_ABITAZIONE,
    SDC.TP_ABITAZIONE, SDC.TP_LOCAZIONE, SDC.DT_INIZIO_INDIR,
    SDC.CD_PROVINCIA_RESIDENZA, SDC.CD_REGIONE_RESIDENZA, SDC.CD_PROVEN_COMMERC,
    SDC.EU_ALTRI_REDDITI, SDC.EU_REDDITO_ANNUO, SDC.NM_REDDITO_MENSILITA,
    SDC.EU_REDDITO_FAMIGLIARE, SDC.FL_DEPOSITO_BANCARIO, SDC.FL_CONTO_BANCARIO,
    SDC.FL_NUOVO_CLIENTE, SDC.FL_GIA_CLIENTE_BANCA,
    SDC.FL_FIRMA_DOPPIA AS FL_FIRMA_DOPPIA_SDC,
    SDC.EU_CUMULO_RISCHIO, SDC.EU_CUMULO_RISCHIO_CRIF, SDC.EU_COMMISSIONE,
    SDC.EU_DEPOSITO_BANCARIO,
    SDC.EU_FIDO,
    SDC.EU_FINANZIATO, SDC.EU_IMPIEGHI,
    SDC.EU_RATA_2 AS EU_RATA_2_SDC,
    SDC.EU_RATA_CRIF, SDC.EU_ALTR_USC,
    SDC.NM_MOROSITA, SDC.EU_MOROSITA, SDC.NM_PROTESTI,
    SDC.DT_ULTIMO_PROTESTO, SDC.EU_PROTESTI,
    SDC.TP_ORGANIZZAZIONE_CARTA, SDC.CD_ORGANIZZAZIONE_CARTA,
    SDC.CD_BLOCCO, SDC.DS_BLOCCO, SDC.NM_CESSIONE_BUSTA_PAGA,
    SDC.TP_PAGAMENTO, SDC.TP_RIPAGAMENTO,
    SDC.CD_TAB_FINANZ, SDC.CD_TIPO_TASSO,
    SDC.NM_RATE   AS NM_RATE_SDC,
    SDC.NM_RATE_2 AS NM_RATE_2_SDC,
    SDC.CD_CBSCORE_CRIF, SDC.CD_CBSCORE_CRIF_ULT_CO, SDC.CD_COMPORT_CRIF,
    SDC.NM_QUANTITA_SCORE_CRIF, SDC.TP_BANCA,
    SDC.CD_BENE, SDC.EU_BENE, SDC.TP_BENE, SDC.DS_BENE

FROM perimetro P

LEFT JOIN pratica_m_base PMB
    ON  PMB.CD_PRATICA      = P.CD_PRATICA
    AND PMB.TP_PROCEDURA    = P.TP_PROCEDURA
    AND PMB.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE

LEFT JOIN {{ ref('sociodemo_score_test') }} SDC
    ON  SDC.CD_PRATICA      = P.CD_PRATICA
    AND SDC.TP_PROCEDURA    = P.TP_PROCEDURA
    AND SDC.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE
    AND SDC.CD_CONTROPARTE  = P.CD_CLIENTE

LEFT JOIN {{ ref('sintesi_accettazione_test') }} SA
    ON  SA.CD_PRATICA   = P.CD_PRATICA
    AND SA.TP_PROCEDURA = P.TP_PROCEDURA

LEFT JOIN variazioni_anag VA
    ON VA.CD_PRATICA = P.CD_PRATICA

LEFT JOIN {{ ref('ana_struttura_interna') }} ASI
    ON ASI.CD_FILIALE = PMB.CD_FILIALE

LEFT JOIN {{ ref('gestione_truffe') }} GT
    ON  GT.CD_PRATICA   = P.CD_PRATICA
    AND GT.TP_PROCEDURA = P.TP_PROCEDURA

LEFT JOIN accettazione_input AI
    ON  AI.CD_PRATICA   = P.CD_PRATICA
    AND AI.TP_PROCEDURA = P.TP_PROCEDURA

LEFT JOIN rischio_consolidamenti_agg IRA
    ON  IRA.CD_PRATICA      = P.CD_PRATICA
    AND IRA.TP_PROCEDURA    = P.TP_PROCEDURA
    AND IRA.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE