-- =============================================================================
-- MODELLO   : dm_cmp_acc_ca_campioni_m
-- PROCESSO  : Campioni Accettazione CA | LAYER: L3 - DataMart
-- DM_ID     : DM_37
-- PK        : CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE
-- =============================================================================

{% set dt_rif = "LAST_DAY(DATEADD('month', -1, CURRENT_DATE))" %}

WITH

-- ===================== PERIMETRO & SINTESI ACCETTAZIONE (MESSI INSIEME) =====================
-- PERIMETRO: STATO >= 30, ESCLUSI ATTRIBUTI RT E RF
perimetro AS (
    SELECT
        P.CD_PRATICA, P.TP_PROCEDURA, P.DT_OSSERVAZIONE, P.CD_CLIENTE,
        P.DT_ESITO, P.DT_CHIUSURA_EFFETTIVA, P.CD_STATO, P.FL_PERDITA_CESSIONE,
        P.DT_DBT, P.DT_CESSIONE, P.DT_PASSAGGIO_PERDITA, P.TS_COMUNICAZIONE_ESITO_DEF,
        P.DT_CARICAMENTO, P.DT_PRIMA_SCADENZA, P.DT_PRIMA_SCADENZA_IST,
        P.CD_MACRO_PRODOTTO_1, P.CD_MACRO_PRODOTTO_2, P.CD_MACRO_PRODOTTO_3, P.CD_MACRO_PRODOTTO_4,
        P.CD_MERCATO_1, P.CD_MERCATO_2, P.CD_MERCATO_3, P.CD_MERCATO_4,
        -- Tutti i campi di SINTESI_ACCETTAZIONE portati direttamente dal perimetro
        SA.CD_STATO_PRAT, SA.CD_ATTRIBUTO_PRAT, SA.CD_BLOCCO_PRAT,
        SA.CD_ESITO_PRAT, SA.DT_ESITO_PRAT, SA.CD_USER_ESITO_FINALE,
        SA.CD_MOTIVO_OVERRIDE, SA.TP_OVERRIDE, SA.CD_ESITO_ELAB_CDE,
        SA.DS_ESITO_ELAB_CDE, SA.CD_ESITO_CHIAMATA, SA.CD_ESITO_CODICE,
        SA.DS_ESITO_MESSAGGIO, SA.CD_OPERAZIONE, SA.NM_RICHIESTA,
        SA.NM_ID_GUID_CF, SA.CD_ESITO_AMLCHECK, SA.DS_ESITO_AMLCHECK,
        SA.FL_PRT_CAR_ORA_SERV, SA.CD_ESITO_ANTIFRAUD, SA.DS_ESITO_ANTIFRAUD,
        SA.CD_ESITO_GIANOS, SA.CD_ESITO_FIRCOSOFT, SA.CD_VALUTAZ_PRT,
        SA.FL_APAG_CON_SOSPENS, SA.FL_SCIPAFI_OBBL, SA.CD_LIVELLO_FIRMA_PRT,
        SA.CD_AREA_RISCHIO, SA.FL_TIPO_VENDITA_CONGIUNTA, SA.EU_FIDO_MASSIMO,
        SA.CD_MOTIVO_ESITO, SA.CD_FASCIA_RBP, SA.CD_FASCIA_RBP_LIGHT,
        SA.CD_TAB_FINANZ_IRR, SA.EU_FIDO_SCORE, SA.CD_UTENTE, SA.TS_RISPOSTA,
        SA.CD_SCORE_MODULO_1_OBJCODE, SA.NM_SCORE_MODULO_1_ALIGNED,
        SA.CD_SCORE_MODULO_2_OBJCODE, SA.NM_SCORE_MODULO_2_ALIGNED,
        SA.CD_SCORE_MODULO_3_OBJCODE, SA.NM_SCORE_MODULO_3_ALIGNED,
        SA.CD_SCORE_MODULO_8_OBJCODE, SA.NM_SCORE_MODULO_8_ALIGNED,
        SA.CD_SCORE_MODULO_9_OBJCODE, SA.NM_SCORE_MODULO_9_ALIGNED,
        SA.CD_SEGMENTAZIONE_CODICE,
        SA.NM_EURISC_CBSCORE_CLI, SA.NM_EURISC_CBSCORE_COO,
        SA.NM_EURISC_NOHIT_PUNTEGGIO_CLI, SA.NM_EURISC_NOHIT_PUNTEGGIO_COO,
        SA.TP_EURISC_FASCIA_SCORE_CLI, SA.TP_EURISC_FASCIA_SCORE_COO,
        SA.NM_CTCPOS_SCORE_COMPLETO_CLI, SA.NM_CTCPOS_SCORE_COMPLETO_COO,
        SA.TP_CTCPOS_SCORE_COMPLETO_FASCIA_CLI, SA.TP_CTCPOS_SCORE_COMPLETO_FASCIA_COO,
        SA.FL_CTCPOS_HIT_NOHIT_CLI, SA.FL_CTCPOS_HIT_NOHIT_COO,
        SA.FL_EURISC_HIT_NOHIT_CLI, SA.FL_EURISC_HIT_NOHIT_COO,
        SA.NM_OB_SCORE_CLI, SA.FL_OB_ESENZIONE_REDDITO_CLI, SA.CD_OB_STATO_CLI,
        SA.CD_CTCPOS_STATO_CLI, SA.CD_CTCPOS_STATO_COO,
        SA.CD_EURISC_CRIF_STATO_CLI, SA.CD_EURISC_CRIF_STATO_COO,
        SA.PC_DBR_PERC_INDEBITAMENTO_PRATICA, SA.CD_INQUIRYCODE, SA.CD_PROCESSCODE,
        SA.CD_INDICATORE_PREQUALIFICA_CLI, SA.CD_INDICATORE_PREQUALIFICA_COO,
        SA.CD_NEWS_BANCO_CLI, SA.CD_NEWS_BANCO_COO,
        SA.CD_SEGMENTO_PERSONAL_CLI, SA.CD_SEGMENTO_PERSONAL_COO,
        SA.NM_REGOLE_KO, SA.DS_REGOLE_KO, SA.NM_REGOLE_NC, SA.DS_REGOLE_NC,
        SA.FL_ESITO_POLICY, SA.NM_LIVELLO_FIRMA_MAX_KO,
        SA.NM_REGOLE_OVERRRIDE, SA.DS_REGOLE_OVERRIDE,
        SA.DS_REGOLA_180_MESSAGGIO, SA.DS_REGOLA_180_DESCRIZIONE_RULES,
        SA.DS_REGOLA_179_MESSAGGIO, SA.DS_REGOLA_179_DESCRIZIONE_RULES,
        SA.DS_REGOLA_194_MESSAGGIO, SA.DS_REGOLA_194_DESCRIZIONE_RULES,
        SA.DS_REGOLA_43_DESCRIZIONE_RULES,
        SA.TP_SCIPAFI_CLI, SA.TP_SCIPAFI_COO,
        SA.CD_ESITO_PRESCREENING, SA.DS_ESITO_PRESCREENING,
        SA.NM_POLICY_PRESCREENING_KO_CLI
    FROM {{ ref('dm_cmp_acc_perimetro_ca') }} P
    LEFT JOIN AGOS_DEV_16000.L2_SCORE_BANCHE_DATI.SINTESI_ACCETTAZIONE SA
        ON  SA.CD_PRATICA   = P.CD_PRATICA
        AND SA.TP_PROCEDURA = P.TP_PROCEDURA
    WHERE CAST(P.CD_STATO AS INT) >= 30
      AND COALESCE(SA.CD_ATTRIBUTO_PRAT, '') NOT IN ('RT', 'RF')
    {% if is_incremental() %}
      AND P.DT_OSSERVAZIONE = {{ dt_rif }}
    {% endif %}
),

-- ===================== AGGREGAZIONE CLIENTE + PRATICA / CARTA CORRENTE =====================
-- La ON resta a livello cliente: serve per le aggregazioni cross-pratica.
-- Gli attributi della pratica corrente filtrano anche su DT_OSSERVAZIONE dentro il CASE.
cliente_agg AS (
    SELECT
        P.CD_PRATICA,
        P.TP_PROCEDURA,
        P.DT_OSSERVAZIONE,
        P.CD_CLIENTE,

        MIN(CL_HIST.DT_CARICAMENTO) AS DT_MIN_CARICAMENTO,
        MIN(CL_HIST.DT_DECORRENZA)  AS DT_MIN_DECORRENZA,
        MIN_BY(CL_HIST.CD_PRATICA, CL_HIST.DT_CARICAMENTO) AS CD_PRATICA_MIN_CARICAMENTO,
        MIN_BY(CL_HIST.CD_PRATICA, CL_HIST.DT_DECORRENZA)  AS CD_PRATICA_MIN_DECORRENZA,
        COUNT(DISTINCT CL_HIST.CD_PRATICA_CARTA) - 1 AS FL_CARTE_PREC,
        -- altre carte del cliente con fido valorizzato, esclusa la carta corrente
        COUNT(DISTINCT CASE WHEN CL_HIST.EU_FIDO IS NOT NULL
                             AND CL_HIST.CD_PRATICA <> P.CD_PRATICA
                            THEN CL_HIST.CD_PRATICA_CARTA END) AS FL_FIDI_COMPLESSIVI,

        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_ABI END) AS CD_ABI,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_AGENTE END) AS CD_AGENTE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_CANALE_ACQUISIZIONE END) AS CD_CANALE_ACQUISIZIONE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_CONVENZIONATO END) AS CD_CONVENZIONATO,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_COOBLIGATO END) AS CD_COOBLIGATO,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_FILIALE END) AS CD_FILIALE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_GIA_CLIENTE_MARKETING END) AS CD_GIA_CLIENTE_MARKETING,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_PUNTO_VENDITA END) AS CD_PUNTO_VENDITA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_RETE_VENDITA END) AS CD_RETE_VENDITA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_SUB_AGENTE END) AS CD_SUB_AGENTE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_TIPO_PRODOTTO END) AS CD_TIPO_PRODOTTO,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_VENDITORE END) AS CD_VENDITORE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DS_INSEGNA END) AS DS_INSEGNA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_APPROVAZIONE END) AS DT_APPROVAZIONE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_CHIUSURA_ANZIANITA END) AS DT_CHIUSURA_ANZIANITA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_CHIUSURA_EFFETTIVA END) AS DT_CHIUSURA_EFFETTIVA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_CHIUSURA_REGOLARE END) AS DT_CHIUSURA_REGOLARE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_DECORRENZA END) AS DT_DECORRENZA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_ESAMINATA END) AS DT_ESAMINATA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_ESTINZIONE_ANTICIPATA END) AS DT_ESTINZIONE_ANTICIPATA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_LIQUIDAZIONE END) AS DT_LIQUIDAZIONE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_MESSA_IN_MORA END) AS DT_MESSA_IN_MORA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_RESPINTA END) AS DT_RESPINTA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_RITIRATA END) AS DT_RITIRATA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_STORNATA END) AS DT_STORNATA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_ULTIMA_SCADENZA END) AS DT_ULTIMA_SCADENZA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_ULTIMA_SCADENZA_IST END) AS DT_ULTIMA_SCADENZA_IST,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_ULT_ACCODAMENTO END) AS DT_ULT_ACCODAMENTO,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.EU_RATA END) AS EU_RATA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.FL_DBT END) AS FL_DBT,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.FL_FIRMA_DOPPIA END) AS FL_FIRMA_DOPPIA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.FL_GIA_CLIENTE_CREDITI END) AS FL_GIA_CLIENTE_CREDITI,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.FL_GIA_CLIENTE_MARKETING END) AS FL_GIA_CLIENTE_MARKETING,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.FL_PERDITA_CESSIONE END) AS FL_PERDITA_CESSIONE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.FL_WEB_CANALE_ACQ END) AS FL_WEB_CANALE_ACQ,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.TP_PAGAMENTO END) AS TP_PAGAMENTO,

        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_EMETTITORE END) AS CD_EMETTITORE,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_PRODOTTO END) AS CD_PRODOTTO,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_STATO_CARTA END) AS CD_STATO_CARTA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.CD_TASSO_INDICIZZATO END) AS CD_TASSO_INDICIZZATO,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_ATTIVAZIONE_CARTA END) AS DT_ATTIVAZIONE_CARTA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_INVIO_CARTA END) AS DT_INVIO_CARTA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.DT_PRIMO_UTILIZZO END) AS DT_PRIMO_UTILIZZO,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.FL_PREPAGATA END) AS FL_PREPAGATA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.NM_TAEG END) AS NM_TAEG,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.NM_TAN END) AS NM_TAN,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.NM_TASSO_MORA END) AS NM_TASSO_MORA,
        MAX(CASE WHEN CL_HIST.CD_PRATICA = P.CD_PRATICA AND CL_HIST.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE THEN CL_HIST.TP_RIMBORSO END) AS TP_RIMBORSO

    FROM perimetro P
    LEFT JOIN (
        SELECT
            PM.CD_CLIENTE, PM.CD_PRATICA, PM.TP_PROCEDURA, PM.DT_OSSERVAZIONE, PM.DT_CARICAMENTO,
            PM.CD_ABI, PM.CD_AGENTE, PM.CD_CANALE_ACQUISIZIONE, PM.CD_CONVENZIONATO,
            PM.CD_COOBLIGATO, PM.CD_FILIALE, PM.CD_GIA_CLIENTE_MARKETING,
            PM.CD_PUNTO_VENDITA, PM.CD_RETE_VENDITA, PM.CD_SUB_AGENTE,
            PM.CD_TIPO_PRODOTTO, PM.CD_VENDITORE, PM.DS_INSEGNA,
            PM.DT_APPROVAZIONE, PM.DT_CHIUSURA_ANZIANITA, PM.DT_CHIUSURA_EFFETTIVA,
            PM.DT_CHIUSURA_REGOLARE, PM.DT_DECORRENZA, PM.DT_ESAMINATA,
            PM.DT_ESTINZIONE_ANTICIPATA, PM.DT_LIQUIDAZIONE, PM.DT_MESSA_IN_MORA,
            PM.DT_RESPINTA, PM.DT_RITIRATA, PM.DT_STORNATA,
            PM.DT_ULTIMA_SCADENZA, PM.DT_ULTIMA_SCADENZA_IST, PM.DT_ULT_ACCODAMENTO,
            PM.EU_RATA, PM.FL_DBT, PM.FL_FIRMA_DOPPIA, PM.FL_GIA_CLIENTE_CREDITI,
            PM.FL_GIA_CLIENTE_MARKETING, PM.FL_PERDITA_CESSIONE, PM.FL_WEB_CANALE_ACQ, PM.TP_PAGAMENTO,
            CM.CD_PRATICA AS CD_PRATICA_CARTA, CM.EU_FIDO, CM.CD_EMETTITORE, CM.CD_PRODOTTO,
            CM.CD_STATO AS CD_STATO_CARTA, CM.CD_TASSO_INDICIZZATO, CM.DT_ATTIVAZIONE_CARTA,
            CM.DT_INVIO_CARTA, CM.DT_PRIMO_UTILIZZO, CM.FL_PREPAGATA, CM.NM_TAEG,
            CM.NM_TAN, CM.NM_TASSO_MORA, CM.TP_RIMBORSO
        FROM {{ ref('pratica_m') }} PM
        LEFT JOIN {{ ref('carta_m') }} CM
            ON  CM.CD_PRATICA      = PM.CD_PRATICA
            AND CM.TP_PROCEDURA    = PM.TP_PROCEDURA
            AND CM.DT_OSSERVAZIONE = PM.DT_OSSERVAZIONE
    ) CL_HIST ON CL_HIST.CD_CLIENTE = P.CD_CLIENTE
    GROUP BY P.CD_PRATICA, P.TP_PROCEDURA, P.DT_OSSERVAZIONE, P.CD_CLIENTE
),

-- ===================== INDICE_RISCHIO_M + VARIAZIONI_ANAGRAFICHE =====================
-- Un'unica scansione per entrambe: le due tabelle sono lette una sola volta e
-- CLI/COOB sono separati per ruolo. Tutti gli aggregati sono MAX(CASE ...),
-- quindi il fan-out tra le due sorgenti non altera i valori.
rischio_anag_agg AS (
    SELECT
        CLA.CD_PRATICA, CLA.TP_PROCEDURA, CLA.DT_OSSERVAZIONE,
        MAX(CASE WHEN IR.CD_CLIENTE = CLA.CD_CLIENTE    AND IR.DT_OSSERVAZIONE = CLA.DT_OSSERVAZIONE THEN IR.NM_IMPAGATE END)          AS NM_IMPAGATE_CURRENT,
        MAX(CASE WHEN IR.CD_CLIENTE = CLA.CD_CLIENTE    AND IR.DT_OSSERVAZIONE = CLA.DT_OSSERVAZIONE THEN IR.NM_MAX_RATE_IMPAGATE END) AS MAX_INSOLVENZA_CLI_WORST,
        MAX(CASE WHEN IR.CD_CLIENTE = TRY_TO_NUMBER(CLA.CD_COOBLIGATO) AND IR.DT_OSSERVAZIONE = CLA.DT_OSSERVAZIONE THEN IR.NM_IMPAGATE END)          AS NM_INSOLVENZA_COOB_CURRENT,
        MAX(CASE WHEN IR.CD_CLIENTE = CLA.CD_CLIENTE THEN IR.NM_IMPAGATE END)                                                          AS MAX_INSOLVENZA_CLIENTE,
        {% for months in [3, 6, 9, 12, 18, 24, 120] %}
        MAX(CASE WHEN IR.CD_CLIENTE = CLA.CD_CLIENTE AND IR.DT_OSSERVAZIONE >= DATEADD('month', -{{ months }}, CLA.DT_OSSERVAZIONE) THEN IR.NM_IMPAGATE END)          AS MAX_INS_CLI_L{{ months }}M,
        MAX(CASE WHEN IR.CD_CLIENTE = CLA.CD_CLIENTE AND IR.DT_OSSERVAZIONE >= DATEADD('month', -{{ months }}, CLA.DT_OSSERVAZIONE) THEN IR.NM_MAX_RATE_IMPAGATE END) AS MAX_INS_CLI_L{{ months }}M_WORST,
        {% endfor %}
        MAX(CASE WHEN VA.CD_CONTROPARTE = CLA.CD_CLIENTE    THEN VA.TS_INIZIO_VALIDITA   END) AS TS_INIZIO_VALIDITA,
        MAX(CASE WHEN VA.CD_CONTROPARTE = CLA.CD_CLIENTE    THEN VA.CD_NAZIONE_NASCITA   END) AS CD_NAZIONE_NASCITA,
        MAX(CASE WHEN VA.CD_CONTROPARTE = CLA.CD_CLIENTE    THEN VA.DS_CITTA_NASCITA     END) AS DS_CITTA_NASCITA,
        MAX(CASE WHEN VA.CD_CONTROPARTE = CLA.CD_CLIENTE    THEN VA.DS_REGIONE_RESIDENZA END) AS DS_REGIONE_RESIDENZA,
        MAX(CASE WHEN VA.CD_CONTROPARTE = CLA.CD_CLIENTE    THEN VA.TP_CONTROPARTE       END) AS TP_CONTROPARTE,
        MAX(CASE WHEN VA.CD_CONTROPARTE = TRY_TO_NUMBER(CLA.CD_COOBLIGATO) THEN VA.CD_NAZIONE_NASCITA   END) AS CD_NAZIONE_COOB
    FROM cliente_agg CLA
    LEFT JOIN {{ ref('indice_rischio_m') }} IR
        ON  IR.CD_CLIENTE IN (CLA.CD_CLIENTE, TRY_TO_NUMBER(CLA.CD_COOBLIGATO))
        AND IR.DT_OSSERVAZIONE >= DATEADD('month', -120, CLA.DT_OSSERVAZIONE)
        AND IR.DT_OSSERVAZIONE <= CLA.DT_OSSERVAZIONE
    LEFT JOIN {{ ref('variazioni_anagrafiche') }} VA
        ON VA.CD_CONTROPARTE IN (CLA.CD_CLIENTE, TRY_TO_NUMBER(CLA.CD_COOBLIGATO))
    GROUP BY CLA.CD_PRATICA, CLA.TP_PROCEDURA, CLA.DT_OSSERVAZIONE
),

-- ===================== CARTE_UTILIZZI =====================
carte_utilizzi_agg AS (
    SELECT
        P.CD_PRATICA, P.TP_PROCEDURA, P.DT_OSSERVAZIONE,
        COUNT(CASE WHEN CU.TP_UTILIZZO = 'PRELIEVO' THEN 1 END) AS NM_ACQUISTI_PRELIEVO,
        COUNT(CASE WHEN CU.TP_UTILIZZO = 'UTILIZZO' THEN 1 END) AS NM_ACQUISTI_UTILIZZO,
        COUNT(CU.CD_PRATICA)                                    AS NM_UTILIZZI_TOT,
        SUM(CU.NM_UTILIZZI)                                     AS NM_UTIL_CARTE_PREC,
        MIN(CU.DT_UTILIZZO)                                     AS DT_MIN_ACQUISTO,
        {% for months in [3, 6, 9, 12, 18, 24] %}
        COUNT(CASE WHEN CU.DT_UTILIZZO >= DATEADD('month', -{{ months }}, P.DT_OSSERVAZIONE) THEN 1 END) AS NM_UTILIZZI_{{ months }}{{ "," if not loop.last }}
        {% endfor %}
    FROM perimetro P
    LEFT JOIN {{ ref('carte_utilizzi') }} CU
        ON  CU.CD_PRATICA   = P.CD_PRATICA
        AND CU.TP_PROCEDURA = P.TP_PROCEDURA
        AND CU.FL_STORNATO  = 'N'
        AND CU.FL_STORNO    = 'N'
    GROUP BY P.CD_PRATICA, P.TP_PROCEDURA, P.DT_OSSERVAZIONE
),

-- ===================== SEGNALAZIONI =====================
segnalazioni_agg AS (
    SELECT
        CD_CONTROPARTE,
        MAX(CASE WHEN TP_SEGNALAZIONE = 'TRUFFATO'   THEN 'S' ELSE 'N' END) AS FL_TRUFFATO,
        MAX(CASE WHEN TP_SEGNALAZIONE = 'TRUFFATORE' THEN 'S' ELSE 'N' END) AS FL_TRUFFATORE
    FROM {{ ref('segnalazioni') }}
    WHERE TP_SEGNALAZIONE IN ('TRUFFATO', 'TRUFFATORE')
    GROUP BY CD_CONTROPARTE
),

-- ===================== ACCETTAZIONE_INPUT =====================
accettazione_input AS (
    SELECT
        AI.CD_PRATICA,
        AI.TP_PROCEDURA,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.CD_ESITO_SCORE END)               AS CD_ESITO_SCORE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.CD_PRATICA_PREV_APP END)          AS CD_PRATICA_PREV_APP_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.FL_GIA_CLIENTE END)               AS FL_GIA_CLIENTE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.CD_CERVED_RAE_CODICE END)         AS CD_CERVED_RAE_CODICE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.CD_STATO_CIVILE END)              AS CD_STATO_CIVILE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.EU_TOT_ENTRATE_MENSILI END)       AS EU_TOT_ENTRATE_MENSILI_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.EU_FIDO END)                      AS EU_FIDO_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.FL_PROTESTI END)                  AS FL_PROTESTI_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.FL_TRUFFATORE END)                AS FL_TRUFFATORE_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI' THEN AI.FL_TIPO_VENDITA_CONGIUNTA END)    AS FL_TIPO_VENDITA_CONGIUNTA_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.CD_ESITO_SCORE END)              AS CD_ESITO_SCORE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.CD_PRATICA_PREV_APP END)         AS CD_PRATICA_PREV_APP_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.FL_GIA_CLIENTE END)              AS FL_GIA_CLIENTE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.CD_CERVED_RAE_CODICE END)        AS CD_CERVED_RAE_CODICE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.CD_STATO_CIVILE END)             AS CD_STATO_CIVILE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.EU_TOT_ENTRATE_MENSILI END)      AS EU_TOT_ENTRATE_MENSILI_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.EU_FIDO END)                     AS EU_FIDO_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.FL_PROTESTI END)                 AS FL_PROTESTI_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.FL_TRUFFATORE END)               AS FL_TRUFFATORE_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN AI.FL_TIPO_VENDITA_CONGIUNTA END)   AS FL_TIPO_VENDITA_CONGIUNTA_COOB,
        MAX(CASE WHEN AI.CD_RUOLO = 'CLI'  THEN APP.DT_LIQUIDAZIONE END)            AS DT_LIQUIDAZIONE_PRAT_PREC_CLI,
        MAX(CASE WHEN AI.CD_RUOLO = 'COOB' THEN APP.DT_LIQUIDAZIONE END)            AS DT_LIQUIDAZIONE_PRAT_PREC_COOB
    FROM {{ ref('accettazione_input') }} AI
    LEFT JOIN {{ ref('accettazione_input_prat_prec') }} APP
        ON APP.CD_PRATICA = AI.CD_PRATICA_PREV_APP
    WHERE AI.CD_RUOLO IN ('CLI', 'COOB')
    GROUP BY AI.CD_PRATICA, AI.TP_PROCEDURA
)

-- ===================== SELECT FINALE =====================
SELECT
    -- === PK + perimetro ===
    P.CD_PRATICA, P.TP_PROCEDURA, P.CD_CLIENTE, P.DT_OSSERVAZIONE,

    -- === Prodotto / mercato / Codice Settore ===
    P.CD_MACRO_PRODOTTO_1, P.CD_MACRO_PRODOTTO_2, P.CD_MACRO_PRODOTTO_3, P.CD_MACRO_PRODOTTO_4,
    P.CD_MERCATO_1, P.CD_MERCATO_2, P.CD_MERCATO_3, P.CD_MERCATO_4,
    CLA.CD_EMETTITORE, CLA.CD_PRODOTTO,
    CLA.CD_TIPO_PRODOTTO, CLA.CD_CANALE_ACQUISIZIONE, CLA.FL_WEB_CANALE_ACQ,
    SDC.EU_BENE AS PREZZO_BENE,

    -- === ANA_STRUTTURA_INTERNA ===
    ASI.CD_FILIALE, ASI.DS_FILIALE,
    ASI.CD_DISTRETTO_FILIALE, ASI.DS_DISTRETTO_FILIALE,
    ASI.CD_AREA_FILIALE, ASI.DS_AREA_FILIALE,

    -- === VARIAZIONI_ANAGRAFICHE ===
    IRA.DS_REGIONE_RESIDENZA AS DS_REGIONE,

    -- === Rete vendita ===
    CLA.CD_RETE_VENDITA, CLA.CD_AGENTE, CLA.CD_SUB_AGENTE, CLA.CD_CONVENZIONATO,
    CLA.CD_PUNTO_VENDITA, CLA.DS_INSEGNA, CLA.CD_VENDITORE,

    -- === CARTA_M - tassi ===
    CLA.CD_TASSO_INDICIZZATO, CLA.NM_TAN, CLA.NM_TAEG, CLA.NM_TASSO_MORA,
    CAST(NULL AS VARCHAR(50)) AS PC_TASSO_CASH,
    CAST(NULL AS VARCHAR(50)) AS PC_TASSO_RTAIL,
    CAST(NULL AS VARCHAR(50)) AS PC_BASE_ASSIC,

    -- === Date processo ===
    P.DT_ESITO_PRAT          AS DT_CARICAMENTO_SCORE,
    P.DT_PRIMA_SCADENZA      AS DT_SCADENZA_PRIMA_RATA,
    P.DT_CARICAMENTO,
    CLA.DT_ESAMINATA,
    P.DT_ESITO,
    CLA.DT_APPROVAZIONE, CLA.DT_RESPINTA, CLA.DT_RITIRATA, CLA.DT_LIQUIDAZIONE,
    CLA.DT_DECORRENZA, CLA.DT_STORNATA, CLA.DT_CHIUSURA_REGOLARE, CLA.DT_ESTINZIONE_ANTICIPATA,
    P.DT_PASSAGGIO_PERDITA, P.DT_CESSIONE,
    CLA.DT_CHIUSURA_EFFETTIVA, CLA.DT_MESSA_IN_MORA,
    P.DT_DBT, P.TS_COMUNICAZIONE_ESITO_DEF,
    CLA.DT_CHIUSURA_ANZIANITA, CLA.DT_ULT_ACCODAMENTO,
    P.DT_PRIMA_SCADENZA,
    P.DT_PRIMA_SCADENZA_IST,
    CLA.DT_ULTIMA_SCADENZA, CLA.DT_ULTIMA_SCADENZA_IST,

    -- === CARTA_M / VARIAZIONI - attributi ===
    CLA.DT_ATTIVAZIONE_CARTA AS DT_ATTIVAZIONE,
    IRA.TS_INIZIO_VALIDITA  AS DT_INIZIO_CLIENTE,
    IRA.CD_NAZIONE_NASCITA  AS CD_NAZIONE_CLI,
    IRA.CD_NAZIONE_COOB     AS CD_NAZIONE_COOB,
    IRA.DS_CITTA_NASCITA    AS CD_PAESE,

    -- === PRATICA_M / CLIENTE ===
    CLA.CD_COOBLIGATO AS CD_COOBBLIGATO,
    CLA.CD_PRATICA_MIN_CARICAMENTO,
    CLA.CD_PRATICA_MIN_DECORRENZA,
    CUA.DT_MIN_ACQUISTO,
    CLA.DT_MIN_CARICAMENTO,
    CLA.DT_MIN_DECORRENZA,

    -- === Stato / flag ===
    P.CD_STATO,
    AI.CD_PRATICA_PREV_APP_CLI AS CD_PRATICA_CROSS_SELLING,
    CLA.CD_GIA_CLIENTE_MARKETING, CLA.FL_GIA_CLIENTE_MARKETING, CLA.FL_GIA_CLIENTE_CREDITI,
    COALESCE(SEG.FL_TRUFFATO, 'N')   AS FL_TRUFFATO,
    COALESCE(SEG.FL_TRUFFATORE, 'N') AS FL_TRUFFATORE,
    CLA.FL_FIDI_COMPLESSIVI,
    CLA.FL_CARTE_PREC,
    CASE WHEN CLA.CD_COOBLIGATO IS NOT NULL THEN 'S' ELSE 'N' END AS FL_COOBBLIGATO,
    AI.FL_TIPO_VENDITA_CONGIUNTA_CLI AS FL_CROSS_SELLING,
    P.FL_PERDITA_CESSIONE, CLA.FL_DBT,

    -- === CARTE_UTILIZZI ===
    CUA.NM_ACQUISTI_PRELIEVO, CUA.NM_ACQUISTI_UTILIZZO, CUA.NM_UTIL_CARTE_PREC,
    CUA.NM_UTILIZZI_12, CUA.NM_UTILIZZI_18, CUA.NM_UTILIZZI_24,
    CUA.NM_UTILIZZI_3, CUA.NM_UTILIZZI_6, CUA.NM_UTILIZZI_9, CUA.NM_UTILIZZI_TOT,

    -- === NM_IMPAG_CURRENT ===
    CASE
        WHEN P.DT_OSSERVAZIONE > COALESCE(P.DT_PASSAGGIO_PERDITA, P.DT_CESSIONE) THEN 'C'
        WHEN P.DT_DBT IS NOT NULL AND COALESCE(P.DT_PASSAGGIO_PERDITA, P.DT_CESSIONE) IS NULL THEN '5000'
        ELSE CAST(IRA.NM_IMPAGATE_CURRENT AS VARCHAR)
    END AS NM_IMPAG_CURRENT,

    -- === INDICE_RISCHIO_M ===
    IRA.NM_IMPAGATE_CURRENT AS MAX_INSOLVENZA_CLI_CURRENT,
    IRA.NM_IMPAGATE_CURRENT AS NM_INSOLVENZA_CLIENTE_CURRENT,
    IRA.NM_INSOLVENZA_COOB_CURRENT,
    IRA.MAX_INS_CLI_L120M, IRA.MAX_INS_CLI_L120M_WORST,
    IRA.MAX_INS_CLI_L12M,  IRA.MAX_INS_CLI_L12M_WORST,
    IRA.MAX_INS_CLI_L18M,  IRA.MAX_INS_CLI_L18M_WORST,
    IRA.MAX_INS_CLI_L24M,  IRA.MAX_INS_CLI_L24M_WORST,
    IRA.MAX_INS_CLI_L3M,   IRA.MAX_INS_CLI_L3M_WORST,
    IRA.MAX_INS_CLI_L6M,   IRA.MAX_INS_CLI_L6M_WORST,
    IRA.MAX_INS_CLI_L9M,   IRA.MAX_INS_CLI_L9M_WORST,
    IRA.MAX_INSOLVENZA_CLI_WORST, IRA.MAX_INSOLVENZA_CLIENTE,

    DATEDIFF('month', SDC.DT_INIZIO_RAPP, P.DT_OSSERVAZIONE) AS NM_MESI_CLIENTE,

    -- === INCASSI_SDD ===
    ISD.EU_IMPORTO,

    -- === CARTE_BLOCCHI ===
    CB.TP_BLOCCO,

    -- === Alias specifici DM ===
    CLA.DT_APPROVAZIONE   AS DT_APERTURA,
    CLA.DT_INVIO_CARTA    AS DT_CONSEGNA_CARTA,
    P.DT_PRIMA_SCADENZA   AS DT_PRIMA_SCADENZA_CARTA,
    CLA.FL_FIRMA_DOPPIA,
    CLA.FL_PREPAGATA,
    IRA.TP_CONTROPARTE,
    CLA.TP_PAGAMENTO,
    CLA.TP_RIMBORSO,
    CASE WHEN CLA.FL_PREPAGATA = 'S' THEN CLA.CD_STATO_CARTA END AS CD_STATO_PREPA,
    CLA.DT_CHIUSURA_EFFETTIVA AS DT_CHIUSURA,
    CLA.DT_PRIMO_UTILIZZO     AS DT_PRIMO_MOV_REGISTR,
    CLA.EU_RATA,
    CLA.CD_ABI                 AS CD_ABI_CLIENTE,
    CASE WHEN CLA.DT_PRIMO_UTILIZZO    IS NULL THEN 'S' ELSE 'N' END AS FL_ATTIVE_NO_UTILIZ,
    CASE WHEN CLA.DT_ATTIVAZIONE_CARTA IS NULL THEN 'S' ELSE 'N' END AS FL_CARTE_NO_ATTIVE,

    -- === ACCETTAZIONE_INPUT ===
    AI.CD_ESITO_SCORE_CLI             AS CD_ESITO_PREC,
    AI.FL_GIA_CLIENTE_CLI             AS FL_GIACLIENTE_CLI,
    AI.FL_GIA_CLIENTE_COOB            AS FL_GIACLIENTE_COBLGT,
    AI.CD_CERVED_RAE_CODICE_CLI       AS CD_RAE_CLI,
    AI.CD_CERVED_RAE_CODICE_COOB      AS CD_RAE_COBLGT,
    AI.CD_STATO_CIVILE_CLI            AS CD_STATO_CIV_CLI,
    AI.CD_STATO_CIVILE_COOB           AS CD_STATO_CIV_COBLGT,
    CAST(NULL AS VARCHAR(50))         AS DT_INIZIO_CLI,
    CAST(NULL AS VARCHAR(50))         AS DT_INIZIO_COBLGT,
    AI.DT_LIQUIDAZIONE_PRAT_PREC_CLI  AS DT_LIQUIDAZIONE_UP,
    AI.DT_LIQUIDAZIONE_PRAT_PREC_CLI  AS DT_UF_CLI,
    AI.DT_LIQUIDAZIONE_PRAT_PREC_COOB AS DT_UF_COBLGT,
    AI.EU_TOT_ENTRATE_MENSILI_CLI     AS EU_ENTRATE_MENS_TOT_CLI,
    AI.EU_TOT_ENTRATE_MENSILI_COOB    AS EU_ENTRATE_MENS_TOT_COBLGT,
    AI.EU_FIDO_CLI                    AS EU_FIDO,
    CAST(NULL AS VARCHAR(50))         AS FL_INSOLVENZE_PREC_CRIF_CLI,
    CAST(NULL AS VARCHAR(50))         AS FL_OPERAZ_NON_PERF_CRIF_CLI,
    AI.FL_PROTESTI_CLI,
    AI.FL_PROTESTI_COOB               AS FL_PROTESTI_COBLGT,
    AI.FL_TRUFFATORE_CLI,
    AI.FL_TRUFFATORE_COOB             AS FL_TRUFFATORE_COBLGT,

    -- === SINTESI_ACCETTAZIONE (Presi direttamente da P) ===
    P.CD_STATO_PRAT, P.CD_ATTRIBUTO_PRAT, P.CD_BLOCCO_PRAT,
    P.CD_ESITO_PRAT, P.DT_ESITO_PRAT, P.CD_USER_ESITO_FINALE,
    P.CD_MOTIVO_OVERRIDE, P.TP_OVERRIDE, P.CD_ESITO_ELAB_CDE,
    P.DS_ESITO_ELAB_CDE, P.CD_ESITO_CHIAMATA, P.CD_ESITO_CODICE,
    P.DS_ESITO_MESSAGGIO, P.CD_OPERAZIONE, P.NM_RICHIESTA,
    P.NM_ID_GUID_CF, P.CD_ESITO_AMLCHECK, P.DS_ESITO_AMLCHECK,
    P.FL_PRT_CAR_ORA_SERV, P.CD_ESITO_ANTIFRAUD, P.DS_ESITO_ANTIFRAUD,
    P.CD_ESITO_GIANOS, P.CD_ESITO_FIRCOSOFT, P.CD_VALUTAZ_PRT,
    P.FL_APAG_CON_SOSPENS, P.FL_SCIPAFI_OBBL, P.CD_LIVELLO_FIRMA_PRT,
    P.CD_AREA_RISCHIO, P.FL_TIPO_VENDITA_CONGIUNTA, P.EU_FIDO_MASSIMO,
    P.CD_MOTIVO_ESITO, P.CD_FASCIA_RBP, P.CD_FASCIA_RBP_LIGHT,
    P.CD_TAB_FINANZ_IRR, P.EU_FIDO_SCORE, P.CD_UTENTE, P.TS_RISPOSTA,
    P.CD_SCORE_MODULO_1_OBJCODE, P.NM_SCORE_MODULO_1_ALIGNED,
    P.CD_SCORE_MODULO_2_OBJCODE, P.NM_SCORE_MODULO_2_ALIGNED,
    P.CD_SCORE_MODULO_3_OBJCODE, P.NM_SCORE_MODULO_3_ALIGNED,
    P.CD_SCORE_MODULO_8_OBJCODE, P.NM_SCORE_MODULO_8_ALIGNED,
    P.CD_SCORE_MODULO_9_OBJCODE, P.NM_SCORE_MODULO_9_ALIGNED,
    P.CD_SEGMENTAZIONE_CODICE,
    P.NM_EURISC_CBSCORE_CLI, P.NM_EURISC_CBSCORE_COO,
    P.NM_EURISC_NOHIT_PUNTEGGIO_CLI, P.NM_EURISC_NOHIT_PUNTEGGIO_COO,
    P.TP_EURISC_FASCIA_SCORE_CLI, P.TP_EURISC_FASCIA_SCORE_COO,
    P.NM_CTCPOS_SCORE_COMPLETO_CLI, P.NM_CTCPOS_SCORE_COMPLETO_COO,
    P.TP_CTCPOS_SCORE_COMPLETO_FASCIA_CLI, P.TP_CTCPOS_SCORE_COMPLETO_FASCIA_COO,
    P.FL_CTCPOS_HIT_NOHIT_CLI, P.FL_CTCPOS_HIT_NOHIT_COO,
    P.FL_EURISC_HIT_NOHIT_CLI, P.FL_EURISC_HIT_NOHIT_COO,
    P.NM_OB_SCORE_CLI, P.FL_OB_ESENZIONE_REDDITO_CLI, P.CD_OB_STATO_CLI,
    P.CD_CTCPOS_STATO_CLI, P.CD_CTCPOS_STATO_COO,
    P.CD_EURISC_CRIF_STATO_CLI, P.CD_EURISC_CRIF_STATO_COO,
    P.PC_DBR_PERC_INDEBITAMENTO_PRATICA, P.CD_INQUIRYCODE, P.CD_PROCESSCODE,
    P.CD_INDICATORE_PREQUALIFICA_CLI, P.CD_INDICATORE_PREQUALIFICA_COO,
    P.CD_NEWS_BANCO_CLI, P.CD_NEWS_BANCO_COO,
    P.CD_SEGMENTO_PERSONAL_CLI, P.CD_SEGMENTO_PERSONAL_COO,
    P.NM_REGOLE_KO, P.DS_REGOLE_KO, P.NM_REGOLE_NC, P.DS_REGOLE_NC,
    P.FL_ESITO_POLICY, P.NM_LIVELLO_FIRMA_MAX_KO,
    P.NM_REGOLE_OVERRRIDE, P.DS_REGOLE_OVERRIDE,
    P.DS_REGOLA_180_MESSAGGIO, P.DS_REGOLA_180_DESCRIZIONE_RULES,
    P.DS_REGOLA_179_MESSAGGIO, P.DS_REGOLA_179_DESCRIZIONE_RULES,
    P.DS_REGOLA_194_MESSAGGIO, P.DS_REGOLA_194_DESCRIZIONE_RULES,
    P.DS_REGOLA_43_DESCRIZIONE_RULES,
    P.TP_SCIPAFI_CLI, P.TP_SCIPAFI_COO,
    P.CD_ESITO_PRESCREENING, P.DS_ESITO_PRESCREENING,
    P.NM_POLICY_PRESCREENING_KO_CLI,

    -- === SOCIODEMO_SCORE_TEST ===
    SDC.DT_OSSERVAZIONE AS TS_INSERIMENTO,
    SDC.CD_CONTROPARTE, SDC.TP_RAPPORTO,
    SDC.DT_CARIC_ULT_PP_REMOTO, SDC.DT_ULTIMA_MORA, SDC.DT_PRIMO_UTILIZZO,
    SDC.DT_INIZIO_RAPP, SDC.DT_APERTURA_PRIMA_PRATICA,
    SDC.CD_SESSO, SDC.CD_CITTADINANZA, SDC.NM_FAMILIARI,
    SDC.CD_STATO_CIVILE, SDC.DS_STATO_CIVILE, SDC.CD_CONIUGE_GARANTE,
    SDC.CD_FORMA_GIURIDICA, SDC.DT_NASCITA, SDC.CD_PROVINCIA_NASCITA,
    SDC.CD_QUALITA, SDC.CD_QUALITA_CONV, SDC.CD_TIPO_AZIENDA,
    SDC.DT_INIZIO_RAPP_BANCA, SDC.TP_PRATICA_INTERNET, SDC.NM_PRATICHE,
    SDC.TP_ATTIVITA, SDC.TP_AMBITO_LAVORATIVO, SDC.DS_DATORE_LAVORO,
    SDC.CD_PARTITA_IVA_DATORE_LAVORO, SDC.CD_SETT_ATTIVITA, SDC.CD_OCCUPAZIONE,
    SDC.DT_INIZIO_OCCUP, SDC.TP_CONTRATTO_LAVORO, SDC.NM_MESI_DURATA,
    SDC.NM_MENSILITA, SDC.FL_ACCREDITO_STIP, SDC.CD_ABITAZIONE,
    SDC.TP_ABITAZIONE, SDC.TP_LOCAZIONE, SDC.DT_INIZIO_INDIR,
    SDC.CD_PROVINCIA_RESIDENZA, SDC.CD_REGIONE_RESIDENZA, SDC.CD_PROVEN_COMMERC,
    SDC.EU_ALTRI_REDDITI, SDC.EU_REDDITO_ANNUO, SDC.NM_REDDITO_MENSILITA,
    SDC.EU_REDDITO_FAMIGLIARE, SDC.FL_DEPOSITO_BANCARIO, SDC.FL_CONTO_BANCARIO,
    SDC.FL_NUOVO_CLIENTE, SDC.FL_GIA_CLIENTE_BANCA,
    SDC.EU_CUMULO_RISCHIO, SDC.EU_CUMULO_RISCHIO_CRIF, SDC.EU_COMMISSIONE,
    SDC.EU_DEPOSITO_BANCARIO, SDC.EU_FINANZIATO, SDC.EU_IMPIEGHI,
    SDC.EU_RATA_2, SDC.EU_RATA_CRIF, SDC.EU_ALTR_USC,
    SDC.NM_MOROSITA, SDC.EU_MOROSITA, SDC.NM_PROTESTI,
    SDC.DT_ULTIMO_PROTESTO, SDC.EU_PROTESTI,
    SDC.TP_ORGANIZZAZIONE_CARTA, SDC.CD_ORGANIZZAZIONE_CARTA,
    SDC.CD_BLOCCO, SDC.DS_BLOCCO, SDC.NM_CESSIONE_BUSTA_PAGA,
    SDC.TP_RIPAGAMENTO, SDC.CD_TAB_FINANZ, SDC.CD_TIPO_TASSO,
    SDC.NM_RATE, SDC.NM_RATE_2,
    SDC.CD_CBSCORE_CRIF, SDC.CD_CBSCORE_CRIF_ULT_CO, SDC.CD_COMPORT_CRIF,
    SDC.NM_QUANTITA_SCORE_CRIF, SDC.TP_BANCA,
    SDC.CD_BENE, SDC.EU_BENE, SDC.TP_BENE, SDC.DS_BENE,

    -- === Altre carte ===
    P.DT_ESITO AS TS_ESITO

FROM perimetro P

LEFT JOIN cliente_agg CLA
    ON  CLA.CD_PRATICA      = P.CD_PRATICA
    AND CLA.TP_PROCEDURA    = P.TP_PROCEDURA
    AND CLA.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE

LEFT JOIN {{ ref('incassi_sdd') }} ISD
    ON  ISD.CD_PRATICA   = P.CD_PRATICA
    AND ISD.TP_PROCEDURA = P.TP_PROCEDURA
    AND ISD.DT_SCADENZA  = P.DT_PRIMA_SCADENZA

LEFT JOIN {{ ref('carte_blocchi') }} CB
    ON  CB.CD_PRATICA   = P.CD_PRATICA
    AND CB.TP_PROCEDURA = P.TP_PROCEDURA

LEFT JOIN carte_utilizzi_agg CUA
    ON  CUA.CD_PRATICA      = P.CD_PRATICA
    AND CUA.TP_PROCEDURA    = P.TP_PROCEDURA
    AND CUA.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE

LEFT JOIN rischio_anag_agg IRA
    ON  IRA.CD_PRATICA      = P.CD_PRATICA
    AND IRA.TP_PROCEDURA    = P.TP_PROCEDURA
    AND IRA.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE

LEFT JOIN AGOS_DEV_16000.L2_SCORING.SOCIODEMO_SCORE_TEST SDC
    ON  SDC.CD_PRATICA      = P.CD_PRATICA
    AND SDC.TP_PROCEDURA    = P.TP_PROCEDURA
    AND SDC.DT_OSSERVAZIONE = P.DT_OSSERVAZIONE
    AND SDC.CD_CONTROPARTE  = P.CD_CLIENTE

LEFT JOIN {{ ref('ana_struttura_interna') }} ASI
    ON ASI.CD_FILIALE = CLA.CD_FILIALE

LEFT JOIN segnalazioni_agg SEG
    ON SEG.CD_CONTROPARTE = P.CD_CLIENTE

LEFT JOIN accettazione_input AI
    ON  AI.CD_PRATICA   = P.CD_PRATICA
    AND AI.TP_PROCEDURA = P.TP_PROCEDURA