-- FREQUENZA : Mensile — incremental append + delete_last_month

WITH
perimetro AS (
    SELECT 
        CD_CONTROPARTE, TS_INIZIO_VALIDITA, TS_FINE_VALIDITA
    FROM {{ ref('variazioni_anagrafiche') }}
    WHERE FL_CLIENTE = 'S'
      AND TS_FINE_VALIDITA = TO_TIMESTAMP_NTZ('9999-12-31 00:00:00.000')
    {% if is_incremental() %}
      -- Clienti con validità nel mese precedente (solo in modalità incrementale).
      AND LAST_DAY(DT_INIZIO_VALIDITA::DATE) = {{ last_day_past_month() }}
    {% endif %}
),

segnalazioni_raw AS (
    SELECT
        CD_CONTROPARTE, TP_SEGNALAZIONE, PR_SEGNALAZIONE, DS_SEGNALAZIONE, CD_RISCHIO, CD_CLASSE, DT_INIZIO, DT_FINE,
        MAX(DT_FINE) OVER (PARTITION BY CD_CONTROPARTE ORDER BY DT_INIZIO, DT_FINE, PR_SEGNALAZIONE
            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
        ) AS MAX_DT_FINE_PRECEDENTE
    FROM {{ ref('segnalazioni_anagrafiche') }}
),

cicli_step2 AS (
    SELECT
        CD_CONTROPARTE, TP_SEGNALAZIONE, PR_SEGNALAZIONE, DS_SEGNALAZIONE, CD_RISCHIO, CD_CLASSE, DT_INIZIO, DT_FINE,
        MAX_DT_FINE_PRECEDENTE,
        SUM(CASE WHEN MAX_DT_FINE_PRECEDENTE IS NULL OR DT_INIZIO > MAX_DT_FINE_PRECEDENTE THEN 1 ELSE 0 END
        ) OVER (
            PARTITION BY CD_CONTROPARTE ORDER BY DT_INIZIO, DT_FINE, PR_SEGNALAZIONE
            ROWS UNBOUNDED PRECEDING
        ) AS CICLO_DEFAULT
    FROM segnalazioni_raw
),

cicli_agg AS (
    SELECT
        CD_CONTROPARTE, CICLO_DEFAULT,
        MIN(DT_INIZIO) AS DT_INGRESSO_DEFAULT,
        MAX(DT_FINE)   AS DT_USCITA_DEFAULT
    FROM cicli_step2
    GROUP BY CD_CONTROPARTE, CICLO_DEFAULT
),

ciclo_attivo AS (
    SELECT
        CD_CONTROPARTE, DT_INGRESSO_DEFAULT, DT_USCITA_DEFAULT
    FROM cicli_agg
    WHERE {{ last_day_past_month() }} BETWEEN DT_INGRESSO_DEFAULT AND DT_USCITA_DEFAULT
),

cicli_completi AS (
    SELECT
        S.CD_CONTROPARTE,
        S.TP_SEGNALAZIONE,
        S.PR_SEGNALAZIONE,
        S.DT_INIZIO,
        S.DT_FINE,
        S.CD_CLASSE,
        C.CICLO_DEFAULT,
        C.DT_INGRESSO_DEFAULT,
        C.DT_USCITA_DEFAULT
    FROM cicli_step2 S
    JOIN cicli_agg C
        ON C.CD_CONTROPARTE = S.CD_CONTROPARTE
        AND C.CICLO_DEFAULT = S.CICLO_DEFAULT
),

segnalazioni_pivot AS (
    SELECT
        CD_CONTROPARTE,
        CASE WHEN MAX(CASE
            WHEN TP_SEGNALAZIONE = 'IPE' AND (DT_FINE IS NULL OR DT_FINE >= CURRENT_DATE)
            THEN 1 ELSE 0
        END) = 1 THEN 'S' ELSE 'N' END  AS FL_IPE,
        CASE WHEN MAX(CASE
            WHEN TP_SEGNALAZIONE = 'UTP' AND (DT_FINE IS NULL OR DT_FINE >= CURRENT_DATE)
            THEN 1 ELSE 0
        END) = 1 THEN 'S' ELSE 'N' END AS FL_UTP,
        CASE WHEN MAX(CASE
            WHEN TP_SEGNALAZIONE = 'SOF' AND (DT_FINE IS NULL OR DT_FINE >= CURRENT_DATE)
            THEN 1 ELSE 0
        END) = 1 THEN 'S' ELSE 'N' END AS FL_SOF,
        CASE WHEN MAX(CASE
            WHEN TP_SEGNALAZIONE = 'BOM' AND (DT_FINE IS NULL OR DT_FINE >= CURRENT_DATE)
            THEN 1 ELSE 0
        END) = 1 THEN 'S' ELSE 'N' END AS FL_BONIS_FORZATO,
        CASE WHEN MAX(CASE
            WHEN TP_SEGNALAZIONE = 'SOV' AND (DT_FINE IS NULL OR DT_FINE >= CURRENT_DATE)
            THEN 1 ELSE 0
        END) = 1 THEN 'S' ELSE 'N' END AS FL_SOVRAINDEB
    FROM segnalazioni_raw
    GROUP BY CD_CONTROPARTE
),

segnalazioni_default_cl AS (
    SELECT
        CD_CONTROPARTE, DS_SEGNALAZIONE, CD_RISCHIO, DT_INIZIO, DT_FINE
    FROM segnalazioni_raw
    WHERE CD_CLASSE IN ('SO', 'O2', 'IN')
),

primo_ingresso AS (
    SELECT
        CD_CONTROPARTE, DS_SEGNALAZIONE,
        ROW_NUMBER() OVER (PARTITION BY CD_CONTROPARTE ORDER BY DT_INIZIO ASC, CD_RISCHIO DESC) AS RN
    FROM segnalazioni_default_cl
),

ultimo_chiuso AS (
    SELECT
        CD_CONTROPARTE, DS_SEGNALAZIONE, DT_FINE,
        ROW_NUMBER() OVER (PARTITION BY CD_CONTROPARTE ORDER BY DT_FINE DESC, CD_RISCHIO DESC) AS RN
    FROM segnalazioni_default_cl
    WHERE DT_FINE IS NOT NULL
),

ultimo_attivo AS (
    SELECT
        CD_CONTROPARTE, DS_SEGNALAZIONE,
        ROW_NUMBER() OVER (PARTITION BY CD_CONTROPARTE ORDER BY DT_INIZIO DESC, CD_RISCHIO DESC) AS RN
    FROM segnalazioni_default_cl
    WHERE DT_INIZIO <= {{ last_day_past_month() }}
      AND (DT_FINE IS NULL OR DT_FINE >= {{ last_day_past_month() }})
),

pratica_raw AS (
    SELECT
        CD_CLIENTE, CD_PRATICA, TP_PROCEDURA, FL_DBT
    FROM {{ ref('pratica_m') }}
    WHERE DT_OSSERVAZIONE = {{ last_day_past_month() }}
),

pratica_cliente_agg AS (
    SELECT
        P.CD_CONTROPARTE,
        CASE
            WHEN MAX(CASE WHEN PM.FL_DBT = 'S' THEN 1 ELSE 0 END) = 1 THEN 'S' ELSE 'N'
        END AS FL_DBT_CLI,
        MAX(CASE WHEN GT.FL_SUBITA = 'S' THEN 'S' ELSE 'N' END) AS FL_TRUFFA
    FROM perimetro P
    LEFT JOIN pratica_raw PM
        ON PM.CD_CLIENTE = P.CD_CONTROPARTE
    LEFT JOIN {{ ref('gestione_truffe') }} GT
        ON GT.CD_PRATICA = PM.CD_PRATICA
        AND GT.TP_PROCEDURA = PM.TP_PROCEDURA
        AND GT.FL_TRUFFA_ATTIVA = 'S'
    GROUP BY P.CD_CONTROPARTE
),

stato_creditizio_agg AS (
    SELECT
        P.CD_CONTROPARTE,
        CASE
            WHEN MAX(CASE WHEN SC.FL_DFLT_EBA = 'S' THEN 1 ELSE 0 END) = 1 THEN 'S' ELSE 'N'
        END AS FL_DFLT_EBA_CLI
    FROM perimetro  P
    LEFT JOIN {{ ref('stato_creditizio_m') }} SC
        ON SC.CD_CONTROPARTE = P.CD_CONTROPARTE
        AND SC.DT_OSSERVAZIONE = {{ last_day_past_month() }}
    GROUP BY P.CD_CONTROPARTE
),

performing_raw AS (
    SELECT
        CD_CLIENTE, FL_FORBEARANCE, DT_INGRS_OBSERVATION, DT_USCITA_OBSERVATION, DT_INGRS_PROBATION,
        DT_USCITA_PROBATION_STIMATA, DT_USCITA_PROBATION
    FROM {{ ref('performing_m') }}
    WHERE DT_OSSERVAZIONE = {{ last_day_past_month() }}
),

perf_ciclo_attivo AS (
    SELECT
        PR.CD_CLIENTE,
        PR.DT_INGRS_PROBATION,
        PR.DT_USCITA_PROBATION_STIMATA,
        PR.DT_USCITA_PROBATION,
        PR.DT_INGRS_OBSERVATION
    FROM performing_raw PR
    JOIN cicli_completi CC
        ON CC.CD_CONTROPARTE = PR.CD_CLIENTE
        AND PR.DT_INGRS_PROBATION BETWEEN CC.DT_INGRESSO_DEFAULT AND CC.DT_USCITA_DEFAULT
),

ristrutturazione_cliente AS (
    SELECT
        CD_CLIENTE, DT_OSSERVAZIONE, DT_RISTRUTTURAZIONE, TP_RISTRUTTURAZIONE,
        ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE ORDER BY DT_RISTRUTTURAZIONE DESC) AS RN
    FROM {{ ref('forbearance_m') }}
    WHERE DT_RISTRUTTURAZIONE IS NOT NULL
),

forborne_cliente AS (
    SELECT
        CD_CLIENTE, DT_OSSERVAZIONE,
        CASE
            WHEN MAX(CASE WHEN FL_FORBEARANCE = 'F' THEN 1 ELSE 0 END) = 1 THEN 'S' ELSE 'N'
        END AS FL_FORBORNE_PRAT
    FROM {{ ref('forbearance_m') }}
    GROUP BY CD_CLIENTE, DT_OSSERVAZIONE
),

forborne_aggr AS (
    SELECT
        P.CD_CONTROPARTE,
        FB.DT_RISTRUTTURAZIONE,
        FO.FL_FORBORNE_PRAT
    FROM perimetro  P
    LEFT JOIN ristrutturazione_cliente FB
        ON FB.CD_CLIENTE = P.CD_CONTROPARTE
        AND FB.DT_OSSERVAZIONE = {{ last_day_past_month() }}
        AND FB.RN = 1
    LEFT JOIN forborne_cliente FO
        ON FO.CD_CLIENTE = P.CD_CONTROPARTE
        AND FO.DT_OSSERVAZIONE = {{ last_day_past_month() }}
),

giorni_scaduto_raw AS (
    SELECT
        CD_CONTROPARTE, NM_GG_SCADUTO_EBA_CLI, NM_GG_SCADUTO_CLI, NM_GG_SCADUTO_CONT, EU_SCADUTO_IMPAG_EBA, EU_IMPIEGO_TOT_EBA,
        ROW_NUMBER() OVER (PARTITION BY CD_CONTROPARTE ORDER BY TS_INSERIMENTO DESC) AS RN
    FROM {{ ref('giorni_scaduto') }}
    WHERE TS_INSERIMENTO <= {{ last_day_past_month() }}
)

SELECT
    P.CD_CONTROPARTE,
    {{ last_day_past_month() }} AS DT_OSSERVAZIONE,
    CA.DT_INGRESSO_DEFAULT AS DT_INGRS_DFLT_EBA,
    CA.DT_USCITA_DEFAULT AS DT_USCITA_DFLT_EBA,
    CASE
        WHEN PE.FL_FORBEARANCE = 'F' AND PE.DT_INGRS_OBSERVATION IS NOT NULL
        AND {{ last_day_past_month() }} >= PE.DT_INGRS_OBSERVATION AND (PE.DT_USCITA_OBSERVATION IS NULL
        OR {{ last_day_past_month() }} <= PE.DT_USCITA_OBSERVATION)
        THEN 'S' ELSE 'N'
    END AS FL_OBSERVATION_F,
    CASE
        WHEN PE.FL_FORBEARANCE = 'NF' AND PE.DT_INGRS_OBSERVATION IS NOT NULL
        AND {{ last_day_past_month() }} >= PE.DT_INGRS_OBSERVATION AND (PE.DT_USCITA_OBSERVATION IS NULL
        OR {{ last_day_past_month() }} <= PE.DT_USCITA_OBSERVATION)
        THEN 'S' ELSE 'N'
    END AS FL_OBSERVATION_NF,
    CASE
        WHEN PE.FL_FORBEARANCE = 'F' AND PE.DT_INGRS_OBSERVATION IS NOT NULL
        AND {{ last_day_past_month() }} >= PE.DT_INGRS_OBSERVATION AND (PE.DT_USCITA_OBSERVATION IS NULL
        OR {{ last_day_past_month() }} <= PE.DT_USCITA_OBSERVATION)
        AND {{ last_day_past_month() }} > DATEADD(DAY, 365, PE.DT_INGRS_OBSERVATION)
        THEN 'S' ELSE 'N'
    END AS FL_PROLUNGATION_F,
    CASE
        WHEN PE.FL_FORBEARANCE = 'NF' AND PE.DT_INGRS_OBSERVATION IS NOT NULL
        AND {{ last_day_past_month() }} >= PE.DT_INGRS_OBSERVATION AND (PE.DT_USCITA_OBSERVATION IS NULL
        OR {{ last_day_past_month() }} <= PE.DT_USCITA_OBSERVATION)
        AND {{ last_day_past_month() }} > DATEADD(DAY, 730, PE.DT_INGRS_OBSERVATION)
        THEN 'S' ELSE 'N'
    END AS FL_PROLUNGATION_NF,
    CASE WHEN PCL.FL_DBT_CLI = 'S' THEN 'S' ELSE 'N' END AS FL_DBT_CLI,
    CASE WHEN SC.FL_DFLT_EBA_CLI = 'S' THEN 'S' ELSE 'N' END AS FL_DFLT_EBA_CLI,
    CASE WHEN PE.FL_FORBEARANCE = 'F' THEN 'S' ELSE 'N' END  AS FL_FORBORNE_CLI,
    PCL.FL_TRUFFA,
    SP.FL_IPE,
    SP.FL_UTP,
    SP.FL_SOF,
    SP.FL_BONIS_FORZATO,
    SP.FL_SOVRAINDEB,
    CASE
        WHEN COALESCE(FB.FL_FORBORNE_PRAT, 'N') = 'S' THEN 'S' ELSE 'N'
    END  AS FL_FORBORNE_PRAT,
    GS.NM_GG_SCADUTO_EBA_CLI AS NM_GG_SCADT_CLI_EBA,
    GS.NM_GG_SCADUTO_CLI AS NM_GG_SCADUTO_CLI,
    GS.NM_GG_SCADUTO_CONT AS NM_GG_SCADUTO_CONTR,
    GS.EU_SCADUTO_IMPAG_EBA AS EU_SCADUTO_IMPAG_EBA,
    GS.EU_IMPIEGO_TOT_EBA AS EU_IMPIEGO_TOT_EBA,
    CASE
        WHEN SC.FL_DFLT_EBA_CLI = 'S' OR UC.DS_SEGNALAZIONE IS NOT NULL THEN PI.DS_SEGNALAZIONE
    END AS DS_MOTIVO_INGRS_DFLT_STO,
    CASE
        WHEN SC.FL_DFLT_EBA_CLI = 'S' THEN UA.DS_SEGNALAZIONE WHEN UC.DS_SEGNALAZIONE IS NOT NULL THEN UC.DS_SEGNALAZIONE
    END AS DS_MOTIVO_EXIT_DFLT_STO,
    {{ custom_to_date('FB.DT_RISTRUTTURAZIONE') }} AS DT_ULTIMA_RISTR,
    PCA.DT_INGRS_PROBATION,
    PCA.DT_USCITA_PROBATION_STIMATA,
    PCA.DT_USCITA_PROBATION,
    PCA.DT_INGRS_OBSERVATION

FROM perimetro P

LEFT JOIN performing_raw PE ON PE.CD_CLIENTE = P.CD_CONTROPARTE
LEFT JOIN pratica_cliente_agg PCL ON PCL.CD_CONTROPARTE = P.CD_CONTROPARTE
LEFT JOIN stato_creditizio_agg SC ON SC.CD_CONTROPARTE = P.CD_CONTROPARTE
LEFT JOIN ciclo_attivo CA ON CA.CD_CONTROPARTE = P.CD_CONTROPARTE
LEFT JOIN segnalazioni_pivot SP ON SP.CD_CONTROPARTE = P.CD_CONTROPARTE
LEFT JOIN forborne_aggr FB ON FB.CD_CONTROPARTE = P.CD_CONTROPARTE
LEFT JOIN giorni_scaduto_raw GS 
    ON GS.CD_CONTROPARTE = P.CD_CONTROPARTE 
    AND GS.RN = 1
LEFT JOIN primo_ingresso PI 
    ON PI.CD_CONTROPARTE = P.CD_CONTROPARTE
    AND PI.RN = 1
LEFT JOIN ultimo_attivo UA 
    ON UA.CD_CONTROPARTE = P.CD_CONTROPARTE
    AND UA.RN = 1
LEFT JOIN ultimo_chiuso UC 
    ON UC.CD_CONTROPARTE = P.CD_CONTROPARTE
    AND UC.RN = 1
    AND COALESCE(SC.FL_DFLT_EBA_CLI, 'N') = 'N'
    AND {{ last_day_past_month() }} <= LAST_DAY(DATEADD(MONTH, 1, UC.DT_FINE))
LEFT JOIN perf_ciclo_attivo PCA ON PCA.CD_CLIENTE = P.CD_CONTROPARTE

{% if is_incremental() %}
    WHERE P.TS_INIZIO_VALIDITA <= {{ last_day_past_month() }}
    AND P.TS_FINE_VALIDITA > {{ last_day_past_month() }}
{% endif %}