-- =============================================================================
-- MODELLO   : DM_CAMPIONI_BASE_LGD_T
-- PROCESSO  : 13_Campioni.LGD  |  LAYER: L3 - DataMart
-- STRATEGIA : incremental / append + pre_hook delete_last_month('DT_OSSERVAZIONE')
-- PK        : CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE
-- =============================================================================
-- ATTENZIONE: versione TEST su branch personale. ref() sostituiti con path
-- hardcoded a tabelle _TEST su AGOS_DEV_16000 per le sole sorgenti indicate
-- dal responsabile; le altre restano ref() perche' i modelli esistono su dev.
-- Da ripristinare a ref() prima del merge su dev.
-- FIX colonne SALDO_GESTIONALE_M (DDL reale verificato):
--   EU_IMPIEGO_GEST  -> EU_IMPIEGO_GESTIONALE (nome corretto)
--   EU_RSCNT         -> EU_RISCONTI (nome corretto, confermato dall'utente)
--   TP_SALDO = 'GEST' -> rimosso, la colonna TP_SALDO non esiste in questa
--     tabella (SALDO_GESTIONALE_M e' gia' dedicata al solo gestionale, a
--     differenza di SALDO_M che conteneva piu' tipi di saldo).
-- =============================================================================

WITH

perimetro AS (
    SELECT
        CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE, CD_CONTROPARTE,
        FL_DBT, FL_DFLT_EBA, DT_INGRS_DFLT_EBA, DT_USCITA_DFLT_EBA,
        FL_OBSERVATION_F, FL_OBSERVATION_NF, FL_PROLUNGATION_F, FL_PROLUNGATION_NF,
        CD_STATO, CD_TIPO_PRODOTTO,
        ROW_NUMBER() OVER (PARTITION BY CD_PRATICA, TP_PROCEDURA ORDER BY DT_INGRS_DFLT_EBA) AS NM_DEF,
        'Q' || TO_CHAR({{ last_day_past_month() }}, 'Q') AS CD_TRIMESTRE_RIFERIMENTO
    FROM {{ ref('dm_pratiche_default_m') }}
    WHERE DT_OSSERVAZIONE >= ADD_MONTHS({{ last_day_past_month() }}, -2)
),

pratica_m_raw AS (
    SELECT
        d.CD_PRATICA, d.TP_PROCEDURA, d.DT_OSSERVAZIONE,
        p.DT_DBT, p.DT_DECORRENZA, p.DT_CHIUSURA_EFFETTIVA AS DT_CHIUSURA,
        p.DT_PASSAGGIO_PERDITA AS DT_PERDITA, p.DT_CESSIONE, p.DT_ULT_ACCODAMENTO, p.FL_ABBUONO,
        d.DT_INGRS_DFLT_EBA AS DT_DEFAULT, d.DT_USCITA_DFLT_EBA AS DT_USCITA_DEFAULT,
        r.DT_ACCODAMENTO, cm.DT_ATTIVAZIONE_CARTA,
        CASE WHEN va.DT_DECESSO IS NOT NULL THEN 'S' ELSE 'N' END AS FL_DECEDUTO,
        COALESCE(NULLIF(f.STDPR_VALUTAZIONE, ''), 'AIRB') AS TP_PERIMETRO,
        p.CD_CLIENTE, p.CD_CONVENZIONATO, p.CD_COOBLIGATO AS CD_COOBLIGATO,
        va.CD_FISCALE, va.DS_RAGIONE_SOCIALE,
        va.CD_SETTORE_ATTIVITA AS CD_SETTORE, CAST(NULL AS VARCHAR) AS DS_SETTORE,
        cm.CD_BLOCCO, cm.TP_CATEGORIA_CARTE AS TP_CARTA, cm.CD_TASSO_INDICIZZATO,-- da levare se confermato
        sc.CD_ORGANIZZAZIONE_CARTA AS CD_ORGANIZZAZIONE,
        p.CD_MERCATO_1, p.CD_MERCATO_2, p.CD_MERCATO_3, p.CD_MERCATO_4,
        p.CD_MACRO_PRODOTTO_1, p.CD_MACRO_PRODOTTO_2, p.CD_MACRO_PRODOTTO_3, p.CD_MACRO_PRODOTTO_4,
        ir.NM_RATE_ACCODATE AS NM_ACCODAMENTI,
        CASE WHEN p.DT_ULT_ACCODAMENTO IS NOT NULL AND p.DT_ULT_ACCODAMENTO >= d.DT_INGRS_DFLT_EBA THEN 'S' ELSE 'N' END AS FL_ACCODAMENTO,
        CASE d.TP_PROCEDURA
            WHEN 'CO' THEN co.NM_TASSO_COSTRUZIONE
            WHEN 'CA' THEN NULL --CD_TASSO_INDICIZZATO
            WHEN 'CQ' THEN cq.NM_TASSO_PERM_INTERESSI
        END AS PC_TASSO
    FROM perimetro d
    LEFT JOIN {{ ref('pratica_m') }} p
        ON p.CD_PRATICA = d.CD_PRATICA AND p.TP_PROCEDURA = d.TP_PROCEDURA AND p.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE
    LEFT JOIN AGOS_DEV_16000.L2_PAGAMENTI_CONTABILITA.RATE_M_TEST r
        ON r.CD_PRATICA = d.CD_PRATICA AND r.TP_PROCEDURA = d.TP_PROCEDURA AND r.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE
    LEFT JOIN (
        SELECT CD_CONTROPARTE, CD_FISCALE, DS_RAGIONE_SOCIALE, DT_DECESSO, CD_SETTORE_ATTIVITA, TS_INIZIO_VALIDITA, TS_FINE_VALIDITA
        FROM {{ ref('variazioni_anagrafiche') }}
        QUALIFY ROW_NUMBER() OVER (PARTITION BY CD_CONTROPARTE, TS_INIZIO_VALIDITA ORDER BY TS_FINE_VALIDITA DESC NULLS FIRST) = 1
    ) va ON va.CD_CONTROPARTE = p.CD_CLIENTE
        AND d.DT_OSSERVAZIONE BETWEEN va.TS_INIZIO_VALIDITA AND va.TS_FINE_VALIDITA
    LEFT JOIN AGOS_DEV_16000.L1_O_BAS.IFBLFSTDPR_TEST f
        ON f.STDPR_PRATICA = d.CD_PRATICA AND f.STDPR_PROVENIENZA = d.TP_PROCEDURA AND f.STDPR_DATA_ESTRAZIONE = d.DT_OSSERVAZIONE
    LEFT JOIN {{ ref('carta_m') }} cm
        ON cm.CD_PRATICA = d.CD_PRATICA AND cm.TP_PROCEDURA = d.TP_PROCEDURA AND cm.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE AND d.TP_PROCEDURA = 'CA'
    LEFT JOIN AGOS_DEV_16000.L2_SCORING.SOCIODEMO_SCORE_TEST sc
        ON sc.CD_PRATICA = d.CD_PRATICA AND sc.TP_PROCEDURA = d.TP_PROCEDURA AND d.TP_PROCEDURA = 'CA'
    LEFT JOIN (
        SELECT CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE, MAX(NM_RATE_ACCODATE) AS NM_RATE_ACCODATE
        FROM {{ ref('indice_rischio_m') }} GROUP BY 1, 2, 3
    ) ir ON ir.CD_PRATICA = d.CD_PRATICA AND ir.TP_PROCEDURA = d.TP_PROCEDURA AND ir.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE
    LEFT JOIN {{ ref('consumo_m') }} co
        ON co.CD_PRATICA = d.CD_PRATICA AND co.TP_PROCEDURA = d.TP_PROCEDURA AND co.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE AND d.TP_PROCEDURA = 'CO'
    LEFT JOIN {{ ref('cqs_m') }} cq
        ON cq.CD_PRATICA = d.CD_PRATICA AND cq.TP_PROCEDURA = d.TP_PROCEDURA AND cq.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE AND d.TP_PROCEDURA = 'CQ'
),

fido_default AS (
    SELECT
        d.CD_PRATICA, d.TP_PROCEDURA, d.DT_OSSERVAZIONE,
        MAX(CASE WHEN fd.DT_OSSERVAZIONE = LAST_DAY(d.DT_INGRS_DFLT_EBA)
                 THEN fd.EU_FIDO END)        AS EU_FIDO_DEFAULT,
        MAX(CASE WHEN fd.DT_OSSERVAZIONE = LAST_DAY(ADD_MONTHS(d.DT_INGRS_DFLT_EBA, -1))
                 THEN fd.EU_FIDO END)        AS EU_FIDO_PRECEDENTE_DEFAULT,
        MAX(CASE WHEN fd.DT_OSSERVAZIONE = LAST_DAY(d.DT_INGRS_DFLT_EBA)
                 THEN fd.EU_FINANZIATO END)  AS EU_FINANZIATO
    FROM perimetro d
    LEFT JOIN {{ ref('pratica_m') }} fd
        ON  fd.CD_PRATICA   = d.CD_PRATICA
        AND fd.TP_PROCEDURA = d.TP_PROCEDURA
        AND fd.DT_OSSERVAZIONE IN (
                LAST_DAY(d.DT_INGRS_DFLT_EBA),
                LAST_DAY(ADD_MONTHS(d.DT_INGRS_DFLT_EBA, -1))
            )
    WHERE d.DT_OSSERVAZIONE = {{ last_day_past_month() }}
    GROUP BY d.CD_PRATICA, d.TP_PROCEDURA, d.DT_OSSERVAZIONE
),

incassi_raw AS (
    SELECT
        p.CD_PRATICA, p.TP_PROCEDURA, p.DT_OSSERVAZIONE,
        SUM(i.EU_IMPORTO) AS EU_INCASSI_TOT, SUM(c.EU_INCASSO_CESSIONE) AS EU_INCASSO_CESSIONE
        {% for n in range(1, 181) %},
        MAX(CASE WHEN DATEDIFF('MONTH', i.DT_OSSERVAZIONE, p.DT_OSSERVAZIONE) = {{ n }} THEN i.EU_IMPORTO END) AS EU_INCASSO_{{ n }},
        MAX(CASE WHEN DATEDIFF('MONTH', i.DT_OSSERVAZIONE, p.DT_OSSERVAZIONE) = {{ n }} THEN i.DT_VALUTA  END) AS DT_INCASSO_{{ n }}
        {% endfor %}
    FROM perimetro p
    LEFT JOIN AGOS_DEV_16000.L2_PAGAMENTI_CONTABILITA.INCASSI_M_TEST i
        ON i.CD_PRATICA = p.CD_PRATICA AND i.TP_PROCEDURA = p.TP_PROCEDURA
        AND i.DT_OSSERVAZIONE BETWEEN ADD_MONTHS(p.DT_OSSERVAZIONE, -180) AND p.DT_OSSERVAZIONE
        AND i.TP_PARTITA IN ('RP','AA','AN','IM','MP')
    LEFT JOIN AGOS_DEV_16000.L2_GESTIONE_CREDITI.CESSIONI c
        ON c.CD_PRATICA = p.CD_PRATICA AND c.TP_PROCEDURA = p.TP_PROCEDURA
        AND c.DT_CESSIONE BETWEEN TRUNC(p.DT_OSSERVAZIONE, 'MM') AND p.DT_OSSERVAZIONE
    GROUP BY p.CD_PRATICA, p.TP_PROCEDURA, p.DT_OSSERVAZIONE
),

flag_contratti_default AS (
    SELECT
        d.CD_PRATICA, d.TP_PROCEDURA, d.DT_OSSERVAZIONE,
        CASE WHEN d.FL_DBT = 'S' AND d.DT_INGRS_DFLT_EBA >= DATE '2003-12-31'
             AND COALESCE(CAST(CASE WHEN d.TP_PROCEDURA IN ('CO','CQ') THEN (s.EU_IMPIEGO_GESTIONALE - COALESCE(s.EU_RISCONTI,0))/100
                                    WHEN d.TP_PROCEDURA = 'CA' THEN s.EU_IMPIEGO_GESTIONALE/100 END AS NUMBER(18,2)), 0)
                 - COALESCE(inc.EU_INCASSI_TOT, 0) <= 0
             THEN 'S' ELSE 'N' END AS FL_DBT_AV,
        CASE WHEN ms.DT_MIN_SCADENZA IS NOT NULL AND ms.DT_MIN_SCADENZA >= d.DT_INGRS_DFLT_EBA THEN 'S' ELSE 'N' END AS FL_CAMBIALI,
        CASE WHEN d.FL_DFLT_EBA = 'S' AND s.EU_SALDO_AVERE > 0 THEN 'S' ELSE 'N' END AS FL_DEFAULT_AVERE
    FROM perimetro d
    LEFT JOIN incassi_raw inc
        ON inc.CD_PRATICA = d.CD_PRATICA AND inc.TP_PROCEDURA = d.TP_PROCEDURA AND inc.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE
    LEFT JOIN (
        SELECT CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE, MIN(DT_SCADENZA) AS DT_MIN_SCADENZA
        FROM AGOS_DEV_16000.L2_PAGAMENTI_CONTABILITA.CAMBIALI_TEST
        WHERE CD_TIPO_PARTITA IN ('AA','AN','IM','MP','RP') AND TS_INSERIMENTO <= {{ last_day_past_month() }}
        GROUP BY 1, 2, 3
    ) ms ON ms.CD_PRATICA = d.CD_PRATICA AND ms.TP_PROCEDURA = d.TP_PROCEDURA AND ms.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE
    LEFT JOIN AGOS_DEV_16000.L2_SALDI.SALDO_GESTIONALE_M s
        ON s.CD_PRATICA = d.CD_PRATICA AND s.TP_PROCEDURA = d.TP_PROCEDURA AND s.DT_OSSERVAZIONE = LAST_DAY(d.DT_INGRS_DFLT_EBA)
    WHERE d.FL_DFLT_EBA = 'S'
),

fl_altri_addebiti AS (
    SELECT
        d.CD_PRATICA, d.TP_PROCEDURA, d.DT_OSSERVAZIONE,
        CASE
            WHEN d.TP_PROCEDURA IN ('CO','CQ') AND aa_co.CD_PRATICA IS NOT NULL AND aa_co.EU_IMPIEGO_GESTIONALE < 15.50 THEN 'S'
            WHEN d.TP_PROCEDURA = 'CA' AND aa_co.CD_PRATICA IS NOT NULL THEN 'S'
            ELSE 'N'
        END AS FL_ALTRI_ADDEBITI
    FROM perimetro d
    LEFT JOIN AGOS_DEV_16000.L2_SALDI.SALDO_GESTIONALE_M aa_co
        ON  aa_co.CD_PRATICA      = d.CD_PRATICA
        AND aa_co.TP_PROCEDURA    = d.TP_PROCEDURA
        AND aa_co.DT_OSSERVAZIONE = d.DT_OSSERVAZIONE
),

ead_raw AS (
    SELECT
        CD_PRATICA, TP_PROCEDURA, DT_INGRS_DFLT_EBA, NM_DEF,
        MAX(CASE WHEN IS_DEF_SNAPSHOT = 1 THEN EAD_SNAPSHOT END) AS EU_EAD_DEF
        {% for n in range(1, 181) %},
        MAX(CASE WHEN NM_MESE_DA_DEFAULT = {{ n }} THEN EAD_MESE END) AS EU_EAD_{{ n }}
        {% endfor %}
    FROM (
        SELECT
            p.CD_PRATICA, p.TP_PROCEDURA, p.DT_INGRS_DFLT_EBA, p.NM_DEF,
            DATEDIFF('MONTH', LAST_DAY(p.DT_INGRS_DFLT_EBA), p.DT_OSSERVAZIONE) + 1 AS NM_MESE_DA_DEFAULT,
            CAST(CASE WHEN p.TP_PROCEDURA IN ('CO','CQ') THEN (s.EU_IMPIEGO_GESTIONALE - COALESCE(s.EU_RISCONTI,0))/100
                     WHEN p.TP_PROCEDURA = 'CA' THEN s.EU_IMPIEGO_GESTIONALE/100 END AS NUMBER(18,2)) AS EAD_MESE,
            CAST(CASE WHEN p.TP_PROCEDURA IN ('CO','CQ') THEN (s.EU_IMPIEGO_GESTIONALE - COALESCE(s.EU_RISCONTI,0))
                     WHEN p.TP_PROCEDURA = 'CA' THEN s.EU_IMPIEGO_GESTIONALE END AS NUMBER(18,2)) AS EAD_SNAPSHOT,
            CASE WHEN p.DT_OSSERVAZIONE = LAST_DAY(p.DT_INGRS_DFLT_EBA) THEN 1 END AS IS_DEF_SNAPSHOT
        FROM perimetro p
        LEFT JOIN AGOS_DEV_16000.L2_SALDI.SALDO_GESTIONALE_M s
            ON s.CD_PRATICA = p.CD_PRATICA AND s.TP_PROCEDURA = p.TP_PROCEDURA AND s.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
        WHERE p.DT_OSSERVAZIONE >= LAST_DAY(p.DT_INGRS_DFLT_EBA)
    ) ead_base
    GROUP BY CD_PRATICA, TP_PROCEDURA, DT_INGRS_DFLT_EBA, NM_DEF
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CD_PRATICA, TP_PROCEDURA ORDER BY DT_INGRS_DFLT_EBA DESC) = 1
)

SELECT
    p.CD_PRATICA, p.TP_PROCEDURA,
    p.CD_STATO AS CD_STATO_PRATICA, p.CD_TIPO_PRODOTTO AS TP_PRODOTTO,
    p.DT_OSSERVAZIONE, p.CD_TRIMESTRE_RIFERIMENTO, p.NM_DEF,
    pm.DT_ATTIVAZIONE_CARTA, pm.DT_DBT, pm.DT_DEFAULT, pm.DT_USCITA_DEFAULT,
    pm.DT_DECORRENZA, pm.DT_CHIUSURA, pm.DT_PERDITA, pm.DT_ACCODAMENTO, pm.DT_CESSIONE,
    CASE WHEN COALESCE(pm.FL_ABBUONO, 'N') = 'S' THEN 'S' ELSE 'N' END AS FL_ABBUONO,
    pm.FL_DECEDUTO,
    CASE WHEN p.FL_DFLT_EBA = 'S' AND p.DT_USCITA_DFLT_EBA IS NOT NULL AND p.DT_USCITA_DFLT_EBA = pm.DT_ACCODAMENTO
         THEN 'S' ELSE 'N' END AS FL_USCITA_DEFAULT_ACCODAMENTO,
    pm.TP_PERIMETRO,
    CASE WHEN COALESCE(p.FL_DBT, 'N') = 'S' THEN 'S' ELSE 'N' END AS FL_DBT,
    fid.EU_FIDO_DEFAULT, fid.EU_FIDO_PRECEDENTE_DEFAULT, fid.EU_FINANZIATO,
    pm.CD_CLIENTE, pm.CD_FISCALE, pm.DS_RAGIONE_SOCIALE, pm.CD_CONVENZIONATO, pm.CD_COOBLIGATO,
    pm.CD_BLOCCO, pm.CD_ORGANIZZAZIONE, pm.TP_CARTA,
    pm.CD_SETTORE, pm.DS_SETTORE,
    pm.CD_MERCATO_1, pm.CD_MERCATO_2, pm.CD_MERCATO_3, pm.CD_MERCATO_4,
    pm.CD_MACRO_PRODOTTO_1, pm.CD_MACRO_PRODOTTO_2, pm.CD_MACRO_PRODOTTO_3, pm.CD_MACRO_PRODOTTO_4,
    fc.FL_DBT_AV, fc.FL_CAMBIALI,
    p.FL_OBSERVATION_F, p.FL_OBSERVATION_NF, p.FL_PROLUNGATION_F, p.FL_PROLUNGATION_NF,
    fc.FL_DEFAULT_AVERE,
    CASE WHEN p.TP_PROCEDURA IN ('CO','CQ') AND p.DT_OSSERVAZIONE = {{ last_day_past_month() }}
              AND EXISTS (
                  SELECT 1 FROM {{ ref('consolidamenti') }} cons
                  WHERE cons.CD_PRATICA_CONSOLIDANTE = p.CD_PRATICA
                    AND cons.TP_PROC_CONSOLIDANTE = p.TP_PROCEDURA
              )
         THEN 'S' ELSE 'N' END AS FL_RIF,
    CASE WHEN p.TP_PROCEDURA = 'CA' AND p.DT_OSSERVAZIONE = {{ last_day_past_month() }}
              AND p.DT_USCITA_DFLT_EBA IS NOT NULL
              AND (pm.DT_CESSIONE IS NOT NULL OR pm.DT_PERDITA IS NOT NULL)
         THEN 'S' ELSE 'N' END AS FL_EX_FORZ_DT_PERD,
    CASE WHEN COALESCE(fa.FL_ALTRI_ADDEBITI, 'N') = 'S' THEN 'S' ELSE 'N' END AS FL_ALTRI_ADDEBITI,
    pm.NM_ACCODAMENTI, pm.FL_ACCODAMENTO, pm.PC_TASSO,
    ir.EU_INCASSI_TOT, ir.EU_INCASSO_CESSIONE
    {% for n in range(1, 181) %}, ir.EU_INCASSO_{{ n }}, ir.DT_INCASSO_{{ n }}{% endfor %},
    er.EU_EAD_DEF
    {% for n in range(1, 181) %}, er.EU_EAD_{{ n }}{% endfor %}

FROM perimetro p
LEFT JOIN pratica_m_raw pm   ON pm.CD_PRATICA = p.CD_PRATICA AND pm.TP_PROCEDURA = p.TP_PROCEDURA AND pm.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
LEFT JOIN fido_default fid   ON fid.CD_PRATICA = p.CD_PRATICA AND fid.TP_PROCEDURA = p.TP_PROCEDURA AND fid.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
LEFT JOIN flag_contratti_default fc ON fc.CD_PRATICA = p.CD_PRATICA AND fc.TP_PROCEDURA = p.TP_PROCEDURA AND fc.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
LEFT JOIN fl_altri_addebiti fa ON fa.CD_PRATICA = p.CD_PRATICA AND fa.TP_PROCEDURA = p.TP_PROCEDURA AND fa.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
LEFT JOIN incassi_raw ir     ON ir.CD_PRATICA = p.CD_PRATICA AND ir.TP_PROCEDURA = p.TP_PROCEDURA AND ir.DT_OSSERVAZIONE = p.DT_OSSERVAZIONE
LEFT JOIN ead_raw er         ON er.CD_PRATICA = p.CD_PRATICA AND er.TP_PROCEDURA = p.TP_PROCEDURA