-- =============================================================================
-- MODELLO   : dm_campioni_sviluppo_m
-- PROCESSO  : 13_Campioni.LGD  |  LAYER: L3 - DataMart
-- SORGENTE  : PRATICA_M (driving) + tabelle di arricchimento
-- FREQUENZA : Mensile - incremental append + delete_last_month('DT_OSSERVAZIONE')
-- PK        : CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE
-- DT_OSS    : unica data di osservazione del run; ancora delle finestre mobili
-- NOTA      : ogni tabella e' letta una sola volta. CLI/COOB sono separati con
--             aggregazione condizionata, mai con due alias della stessa tabella.
-- =============================================================================

{% set DT_OSS = last_day_past_month() %}
{% set MESI_RESP = [3, 6, 9, 12] %}
{% set MESI_INS  = [3, 6, 9, 12, 18, 24] %}

WITH

-- ===================== PRATICA_M (CTE guida) =====================
pratica_storico AS (
    SELECT
        CD_PRATICA, TP_PROCEDURA, DT_OSSERVAZIONE, CD_CLIENTE, CD_COOBLIGATO,
        CD_ABI, CD_CAB, CD_CANALE_ACQUISIZIONE, CD_STATO,
        DT_CHIUSURA_EFFETTIVA, DT_DBT, DT_DECORRENZA, DT_PASSAGGIO_PERDITA,
        DT_CESSIONE, DT_PRIMA_SCADENZA, EU_EROGATO, EU_FIDO, FL_FIRMA_DOPPIA,
        DT_CARICAMENTO, DT_LIQUIDAZIONE, DT_ULT_ACCODAMENTO, DT_APPROVAZIONE,
        DT_STORNATA, DT_ESTINZIONE_ANTICIPATA, DT_ULTIMA_SCADENZA, DT_RESPINTA,
        FL_CARTOLARIZZATA,
        CD_MERCATO_1, CD_MERCATO_2, CD_MERCATO_3, CD_MERCATO_4,
        CD_MACRO_PRODOTTO_1, CD_MACRO_PRODOTTO_2, CD_MACRO_PRODOTTO_3, CD_MACRO_PRODOTTO_4,
        CD_DESTINAZIONE_BENE, CD_PRODOTTO, CD_TIPO_PRODOTTO, FL_WEB_CANALE_ACQ,

        SUM(CASE WHEN TP_PROCEDURA = 'CA' AND CD_STATO > 40 AND DT_STORNATA IS NULL
                  AND DT_CESSIONE IS NULL AND DT_PASSAGGIO_PERDITA IS NULL AND DT_LIQUIDAZIONE IS NOT NULL
             THEN 1 ELSE 0 END) OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS NM_CONTRATTI_ATTIVI_CARTA,
        SUM(CASE WHEN TP_PROCEDURA = 'CO' AND CD_STATO > 40 AND DT_STORNATA IS NULL
                  AND DT_CESSIONE IS NULL AND DT_PASSAGGIO_PERDITA IS NULL AND DT_LIQUIDAZIONE IS NOT NULL
             THEN 1 ELSE 0 END) OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS NM_CONTRATTI_ATTIVI_CONSUMO,
        SUM(CASE WHEN CD_MACRO_PRODOTTO_1 = 'CA' THEN 1 ELSE 0 END) OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS NM_CONTRATTI_CARTA,
        SUM(CASE WHEN CD_MACRO_PRODOTTO_1 = 'CO' THEN 1 ELSE 0 END) OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS NM_CONTRATTI_CONSUMO,
        SUM(CASE WHEN TP_PROCEDURA = 'CQ'        THEN 1 ELSE 0 END) OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS NM_CQS_CLI,
        {% for m in MESI_RESP %}
        COUNT(CASE WHEN DT_RESPINTA >= ADD_MONTHS(DT_OSSERVAZIONE, -{{ m }}) THEN 1 END)
            OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS _RESP_{{ m }}M_TOT,
        COUNT(CASE WHEN DT_RESPINTA >= ADD_MONTHS(DT_OSSERVAZIONE, -{{ m }}) AND TP_PROCEDURA = 'CA' THEN 1 END)
            OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS _RESP_{{ m }}M_CA,
        COUNT(CASE WHEN DT_RESPINTA >= ADD_MONTHS(DT_OSSERVAZIONE, -{{ m }}) AND TP_PROCEDURA = 'CO' THEN 1 END)
            OVER (PARTITION BY CD_CLIENTE, DT_OSSERVAZIONE) AS _RESP_{{ m }}M_CO{{ "," if not loop.last }}
        {% endfor %}
    FROM {{ ref('pratica_m') }}
    {% if is_incremental() %}
    WHERE DT_OSSERVAZIONE = {{ DT_OSS }}
    {% endif %}
),

-- ===================== SOCIODEMO_SCORE + BAPRATCT (letture uniche, pivot CLI/COOB) =====================
sociodemo_impegni_pivot AS (
    SELECT
        K.CD_PRATICA, K.TP_PROCEDURA, K.DT_OSSERVAZIONE,
        -- cliente
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_CONTROPARTE          END) AS CLI_CD_CONTROPARTE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DT_OSSERVAZIONE         END) AS CLI_DT_OSSERVAZIONE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_BLOCCO               END) AS CLI_CD_BLOCCO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_CBSCORE_CRIF         END) AS CLI_CD_CBSCORE_CRIF,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_CITTADINANZA         END) AS CLI_CD_CITTADINANZA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_COMPORT_CRIF         END) AS CLI_CD_COMPORT_CRIF,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_FORMA_GIURIDICA      END) AS CLI_CD_FORMA_GIURIDICA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_OCCUPAZIONE          END) AS CLI_CD_OCCUPAZIONE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_ORGANIZZAZIONE_CARTA END) AS CLI_CD_ORGANIZZAZIONE_CARTA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_PROVEN_COMMERC       END) AS CLI_CD_PROVEN_COMMERC,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_PROVINCIA_NASCITA    END) AS CLI_CD_PROVINCIA_NASCITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_PROVINCIA_RESIDENZA  END) AS CLI_CD_PROVINCIA_RESIDENZA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_QUALITA              END) AS CLI_CD_QUALITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_QUALITA_CONV         END) AS CLI_CD_QUALITA_CONV,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_REGIONE_RESIDENZA    END) AS CLI_CD_REGIONE_RESIDENZA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_SESSO                END) AS CLI_CD_SESSO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_SETT_ATTIVITA        END) AS CLI_CD_SETT_ATTIVITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_STATO_CIVILE         END) AS CLI_CD_STATO_CIVILE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_TAB_FINANZ           END) AS CLI_CD_TAB_FINANZ,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_TIPO_AZIENDA         END) AS CLI_CD_TIPO_AZIENDA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.CD_TIPO_TASSO           END) AS CLI_CD_TIPO_TASSO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DS_BENE                 END) AS CLI_DS_BENE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DT_INIZIO_INDIR         END) AS CLI_DT_INIZIO_INDIR,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DT_INIZIO_OCCUP         END) AS CLI_DT_INIZIO_OCCUP,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DT_INIZIO_RAPP          END) AS CLI_DT_INIZIO_RAPP,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DT_INIZIO_RAPP_BANCA    END) AS CLI_DT_INIZIO_RAPP_BANCA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DT_NASCITA              END) AS CLI_DT_NASCITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.DT_ULTIMO_PROTESTO      END) AS CLI_DT_ULTIMO_PROTESTO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_ALTRI_REDDITI        END) AS CLI_EU_ALTRI_REDDITI,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_COMMISSIONE          END) AS CLI_EU_COMMISSIONE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_CUMULO_RISCHIO       END) AS CLI_EU_CUMULO_RISCHIO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_CUMULO_RISCHIO_CRIF  END) AS CLI_EU_CUMULO_RISCHIO_CRIF,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_FIDO                 END) AS CLI_EU_FIDO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_FINANZIATO           END) AS CLI_EU_FINANZIATO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_MOROSITA             END) AS CLI_EU_MOROSITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_PROTESTI             END) AS CLI_EU_PROTESTI,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_RATA                 END) AS CLI_EU_RATA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_RATA_CRIF            END) AS CLI_EU_RATA_CRIF,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_REDDITO_ANNUO        END) AS CLI_EU_REDDITO_ANNUO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.EU_REDDITO_FAMIGLIARE   END) AS CLI_EU_REDDITO_FAMIGLIARE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.FL_CONTO_BANCARIO       END) AS CLI_FL_CONTO_BANCARIO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.FL_DEPOSITO_BANCARIO    END) AS CLI_FL_DEPOSITO_BANCARIO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.FL_FIRMA_DOPPIA         END) AS CLI_FL_FIRMA_DOPPIA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.NM_CESSIONE_BUSTA_PAGA  END) AS CLI_NM_CESSIONE_BUSTA_PAGA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.NM_FAMILIARI            END) AS CLI_NM_FAMILIARI,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.NM_MENSILITA            END) AS CLI_NM_MENSILITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.NM_MESI_DURATA          END) AS CLI_NM_MESI_DURATA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.NM_MOROSITA             END) AS CLI_NM_MOROSITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.NM_PROTESTI             END) AS CLI_NM_PROTESTI,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_ABITAZIONE           END) AS CLI_TP_ABITAZIONE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_ATTIVITA             END) AS CLI_TP_ATTIVITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_BANCA                END) AS CLI_TP_BANCA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_BENE                 END) AS CLI_TP_BENE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_CONTRATTO_LAVORO     END) AS CLI_TP_CONTRATTO_LAVORO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_LOCAZIONE            END) AS CLI_TP_LOCAZIONE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_PAGAMENTO            END) AS CLI_TP_PAGAMENTO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_PRATICA_INTERNET     END) AS CLI_TP_PRATICA_INTERNET,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_PROCEDURA            END) AS CLI_TP_PROCEDURA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = K.CD_CLIENTE    THEN SD.TP_RIPAGAMENTO          END) AS CLI_TP_RIPAGAMENTO,
        -- coobligato
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.CD_CONTROPARTE          END) AS COOB_CD_CONTROPARTE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.CD_STATO_CIVILE         END) AS COOB_CD_STATO_CIVILE,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_ALTRI_REDDITI        END) AS COOB_EU_ALTRI_REDDITI,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_ALTR_USC             END) AS COOB_EU_ALTR_USC,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_CUMULO_RISCHIO       END) AS COOB_EU_CUMULO_RISCHIO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_CUMULO_RISCHIO_CRIF  END) AS COOB_EU_CUMULO_RISCHIO_CRIF,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_DEPOSITO_BANCARIO    END) AS COOB_EU_DEPOSITO_BANCARIO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_FIDO                 END) AS COOB_EU_FIDO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_MOROSITA             END) AS COOB_EU_MOROSITA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_PROTESTI             END) AS COOB_EU_PROTESTI,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_RATA                 END) AS COOB_EU_RATA,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_RATA_CRIF            END) AS COOB_EU_RATA_CRIF,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.EU_REDDITO_ANNUO        END) AS COOB_EU_REDDITO_ANNUO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.FL_CONTO_BANCARIO       END) AS COOB_FL_CONTO_BANCARIO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.FL_DEPOSITO_BANCARIO    END) AS COOB_FL_DEPOSITO_BANCARIO,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.NM_PROTESTI             END) AS COOB_NM_PROTESTI,
        MAX(CASE WHEN SD.CD_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO) THEN SD.TP_CONTROPARTE          END) AS COOB_TP_CONTROPARTE,
        -- impegni (BAPRATCT)
        MAX(CASE WHEN B.BAPCT_CONTROPARTE = K.CD_CLIENTE THEN B.BAPCT_IMPEGNI END)            AS CD_IMPEGNI_CLI,
        MAX(CASE WHEN B.BAPCT_CONTROPARTE = TRY_TO_NUMBER(K.CD_COOBLIGATO)
                 THEN B.BAPCT_IMPEGNI END)                                                    AS CD_IMPEGNI_COOB
    FROM pratica_storico K
    LEFT JOIN AGOS_DEV_16000.L2_SCORING.SOCIODEMO_SCORE_TEST SD
        ON  SD.CD_PRATICA      = K.CD_PRATICA
        AND SD.TP_PROCEDURA    = K.TP_PROCEDURA
        AND SD.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE
        AND SD.CD_CONTROPARTE IN (K.CD_CLIENTE, TRY_TO_NUMBER(K.CD_COOBLIGATO))
    LEFT JOIN {{ ref('bapratct') }} B
        ON  B.BAPCT_NUM_PRATICA = K.CD_PRATICA
        AND B.BAPCT_PROCEDURA   = K.TP_PROCEDURA
        AND B.BAPCT_CONTROPARTE IN (K.CD_CLIENTE, TRY_TO_NUMBER(K.CD_COOBLIGATO))
    GROUP BY K.CD_PRATICA, K.TP_PROCEDURA, K.DT_OSSERVAZIONE
)


-- ===================== SELECT FINALE =====================
SELECT
    K.CD_PRATICA, K.TP_PROCEDURA, K.DT_OSSERVAZIONE,
    K.CD_CLIENTE            AS CD_CONTROPARTE,
    K.CD_ABI                AS CD_ABI_CLI,
    K.CD_CAB                AS CD_CAB_CLI,
    K.CD_CANALE_ACQUISIZIONE AS CD_ORIGINE_PRAT,
    SI.DS_MARCA_AUTO        AS CD_MARCA_AUTO,
    K.CD_STATO,
    K.DT_CHIUSURA_EFFETTIVA AS DT_CHIUSURA,
    K.DT_DBT,
    K.DT_DECORRENZA         AS DT_DECORR,
    K.DT_PASSAGGIO_PERDITA, K.DT_CESSIONE,
    K.DT_PRIMA_SCADENZA     AS DT_PRIMA_SCAD,
    CAR.DT_PRIMO_UTILIZZO   AS CAR_DT_PRIMO_UTILIZZO,
    K.EU_EROGATO, K.EU_FIDO,
    K.EU_FIDO               AS EU_FIDO_CLI,
    K.EU_FIDO               AS EU_FIDO_COOB,
    K.EU_FIDO               AS EU_ULT_PAGAM,
    CONSM.FL_AUTO_NUOVA     AS FL_AUTO_NUOVA_USATA,
    K.FL_FIRMA_DOPPIA,
    SD.CLI_FL_FIRMA_DOPPIA  AS FL_FIRMA_DOPPIA_IST,
    K.FL_CARTOLARIZZATA     AS FL_CARTOLARIZZAZIONE,
    CASE WHEN CONSM.EU_MAXI_RATA > 0 THEN 'S' ELSE 'N' END AS FL_MAXIRATA,
    CONSM.TP_AUTO           AS CONSM_TP_AUTO,
    CAR.DT_ATTIVAZIONE_CARTA::TIMESTAMP_NTZ AS TS_ATTIVAZ,
    K.DT_CARICAMENTO::TIMESTAMP_NTZ         AS TS_CARIC,
    K.DT_CARICAMENTO::TIMESTAMP_NTZ         AS TS_CARIC_ULT_PRAT_PRESTITO,
    K.DT_CARICAMENTO        AS DT_CARIC_PRIMA_PRAT,
    K.DT_LIQUIDAZIONE::TIMESTAMP_NTZ        AS TS_LIQUIDAZIONE,
    K.DT_ULT_ACCODAMENTO    AS DT_ACCOD,
    K.DT_APPROVAZIONE       AS DT_APPROV,
    K.DT_STORNATA           AS DT_STORNO,
    K.DT_ESTINZIONE_ANTICIPATA AS DT_ESTINZIONE,
    K.DT_ULTIMA_SCADENZA    AS DT_ULT_SCAD,
    K.DT_DECORRENZA         AS DT_INZIO_CLIENTE_AG_CLI,
    K.CD_MERCATO_1, K.CD_MERCATO_2, K.CD_MERCATO_3, K.CD_MERCATO_4,
    K.CD_MACRO_PRODOTTO_1, K.CD_MACRO_PRODOTTO_2, K.CD_MACRO_PRODOTTO_3, K.CD_MACRO_PRODOTTO_4,
    COALESCE(K.DT_PASSAGGIO_PERDITA, K.DT_CESSIONE) AS FL_PRAT_CESSIONE_PERDITA,
    K.CD_DESTINAZIONE_BENE, K.CD_PRODOTTO, K.CD_TIPO_PRODOTTO, K.FL_WEB_CANALE_ACQ,

    -- === SOCIODEMO_SCORE - cliente ===
    SD.CLI_CD_CONTROPARTE           AS CD_CLIENTE,
    SD.CLI_CD_BLOCCO                AS CD_BLOCCO_IST,
    SD.CLI_CD_CBSCORE_CRIF          AS CD_CB_SCORE_CRIF_PLUS_CLI,
    SD.CLI_CD_CITTADINANZA          AS CD_CITTADINANZA,
    SD.CLI_CD_COMPORT_CRIF          AS CD_SCORE_COMPORTAMENTALE_CRIF_CLIE,
    SD.CLI_CD_FORMA_GIURIDICA       AS CD_FORMA_GIUR,
    SD.CLI_CD_OCCUPAZIONE           AS CD_OCCUP,
    SD.CLI_CD_ORGANIZZAZIONE_CARTA  AS CD_ORG_CARTA,
    SD.CLI_CD_ORGANIZZAZIONE_CARTA  AS TP_ORG,
    SD.CLI_CD_ORGANIZZAZIONE_CARTA  AS TP_ORG_CARTA,
    SD.CLI_CD_PROVEN_COMMERC        AS CD_PROVENIENZA_COMMERCIALE,
    SD.CLI_CD_PROVINCIA_NASCITA     AS CD_PROV_NASCITA_IST,
    SD.CLI_CD_PROVINCIA_RESIDENZA   AS CD_PROV_RESID_IST,
    SD.CLI_CD_QUALITA               AS CD_QUALITA_CLI,
    SD.CLI_CD_QUALITA_CONV          AS CD_QUALITA_CONV,
    SD.CLI_CD_REGIONE_RESIDENZA     AS CD_REGIONE_RESID,
    SD.CLI_CD_SESSO                 AS CD_SESSO_CLI,
    SD.CLI_CD_SETT_ATTIVITA         AS CD_SETTORE_ATTIVITA_CLI,
    SD.CLI_CD_STATO_CIVILE          AS CD_STATO_CIVILE_CLI,
    SD.CLI_CD_TAB_FINANZ            AS CD_TAB_FINANZIARIA,
    SD.CLI_CD_TIPO_AZIENDA          AS CD_AZIENDA_CLI_IST,
    SD.CLI_CD_TIPO_TASSO            AS TP_TASSO,
    SD.CLI_DS_BENE                  AS DS_BENE,
    SD.CLI_DT_INIZIO_INDIR          AS DT_INDIR_CLI,
    DATEDIFF('year', SD.CLI_DT_INIZIO_INDIR, K.DT_OSSERVAZIONE) AS NM_ANZIANITA_INDIR_UC,
    SD.CLI_DT_INIZIO_OCCUP          AS DT_INIZIO_VALIDITA_OCCUP_CLI,
    SD.CLI_DT_INIZIO_RAPP           AS DT_INIZIO_RAPPORTO_CLI_IST,
    SD.CLI_DT_INIZIO_RAPP_BANCA     AS DT_INIZIO_RAPPORTO_BANC,
    SD.CLI_DT_NASCITA               AS DT_NASCITA_CLI,
    SD.CLI_DT_ULTIMO_PROTESTO       AS DT_ULT_PROTESTO,
    SD.CLI_EU_ALTRI_REDDITI         AS EU_ALTRI_REDDITO_CLI,
    SD.CLI_EU_COMMISSIONE           AS EU_COMMISS,
    SD.CLI_EU_CUMULO_RISCHIO        AS EU_CUMULO_RISCHIO_AGOS_CLI,
    SD.CLI_EU_CUMULO_RISCHIO        AS EU_CUMULO_RISCHIO_AGOS_ATTRIBUITO_CLI,
    SD.CLI_EU_CUMULO_RISCHIO_CRIF   AS EU_CUMULO_RISCHIO_CRIF_CLI,
    SD.CLI_EU_CUMULO_RISCHIO_CRIF   AS EU_CUMULO_RISCHIO_CRIF_ATTRIBUITO_CLI,
    SD.CLI_EU_FIDO                  AS EU_FIDO_CLI_IST,
    SD.CLI_EU_FINANZIATO            AS EU_FINANZIATO,
    SD.CLI_EU_MOROSITA              AS EU_MOROSITA_CLI_IST,
    SD.CLI_EU_PROTESTI              AS EU_PROTESTI_CLI,
    SD.CLI_NM_PROTESTI              AS NM_PROTESTI,
    SD.CLI_EU_RATA                  AS EU_RATA,
    SD.CLI_EU_RATA                  AS EU_RATA_MENSILIZZATA_CLI,
    SD.CLI_EU_RATA_CRIF             AS EU_RATA_CRIF_CLI,
    SD.CLI_EU_REDDITO_ANNUO         AS EU_REDDITO_ANNUO_CLI,
    SD.CLI_EU_REDDITO_FAMIGLIARE    AS EU_REDDITO_FAMIGLIARI,
    SD.CLI_FL_CONTO_BANCARIO        AS FL_CONTO_BANC_CLI,
    SD.CLI_FL_CONTO_BANCARIO        AS CD_CARTA_BANCO,
    SD.CLI_FL_DEPOSITO_BANCARIO     AS FL_DEPOSITO_BANC_CLI,
    CASE WHEN SD.CLI_NM_PROTESTI > 0 THEN 'Y' ELSE 'N' END AS FL_PROTESTI,
    SD.CLI_NM_CESSIONE_BUSTA_PAGA   AS NM_CESSIONE_BUSTA_PAGA_CLI,
    SD.CLI_NM_FAMILIARI             AS NM_FAMILIARI,
    SD.CLI_NM_MESI_DURATA           AS NM_DURATA_CONTR_LAVORO,
    SD.CLI_NM_MESI_DURATA           AS NM_MESI_DILAZIONE_IST,
    SD.CLI_NM_MOROSITA              AS NM_MOROSITA_CLI_IST,
    SD.CLI_NM_MENSILITA             AS NM_MENSALITA_CLIENTI,
    SD.CLI_TP_ABITAZIONE            AS TP_ABITAZ_CLI,
    SD.CLI_TP_ATTIVITA              AS TP_ATTIVITA_CLI,
    SD.CLI_TP_ATTIVITA              AS TP_ATTIVITA_CONV,
    SD.CLI_TP_ATTIVITA              AS TP_SETTORE_ATTIVITA,
    SD.CLI_TP_BANCA                 AS TP_BANC,
    SD.CLI_TP_BENE                  AS TP_BENE,
    SD.CLI_TP_CONTRATTO_LAVORO      AS TP_CONTR_TEMPO_DET_INDET,
    SD.CLI_TP_LOCAZIONE             AS TP_LOCAZ,
    SD.CLI_TP_PAGAMENTO             AS TP_MODALITA_PAGAM_IST,
    SD.CLI_TP_PAGAMENTO             AS CD_PAGAM_ULT,
    SD.CLI_TP_PRATICA_INTERNET      AS TP_PRAT_INTERNET,
    SD.CLI_TP_RIPAGAMENTO           AS TP_RIPAGAMENTO_IST,
    SD.CLI_TP_PROCEDURA             AS TP_ULT_FINANZIAMENTO,
    SD.CLI_DT_OSSERVAZIONE          AS DT_INSER_SCORE,
    DATEDIFF('year', SD.CLI_DT_NASCITA, K.DT_OSSERVAZIONE) AS NM_ANNI_ETA_ULT_CONTR,

    -- === SOCIODEMO_SCORE - coobligato ===
    SD.COOB_CD_CONTROPARTE          AS CD_COOBLIGATO,
    SD.COOB_CD_STATO_CIVILE         AS CD_STATO_CIVILE_COOB,
    SD.COOB_EU_ALTRI_REDDITI        AS EU_ALTRI_REDDITO_COOB,
    SD.COOB_EU_CUMULO_RISCHIO       AS EU_CUMULO_RISCHIO_AGOS_ATTRIBUITO_COOB,
    SD.COOB_EU_CUMULO_RISCHIO       AS EU_CUMULO_RISCHIO_AGOS_COOB,
    SD.COOB_EU_CUMULO_RISCHIO_CRIF  AS EU_CUMULO_RISCHIO_CRIF_COOB,
    SD.COOB_EU_CUMULO_RISCHIO_CRIF  AS EU_CUMULO_RISCHIO_CRIF_ATTRIBUITO_COOB,
    SD.COOB_EU_DEPOSITO_BANCARIO    AS EU_DEPOSITO_BANC_COO,
    SD.COOB_EU_FIDO                 AS EU_FIDO_COOB_IST,
    SD.COOB_EU_MOROSITA             AS EU_MOROSITA_COOB_IST,
    SD.COOB_EU_PROTESTI             AS EU_PROTESTI_COOB,
    SD.COOB_EU_RATA                 AS EU_RATA_MENSILIZZATA_COOB,
    SD.COOB_EU_RATA_CRIF            AS EU_RATA_CRIF_COOBLIGATO_COOB,
    SD.COOB_EU_REDDITO_ANNUO        AS EU_REDDITO_COOB,
    SD.COOB_FL_CONTO_BANCARIO       AS FL_CONTO_BANC_COOB,
    SD.COOB_FL_DEPOSITO_BANCARIO    AS FL_DEPOSITO_BANC_COOB,
    SD.COOB_NM_PROTESTI             AS NM_PROTESTI_COOB,
    CASE WHEN SD.COOB_TP_CONTROPARTE = 'COOB' THEN SD.COOB_EU_ALTR_USC END AS EU_ALTRI_ADDEBITI_COOB,

    -- === VARIAZIONI_ANAGRAFICHE ===
    VA.CD_PROVINCIA_NASCITA     AS CD_PROV_NASCITA,
    VA.CD_PROVINCIA_RESIDENZA   AS CD_PROV_RESID,
    VA.CD_OCCUPAZIONE           AS CD_AZIENDA_CLI,
    VA.DT_INIZIO_OCCUPAZIONE_CLI AS DT_INIZIO_RAPPORTO_CLI,
    VA.CD_FISCALE               AS CD_FISCALE_CLI,
    VA.CD_FISCALE               AS CD_FISCALE_COOB,
    VA.CD_NAZIONE_RESIDENZA     AS CD_NAZIONE_CLI,
    VA.CD_PARTITA_IVA           AS CD_PIVA,
    VA.DS_NAZIONE_NASCITA       AS DS_NAZIONE_CLI,

    -- === SALDO GESTIONALE / CARTA / CONSUMO ===
    SG.EU_IMPIEGO_GESTIONALE    AS EU_IMPIEGHI_CLI,
    SG.EU_MORA                  AS EU_MOROSITA_CLI,
    SG.EU_MORA                  AS EU_MOROSITA_COOB,
    SG.EU_RATEO,
    CONSM.DS_DATO_AGG_1         AS CD_USATO_L_IDENTIFICAZIONE_PROFAMILY,
    CAR.TP_CATEGORIA_CARTE      AS TP_CARTA,
    CAR.TP_RIMBORSO             AS TP_MODALITA_RIPAGAMENTO,
    CAR.DT_DATA_VAL_ORIG        AS FL_CARTA_CONVERT,
    CAR.DT_INVIO_CARTA          AS DT_CONSEGNA_CARTA,
    CAR.DT_PRIMO_UTILIZZO       AS DT_PRIMO_ACQUISTO,
    CAR.DT_SCADENZA             AS DT_SCAD,
    CAR.DT_PRIMO_UTILIZZO       AS FL_CARTA_UTILIZZATA,
    CAR.EU_PLAFOND              AS EU_LIMITE_CARTA,
    CAR.DT_DATA_VAL_ORIG        AS CD_STATO_CONVERSIONE_CARTA,

    -- === CARTE_UTILIZZI ===
    UCH.DT_UTILIZZO             AS DT_ULT_UTILIZZO,
    UCH.DT_UTILIZZO             AS DT_ULT_ACQUISTO,
    UCH.DT_UTILIZZO             AS DT_ULT_UTILIZZO_STO,
    UCH.CD_CIRCUITO             AS CD_CIRCUITO_CARTA,
    UCH.NM_UTILIZZI_ULTIMI_12M, UCH.NM_UTILIZZI_ULTIMI_3M,
    UCH.NM_UTILIZZI_ULTIMI_6M,  UCH.NM_UTILIZZI_TOT,

    -- === RATE ===
    ACR.NM_RATA                 AS NM_RATA_ATTUALE,
    CAR.DT_SCADENZA             AS DT_SCAD_PRECEDENTE,
    ACR.NM_RATE_ACCODATE_12M,
    ACR.FL_ACCODAMENTO_TOT      AS NM_RATE_ACCODATE_TOT,
    ACR.NM_RATA_ORIG            AS NM_RATE,
    ACR.NM_RATE_SCADUTE,
    ACR.NM_RATA                 AS NM_RATE_TOT_INCLUSE_PIANI_TOT,

    -- === MOV_PRODUZIONE / GIORNI SCADUTO ===
    MP.NM_IRR_NUM, MP.NM_IRR_DEN,
    MP.NM_TAN1_DEN AS NM_TAN_DEN, MP.NM_TAN1_NUM AS NM_TAN_NUM,
    MP.NM_TAN2_DEN AS NM_TAN_DEN_2, MP.NM_TAN2_NUM AS NM_TAN_NUM_2,
    GSH.NM_GG_SCADUTO_CLI_MESE  AS NM_GIORNI_SCADUTO,
    GSH.NM_MAX_INSOLVENZA_CLI   AS NM_GIORNI_SCAD_EBA,
    GSH.NM_GG_SCADUTO_CLI_MESE  AS NM_MAX_INSOLUTI_MENSILE,
    GSH.NM_GG_SCADUTO_CLI_MESE  AS NM_MAX_ARRETRATI,

    CASE WHEN CONS.CD_PRATICA_CONSOLIDATA IS NOT NULL THEN 'S' ELSE 'N' END AS FL_RIFINANZIAMENTO,
    CONSM.EU_PREZZO_BENE        AS EU_BENE,
    CONSM.NM_TASSO_COSTRUZIONE  AS EU_TASSO_MEDIO,
    CONSM.NM_MESI_DILAZIONE     AS CONSM_NM_MESI_DILAZIONE,
    CONSM.EU_MAXI_RATA          AS EU_MAXIRATA,
    SAL.EU_SALDO_MESE_1         AS EU_ON_BALANCE,
    GT.TP_TRUFFA,
    MOR.DT_MORATORIA            AS DT_ULT_MORA,
    MOR.FL_MORATORIA            AS NM_MOROSITA_CLI,
    DPD.DT_INGRS_DFLT_EBA       AS DT_DFLT,
    CEC.EU_DISPONIBILITA_M      AS EU_DISPON,
    CEC.EU_DISPONIBILITA_M      AS EU_DISPON_CONTABILE,
    CEC.EU_DISPONIBILITA_M      AS DT_PROX_PAGAM,
    PAP.EU_PERDITA,
    SG.EU_RISCONTI,
    CASE WHEN SC.FL_DFLT_EBA = 'S' THEN SG.EU_RISCONTI END AS EU_RISCONTO_DFLT,
    SI.EU_ANTICIPO              AS EU_ANTICIPO_IST,
    SA.FL_CTCPOS_HIT_NOHIT_CLI  AS CD_CTC_CLIENTE,
    SA.FL_CTCPOS_HIT_NOHIT_COO  AS CD_CTC_COOB,
    SI.EU_IMPORTO_RATA_2PERIODO AS EU_RATA_SEC_PER,
    SI.NM_DURATA_1PERIODO       AS NM_RATE_PRIMO_PERODO,
    IT.TP_FORMA_PAGAMENTO       AS TP_PAGAMENTO,
    CB.CD_BLOCCO_OCS            AS CD_BLOCCO,
    IH.NM_INSOLUTO_CORRENTE, IH.NM_INSOL_ULTIMI_12_MESI, IH.NM_INSOL_ULTIMI_24_MESI,

    -- === Respinte del cliente, escludendo la pratica corrente ===
    K.NM_CONTRATTI_CARTA, K.NM_CQS_CLI,
    {% for m in MESI_RESP %}
    K._RESP_{{ m }}M_TOT - CASE WHEN K.DT_RESPINTA >= ADD_MONTHS(K.DT_OSSERVAZIONE, -{{ m }}) THEN 1 ELSE 0 END AS NM_RESPINTE_{{ 'L12M' if m == 12 else (m|string) + 'M' }},
    K._RESP_{{ m }}M_CA  - CASE WHEN K.DT_RESPINTA >= ADD_MONTHS(K.DT_OSSERVAZIONE, -{{ m }}) AND K.TP_PROCEDURA = 'CA' THEN 1 ELSE 0 END AS NM_RESPINTE_{{ 'L12M' if m == 12 else (m|string) + 'M' }}_CA,
    K._RESP_{{ m }}M_CO  - CASE WHEN K.DT_RESPINTA >= ADD_MONTHS(K.DT_OSSERVAZIONE, -{{ m }}) AND K.TP_PROCEDURA = 'CO' THEN 1 ELSE 0 END AS NM_RESPINTE_{{ 'L12M' if m == 12 else (m|string) + 'M' }}_CO,
    {% endfor %}

    -- === DM_CAMPIONI_SOCIO ===
    SOCIO.DT_ULTIMA_RTL_PAGAMENTO, SOCIO.DT_APERTURA_PRIMA_PRATICA,
    SOCIO.DT_CARIC_PRI_PRA_ACC, SOCIO.DT_CARIC_ULT_PRA_ACC, SOCIO.DT_CARIC_ULT_PRA_RES,
    SOCIO.DT_PRI_SCAD_ULT_CONS, SOCIO.DT_ULTIMO_ANTICIPO,
    SOCIO.NM_INSOL_TOT_CONSUMO, SOCIO.NM_INSOL_TOT_COOB,
    SOCIO.DT_ULTIMA_DELINQUENCY, SOCIO.TP_ATTIVITA_PREC, SOCIO.NM_RATE_TOT_ULT_CONS,

    ACR.FL_ACCODAMENTO, ACR.FL_ACCODAMENTO_L12M, ACR.FL_ACCODAMENTO_TOT,
    ACR.DT_FIRST_ACCODAMENTO,
    GSH.NM_MAX_INSOLVENZA_CLI,
    {% for m in MESI_INS %}
    GSH.NM_MAX_INS_CLI_L{{ m }}M{{ "," if not loop.last }}
    {% endfor %},

    CASE WHEN DPD.DT_INGRS_DFLT_EBA IS NOT NULL AND DPD.FL_DFLT_EBA = 'S'
         THEN COALESCE(SG.EU_IMPIEGO_GESTIONALE, 0) + COALESCE(SG.EU_MORA, 0) + COALESCE(SG.EU_RISCONTI, 0)
    END AS EU_EAD_DEFAULT_CRRV2,
    CASE WHEN K.CD_COOBLIGATO IS NOT NULL THEN 'S' ELSE 'N' END AS FL_COOBBLIGATO,
    CASE WHEN K.DT_CESSIONE IS NOT NULL THEN 'S' ELSE 'N' END AS FL_CESSIONE,
    CASE WHEN K.DT_PASSAGGIO_PERDITA IS NOT NULL THEN 'S' ELSE 'N' END AS FL_PERDITA,
    DATEDIFF('month', K.DT_PRIMA_SCADENZA, K.DT_OSSERVAZIONE) AS NM_ANZIANITA_PRATICA,
    K.NM_CONTRATTI_ATTIVI_CARTA, K.NM_CONTRATTI_ATTIVI_CONSUMO,
    CASE
        WHEN DPD.DT_INGRS_DFLT_EBA IS NULL THEN 'NA'
        WHEN DPD.DT_INGRS_DFLT_EBA >= ADD_MONTHS(K.DT_OSSERVAZIONE, -12)
             AND DPD.DT_INGRS_DFLT_EBA < K.DT_OSSERVAZIONE THEN 'S'
        ELSE 'N'
    END AS FL_DEFAULT_12,
    COALESCE(NULLIF(F.STDPR_VALUTAZIONE, ''), 'AIRB') AS TP_PERIMETRO,

    SOCIO.NM_ANZIANITA_CONTRATTO_UC   AS NM_ANNI_UC,
    SOCIO.NM_ANZIANITA_OCCUPAZIONE_UC AS NM_ANZIANITA_OCCUP_UC,
    SOCIO.CD_ABITAZIONE_UC, SOCIO.CD_BENE_UC, SOCIO.CD_IMPIEGO_UC,
    SOCIO.CD_SCORE_CRIF_COOBLIGATO_UC AS CD_SCORE_CRIF_COOB_UC,
    SOCIO.CD_STATO_CIVILE_UC, SOCIO.EU_REDDITO_MENSILE_UC, SOCIO.NM_MESI_APERTURA_CA_UC,
    SOCIO.CD_ESITO_FIL_ULT_PP_UC, SOCIO.CD_ESITO_UTILIZZO_UC,
    SOCIO.DT_DECOR_ULT_PRATICA        AS DT_DECOR_UC,
    SOCIO.EU_FINANZIATO_UC,
    SOCIO.NM_PRATICHE                 AS NM_CONTRATTI_TOT,
    SOCIO.NM_PRAT_ACC_CONS, SOCIO.NM_PRAT_RES_CONS, SOCIO.NM_PRAT_RES_GEST,
    SOCIO.NM_PRAT_RIT_CONS, SOCIO.NM_PRATICHE, SOCIO.NM_PRATICHE_CLIE, SOCIO.NM_PRATICHE_COOB,

    COALESCE(CONSM.EU_ANTICIPO, CQS.EU_ANTICIPO) AS EU_ANTICIPO,
    {% for n in range(1, 13) %}
    SAL.EU_SALDO_MESE_{{ n }}{{ "," if not loop.last }}
    {% endfor %},
    CASE WHEN ACR.DT_ACCODAMENTO > DPD.DT_USCITA_DFLT_EBA THEN ACR.DT_ACCODAMENTO END AS DT_ACCOD_POST_DFLT,
    IT.DT_DELL_ULT_PAGAM,
    UCH.DT_ULT_PAGAM_CARTA,
    CAR.FL_PREPAGATA            AS FL_CARTA_PREPAG,
    CASE WHEN CAR.FL_PREPAGATA = 'S' THEN CAR.CD_STATO END AS CD_STATO_PREPAG,
    SD.CD_IMPEGNI_CLI, SD.CD_IMPEGNI_COOB,
    OXD.DRPRA_N_INS_DA_SSI      AS NM_INSOL_WORST_TOT_WORST,
    SOCIO.NM_MESI_APERTURA_CA_UC AS NM_MESI_APERT_CARTA_DALL,
    SI.NM_DURATA_2PERIODO       AS NM_RATE_SEC_PER

FROM pratica_storico K

LEFT JOIN sociodemo_impegni_pivot SD
    ON SD.CD_PRATICA = K.CD_PRATICA AND SD.TP_PROCEDURA = K.TP_PROCEDURA AND SD.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('saldo_gestionale_m') }} SG
    ON SG.CD_PRATICA = K.CD_PRATICA AND SG.TP_PROCEDURA = K.TP_PROCEDURA AND SG.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('stato_creditizio_m') }} SC
    ON SC.CD_PRATICA = K.CD_PRATICA AND SC.TP_PROCEDURA = K.TP_PROCEDURA AND SC.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('carta_m') }} CAR
    ON CAR.CD_PRATICA = K.CD_PRATICA AND CAR.TP_PROCEDURA = K.TP_PROCEDURA AND CAR.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('consumo_m') }} CONSM
    ON CONSM.CD_PRATICA = K.CD_PRATICA AND CONSM.TP_PROCEDURA = K.TP_PROCEDURA AND CONSM.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('cqs_m') }} CQS
    ON CQS.CD_PRATICA = K.CD_PRATICA AND CQS.TP_PROCEDURA = K.TP_PROCEDURA AND CQS.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('moratorie_m') }} MOR
    ON MOR.CD_PRATICA = K.CD_PRATICA AND MOR.TP_PROCEDURA = K.TP_PROCEDURA AND MOR.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('carte_estratto_conto_m') }} CEC
    ON CEC.CD_PRATICA = K.CD_PRATICA AND CEC.TP_PROCEDURA = K.TP_PROCEDURA AND CEC.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('dm_mov_produzione_m') }} MP
    ON MP.CD_PRATICA = K.CD_PRATICA AND MP.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN {{ ref('gestione_truffe') }} GT
    ON GT.CD_PRATICA = K.CD_PRATICA AND GT.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN {{ ref('dm_pratiche_default_m') }} DPD
    ON DPD.CD_PRATICA = K.CD_PRATICA AND DPD.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN {{ ref('passaggi_a_perdita') }} PAP
    ON PAP.CD_PRATICA = K.CD_PRATICA AND PAP.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN {{ ref('scoring_input') }} SI
    ON SI.CD_PRATICA = K.CD_PRATICA AND SI.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN {{ ref('sintesi_accettazione') }} SA
    ON SA.CD_PRATICA = K.CD_PRATICA AND SA.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN {{ ref('carte_blocchi') }} CB
    ON CB.CD_PRATICA = K.CD_PRATICA AND CB.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN {{ ref('consolidamenti') }} CONS
    ON  CONS.CD_PRATICA_CONSOLIDANTE = K.CD_PRATICA
    AND CONS.TP_PROC_CONSOLIDANTE    = K.TP_PROCEDURA
    AND CONS.DT_DECORRENZA          <= K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('variazioni_anagrafiche') }} VA
    ON VA.CD_CONTROPARTE = K.CD_CLIENTE

LEFT JOIN {{ ref('dm_campioni_socio') }} SOCIO
    ON SOCIO.CD_PRATICA = K.CD_PRATICA AND SOCIO.TP_PROCEDURA = K.TP_PROCEDURA AND SOCIO.DT_OSSERVAZIONE = K.DT_OSSERVAZIONE

LEFT JOIN AGOS_DEV_16000.L1_O_BAS.IFBLFSTDPR_TEST F
    ON  F.STDPR_PRATICA          = K.CD_PRATICA
    AND F.STDPR_PROVENIENZA      = K.TP_PROCEDURA
    AND F.STDPR_DATA_ESTRAZIONE  = K.DT_OSSERVAZIONE

LEFT JOIN {{ ref('oxdrfpra') }} OXD
    ON  OXD.DRPRA_PRATICA         = K.CD_PRATICA
    AND OXD.DRPRA_PROVENIENZA     = K.TP_PROCEDURA
    AND OXD.DRPRA_DATA_ESTRAZIONE = TO_NUMBER(TO_CHAR(K.DT_OSSERVAZIONE, 'YYYYMMDD'))

LEFT JOIN (
    SELECT
        CD_PRATICA, TP_PROCEDURA,
        MAX(CASE WHEN TP_FORMA_PAGAMENTO = 'CONTANTE' THEN DT_REGISTRAZIONE END) AS DT_DELL_ULT_PAGAM,
        MAX_BY(TP_FORMA_PAGAMENTO, DT_REGISTRAZIONE)                             AS TP_FORMA_PAGAMENTO
    FROM {{ ref('incassi_testata') }}
    GROUP BY CD_PRATICA, TP_PROCEDURA
) IT
    ON IT.CD_PRATICA = K.CD_PRATICA AND IT.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN (
    SELECT
        S.CD_PRATICA, S.TP_PROCEDURA,
        {% for n in range(1, 13) %}
        MAX(CASE WHEN DATEDIFF('MONTH', S.DT_OSSERVAZIONE, {{ DT_OSS }}) = {{ n - 1 }} THEN S.EU_ON_BALANCE END) AS EU_SALDO_MESE_{{ n }}{{ "," if not loop.last }}
        {% endfor %}
    FROM {{ ref('saldo_contabile_m') }} S
    WHERE S.DT_OSSERVAZIONE BETWEEN ADD_MONTHS({{ DT_OSS }}, -11) AND {{ DT_OSS }}
    GROUP BY S.CD_PRATICA, S.TP_PROCEDURA
) SAL
    ON SAL.CD_PRATICA = K.CD_PRATICA AND SAL.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN (
    SELECT
        CU.CD_PRATICA, CU.TP_PROCEDURA,
        MAX(CU.DT_UTILIZZO)                    AS DT_UTILIZZO,
        MAX_BY(CU.CD_CIRCUITO, CU.DT_UTILIZZO) AS CD_CIRCUITO,
        MAX(CU.DT_APPROVAZIONE_UTILIZZO)       AS DT_ULT_PAGAM_CARTA,
        COUNT(CU.DT_UTILIZZO)                  AS NM_UTILIZZI_TOT,
        {% for m in [3, 6, 12] %}
        COUNT(CASE WHEN CU.DT_UTILIZZO >= ADD_MONTHS({{ DT_OSS }}, -{{ m }}) THEN 1 END) AS NM_UTILIZZI_ULTIMI_{{ m }}M{{ "," if not loop.last }}
        {% endfor %}
    FROM {{ ref('carte_utilizzi') }} CU
    WHERE CU.DT_UTILIZZO <= {{ DT_OSS }}
    GROUP BY CU.CD_PRATICA, CU.TP_PROCEDURA
) UCH
    ON UCH.CD_PRATICA = K.CD_PRATICA AND UCH.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN (
    SELECT
        I.CD_PRATICA, I.TP_PROCEDURA,
        COUNT(CASE WHEN TRUNC(TO_DATE(TO_VARCHAR(I.DT_SCADENZA), 'YYYYMMDD'), 'MM') = TRUNC({{ DT_OSS }}, 'MM') THEN 1 END) AS NM_INSOLUTO_CORRENTE,
        COUNT(CASE WHEN TO_DATE(TO_VARCHAR(I.DT_SCADENZA), 'YYYYMMDD') >= ADD_MONTHS({{ DT_OSS }}, -12) THEN 1 END)         AS NM_INSOL_ULTIMI_12_MESI,
        COUNT(CASE WHEN TO_DATE(TO_VARCHAR(I.DT_SCADENZA), 'YYYYMMDD') >= ADD_MONTHS({{ DT_OSS }}, -24) THEN 1 END)         AS NM_INSOL_ULTIMI_24_MESI
    FROM AGOS_DEV_16000.L2_PERFORMING_M.INSOLUTI_TEST I
    WHERE TO_DATE(TO_VARCHAR(I.DT_SCADENZA), 'YYYYMMDD') <= {{ DT_OSS }}
    GROUP BY I.CD_PRATICA, I.TP_PROCEDURA
) IH
    ON IH.CD_PRATICA = K.CD_PRATICA AND IH.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN (
    SELECT
        RM.CD_PRATICA, RM.TP_PROCEDURA,
        MAX(CASE WHEN DATE_TRUNC('MONTH', RM.DT_SCADENZA) = DATE_TRUNC('MONTH', {{ DT_OSS }}) THEN RM.NM_RATA END)         AS NM_RATA,
        MAX(CASE WHEN RM.DT_SCADENZA <= LAST_DAY(ADD_MONTHS({{ DT_OSS }}, -1)) AND RM.DT_FINE_VALIDITA = '9999-12-31' THEN RM.NM_RATA END) AS NM_RATE_SCADUTE,
        MAX(CASE WHEN DATE_TRUNC('MONTH', RM.DT_SCADENZA) = DATE_TRUNC('MONTH', {{ DT_OSS }}) THEN RM.NM_RATA_ORIG END)    AS NM_RATA_ORIG,
        MAX(CASE WHEN DATE_TRUNC('MONTH', RM.DT_SCADENZA) = DATE_TRUNC('MONTH', {{ DT_OSS }}) THEN RM.DT_ACCODAMENTO END)  AS DT_ACCODAMENTO,
        MAX(CASE WHEN RM.FL_ACCODAMENTO = 'Y' THEN 1 ELSE 0 END)                   AS FL_ACCODAMENTO,
        MAX(CASE WHEN RM.RN <= 12 AND RM.FL_ACCODAMENTO = 'Y' THEN 1 ELSE 0 END)   AS FL_ACCODAMENTO_L12M,
        SUM(CASE WHEN RM.RN <= 12 AND RM.FL_ACCODAMENTO = 'Y' THEN 1 ELSE 0 END)   AS NM_RATE_ACCODATE_12M,
        SUM(CASE WHEN RM.FL_ACCODAMENTO = 'Y' THEN 1 ELSE 0 END)                   AS FL_ACCODAMENTO_TOT,
        MIN(CASE WHEN RM.FL_ACCODAMENTO = 'Y' THEN RM.DT_ACCODAMENTO END)          AS DT_FIRST_ACCODAMENTO,
        MAX(CASE WHEN RM.FL_ACCODAMENTO = 'Y' THEN RM.DT_ACCODAMENTO END)          AS DT_LAST_ACCODAMENTO
    FROM (
        SELECT
            CD_PRATICA, TP_PROCEDURA, DT_SCADENZA, NM_RATA, NM_RATA_ORIG,
            DT_ACCODAMENTO, FL_ACCODAMENTO, DT_FINE_VALIDITA,
            ROW_NUMBER() OVER (PARTITION BY CD_PRATICA, TP_PROCEDURA ORDER BY DT_SCADENZA DESC) AS RN
        FROM {{ ref('rate_pratica') }}
    ) RM
    GROUP BY RM.CD_PRATICA, RM.TP_PROCEDURA
) ACR
    ON ACR.CD_PRATICA = K.CD_PRATICA AND ACR.TP_PROCEDURA = K.TP_PROCEDURA

LEFT JOIN (
    SELECT
        GS.CD_PRATICA, GS.TP_PROCEDURA,
        MAX(CASE WHEN GS.TS_INSERIMENTO = {{ DT_OSS }} THEN GS.NM_GG_SCADUTO_CLI END)     AS NM_GG_SCADUTO_CLI_MESE,
        MAX(CASE WHEN GS.TS_INSERIMENTO = {{ DT_OSS }} THEN GS.NM_GG_SCADUTO_EBA_CLI END) AS NM_MAX_INSOLVENZA_CLI,
        {% for m in MESI_INS %}
        MAX(CASE WHEN GS.TS_INSERIMENTO = ADD_MONTHS({{ DT_OSS }}, -{{ m }}) THEN GS.NM_GG_SCADUTO_EBA_CLI END) AS NM_MAX_INS_CLI_L{{ m }}M{{ "," if not loop.last }}
        {% endfor %}
    FROM {{ ref('giorni_scaduto') }} GS
    WHERE GS.TS_INSERIMENTO IN (
        {{ DT_OSS }}{% for m in MESI_INS %}, ADD_MONTHS({{ DT_OSS }}, -{{ m }}){% endfor %}
    )
    GROUP BY GS.CD_PRATICA, GS.TP_PROCEDURA
) GSH
    ON GSH.CD_PRATICA = K.CD_PRATICA AND GSH.TP_PROCEDURA = K.TP_PROCEDURA