-- Storicizzazione: S3 (incremental / append) - chiave tecnica DT_OSSERVAZIONE

SELECT
    DREXT_PRATICA AS CD_PRATICA,
    DREXT_PROVENIENZA AS TP_PROCEDURA,
    CAST(DREXT_CLIENTE AS VARCHAR(9)) AS CD_CONTROPARTE,
    --TODO: CAMPO DATA DA AGGIORNARE IN CASO DI SORGENTE MENSILE
    {{ custom_to_date('DREXT_DATA_ESTRAZIONE') }} AS DT_OSSERVAZIONE,
    {{ custom_to_decimal('DREXT_IMPORTO') }} AS EU_OFF_BALANCE
FROM {{ ref('oxdrfext') }}
WHERE {{ custom_to_date('DREXT_DATA_ESTRAZIONE') }} = LAST_DAY(DATEADD('month', -1, CURRENT_DATE()))
    AND DREXT_TIPOLOGIA = 'CIM'
    AND FL_DELETED = 'N'
UNION ALL
SELECT
    DRPRA_PRATICA AS CD_PRATICA,
    DRPRA_PROVENIENZA AS TP_PROCEDURA,
    CAST(DRPRA_CLIENTE AS VARCHAR(9)) AS CD_CONTROPARTE,
    --TODO: CAMPO DATA DA AGGIORNARE IN CASO DI SORGENTE MENSILE
    {{ custom_to_date('DRPRA_DATA_ESTRAZIONE') }} AS DT_OSSERVAZIONE,
    {{ custom_to_decimal('DRPRA_FINANZIATO_ORIG - DRPRA_SALDO') }} AS EU_OFF_BALANCE
FROM {{ ref('oxdrfpra') }}
WHERE {{ custom_to_date('DRPRA_DATA_ESTRAZIONE') }} = LAST_DAY(DATEADD('month', -1, CURRENT_DATE()))
    AND DRPRA_TIPO = 'AN'
    AND FL_DELETED = 'N'
    AND (DRPRA_FINANZIATO_ORIG - DRPRA_SALDO) > 0

{% if is_incremental() %}
WHERE {{ custom_to_date('DT_OSSERVAZIONE') }} = {{ last_day_past_month() }}
{% endif %}
