-- Storicizzazione: S3 (incremental / append) - chiave tecnica DT_OSSERVAZIONE
WITH
cte_base AS (
    SELECT
        p.DRPRA_PROVENIENZA, p.DRPRA_PRATICA, {{ custom_to_date('p.DRPRA_DATA_ESTRAZIONE') }} AS DRPRA_DATA_ESTRAZIONE,
        c.IACT_DATA_VAL_IAS, c.IACT_VERSIONE
    FROM {{ ref('oxdrfpra') }} p
    LEFT JOIN {{ ref('oxiafct') }} c
        ON  c.IACT_PROCEDURA = p.DRPRA_PROVENIENZA
        AND c.IACT_CONTRATTO = p.DRPRA_PRATICA
        AND TO_DATE(c.TS_CARICAMENTO) <= {{ custom_to_date('p.DRPRA_DATA_ESTRAZIONE') }}
        AND c.IACT_DATA_VAL_IAS < p.DRPRA_DATA_ESTRAZIONE
        AND C.FL_DELETED = 'N'
    WHERE {{ custom_to_date('P.DRPRA_DATA_ESTRAZIONE') }} = LAST_DAY(DATEADD('month', -1, CURRENT_DATE()))
    AND P.FL_DELETED = 'N'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY p.DRPRA_PRATICA, p.DRPRA_PROVENIENZA ORDER BY c.IACT_DATA_VAL_IAS DESC, c.IACT_VERSIONE DESC) = 1
),

risconti_unpivot_base AS (
    SELECT
        COMP_CONTRATTO, COMP_PROCEDURA, COMP_VERSIONE, COMP_ANNO, COMP_TIPO_IMPORTO, COMP_SOTTO_TIPO,
        RIGHT(mese_num, 2) AS mese_num,
        LAST_DAY(TO_DATE(COMP_ANNO || '-' || RIGHT(mese_num, 2) || '-01', 'YYYY-MM-DD')) AS data_fine_mese,
        importo_risconto
    FROM {{ ref('oxiafcompe') }}
    UNPIVOT (
        importo_risconto FOR mese_num IN (
        COMP_RISCONTO_01 AS M01, COMP_RISCONTO_02 AS M02, COMP_RISCONTO_03 AS M03, COMP_RISCONTO_04 AS M04,
        COMP_RISCONTO_05 AS M05, COMP_RISCONTO_06 AS M06, COMP_RISCONTO_07 AS M07, COMP_RISCONTO_08 AS M08,
        COMP_RISCONTO_09 AS M09, COMP_RISCONTO_10 AS M10, COMP_RISCONTO_11 AS M11, COMP_RISCONTO_12 AS M12))
    WHERE FL_DELETED = 'N'
),

risconti_tot AS (
    SELECT
        b.DRPRA_PROVENIENZA, b.DRPRA_PRATICA, b.DRPRA_DATA_ESTRAZIONE,
        SUM(r.importo_risconto) AS importo_risconto_totale_consumo,
        SUM(CASE WHEN r.COMP_TIPO_IMPORTO = 'RIC' THEN r.importo_risconto ELSE 0 END) AS importo_risconto_totale_cqs,
        SUM(CASE WHEN r.COMP_TIPO_IMPORTO = 'IN1' THEN r.importo_risconto ELSE 0 END) AS importo_risconto_interessi
    FROM cte_base b
    LEFT JOIN risconti_unpivot_base r
        ON  r.COMP_CONTRATTO = b.DRPRA_PRATICA
        AND r.COMP_PROCEDURA = b.DRPRA_PROVENIENZA
        AND r.COMP_VERSIONE = b.IACT_VERSIONE
        AND r.data_fine_mese > b.DRPRA_DATA_ESTRAZIONE
        AND r.COMP_SOTTO_TIPO <> '99999'
    GROUP BY b.DRPRA_PRATICA, b.DRPRA_PROVENIENZA, b.DRPRA_DATA_ESTRAZIONE
)

SELECT
    P.DRPRA_PRATICA AS CD_PRATICA,
    P.DRPRA_PROVENIENZA AS TP_PROCEDURA,
    {{ custom_to_date('P.DRPRA_DATA_ESTRAZIONE') }} AS DT_OSSERVAZIONE,
    CASE
        WHEN P.DRPRA_PROVENIENZA = 'CA' THEN P.DRPRA_PRATICA
        WHEN P.DRPRA_PROVENIENZA = 'CO' THEN COALESCE(PR.SCPRA_NUM_PRATICA, P.DRPRA_PRATICA)
        WHEN P.DRPRA_PROVENIENZA = 'CQ' THEN COALESCE(NULLIF(P.DRPRA_NUM_PRATICA_ORIG,0), P.DRPRA_PRATICA)
        ELSE NULL
    END AS CD_PRATICA_CLIENTE,
    P.DRPRA_CLIENTE AS CD_CONTROPARTE,
    {{ custom_to_decimal('CASE
    WHEN P.DRPRA_PROVENIENZA = \'CO\' THEN (COALESCE(P.DRPRA_CAP_RESIDUO_IAS_VIGI,0) + COALESCE(P.DRPRA_INT_FUTURI_VIGI,0) + 
    COALESCE(P.DRPRA_CAPITALE_SCADUTO,0) + COALESCE(P.DRPRA_SCADUTO_IMPAGATO, 0) - COALESCE(P.DRPRA_CAPITALE_SCADUTO, 0) - 
    COALESCE(P.DRPRA_ALTRI_ADD_SCADUTI, 0) + COALESCE(P.DRPRA_ALTRI_ADD_SCADUTI,0) + COALESCE(RTC.importo_risconto_totale_consumo,0))
    WHEN P.DRPRA_PROVENIENZA = \'CA\' THEN (COALESCE(P.DRPRA_CAP_RESIDUO_IAS_VIGI,0) + COALESCE(P.DRPRA_CAPITALE_SCADUTO,0) + 
    COALESCE(P.DRPRA_SCADUTO_IMPAGATO, 0) - COALESCE(P.DRPRA_CAPITALE_SCADUTO, 0) - 
    COALESCE(P.DRPRA_ALTRI_ADD_SCADUTI, 0) + COALESCE(P.DRPRA_ALTRI_ADD_SCADUTI,0) )
    WHEN P.DRPRA_PROVENIENZA = \'CQ\' THEN (COALESCE(P.DRPRA_CAP_RESIDUO_IAS_VIGI,0) + COALESCE(P.DRPRA_INT_FUTURI_VIGI,0) + 
    COALESCE(CASE WHEN P.DRPRA_NUM_PRATICA_ORIG <> 0 THEN P.DRPRA_CREDITO_ATC ELSE P.DRPRA_CAPITALE_SCADUTO END,0) + 
    COALESCE(P.DRPRA_SCADUTO_IMPAGATO, 0) - COALESCE(P.DRPRA_CAPITALE_SCADUTO, 0) - 
    COALESCE(P.DRPRA_ALTRI_ADD_SCADUTI, 0) + COALESCE(P.DRPRA_ALTRI_ADD_SCADUTI,0) - COALESCE(P.DRPRA_PAG_ANTICIPATI,0) + 
    COALESCE(RTC.importo_risconto_totale_cqs,0) + CASE WHEN P.DRPRA_TIPO = \'AN\' THEN COALESCE(P.DRPRA_SALDO,0) ELSE 0 END)
    END', 13, 2) }} AS EU_ON_BALANCE,
    {{ custom_to_decimal('P.DRPRA_CAP_RESIDUO_IAS_VIGI', 13, 2) }} AS EU_CAPITALE_SCADERE,
    {{ custom_to_decimal('P.DRPRA_INT_FUTURI_VIGI', 13, 2) }} AS EU_INTERESSI_SCADERE,
    0 AS EU_SPESE_SCADERE,
    CASE
        WHEN P.DRPRA_PROVENIENZA = 'CQ' AND P.DRPRA_NUM_PRATICA_ORIG <> 0 THEN {{ custom_to_decimal('P.DRPRA_CREDITO_ATC', 13, 2) }}
        ELSE {{ custom_to_decimal('P.DRPRA_CAPITALE_SCADUTO', 13, 2) }}
    END AS EU_CAPITALE_SCADUTO,
    {{ custom_to_decimal('COALESCE(P.DRPRA_SCADUTO_IMPAGATO, 0) - COALESCE(P.DRPRA_CAPITALE_SCADUTO, 0) - 
    COALESCE(P.DRPRA_ALTRI_ADD_SCADUTI, 0)', 13, 2) }} AS EU_INTERESSI_SCADUTO,
    {{ custom_to_decimal('P.DRPRA_ALTRI_ADD_SCADUTI', 13, 2) }} AS EU_SPESE,
    {{ custom_to_decimal('P.DRPRA_SALDO_MORA', 13, 2) }} AS EU_MORA,
    {{ custom_to_decimal('P.DRPRA_SALDO', 13, 2) }} AS EU_SALDO_AVERE,
    CASE WHEN P.DRPRA_TIPO = 'AN' THEN {{ custom_to_decimal('P.DRPRA_SALDO ', 13, 2) }}
    ELSE 0 END AS EU_ANTICIPI_EROGATI,
    {{ custom_to_decimal('P.DRPRA_PAG_ANTICIPATI', 13, 2) }} AS EU_PAG_ESUB_NON_ALLOCATI,
    0 AS EU_INTERESSI_MATURATI_SCADERE,
    {{ custom_to_decimal('P.DRPRA_RATEO_INT_IAS', 13, 2) }} AS EU_RATEO,
    CASE WHEN P.DRPRA_PROVENIENZA = 'CO' THEN {{ custom_to_decimal('COALESCE(RTC.importo_risconto_totale_consumo,0)', 13, 2) }} 
    WHEN P.DRPRA_PROVENIENZA = 'CQ' THEN {{ custom_to_decimal('COALESCE(RTC.importo_risconto_totale_cqs,0)', 13, 2) }} 
    ELSE 0 END AS EU_RISCONTI,
    CASE WHEN P.DRPRA_PROVENIENZA = 'CO' THEN {{ custom_to_decimal('COALESCE(RTC.importo_risconto_totale_consumo, 0) - 
    COALESCE(RTC.importo_risconto_interessi, 0)', 13, 2) }}
    WHEN P.DRPRA_PROVENIENZA = 'CQ' THEN {{ custom_to_decimal('COALESCE(RTC.importo_risconto_totale_cqs, 0) - 
    COALESCE(RTC.importo_risconto_interessi, 0)', 13, 2) }} 
    ELSE 0 END AS EU_RISCONTI_ALTRI,
    CASE WHEN P.DRPRA_PROVENIENZA = 'CA' THEN 0
    ELSE {{ custom_to_decimal('COALESCE(RTC.importo_risconto_interessi,0)', 13, 2) }} END AS EU_RISCONTI_INTERESSI
FROM {{ ref('oxdrfpra') }} P
LEFT JOIN {{ ref('plsecprst') }} PR
    ON PR.SCPRA_NUM_PRATICA + 7000000000 = P.DRPRA_PRATICA
    AND PR.FL_DELETED = 'N'
LEFT JOIN risconti_tot RTC
    ON P.DRPRA_PRATICA = RTC.DRPRA_PRATICA
    AND P.DRPRA_PROVENIENZA = RTC.DRPRA_PROVENIENZA
WHERE P.FL_DELETED = 'N'
/*AND {{ custom_to_date('P.DRPRA_DATA_ESTRAZIONE') }} = LAST_DAY(DATEADD('month', -1, CURRENT_DATE()))*/

{% if is_incremental() %}
WHERE DT_OSSERVAZIONE = {{ last_day_past_month() }}
{% endif %}