select
  TRY_CAST(ts_riferimento AS TIMESTAMP_NTZ) as ts_riferimento,
  TRY_CAST('{{ run_started_at }}' AS TIMESTAMP_NTZ) as ts_caricamento,
  'N' as fl_deleted,
  NULL::TIMESTAMP_NTZ as ts_deleted,
  sys_change_operation,
  TRY_CAST(lastmodifieddata AS TIMESTAMP_NTZ) as lastmodifieddata,
  TRY_CAST(IFF(RTRIM(TCAP_PROVENIENZA) = '', ' ', RTRIM(TCAP_PROVENIENZA)) AS VARCHAR(2)) AS tcap_provenienza,
  TRY_CAST(IFF(RTRIM(TCAP_PRODOTTO) = '', ' ', RTRIM(TCAP_PRODOTTO)) AS VARCHAR(2)) AS tcap_prodotto,
  TRY_CAST(IFF(RTRIM(TCAP_TAB_FINANZIARIA) = '', ' ', RTRIM(TCAP_TAB_FINANZIARIA)) AS VARCHAR(3)) AS tcap_tab_finanziaria,
  TRY_CAST(TCAP_EMETTITORE AS NUMBER(3,0)) AS tcap_emettitore,
  TRY_CAST(IFF(RTRIM(TCAP_TIPO_PRODOTTO) = '', ' ', RTRIM(TCAP_TIPO_PRODOTTO)) AS VARCHAR(2)) AS tcap_tipo_prodotto,
  TRY_CAST(IFF(RTRIM(TCAP_DEST_FINANZ) = '', ' ', RTRIM(TCAP_DEST_FINANZ)) AS VARCHAR(3)) AS tcap_dest_finanz,
  TRY_CAST(TCAP_CONVENZIONATO AS NUMBER(9,0)) AS tcap_convenzionato,
  TRY_CAST(TCAP_ISTITUTO_FINANZ AS NUMBER(5,0)) AS tcap_istituto_finanz,
  TRY_CAST(IFF(RTRIM(TCAP_MOD_PAGAMENTO) = '', ' ', RTRIM(TCAP_MOD_PAGAMENTO)) AS VARCHAR(2)) AS tcap_mod_pagamento,
  TRY_CAST(IFF(RTRIM(TCAP_TIPO_CARICAMENTO) = '', ' ', RTRIM(TCAP_TIPO_CARICAMENTO)) AS VARCHAR(2)) AS tcap_tipo_caricamento,
  TRY_CAST(IFF(RTRIM(TCAP_CANALE_ACQ) = '', ' ', RTRIM(TCAP_CANALE_ACQ)) AS VARCHAR(3)) AS tcap_canale_acq,
  TRY_CAST(IFF(RTRIM(TCAP_ACCORDO) = '', ' ', RTRIM(TCAP_ACCORDO)) AS VARCHAR(6)) AS tcap_accordo,
  TRY_CAST(TCAP_INTERM_AGG AS NUMBER(9,0)) AS tcap_interm_agg,
  TRY_CAST(IFF(RTRIM(TCAP_CODICE_PACCHETTO) = '', ' ', RTRIM(TCAP_CODICE_PACCHETTO)) AS VARCHAR(5)) AS tcap_codice_pacchetto,
  TRY_CAST(IFF(RTRIM(TCAP_CODICE_GRUPPO) = '', ' ', RTRIM(TCAP_CODICE_GRUPPO)) AS VARCHAR(5)) AS tcap_codice_gruppo,
  TRY_CAST(IFF(RTRIM(TCAP_OBBLIG_FACOLT) = '', ' ', RTRIM(TCAP_OBBLIG_FACOLT)) AS VARCHAR(1)) AS tcap_obblig_facolt,
  TRY_CAST(IFF(RTRIM(TCAP_INCLUDI_ESCLUDI) = '', ' ', RTRIM(TCAP_INCLUDI_ESCLUDI)) AS VARCHAR(1)) AS tcap_includi_escludi,
  TRY_CAST(TCAP_DATA_INIZIO_VAL AS NUMBER(8,0)) AS tcap_data_inizio_val,
  TRY_CAST(TCAP_DATA_FINE_VAL AS NUMBER(8,0)) AS tcap_data_fine_val,
  TRY_CAST(ROWID AS NUMBER(38, 0)) AS rowid
from {{ source('source_l0','cctababpac') }}
